### ISSUE TITLE
[Bug]: 某些情况文件删除操作无法同步

### ISSUE THREAD

**Issue by Yaozhuwa** [remotely-save/remotely-save#100]
### What happened?

我用的是S3方式来同步Linux和 windows 的仓库。

1. 在windows上删除文件，手动同步，打开linux的OB，手动同步，删除操作正常。√
2. 在linux的OB上删除文件，手动同步，打开Windows的OB手动同步，删除操作无法同步到本地。×

### What OS are you using?

Windows, Linux

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.19

### Version of Obsidian

0.14.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> 在linux的OB上删除文件，手动同步

1. 你好，请问这一步删除文件，是在打开 Obsidian 的情况下删除的是吗？此外在 Windows 上有修改过对应文件吗？
2. 此外，linux 上删除后，手动同步后，此时在 s3 的网站上看，对应文件是删除还是没有被删除状态呢？

**Comment by Yaozhuwa** [comment]
在OB中操作的。
现在我复现不出来了~~~ 抱 歉
