### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by caibimiaokong** [remotely-save/remotely-save#102]
### What happened?

无法访问到对应的存储桶

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using?

webdav

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
请问到底是 s3 还是 webdav 呢？

如果是 s3 的话，建议还是检查一下设置，特别地，endpoint 输入不应该带有 bucket 的部分

**Comment by fyears** [comment]
由于没有收到进一步回复，先关闭了。。
