### ISSUE TITLE
[Bug]: Failed to load plugin remotely-save

### ISSUE THREAD

**Issue by owlright** [remotely-save/remotely-save#103]
### What happened?

I use iphone 6, iOS 12.5.5. After I install the plugin, I can't enable it.
When turning on the switch, it always pop up a message saying "Failed to load plugin remotely-save"

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.21

### Version of Obsidian

1.2.0

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
dup of https://github.com/remotely-save/remotely-save/issues/75 and https://github.com/remotely-save/remotely-save/issues/101

I am sorry to, but I do not have any iOS device that runs old iOS version to debug this.... (The plugin is confirmed to work on iOS 15.)

**Comment by gabornj** [comment]
the same issue appears in my ipad.
is there any way out?
