### ISSUE TITLE
[Feature Request]: MEGA Support

### ISSUE THREAD

**Issue by Azarattum** [remotely-save/remotely-save#110]
### What feature are you suggesting?

In the service list you listed MEGA as “never support” because there’s no JS API available. But there is an unofficial [megajs npm package](https://www.npmjs.com/package/megajs) which runs both in node and in browser. I think it’s functionality would be sufficient to add support for syncing. 

Take a look at their docs here: https://mega.js.org/

### What remote cloud services are you using, or suggesting adding the feature to?

others

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Thanks, I will try to investigate this method. My concern is that I prefer to rely on official sdks as much as possible for better security and support.

**Comment by fyears** [comment]
final decision: will not support mega because of it's complexity

Sorry.
