### ISSUE TITLE
[Bug]: 手动同步出错

### ISSUE THREAD

**Issue by beaufang** [remotely-save/remotely-save#113]
### What happened?

![image](https://user-images.githubusercontent.com/18215661/169043047-d100cf92-5e5f-4d55-b131-0ba3fcdaeb34.png)

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

0.14.6

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
请问可以根据[这里](https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/export_sync_plans.md)导出 sync plan，并且看看 900-other 这个文件夹对应的 json 部分是什么吗？

截图错误是因为文件夹带有开头的 `/` 符号，但是正常来说代码应该已经处理掉，需要看看是哪一个环节有问题

**Comment by beaufang** [comment]
![image](https://user-images.githubusercontent.com/18215661/169297840-24fbf961-cb97-4846-b08b-17939f60e2bb.png)
sync plan 中确实有一个以 `/` 打头的文件夹，但是在 obsidian 目录中是没有这个文件夹。只有一个 900-Other 文件夹，而且是空的
![image](https://user-images.githubusercontent.com/18215661/169298116-0a467bf5-2143-42ec-8c13-2533a6d26d5b.png)

**Comment by beaufang** [comment]
![image](https://user-images.githubusercontent.com/18215661/169523440-e1bce217-0882-4706-9784-152cad9d4caa.png)

**Comment by fyears** [comment]
这看上去是 Obsidian 的一个 bug。在 windows Obsidian 上，按快捷键 ctrl+shift+i 打开 debug 控制台，去到 console tab，输入以下命令按回车，看看 `900-other` 和 `excalidraw` 文件夹对应的两个 json 是怎样的？

```js
app.vault.getAllLoadedFiles()
```

如果还是 `/900-other` （带斜杠前缀） 和 `excalidraw` （不带斜杠前缀）的话，那看上去是 Obsidian 的 bug，我这边可以汇报 bug 且插件的下一个版本做兼容。如果都没有的话，那么还是插件内某个步骤导致了 bug。

**Comment by beaufang** [comment]
今天再手动同步好了。看了下控制台，没有 `/900-other` 这个目录了。谢谢啦

**Comment by fyears** [comment]
啊这，这么神奇。。。那我先关闭了。。。之后还有问题的话可以重开 issue
