### ISSUE TITLE
[Feature Request]: pCloud support

### ISSUE THREAD

**Issue by dist3r** [remotely-save/remotely-save#114]
### What feature are you suggesting?

First of all, thank you for the great work. Could you please add support for pCloud storage as well? It has an official JavaScript API: https://github.com/pCloud/pcloud-sdk-js 

### What remote cloud services are you using, or suggesting adding the feature to?

others

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Amanse** [comment]
pcloud has webdav support, the only downside is it doesn't work with 2FA

**Comment by fyears** [comment]
Final decision: will not implement direct pcloud support due to extra complexity

**Comment by blagi** [comment]
Can you add this Pcloud links to https://github.com/remotely-save/remotely-save/blob/master/docs/services_connectable_or_not.md 
?
