### ISSUE TITLE
[Feature Request]:  Save the deletion information to metadata file even if the plugin don't sync

### ISSUE THREAD

**Issue by HaujetZhao** [remotely-save/remotely-save#118]
### What feature are you suggesting?

Let me first explain what this trying to solve. 

1. On PC, store the vault `test` in a OneDrive `app/remotely-save/test` folder. 
2. On iPhone, using `remotely-sync` connect vault `test` to the OneDrive. 
3. The normal modification and deletion from iPhone could be synced to PC. 
4. If delete a file on PC, it's directly synced to OneDrive (not by remotely-sync plugin), so the deletion does not exist in metadata, and when sync on iPhone, the plugin will re-upload the deleted file. 

So I believe the `remotely-sync` on PC should have a mechanism to save the deletion information to metadata file even if it don't sync to remote server. So that the mobile side can know the PC had some deletion. 

One possible method is to add an `Local` remote server type, when click sync, the plugin just compare the database and the real file list, saving deleted items to metadata, this metadata file will be automatically synced to Cloud by OneDrive or other cloud service APP. 

才知道开发者是说中文的。那我不费劲描述成英文了。用中文解释下：

1. 在 PC 端，将 vault 放到 OneDrive 或者坚果云的同步目录，无需使用 remotely-sync，后台 App 就会自动将更改同步到远端
2. 但如果，在 PC 上删除了文件，这个行为被 OneDrive 或坚果云同步到了云端，当用手机端 remotely-save 去检查时，就会因为云端 metadata 里没有删除信息，误认为是云端没有这个文件，而将手机端本应该被删除的文件重新上传到云端，云端的文件又会被重新下载到 PC 端上，这样，PC 端就删除了个寂寞。

因此，建议，即便 PC 端的 remotely-save 没有向云端进行同步，也可以自动或手动检查下本地文件目录，与数据库比对下，如果发现少了文件，那大概率是用户在 Explorer 中删除了，就把这个信息写到 metadata 中，这个 metadata 肯定会被 OneDrive 同步到云端，这样，手机端一检查，就能知道，PC 端删了哪些东西了。

一个可行的方法是，添加一个「本地」的远程服务器类型，每次同步时，就只检查删除了哪些文件，写入 metadata，把同步的任务交给后台的 OneDrive 这类官方软件（实时性更强）。

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
这里就要增加一个模式：仅生成显式的 metadata 文件且不自动同步。技术上可能不困难，但是感觉用户很难一眼看懂是什么作用的……

**Comment by fyears** [comment]
目前来说本地不会生成显式的 metadata 文件

**Comment by keeyangyy** [comment]
能不能这样考虑，出一个选项：使用第三方软件自动同步，这个选项勾选后，自动在本地生成显式metadata记录删除信息。提到这个主要是考虑到，同步问题主要出在移动端。PC端可以通过同步盘解决，移动端比如ios并没有这种同步盘，安卓有个foldersync，但要调出软件操作毕竟不够友好，因此插件在移动端这里起了很大作用。移动端低频使用，使用前和后各用插件触发一次同步，PC端高频使用，靠同步盘直接开就能用，操作更简洁。当然，我这里只是建议哈，非常感谢开发者，解决了同步问题。

**Comment by fyears** [comment]
> 我发现foldersync可以同步删除操作，不知道他们是怎么做的，好像没有metadata。

**Comment by JunerLee** [comment]
> > 我发现foldersync可以同步删除操作，不知道他们是怎么做的，好像没有metadata。
> 
> 这个，确实是有点神奇，想不通怎么做到的。
> 
> > 使用第三方软件自动同步，这个选项勾选后，自动在本地生成显式metadata记录删除信息。
> 
> 本质上就是本地生成 metadata 文件。这里我思考一下。技术上是可以加的。

这个解决了吗，最近同步也发现了这个问题，PC端的删除会被同步回来，应该就是metadata的缘故。

**Comment by fyears** [comment]
会在更新的 sync 算法中解决此问题。本 issue 先关闭了
