### ISSUE TITLE
[Feature Request]: 使用内置数据库存储文件列表

### ISSUE THREAD

**Issue by HaujetZhao** [remotely-save/remotely-save#119]
### What feature are you suggesting?

因为不太懂这方面的开发，我不确定这个方法的可行性，只能是提一下。

我现在的 vault 中约有 600 个文件，用的远端是 OneDrive，每次在手机端点击同步按钮，都要在第二步「2/8 正在获取远端的元数据」等上 13 秒钟左右。看了下日志，我推测这个阶段，是在等 OneDrive 返回所有文件路径、修改时间、文件大小等信息的 json 回复，这个信息是发送 api 请求，让服务器去实时生成后再返回。像我这样几百个文件的统计就要十几秒，那如果文件过多，超过 1000 个文件，返回文件列表所需的时间只怕会非常长。

所以，我想，可不可以让插件扫描、比对所有本地文件信息，将这些信息更新（相对路径、修改时间、大小）到一个存储在 vault 文件夹内的本地数据库文件，它的体积应该不会很大，同步的时候，不需要请求云服务生成所有文件的目录，只需要下载这一个数据库文件，就可以和本地的数据库对比下哪些文件发生了改动，再合并数据库改动，将修改的文件和更新后的数据库上传到云服务。

如果用 json 的话，冗余数据较多，这个数据库文件会比较大，或许可以使用 sqlite 数据库用于记录文件变化。

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> 看了下日志，我推测这个阶段，是在等 OneDrive 返回所有文件路径、修改时间、文件大小等信息的 json 回复，这个信息是发送 api 请求，让服务器去实时生成后再返回。像我这样几百个文件的统计就要十几秒，那如果文件过多，超过 1000 个文件，返回文件列表所需的时间只怕会非常长。

大体上是你描述的那样运作。但是这里只是下载 json 而不是实际内容，即使1000个文件也不会超过几 mb 。耗时很长可以先看看是不是网络问题。


> 所以，我想，可不可以让插件扫描、比对所有本地文件信息，将这些信息更新（相对路径、修改时间、大小）到一个存储在 vault 文件夹内的本地数据库文件，它的体积应该不会很大，同步的时候，不需要请求云服务生成所有文件的目录，只需要下载这一个数据库文件，就可以和本地的数据库对比下哪些文件发生了改动，再合并数据库改动，将修改的文件和更新后的数据库上传到云服务。

你说的这个东西，本质上和“服务器实时生成的 json”是同一个东西，唯一可能节省的是服务器**生成 json** 的时间，而不是下载 json 的时间。而且代价是**失去**了用户直接编辑服务器内容的能力。例如，有时候用户直接在网页版 onedrive 编辑文件，那么就会和这个数据库记录的就不一致了。最稳妥还是用服务器实时生成当前状态。

综上，暂不考虑用生成数据库的方式。不过耗时问题之后可能会看看怎么解决。
