### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Xieleilab** [remotely-save/remotely-save#121]
### What happened?

使用坚果云webdav同步，第一次同步了一部分文件后，过半个小时再点击同步，就无法把文件上传到坚果云了

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

0.14.6

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
出现了什么错误提示呢？此外坚果云有 api 数量限制，可能触发上限了。
