### ISSUE TITLE
[Bug]: 在安卓上同步s3上的视频资源，视频有概率分片

### ISSUE THREAD

**Issue by OriOYue** [remotely-save/remotely-save#123]
### What happened?

问题：设置了密码，将云端内容清空后，在PC上传一个视频（39M，名称：冬日如梦.mp4），并同步到S3（腾讯COS）上，最后在安卓上同步视频资源时，该视频会被分成12个小视频（名称：冬日如梦_234243423312424.mp4），导致视频文件被破坏。
但是从COS上可以看出，视频上传时并没有分片（S3上有一个38M的文件），应该是在安卓端发生了分片。

该情况在之前也发生过（当时可以在无密码，s3/onedrive情况下都会复现，当时我将进阶设置中的并行度从20设置为默认的5后，问题就解决了，所以并没有反馈）

情况很迷惑，只有部分视频会出现这种情况，感觉与视频大小无关（上次这种情况发生在100M的视频文件上，当时39M的视频没有分片，而现在又发生在了39M的视频上）。

因为自己有同步视频文件的需要，希望大佬能解决和解答一下，感谢！

### What OS are you using?

Android

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

0.14.6

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
对于 s3 分片上传下载，应该是截图这个选项控制，parts concurrency ，是 s3 设置里面的子设置。麻烦设置成 1 规避一下。

![3BB54550-9545-46C1-9BA1-5C3E59ED729E](https://user-images.githubusercontent.com/1142836/171384877-86c1ba1f-d722-4f58-987b-4e969debfaee.jpeg)

**Comment by fyears** [comment]
我这边无法复现。。。

请问这样操作再试试？

1. 服务器端设置 cors，可以参考[这个](https://github.com/remotely-save/remotely-save/blob/master/docs/s3_cors_configure.md)，一般来说都是设置 Origin 和 exposed headers，不同平台设置方式略有不同。
2. remotely save 插件这个“bypass cors issue locally”设置为 no
  ![image](https://user-images.githubusercontent.com/1142836/171387541-a5dc43a2-f30c-44dd-b06b-c447c826fdc5.png)
3. 再同步

**Comment by OriOYue** [comment]
原先我那个视频是在 `90-资源文件夹/媒体资源区`文件夹下，
刚才我将视频移动到`95-媒体资源区`文件夹下，问题解决了，
我又上传了新的视频也没出现问题。
（并且我将PC端的CROS恢复为enable，移动端的分块并行度改为默认的20，问题也没有出现）
看来是不能在二级目录下。

> 大佬，以后能不能优化一下对大文件的上传和下载，我在PC端设置密码的情况下，上传一个100多M的视频，OB就会黑屏，需要重启才能正常使用OB，再次上传视频，还是一样的情况。因为有上传视频的需要，所以希望支持几百M视频上传下载，感谢！

**Comment by OriOYue** [comment]
> 服务商：腾讯COS，不太清楚path style是什么意思，是S3的服务地址（cos.ap-beijin.myqcloud.com），还是其他？
我在S3上下载了一个文件，其地址类似这样：https://存储桶名称.cos.区域.myqcloud.com/文件名称?配置=key

> 感谢解答，只能说期待官方优化了。

**Comment by OriOYue** [comment]
我刚设置path style（PC安卓都设置），再同步二级目录下的视频，仍然出现分片现象。

**Comment by fyears** [comment]
此外也建议你把 obsodian android 版本升级到最新版再试试。

**Comment by OriOYue** [comment]
哈哈，我也实在没法了，我刚在一个全新的库上同步了二级目录下的视频，竟然没有分片。感觉就是偶然发生。毕竟上次也是这样，同一个目录下，有些视频会分片，有些不会，而同一个视频在不同的目录下也有不同的结果。我还是选择妥协，不同步大文件了。

安卓上的也是最新版本。

最后感谢大佬的耐心解答。

**Comment by fyears** [comment]
谢谢反馈。这个确实没有较好办法 debug 和处理。

一个简单的方法就是，一般来说我们认为大文件不会经常改动，本插件支持忽略大文件，然后每次变更后手动同步少量大文件。
