### ISSUE TITLE
[Bug]: Failed to load on mobile

### ISSUE THREAD

**Issue by williamhartono** [remotely-save/remotely-save#125]
### What happened?

After installing the plugin via the Obsidian mobile app, it cannot be enabled. A banner pops up, saying: **“Failed to load plugin remotely-save”**.

I checked the phone’s file manager, and sure enough, the remotely-save **directory was saved correctly**, hidden within the Obsidian directory.

**Other community plugins can be enabled successfully** (e.g. “Advanced Tables”), and remotely-save also works on my iPad also running the Obsidian mobile app.

This issue was encountered on a Huawei P40 Pro Android phone (Android version 10, EMUI 11.0.0, 
![Screenshot_20220531_114413_md obsidian](https://user-images.githubusercontent.com/106573860/171094682-a8339823-8c96-4b12-81ee-2de80c9d33c5.jpg)
![Screenshot_20220531_114437_com huawei filemanager](https://user-images.githubusercontent.com/106573860/171094693-890eca62-1696-468d-8b9b-c14a74e076a2.jpg)
no Google Play Services).

### What OS are you using?

Android

### What remote cloud services are you using?

others

### Version of the plugin

0.3.25

### Version of Obsidian

1.0.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Currently no clues yet. Would you please upgrade the Obsidian and try again? Currently the official Obsidian mobile version is 1.2.0 .

**Comment by williamhartono** [comment]
Hi again, sorry for

**Comment by fyears** [comment]
Thank you for your report!
