### ISSUE TITLE
[Feature Request]: Allow syncing to a specified Onedrive folder

### ISSUE THREAD

**Issue by nyejon** [remotely-save/remotely-save#127]
### What feature are you suggesting?

Hi,

It would be great to be able to synchronise the vault to a specific folder on OneDrive instead of the apps/remotely-save folder.

Thanks,
Jonathan

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
dup of https://github.com/remotely-save/remotely-save/issues/293 .
Similar design result of OneDrive and Dropbox.
