### ISSUE TITLE
[Bug]: Minio is not connectability

### ISSUE THREAD

**Issue by WonderfulSoap** [remotely-save/remotely-save#128]
### What happened?

Couldn't connect to Minio.

Firstly, I started a minio server by docker and crated a new bucket named `note` in minio admin console.
```shell
docker run --rm \
  -p 9000:9000 \
  -p 9001:9001 \
  -e "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE" \
  -e "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
  -e "MINIO_REGION: us-east-1" \
  quay.io/minio/minio server /data --console-address ":9001"
```
![image](https://user-images.githubusercontent.com/86732447/171822092-b09d56e5-14cf-4301-93f8-02739b757ece.png)

And then, I set these info in plugin:
```
Server: S3 or compatible
Endpoint: http://localhost:9000
Region: us-east-1
Access Key ID: AKIAIOSFODNN7EXAMPLE
Secret Access Key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
Bucket Name: note
S3 URL style: Path-Style
CORS: Enable
Parts Concurrency: 20
```

After clicking the `check` button, this error happened:
![image](https://user-images.githubusercontent.com/86732447/171820701-b3a2604f-4962-43cc-ab13-b070407ce6d3.png)

And this is the debug info in console:
```
UnknownError
    at n [as constructor] (eval at <anonymous> (app.js:1:1494667), <anonymous>:211:88780)
    at new n (eval at <anonymous> (app.js:1:1494667), <anonymous>:211:129983)
    at eval (eval at <anonymous> (app.js:1:1494667), <anonymous>:211:159783)
    at eval (eval at <anonymous> (app.js:1:1494667), <anonymous>:177:281483)
    at Object.eval [as next] (eval at <anonymous> (app.js:1:1494667), <anonymous>:177:281588)
    at a (eval at <anonymous> (app.js:1:1494667), <anonymous>:177:280327)
```

### What OS are you using?

Windows

### What remote cloud services are you using?

others

### Version of the plugin

0.3.25

### Version of Obsidian

0.14.6

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
https://stackoverflow.com/questions/65000942/how-to-fix-the-unknown-error-in-accessing-s3-bucket

I do not personally use minio, but is it possible that it needs some permissions configurations?

**Comment by fyears** [comment]
might be related to custom port. tests and supports discussed in: #416
