### ISSUE TITLE
[Bug]: getting_remote_file_list error

### ISSUE THREAD

**Issue by andy2718** [remotely-save/remotely-save#129]
### What happened?

I use remotely-save to sync between my pc and iphone successfully. But failed when i use my android phone. 

### What OS are you using?

Android

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

1.2.0(50)

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Newdea** [comment]
也遇到这个问题了，之前是在电脑上进行第一次同步，但没同步完就关了OB，然后在手机上想继续同步，就报错了

**Comment by fyears** [comment]
What specific error did the plugin return?

And would you like to update the Obsidian to the latest version and try the full syncing process again? (Currently the latest Obsidian is 1.2.3)

**Comment by andy2718** [comment]
I update the Obsidian and sync successfully.
