### ISSUE TITLE
[Bug]: repetitively creating subfolders

### ISSUE THREAD

**Issue by Wilson0125** [remotely-save/remotely-save#133]
### What happened?

each time I sync my notes, it will create a new folder in the original one and save the new .md files inside
ex:
emotely-save\note.md
became
remotely-save\remotely-saved\note.md
and if sync again, it would be
remotely-save\remotely-save\remotely-saved\note.md

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

0.14.15

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
(you can use Chinese to report the issue)

Could you please create a **test vault**, and create some **not empty** test notes (syncing to onedrive will skip empty files) and test folders inside it, without installing any other plugins, and try to reproduce the error?

If you can still reproduce the error in the test vault, would you please export the sync plan following the instruction [here](https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/export_sync_plans.md)? Just remember to remove any personal sensitive information before posting here.

**Comment by Wilson0125** [comment]
Thank for your reply, but the problem still exists  :(
Here's the sync plan

{
  "ts": 1656492286623,
  "tsFmt": "2022-06-29T16:44:46+08:00",
  "remoteType": "onedrive",
  "syncTriggerSource": "manual",
  "mixedStates": {
    "remotely-save/": {
      "key": "remotely-save/",
      "existLocal": true,
      "sizeLocal": 0,
      "existRemote": false,
      "deltimeRemote": 1656492252642,
      "deltimeRemoteFmt": "2022-06-29T16:44:12+08:00",
      "decision": "createFolder",
      "decisionBranch": 15
    },
    "test vault/": {
      "key": "test vault/",
      "existLocal": true,
      "mtimeLocal": 1656492272324,
      "mtimeLocalFmt": "2022-06-29T16:44:32+08:00",
      "sizeLocal": 0,
      "existRemote": false,
      "changeLocalMtimeUsingMapping": true,
      "decision": "createFolder",
      "decisionBranch": 13
    },
    "test vault/test.md": {
      "key": "test vault/test.md",
      "existLocal": true,
      "mtimeLocal": 1656492279072,
      "mtimeLocalFmt": "2022-06-29T16:44:39+08:00",
      "sizeLocal": 4,
      "existRemote": false,
      "changeLocalMtimeUsingMapping": true,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
    },
    "未命名/": {
      "key": "未命名/",
      "deltimeRemote": 1656492250060,
      "deltimeRemoteFmt": "2022-06-29T16:44:10+08:00",
      "existLocal": false,
      "existRemote": false,
      "deltimeLocal": 1656492272324,
      "deltimeLocalFmt": "2022-06-29T16:44:32+08:00",
      "decision": "uploadLocalDelHistToRemoteFolder",
      "decisionBranch": 8
    },
    "test vault/未命名.md": {
      "key": "test vault/未命名.md",
      "deltimeLocal": 1656492276701,
      "deltimeLocalFmt": "2022-06-29T16:44:36+08:00",
      "existLocal": false,
      "existRemote": false,
      "decision": "uploadLocalDelHistToRemote",
      "decisionBranch": 6
    }
  }
}

**Comment by fyears** [comment]
should be fixed in latest version
