### ISSUE TITLE
[Feature Request]: 同步的速度疑问

### ISSUE THREAD

**Issue by YIRU69** [remotely-save/remotely-save#134]
### What feature are you suggesting?

首先十分感谢作者的付出，你的插件让我的同步变的更加了快捷

我一直有一个疑问，一开始我用的同步方式的dropbox，因为是在国外，需要科学访问，我当时对速度归与是这个原因

后来在论坛上看到你的回答，我最近尝试使用了S3进行同步，使用了腾讯云，的确是快了很多，这个快是指的第8步

随之而来我就产生了疑问，为何第1-7步会需要这么多时间，我同步大概需要30s-40s的时间，其中第8步只需要1s的时间

所以请问可以优化这个问题吗，万分感谢

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
前面几步是下载 s3 的文件列表，和 meta 文件。然后和本地列表进行对比，看有什么文件是新增和删除的，从而决定上传下载哪些文件。

假如你是增量同步的话，最后一步是只会上传下载变动了的文件。

一般受限于下载速度，以及 cpu 运算速度（因为对比文件列表是用 js 完成的）。之后如果有时间的话我想想怎么优化，现在先保证正确性。
