### ISSUE TITLE
[Feature Request]: Need incremental synchronization of WebDAV

### ISSUE THREAD

**Issue by StevenGLee** [remotely-save/remotely-save#136]
### What feature are you suggesting?

Some cloud storage providers impose restrictions on the request number during a certain period of time, e.g., Nutstore (Jianguoyun) limits the number of WebDAV requests from third-party applications to 1500 per 30 minutes. Since there are over 1700 files in my vault, I can't sync the vault to my mobile devices completely without increment synchronization. Hope Remotely Save can implement this feature. 

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Currently the plugin always uses incremental synchronization. If you cannot sync the full vault at one time, you can just start syncing again after the rate-limit period.

**Comment by StevenGLee** [comment]
> Currently the plugin always uses incremental synchronization. If you cannot sync the full vault at one time, you can just start syncing again after the rate-limit period.

Thank you. I have just realized that it is the screen-off that prevents my vault from syncing completely.
