### ISSUE TITLE
[Bug]: Keeps theme after delete

### ISSUE THREAD

**Issue by JustAStudentOfTechnology** [remotely-save/remotely-save#137]
### What happened?

Downloaded theme from community themes. Deleted it and it kept synchronizing the theme back. I recommend creating an inventory for certain settings that when they are changed (item removed) it wont re-sync the old item. 

### What OS are you using?

Windows, Android

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

0.14.15

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sytone** [comment]
There is no tracking in obsidian for files in the .obsidian directory. This means there is no way to know in the plugin if the theme was deleted as it is in the .obsidian directory. So the plugin will replicate the file back so it matches remote and you do not have data loss. 

To remove you need to delete from all clients and also remote. Then next sync will not find it on the remote and pull it down.

**Comment by fyears** [comment]
As sytone says, `.obsidian` is special and this plugin do not have a better way to sync this folder right now. Sorry.
