### ISSUE TITLE
[Feature Request]: Allow syncing to a specified Dropbox folder

### ISSUE THREAD

**Issue by domOrielton** [remotely-save/remotely-save#140]
### What feature are you suggesting?

Very similar to [#127](https://github.com/remotely-save/remotely-save/issues/127) but adding as  #127 is for OneDrive, this is for Dropbox.

It would be great to be able to synchronise the vault to a specific folder on Dropbox instead of the apps/remotely-save folder.

Thanks!

### What remote cloud services are you using, or suggesting adding the feature to?

Dropbox

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
dup of https://github.com/remotely-save/remotely-save/issues/293
