### ISSUE TITLE
[Bug]: In some cases, synchronization may lose data.

### ISSUE THREAD

**Issue by gclove** [remotely-save/remotely-save#141]
### What happened?

I forgot the details, but it's roughly like this.

> 1. I created a new note file on computer A and clicked sync once.

I forgot the prompt at the time, but it is possible that the prompt was successful.

> 2. When I click sync on another computer B, I sync to a file with such content.
> Then I edited other files on B and clicked sync.

> 3. After computer A is synchronized, the file also becomes like this.

---

Is the key point in step 2?
I guess the pull down might get the wrong file ?

```html
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml'>
  <head>
    <meta content='text/html; charset=utf-8' http-equiv='content-type' />
    <style type='text/css'>
      body {
        font-family: Arial;
        margin-left: 40px;
      }

      img {
        border: 0 none;
      }

      #content {
        margin-left: auto;
        margin-right: auto
      }

      #message h2 {
        font-size: 20px;
        font-weight: normal;
        color: #000000;
        margin: 34px 0px 0px 0px
      }

      #message p {
        font-size: 13px;
        color: #000000;
        margin: 7px 0px 0px0px
      }

      #errorref {
        font-size: 11px;
        color: #737373;
        margin-top: 41px
      }
    </style>
    <title>OneDrive</title>
  </head>
  <body>
    <div id='content'>
      <div id='message'>
        <h2>Our services aren't available right now</h2>
        <p>We're working to restore all services as soon as possible. Please check back soon.</p>
      </div>
      <div id='errorref'>
        <span>Ref A: 08B43CB6B7BB416A8115E95D040A8A75 Ref B: TYO01EDGE3507 Ref C: 2022-06-19T12:46:09Z</span>
      </div>
    </div>
  </body>
</html>
```

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

0.14.15

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fenixfu** [comment]
got exactly the same error page replacing the original note
also using onedrive, syncing between my windows 10 pc and my android cellphone and my ipad

**Comment by fyears** [comment]
> Our services aren't available right now

As the contents indicate, may be it's not the bug from the plugin side.
