### ISSUE TITLE
[Feature Request]: 求onedrive企业版同步功能

### ISSUE THREAD

**Issue by sometimes-naaive** [remotely-save/remotely-save#143]
### What feature are you suggesting?

希望能支持onedrive企业版，目前用的学校给的微软教育版a1账号，连接时提示需要管理员批准，但是我用其他软件如joplin就可以直接连接上，求作者大大更新支持onedrive企业版

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
dup of https://github.com/remotely-save/remotely-save/issues/11
主要是没有账号测试开发。。。

**Comment by hi-yiyang** [comment]
我可以为你创建一个不含任何信息的、可以任意使用的空Onedrive for Business账号。Let me know if that would be helpful.

> dup of #11 主要是没有账号测试开发。。。

**Comment by berot3** [comment]
@fyears please see response by @hi-yiyang :)
