### ISSUE TITLE
[Feature Request]: Use webhooks for onedrive sync instead of polling

### ISSUE THREAD

**Issue by ferezoz** [remotely-save/remotely-save#146]
### What feature are you suggesting?

It would be great to use webhooks for Onedrive instead of polling for changes. Onedrive API offers webhooks to get notifications on changes https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/using-webhooks?view=odsp-graph-online.

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
No considered at this moment.

The main reason is that the logic are the same for different backend (s3, webdav, onedrive...) now. If the "webhooks" are added, a lot of logics have to be rewritten.
