### ISSUE TITLE
[Bug]: Does not sync the file when its content is empty

### ISSUE THREAD

**Issue by ferezoz** [remotely-save/remotely-save#147]
### What happened?

When you don't have content in a file it won't sync. This causes two issues:

- When you create a file and haven't added any content, it won't sync
- When you have any content in a file and you remove all of its content at once, it won't sync and your other device will still see the content that it had before

To work around this you have to add at least one letter to the file and then it will sync but it doesn't seem right.

This is happening using OneDrive but might be happening for the other cloud services.

### What OS are you using?

macOS

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

0.14.15

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
That's intended. Because OneDrive doesn't support uploading empty files.
