### ISSUE TITLE
[Bug]: Password does not support dashes on iOS (OneDrive for personal)

### ISSUE THREAD

**Issue by mimalenke** [remotely-save/remotely-save#148]
### What happened?

If I use a password containing dashes like `My-Password` the sync to "OneDrive for personal" will sucessfully upload the file to server, but a following sync fails on iOS-client (iPad 8. Gen, iOS 15.5).  Other clients (e.g. Android) can sync without problems.

Error message on iPad:
> remotely-save-1656849124016: abort sync, triggerSource=manual, error while checking_password
> invalid_text_after_decryption

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.2.3

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
That's unexpected. If you use a new test vault (avoid damages to any real-usage vaults!) and use a password without dash, can the test files synced correctly?

**Comment by fyears** [comment]
Close cuz no more info
