### ISSUE TITLE
[Bug]: Android can not load this plugin

### ISSUE THREAD

**Issue by SUOMALILI** [remotely-save/remotely-save#149]
### What happened?

I install a brand new version of obsidian and install nothing but ...

### What OS are you using?

Android

### What remote cloud services are you using?

others

### Version of the plugin

0.3.25

### Version of Obsidian

0.14.15

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by tarunyad** [comment]
exactly same problem with me, it was working fine till yesterday i formatted my Chromebook and installed from play store again  now its showing "failed to load plugin"

**Comment by EuriNaiz** [comment]
I'm here exactly for that reason, today my Chromebook got updated and cannot load the plugin... It works fine with the appimage, but it doesn't on android app. :(

**Comment by tarunyad** [comment]
> I'm here exactly for that reason, today my Chromebook got updated and cannot load the plugin... It works fine with the appimage, but it doesn't on android app. :(

well i updated to chromeos beta and link stopped working ... perhaps its the os problem.. i also read somewhere in beta update document stack is frozen ... so i reverted back to stable, power-washed and it started working again. if u r trying this make sure ur vault is backed up.

**Comment by fyears** [comment]
Might be dup of https://github.com/remotely-save/remotely-save/issues/177

I would like to debug this, but i don't have a chromebook...

**Comment by fyears** [comment]
closed cuz no more info, no way to reproduce

**Comment by EuriNaiz** [comment]
I discovered the reason why it happens, it happens when ChrOS is updated but the web components (from playstore) is not updated, it can be easily solved just downloading all playstore updates et voilà.

**Comment by fyears** [comment]
@EuriNaiz wow this is absolutely helpful info!!! i will add the solution to documents

**Comment by fyears** [comment]
might be this: https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en&gl=US

**Comment by EuriNaiz** [comment]
:D Good to be helpful, and yes, it is com.google.android.webview, I can predict when it could fail, but idk why, I know ChrOS has android in a VM, so in theory it shouldn't affect.
