### ISSUE TITLE
[Bug]: Desktop App Overwrites Other Changes

### ISSUE THREAD

**Issue by bradenroper** [remotely-save/remotely-save#151]
### What happened?

I may have missed something, but it seems to me that the desktop app (Windows 11) saves out its own version as the most up-to-date.

For example, I can

1. Make a change on Desktop
2. Start sync on Desktop
3. See the change on Dropbox website
4. Start sync on Android
5. See desktop changes on Android

However, if I go the other way

1. Make a change on Android
2. Start sync on Android
3. See the change on Dropbox website
4. Start sync on Desktop
5. Change does not show on Desktop, and the file on Dropbox website has been updated to the Desktop file version.

It seems to be that the desktop version is effectively saving before attempting sync.

### What OS are you using?

Windows, Android

### What remote cloud services are you using?

Dropbox

### Version of the plugin

0.3.25

### Version of Obsidian

0.15.6

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by bradenroper** [comment]
Could potentially also be an issue with the desktop apps ability to pull files from Dropbox or compare timestamps? I noticed that time stamps in the Windows explorer do not update upon sync, but after running the sync command on the Desktop app, I will not get the updated version even if the Dropbox website reports a timestamp more recent than the local file on WIndows.

This could also be an issue with the way I set up my Vaults. I wasn't sure the recommend way to open the "same" Vault on Windows and Android, so I ended up creating one of the same name and installing Remotely-Save to both of them. Is there a more recommended way of opening a Vault that already exists on Dropbox but does not yet exist locally?

**Comment by fyears** [comment]
the latest version of the plugin, keeps a mapping of local modified time and remote modified time **after the initial sync**.

#- [ ] but on a different machine it's impossible to do that, because no where can we obtain the **local modified time on other machines**. Basically modified time on every machine is distributed.
