### ISSUE TITLE
[Feature Request]: S3 Sync support for old SignatureV2 method.

### ISSUE THREAD

**Issue by tywtyw2002** [remotely-save/remotely-save#152]
### What feature are you suggesting?

Lots of s3 compatible storage still not merge to signature v4. 

Please add this feature to let `[remotely-save](https://github.com/remotely-save/remotely-save)` work with signature v2.

> Amazon removed support for signature v2 support in [AWS SDK for JavaScript v3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html) since it's now mostly deprecated across AWS infrastructure. Unfortunately, with the widespread adoption of S3 protocols, the need for less secure (but much computationally lighter) v2 signing is still desirable.

https://www.npmjs.com/package/aws-sdk-signature-v2

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Sorry, but due to the extra complexity, I am not adding this support right now. And, I would like the library dependencies being "official" as many as possible. 

Pull requests are welcome although.
