### ISSUE TITLE
[Feature Request]: Sync conflicts solution and version control

### ISSUE THREAD

**Issue by HomoY** [remotely-save/remotely-save#155]
### What feature are you suggesting?

Dear developer,

Thank you so much for your efforts, I have a deep trial for your work and I come up with two enhancements that might be helpful for you to improve it!

I have done an experiment on two computers sync by webdav. First, I change a file in one machine, and then, I change the same file but by different text in the other one. If I sync the first, and then the second. The modification in the second would be overwrited by the first. I wonder if we could add a feature for users to choose which contents to store if conflicts, because people would be careless if they happened forget to first sync and modification when they switch to another machine. 

Besides, the file stored in the server would be dangerous when someone just happens to delete it, or he carelessly delete the notes locally. If we can have a version control for few days, the plugin would be great!

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by soyzhc** [comment]
so do i

**Comment by Kelatte** [comment]
i highly agrees with your!

**Comment by Sakura-Qy** [comment]
我也觉得很有必要

**Comment by fyears** [comment]
That's technically difficult. For example, what is the UI/UX if there are **many files** conflicting??? And how does the plugin decide whether the user what to change the file actually or what to recover the file?? Pull requests are welcome though.

If version control is involved, may be [git](https://github.com/denolehov/obsidian-git) is better..

**Comment by theMasix** [comment]
I suggest CRDT-based solutions.
Let's discuss!
https://github.com/remotely-save/remotely-save/issues/278
