### ISSUE TITLE
[Feature Request]: 同步.trash文件夹

### ISSUE THREAD

**Issue by youtiaoguagua** [remotely-save/remotely-save#156]
### What feature are you suggesting?

目前好像不会同步.trash文件夹

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
由于 Obsidian 机制问题，不会同步 `.` 开头的隐藏文件夹
