### ISSUE TITLE
[Bug]: cannot sync files in the second folder

### ISSUE THREAD

**Issue by walyitee** [remotely-save/remotely-save#157]
### What happened?

windows电脑上在库文件夹下新建了个文件夹，里面新增一个文件，同步之后，坚果云里有二级目录及其下的文件，而我在安卓手机和Mac上同步后只有显示新建的二级目录，目录里的文件显示为空

### What OS are you using?

Windows, macOS, Android

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

0.15.6

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by NightPhoenixRus** [comment]
I have a very similar problem: plugin works good with files and folders in main vault directory, uploads all vault files to cloud service, but doesn't download any content located in vault subdirectories from cloud. 

OS: Android 9, Windows 7 SP1
Cloud service: Yandex.Disk (WebDAV)
Plugin version: 0.3.25
Obsidian version: 1.3.1 (65) API v0.15.9 (Android), v0.15.9 (Windows)
Password wasn't used
I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
你好，Depth Header Sent To Servers 设置麻烦设置为 only supports depth='1' ，再试一下？

**Comment by fyears** [comment]
应该问题处理了的。先关闭了。
