### ISSUE TITLE
[Bug]:Files with double quotes in their names cannot be synchronized

### ISSUE THREAD

**Issue by hakter** [remotely-save/remotely-save#159]
### What happened?

when sync ，will report undefined object error

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.3.0 api v0.15.6

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
MIGHT be duplicated of https://github.com/remotely-save/remotely-save/discussions/176  ? Because OneDrive are likely to follow Windows file name restrictions, so it doesn't support double quotes in file names.
