### ISSUE TITLE
[Bug]: (webdav)error while getting_remote_extra_meta,Invalid response: 503 Service Unavailable

### ISSUE THREAD

**Issue by jsjcjsjc** [remotely-save/remotely-save#160]
### What happened?

Hi
Thanks for your plugin, it's really cool ;-)

 after several times sync, it will display "error while getting_remote_extra_meta,Invalid response: 503 Service Unavailable"
could you please help me with it ?
![](http://cloud.g60.net/d/cloud/temp/img/69a6fe64-9f7c-49b8-91a7-378af556e33f.png)
Thanks

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

0.15.6

### Using password or not

- [x] NO.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Probably using Jianguoyun and dup of https://github.com/remotely-save/remotely-save/issues/284
