### ISSUE TITLE
[Bug]: deletion issue  caused by sync

### ISSUE THREAD

**Issue by johnsonzx** [remotely-save/remotely-save#162]
### What happened?

open a new File Folder  and sync, we can get all the files from cloud service( such as qcloud cos bucket), then if you rename this File Folder,  you can get an empty Folder with a different name, and then if you run sync in this renamed Folder , you deleted all the files.

### What OS are you using?

macOS, iOS (iPhone, iPad)

### What remote cloud services are you using?

others

### Version of the plugin

latest version

### Version of Obsidian

latest version

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
cannot reproduce the issue using qcloud cos 腾讯云.
