### ISSUE TITLE
[Feature Request]: Ignore specified files / patterns

### ISSUE THREAD

**Issue by YangHanlin** [remotely-save/remotely-save#163]
### What feature are you suggesting?

I would like to be able to ignore certain files (i.e. local versions are not compared to, uploaded to or downloaded from remote versions) according to paths or patterns specified by me. This feature can be especially helpful when the option `Sync Config Dir (experimental)` is enabled. To name 2 examples:

- Ignoring `.obsidian/workspace` to avoid synchronizing pane layouts and opened files across all devices. I'd like to open the graph view on Obsidian desktop, but do not want it on Obsidian for Android as it takes up too much horizontal space on mobile views. Ignoring it is also [considered best practice](https://help.obsidian.md/Advanced+topics/How+Obsidian+stores+data#Per+vault+data) by the official docs.
- Ignoring `.obsidian/plugins` and `.obsidian/community-plugins.json` to exclude plugins from synchronization. I've installed many plugins on Obsidian desktop but do not want all of them on the phone, which cause lags on start.

Anyway, thanks for this great plugin for saving me time and expenses that would be otherwise consumed with Obsidian Sync. Thanks for your great work 😀

### What remote cloud services are you using, or suggesting adding the feature to?

_No response_ (It seems not related to a specific remote cloud service type)

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by YangHanlin** [comment]
I'll try working on it.

**Comment by Ellpeck** [comment]
I agree that this would be incredibly useful, especially for excluding the workspace file from sync, but also for excluding various files that might not be necessary on some devices.

**Comment by langshangyuan** [comment]
Quite agree this enhancement. Maybe include specify files inside .obsidian folder such as community plugin configuration files, or data files is easier to do. And if it's possible to sync file start with the dot symbol which is regularly considered as hidden files in Linux and macOS.

**Comment by fyears** [comment]
The new pr will be merged
