### ISSUE TITLE
[Feature Request]: 同步腾讯云的时候我想能不能做到一个key进行读写修改的权限，另外创建一个guest全的key给朋友进行分享，只能下载不能上传

### ISSUE THREAD

**Issue by ictmuzi** [remotely-save/remotely-save#165]
### What feature are you suggesting?

同步腾讯云桶的时候我想能不能做到一个key进行读写修改的权限，另外创建一个guest全的key给朋友进行分享，只能下载不能上传
![b899d22951c9263d4700a4d38988b94](https://user-images.githubusercontent.com/77148385/183633361-08c95981-9f90-423f-b720-3c2e8d549fcd.jpg)

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [x] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
你好，这里建议查询 s3 的文档，并不属于 remotely-save 的设置范畴。
