### ISSUE TITLE
[Bug]: Sync fails on s3-compatible api even when connection check passes

### ISSUE THREAD

**Issue by FloncDev** [remotely-save/remotely-save#167]
### What happened?

When I setup the sync and and check connectivity, it says the bucket can be accessed.

But when I try and sync, on step 8 it errors with the following
![image](https://user-images.githubusercontent.com/37045958/184223180-7c8c1519-c79e-4804-a469-e4378d952302.png)

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

0.15.9

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
I update the s3 sdk in new version. Please try 0.3.28 or upper. Feel free to recreate an issue if reproducible using a newly created test vault.
