### ISSUE TITLE
[Bug]: 同步出错

### ISSUE THREAD

**Issue by dylan-ing** [remotely-save/remotely-save#169]
### What happened?

在同步过程中会出现一种现象导致obsidian程序崩溃：
同步过程中会卡在一个文件上，可能是一个.md文件或者一张png图片，然后下载速率会迅速达到最大，但一直卡在这个同步文件上（小于1MB），30s左右obsidian就会因为内存问题崩溃闪退

这种情况出现往往会出现在第一次同步数据（数据量比较大）过程中

### What OS are you using?

Android

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

1.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
背后是多文件同步的，所以显示是小文件，可能背后还是在同步某个大文件。

如有怀疑，可以设置“跳过大文件”和减少并行度试试
