### ISSUE TITLE
[Feature Request]: 并行度

### ISSUE THREAD

**Issue by dylan-ing** [remotely-save/remotely-save#170]
### What feature are you suggesting?

希望能够增加自定义并行度功能，当同步文件数比较大但单个文件比较小时，固定的并行度有些不方便

谢谢

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
你好，目前高阶设定里已经支持
