### ISSUE TITLE
[Bug]: 1660487836118：中断同步，同步来源=manual

### ISSUE THREAD

**Issue by zhaoliang0302** [remotely-save/remotely-save#171]
### What happened?

用的坚果云，账号密码都正确，安装完插件第一次同步没问题，再点同步就报错，ipad端也是一样情况
![image](https://user-images.githubusercontent.com/42333702/184541940-9f0d84cc-c439-4647-b86d-763bc9e45fb0.png)

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

0.15.9

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Chenm25** [comment]
+1 I had the same problem today.

**Comment by zhaoliang0302** [comment]
改用腾讯云cos存储一切正常，应该是坚果云限制的

**Comment by Ravenclawer** [comment]
#183 have the same issue, this might be caused by setting up sync on mac and windows

**Comment by Ravenclawer** [comment]
可能是同时在苹果设备和微软设备上同时设置同步导致的，应该和坚果云没有什么关系

**Comment by zhaoliang0302** [comment]
我就是win+ipados，坚果云报错，腾讯云没问题

**Comment by YangHanlin** [comment]
坚果云有请求速率限制，可以等 30 分钟再试。

> **访问频率限制：** 由于WebDAV协议比较占用系统资源，免费版用户限制访问频率为每30分钟不超过600次请求。付费用户限制访问频率为每30分钟不超过1500次请求。

https://help.jianguoyun.com/?p=2064

**Comment by Ravenclawer** [comment]
这个应该不是坚果云的问题，我用的是teracloud，也出现了这个问题，而且一旦出现了这个问题，这个库的同步功能就废，除非新建一个库，新建的笔记可以同步，而把旧的库里的笔记拷贝过去也还是会导致无法同步。
This is not the problem of Webdav provider, I personally use Teracloud and facing the same issue. Once this issue happened in your vault, the entire vault cannot be synced to Webdav even if you wait for days and weeks. unless you create a new vault and write new notes, the new notes can be synced to the Webdav server, but if you copy some of the notes from the previous vault that cannot synced to the current vault, it will make the current vault unable to sync anymore, it's like a virus.

**Comment by zhaoliang0302** [comment]
> 坚果云有请求速率限制，可以等 30 分钟再试。
> 
> > **访问频率限制：** 由于WebDAV协议比较占用系统资源，免费版用户限制访问频率为每30分钟不超过600次请求。付费用户限制访问频率为每30分钟不超过1500次请求。
> 
> https://help.jianguoyun.com/?p=2064

我自己的笔记不到100个md文件，显然同步不会超过限制，但是同步两次就会报错。腾讯云服务器对象存储至今没出错过，费用也低得可以忽略

**Comment by wangtaiyi** [comment]
> 这个应该不是坚果云的问题，我用的是teracloud，也出现了这个问题，而且一旦出现了这个问题，这个库的同步功能就废，除非新建一个库，新建的笔记可以同步，而把旧的库里的笔记拷贝过去也还是会导致无法同步。 This is not the problem of Webdav provider, I personally use Teracloud and facing the same issue. Once this issue happened in your vault, the entire vault cannot be synced to Webdav even if you wait for days and weeks. unless you create a new vault and write new notes, the new notes can be synced to the Webdav server, but if you copy some of the notes from the previous vault that cannot synced to the current vault, it will make the current vault unable to sync anymore, it's like a virus.

那请问有什么好办法解决么
