### ISSUE TITLE
[Bug]: DS_Store file in MacOS would cause 403 conflict

### ISSUE THREAD

**Issue by yodahuang** [remotely-save/remotely-save#172]
### What happened?

Finder may choose to add a hidden `.DS_Store` file in `.obsidian` folder. This file does not exist in other OS. Thus the sync process panics as it see "newer changes from other system" and "newer .DS_Store" file added in local.

### What OS are you using?

macOS

### What remote cloud services are you using?

Dropbox

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by MiracleXYZ** [comment]
I ran into the same issue today, getting a 409 Conflict. Hope we can just ignore these `.DS_Store` files.

**Comment by fyears** [comment]
That's strange. I will try to fix it

**Comment by mak-cs** [comment]
I ran into the same issue today, getting a 409 Conflict. What can I do to?

**Comment by yodahuang** [comment]
My solution is to simply deletehe `DS_Store` file. It just stores some file metadata used in Finder and is normally fine to delete.

**Comment by fyears** [comment]
The new version (>=0.3.28) will skip `.DS_Store`
