### ISSUE TITLE
[Bug]: 本地删除插件后，同步到云端，云端未删除，本地插件又回来了

### ISSUE THREAD

**Issue by WystanW** [remotely-save/remotely-save#173]
### What happened?

目前想删除一个插件，在ob里面点击卸载以后，可以很清楚看到在finder/windows资源管理器里面这个插件文件夹已经被删除了。但是点击remotely save的同步按钮之后，云端并没有删除这个文件夹，反而是本地这个插件文件夹又回来了，remotely save是否不支持插件删除的同步？

（目前使用的是腾讯云COS）

### What OS are you using?

Windows, macOS

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

0.15.9

### Using password or not

- [x] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by WystanW** [comment]
好像没人维护了

**Comment by rLry** [comment]
> 好像没人维护了

同样的问题，只能手动在onedrive云端删除后本地同步才能生效。建议暂时不同步插件和配置文件，仅同步文件本身

**Comment by fyears** [comment]
你好，前一阵比较忙，故此确实有段时间不更新了。

不过，回到原始问题：“是否不支持插件删除”，答案：“是的”，因为插件是隐藏文件夹，目前 Obsidian 没有较好的方式来监听隐藏文件夹的变动
