### ISSUE TITLE
[Bug]: iOS note titles including Windows disallowed characters cause sync failures on Windows

### ISSUE THREAD

**Issue by wshrbn** [remotely-save/remotely-save#174]
### What happened?

iOS allows note titles to have some characters which are disallowed in Windows filenames. Notes with disallowed characters in the title will fail to sync to Windows ("ENOENT" error), and will interrupt the entire sync if enough notes fail to sync.

- iOS disallowed: `\ / :`
- Windows disallowed: `* " \ / < > : | ?`
- Problem characters for sync between iOS and Windows: `* " < > | ?`

**Steps to reproduce:**
1. On iOS, create 1 note with title including at least one of the following characters: `* " < > | ?`. Observe that note can be created successfully.
2. On iOS, sync to OneDrive folder using remotely-save. Observe sync completes successfully.
3. On Windows, sync to same OneDrive folder using remotely-save. Observe sync fails for notes with disallowed characters, but rest of sync continues, with error message: `<NoteTitle>.md: ENOENT: no such file or directory, open '<WindowsDirectory>\<NoteTitle>.md'`
4. On iOS, create 2 more notes with titles including the problem characters, then sync using remotely-save again.
5. On Windows, sync using remotely-save again. Observe entire sync fails with error messages: `too many errors, stop the remaining tasks` and `remotely-save-<unixtimestamp>: abort sync, triggerSource=manual, error while syncing`

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

Windows 0.15.9 / iOS 1.3.0 (63)

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Ravenclawer** [comment]
#183 may caused by the problem this issue explained, I have tried to set up sync between ios, mac and windows and then the sync on windows always failed as I have described in the comment section of the issue #183

**Comment by KhaaL** [comment]
Thank you for the detailed bug report, I've run into the exact same issue. I have remote save on Android, Linux and Windows - and had a file containing a "?" in one of my linux devices. My windows machine did not like that, and removing the offending character from the filename made everyone happy.

This can be a tricky issue to handle, perhaps by stopping the sync from happening unless the potentially offending characters are removed? Or at least give a warning to the user during set up.

**Comment by fyears** [comment]
Hi all. Obviously it's a limitation -- rather than a bug, because the plugin don't or just cannot create the file on different platforms. I am afraid this is better to just change the file names... I'd like to note down the warning in the doc.
