### ISSUE TITLE
[Bug]: Chromebook Not Authorizing for DropBox

### ISSUE THREAD

**Issue by Vyeche** [remotely-save/remotely-save#177]
### What happened?

When I try to connect my DropBox account using my ChromeBook. It opens the link to Dropbox, but then after agreeing I’m returned to the Obsidian app, but not authorized. When I install the deb version of Obsidian the issue goes away. However, in ChromeBook play store it doesn’t work.

![840A05B0-FB7B-45B2-ADD2-929B8DAC8DAD](https://user-images.githubusercontent.com/972377/186800444-d6cddbed-cb46-4c38-a77c-8a05f55a0fca.jpeg)
![986F6018-87C0-4B02-BD47-A5D5C13DFBE9](https://user-images.githubusercontent.com/972377/186800445-f886e3be-6643-4388-b28a-ce1ed3fb35d2.jpeg)
![839D7FC3-6487-45B8-AE52-CD137968DF96](https://user-images.githubusercontent.com/972377/186800447-08f95cca-19dd-4cdc-bc9d-4b541d680c19.jpeg)

Please advice?

### What OS are you using?

Android

### What remote cloud services are you using?

Dropbox

### Version of the plugin

0.3.25

### Version of Obsidian

1.3.1

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
dup of https://github.com/remotely-save/remotely-save/issues/177 , bug from chromebook obsidian?
