### ISSUE TITLE
[Feature Request]: LIVE Synchronize (File Change Monitoring)

### ISSUE THREAD

**Issue by ycbrd** [remotely-save/remotely-save#178]
### What feature are you suggesting?

Monitor the change of files like the offical sync service. Only upload the changed files in every 5s.
This should avoid comparing "last modified time" for each and every single file in a large valut, which certainly takes long in each and every time I sync.
It also spare me from having to manually sync and wait wait wait before I exit the obsidian.

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by e0c615c8e4d846ef817cd5063a88716c** [comment]
I would also like this functionality for S3.

**Comment by whitekr0w** [comment]
I would recommend using the LiveSync plugin for this -- as this this is probably out of scope for this plugin.

**Comment by ycbrd** [comment]
> I would recommend using the LiveSync plugin for this -- as this this is probably out of scope for this plugin.

LiveSync plugin requires a CouchDB to sync, while this plugin doesn't. WebDAV or S3 is much easier to setup than CouchDB.

**Comment by fyears** [comment]
dup of https://github.com/remotely-save/remotely-save/pull/340
