### ISSUE TITLE
[Bug]: Android app crashes when syncing large files

### ISSUE THREAD

**Issue by mpohoril** [remotely-save/remotely-save#182]
### What happened?

Obsidian app crashes when syncing large (??? .mp4) files with Remotely-save. It used to work well, but now 100% cases it crashes. App just closes without any messages.
File sizes are less than 50mb.

Android 12 on Samsung Galaxy S22 Ultra. 5,7 GB free ram of 12 GB 

### What OS are you using?

Android

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.3.1 (65)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by simonla** [comment]
![image](https://user-images.githubusercontent.com/14934570/188217737-77071def-4a48-4a65-8a2a-dece6338c9aa.png)

Same to me

I will try to fix it on capacitor

**Comment by simonla** [comment]
I decompiled obsidian apk and found out why it crashed

Obsidian will convert http response body to base64 string in java. Then return resp to Javascripts world via jsbridge which provided by capacitor plugin

If http response body is huge, JVM will crash because of out of memory

**Comment by simonla** [comment]
Can we download chunk by chunk？

**Comment by fyears** [comment]
But finally we still have to convert the large file into a large `ArrayBuffer` in memory, which is unavoidable.

A better way might be just ignore syncing large files: https://github.com/remotely-save/remotely-save/blob/master/docs/sync_ignoring_large_files.md   (You can manually copy-paste the large files instead of using this plugin, because **usually** large files are not changed frequently!)

**Comment by simonla** [comment]
> But finally we still have to convert the large file into a large `ArrayBuffer` in memory, which is unavoidable.
> 
> A better way might be just ignore syncing large files: https://github.com/remotely-save/remotely-save/blob/master/docs/sync_ignoring_large_files.md (You can manually copy-paste the large files instead of using this plugin, because **usually** large files are not changed frequently!)

But ArrayBuffer will not cause crash
