### ISSUE TITLE
[Bug]: 能帮看看是什么问题吗？无法同步！

### ISSUE THREAD

**Issue by AlesiaGFields** [remotely-save/remotely-save#183]
### What happened?

我最近用windows电脑和mac电脑之间同步。没有用mac之前都能正常同步。但是和mac电脑同步开始就不正常了。提示
remotely-save-1661845536484:中断同步，同步来源=manual,出错阶段=syncling
不知道什么原因。
webdav用的是teracloud这款网盘。
![微信图片_20220831095921](https://user-images.githubusercontent.com/108207534/187576139-8f84a5c3-e6e8-4ae4-acb7-5e71960dc7c5.jpg)

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

0.15.9

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Ravenclawer** [comment]
I have also encountered a similar problem, I'm currently using 0.15.9 on windows and the error message is:
![image](https://user-images.githubusercontent.com/73892411/188304529-d3d89f0d-fcc2-4228-a601-8472f7b6da86.png)

**Comment by Ravenclawer** [comment]
I also encounter this issue after using mac as one of the syncing device

**Comment by Ravenclawer** [comment]
I tried to delete the vault in the cloud, delete the remotely save plugin and re-download it and even applying a new webdav account. these three way all failed

**Comment by Ravenclawer** [comment]
after the above three methods , i tried creating a new vault and it works

**Comment by Ravenclawer** [comment]
I tried to create a new vault and it works well with the remotely save plugin but when I copy-paste the old vault with the error to the new vault as a subfolder, the new vault shows the same error even after I tried to delete the .obsidain folder in the old vault that I placed inside the new vault, something must have happened with files in the old vault. After I delete the old vault, the new vault's sync function returns to normal.

**Comment by PassionPenguin** [comment]
@Ravenclawer a log from backend from your cloud provider can reveal all the issues.

**Comment by fyears** [comment]
status 404 很可能是配置有问题，建议检查网址之类的。如有更明确的 debug log 可以重开 issue 看看。
