### ISSUE TITLE
[Suggestion]: We need two button ,One is upload another is download | sync error

### ISSUE THREAD

**Issue by Yuelioi** [remotely-save/remotely-save#186]
### What happened?

when I sync ,something lost.

Maybe we can use two button, It wont get error anytime in this way.

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Firstly, please always backup your vault before using this plugin.

Secondly, if some files are lost unexpectedly, maybe https://github.com/remotely-save/remotely-save/tree/master/docs/how_to_debug is something you need.

Thirdly, adding "upload" and "download" buttons may be not the solution to "file lost problem". And this plugin is designed to "sync", so currently these two separate buttons are not considered to be implemented. Sorry.
