### ISSUE TITLE
[Bug]: Sync not working 

### ISSUE THREAD

**Issue by promexio** [remotely-save/remotely-save#187]
### What happened?

Hi:
I just try to migrate manually from Joplin to Obsidian.
To do so, I've installed this plugin to sync with my webdav server, already in use with a different folder and account with Joplin since some time.
Now, on Obsidian I get frequenly errors, see below.
Strangely I can bypass this by re-syncing until it works. And all of a sudden everything is synced. Sometimes one file is missing, so I restart syncing until it works also for this file.
Have you any idea ? The same strange behaviour occurs on the iphone app!

### What OS are you using?

macOS, iOS (iPhone, iPad)

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

0.15.9

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by promexio** [comment]
Any ideas / news??

**Comment by fyears** [comment]
If you are using 坚果云 Jianguoyun/NutStore, it's possible that the plugin reaches the api limit. No good way to work around the limit. 

See also https://github.com/remotely-save/remotely-save/issues/284
