### ISSUE TITLE
[Bug]: Webdav Sync not working since Obsidian Update

### ISSUE THREAD

**Issue by SomeNix** [remotely-save/remotely-save#188]
### What happened?

Soo since the Obsidian Update, where you had to update the Auto Updater a few Versions ago, webdav Sync isnt working anymore.
Its maybe Version v0.15.6? 
I spend weeks trying to debug on my end, but on my other devices, which used an older Obsidian Version it still worked, so the Obsidian Update must had broke sth.

Since then there is a 401 Error in the get remote files list Stage every time.
On older Obsidian Versions it worked very well but not now anymore. No Config Changes were made.

`[2022-09-08T23:20:54+02:00] remotely-save-: start sync, triggerSource=manual
[2022-09-08T23:20:54+02:00] ERROR! MESSAGE: Request failed, status 401, STACK: Error: Request failed, status 401
    at new t (app://obsidian.md/app.js:1:1454507)
    at VN (app://obsidian.md/app.js:1:1454662)
    at app://obsidian.md/app.js:1:1455339
    at app://obsidian.md/app.js:1:235078
    at Object.next (app://obsidian.md/app.js:1:235183)
    at s (app://obsidian.md/app.js:1:233922)`

If you need further assistance debugging, im happy to provide that.

### What OS are you using?

Windows,MacOS

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

v0.15.9

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by KosmosisDire** [comment]
I'm having this problem as well

**Comment by XieZhuoJun** [comment]
I faced the same issue using digest mode for authentication.
And the issue is gone when I switched to basic mode on both webdav server and this plugin.

**Comment by fyears** [comment]
new version updates the webdav library dependency.
