### ISSUE TITLE
[Bug]: IOS端更新文件变少

### ISSUE THREAD

**Issue by sky90038528** [remotely-save/remotely-save#189]
### What happened?

![Snipaste_2022-09-12_18-01-12](https://user-images.githubusercontent.com/14570203/189627024-c2df8e86-e8f1-4ea2-a5b0-75107cafdf6e.png)

![2022-09-12 180523](https://user-images.githubusercontent.com/14570203/189627723-2f78f6e4-113d-4466-9571-2c44855a9d24.png)

本地显示有将近两千多个文件，但用手机同步下来只有 897 个文件，并且显示同步完成，导致手机端很多图片文件也不能显示，主要是GIF文件，使用的坚果云webdav

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.3.1

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by bubblezone** [comment]
这个是因为触发了坚果云的限制，不是bug。不推荐坚果云。

**Comment by sky90038528** [comment]
哦哦哦这样啊，原来是坚果云的原因

**Comment by fyears** [comment]
同上，坚果云有 api 数量限制，本插件无法解决。可以隔一段时间同步一下，最终会达到一致的。
