### ISSUE TITLE
[Bug]: 文件乱码

### ISSUE THREAD

**Issue by zhangpanzhan** [remotely-save/remotely-save#191]
### What happened?

webdav设置好以后，文件原来是md格式，同步以后，格式也不是md了，而且文件下载打开后乱码。
环境：obsidian remotely-save + cloudreve webdav

### What OS are you using?

macOS

### What remote cloud services are you using?

webdav

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
请问：试一下用新的测试 vault（不要用真的在用的 vault）+测试文件，只安装本插件，可以复现这个问题吗？

**Comment by fyears** [comment]
没新的回复，先关闭了。
