### ISSUE TITLE
Set base directory as root

### ISSUE THREAD

**Issue by Drezzler** [remotely-save/remotely-save#192]
### What feature are you suggesting?

Thank you so much for this nice plugin..

So, I am using websdav for file sync.

In my server, I have a exposed my entire notes, folder

What should i set in "Remote base directory" setting, so that the sync happens from the exposed folder itself, without creating a subfolder.

I tried setting "/" but it is not allowed in the settings.

Any help is much appreciated.

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Sorry, currently some users might have many vaults, but just one webdav server, so the plugin **always** need different sub folders (by default the vault names) to store different vaults. It's indeed possible to set the base dir as root, but it needs some time to support.

**Comment by superzanti** [comment]
I'm hoping to get this feature. This plugin is almost perfect for my application.
I would really appreciate it!
