### ISSUE TITLE
[Bug]: File Deletion Not Properly Handled in Config Folder

### ISSUE THREAD

**Issue by MiracleXYZ** [remotely-save/remotely-save#194]
### What happened?

When I delete some files in the `.obsidian` folder, the syncing always downloads these files back.

### What OS are you using?

macOS, iOS (iPhone, iPad)

### What remote cloud services are you using?

S3

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
fixed
