### ISSUE TITLE
[Bug]: 自建 S3 endpoint 自定义端口号导致403错误。

### ISSUE THREAD

**Issue by leeh11** [remotely-save/remotely-save#195]
### What happened?

我用Minio自建S3服务器，因为是内网穿透，用自定义端口号访问，报403。

同一套接口我用Joplin测试可以成功访问。

endpoint类似这样：https://aaa.com:9000

logs:
```
2022-09-19T11:46:58+08:00] ERROR! MESSAGE: Request failed, status 403, STACK: Error: Request failed, status 403
    at new t (app://obsidian.md/app.js:1:1454507)
    at VN (app://obsidian.md/app.js:1:1454662)
    at app://obsidian.md/app.js:1:1455339
    at app://obsidian.md/app.js:1:235078
    at Object.next (app://obsidian.md/app.js:1:235183)
    at s (app://obsidian.md/app.js:1:233922)
```

为了测试是否端口号导致的问题， 我在云服务器上搭建了相同的环境，用的默认443端口，可以正常访问。

### What OS are you using?

macOS

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

0.15.9

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by rewalax** [comment]
have the same problem

**Comment by kumaresh0** [comment]
<img width="306" alt="image" src="https://github.com/remotely-save/remotely-save/assets/117239791/396b2e2d-4821-47a7-9db9-0b50227d959d">

**Comment by primejava** [comment]
same question

**Comment by fyears** [comment]
dup of #227

**Comment by fyears** [comment]
#416
