### ISSUE TITLE
[Bug]: OB同步时出现黑屏

### ISSUE THREAD

**Issue by sky90038528** [remotely-save/remotely-save#196]
### What happened?

使用的腾讯云，前面4个多G时同步没问题，现在加一些东西，同步就黑屏了，已知的文件数量和大小如图，麻烦看一下是什么问题
另外求大佬抽时间能适配一下IOS系统 14版本的插件，现在的IOS升级高版本手机会卡，所以一直用低版本的 。。
大佬有没有群加一下？
![image](https://user-images.githubusercontent.com/14570203/191906026-249b5ed0-31e8-4007-adec-d090677033f5.png)

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

0.15.9

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
这里用的是 Obsidian 的 js 进行上传下载，文件太多或者太大的话，可能 js 不支持就挂了，特别是手机这个情况更严重。试试设置里“跳过大文件”吧，一些大文件不经常变动的话可以手动维护而跳过插件同步，
