### ISSUE TITLE
[Bug]: Failed to PutOrAdd in database because not enough space in domain

### ISSUE THREAD

**Issue by NAL100** [remotely-save/remotely-save#198]
### What happened?

I'm trying to sync but am getting an error it says "abort sync, triggerSource=manual, error while generating plan" and then "Failed to PutOrAdd in database because not enough space for domain."

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

1.3.2 (69)

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by SONDLecT** [comment]
I am experiencing the same bug. 
# What OS are you using?
iOS (iPhone, iPad)

# What remote cloud services are you using?
S3

# Version of the plugin

0.3.25

# Version of Obsidian

v.1.0.0

# Using password or not

    Yes.

# Ensure no sensitive information

I ensure that no sensitive information is submitted in the issue.

**Comment by SaladNinja** [comment]
I have the exact same bug with my plugin, too.
Please check this out.

What OS are you using?
iPadOS 16.1(20B82)

What remote cloud services are you using?
ONEdrive for personal 

Version of the plugin
0.3.25

Version of Obsidian
v.1.4.1

Using password or not
No

![IMG_0550](https://user-images.githubusercontent.com/98632417/202066846-5adc113a-ba3f-4f22-97d3-cd1c8fccef2c.jpg)

**Comment by SaladNinja** [comment]
This issue has been solved. I'd put my solution here for anyone having the same problem. Try the following:
1. community plugins-remotely save - reset local internal cache/database
2. reinstall the plugin
should have

**Comment by SONDLecT** [comment]
I am having the same issue, and the suggested solution does not seem to consistently work. iOS (on two devices) and Linux. Using AWS bucket to sync.

**Comment by PupupupuTong** [comment]
> 此问题已解决。我会把我的解决方案放在这里，供任何有同样问题的人使用。请尝试以下操作：
> 
> 1. 社区插件-远程保存 - 重置本地内部缓存/数据库
> 2. 重新安装插件应该有

尝试了这个办法，还是不能同步，但报错信息变了。奇怪的是我的安卓设备一切正常，或许是ios系统的问题？

![IMG_1937](https://github.com/remotely-save/remotely-save/assets/69069739/8c007c08-3c94-4ec4-b25b-ac5895d625ed)

**Comment by fyears** [comment]
Rest everything (in the very bottom of the setting page of the plugin) should help.

**Comment by fyears** [comment]
@PupupupuTong 新建一个vault可以复现的话，可以重来issue看看

**Comment by liutianyan** [comment]
> 尝试了这个办法，还是不能同步，但报错信息变了。奇怪的是我的安卓设备一切正常，或许是ios系统的问题？

后来解决了吗？我也遇到同样的问题

**Comment by liutianyan** [comment]
> @liutianyan 请尝试重置本地内部缓存/数据库，以及如果有多个 vault 的话，都要重置一下。
> 
> 如果是老 ios 系统的话，请升级一下。
> 
> 如果还有问题，请看看有没有安装别的插件，可能别的插件导致缓存塞满了。
> 
> 假如**数据有备份的话**（一定要备份！！！！！！！！！！），可以考虑卸载重装 Obsidian 试试（注意卸载的话本地所有 vault 的数据和文件都没了！！！！！！！！！！一定要备份！！！！！！！）。

谢谢回复！后来重启手机就可以了。也就是 reset 后再重启手机。说实话发现冲突后被覆盖的问题后，我在 webdav 上新开了个只写的账号，数据倒是没啥风险的了。我主要在电脑上写，在手机上看。同时，确实是老设备，但升级系统会变慢，所以我现在只能停留在 0.3.16

**Comment by liutianyan** [comment]
新问题出现出了，有以下提示：
同步来源=manual，出错阶段=syncing Request failed，status 405

然后试过reset、重启手机、删除同步计划历史，删除 data.json 重新配置，都不行
NAS 主机上的 webdav 服务应该是正常的。因为 Mac 端有在写入
同时新建 webdav 账号，也还是提示 405

旧版本，到 7/8 之后了，开始数据交换了，然后才出错的。

**Comment by fyears** [comment]
> 新问题出现出了，有以下提示： 同步来源=manual，出错阶段=syncing Request failed，status 405
> 
> 然后试过reset、重启手机、删除同步计划历史，删除 data.json 重新配置，都不行 NAS 主机上的 webdav 服务应该是正常的。因为 Mac 端有在写入 同时新建 webdav 账号，也还是提示 405
> 
> 旧版本，到 7/8 之后了，开始数据交换了，然后才出错的。

请新建一个 issue 哈，此外你做了什么变更呢？软件是**不会**无缘无故不行的，一定是**有做变更**才会之前可以现在不可以的。有没有更新：ios/android ，obsidian，remotely save ，nas 系统，nas webdav，网络配置，账号，密码，等等呢？

**Comment by liutianyan** [comment]
> 新问题出现出了，有以下提示： 同步来源=manual，出错阶段=syncing Request failed，status 405
> 
> 然后试过reset、重启手机、删除同步计划历史，删除 data.json 重新配置，都不行 NAS 主机上的 webdav 服务应该是正常的。因为 Mac 端有在写入 同时新建 webdav 账号，也还是提示 405
> 
> 旧版本，到 7/8 之后了，开始数据交换了，然后才出错的。

我印象里没有变更啥，因为移动端现在是只读的了。我先去建条新的 issue
