### ISSUE TITLE
[Feature Request]: Sync on Save

### ISSUE THREAD

**Issue by Ellpeck** [remotely-save/remotely-save#199]
### What feature are you suggesting?

I'm sorry if this already exists and I just totally missed it, but I would love to see a setting like "Sync on Save" instead of (or in addition to) the scheduled sync. This would cause the plugin to detect any time a document in Obsidian is saved to disk (which usually happens every few seconds in Obsidian), and then it would upload that file specifically. This would allow synchronizing efficiently without having to press the Sync button or having to wait for the sync timer to be over.

Thanks so much for this plugin!

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by git10135405** [comment]
I hope so too.

**Comment by BE-Code** [comment]
If this can’t be done then maybe syncing on an interval only when the app is active so it does not run in the background

**Comment by giulianoSev** [comment]
I would love this

**Comment by fyears** [comment]
Hi all!! Greatly appreciate @smpurkis 's work. I will review the PR and try to merge it if everything goes as intended.
