### ISSUE TITLE
[Bug]: 同步时频繁出现Request failed, status 503

### ISSUE THREAD

**Issue by xbaibs** [remotely-save/remotely-save#201]
### What happened?

Windows端OB同步时出现以下信息：
_1/8 Remotely save 准备同步（webdav）
2/8 正在获取远端的元数据
remotely-save：中断同步，同步来源=manual，出错阶段=getting_remote_files_list
Request failed, status 503_

同步时以上信息会出现并伴同步失败。重新安装Remotely Save会暂时解决问题，但第二次同步时又会出现这个问题。
使用的坚果云的WebDav服务，我不确定是不是坚果云的问题。
另一个客户端是安卓版OB最新版本，也是靠Remotely Save同步，但并没有出现此问题。

The following message appears when OB syncs on the Windows side.
_1/8 Remotely save Ready to sync (webdav)
2/8 Getting metadata on remote side
remotely-save: interrupted sync, sync-source=manual, error-phase=getting_remote_files_list
Request failed, status 503_

The above message will appear with the sync failure when syncing. Reinstalling Remotely Save solves the problem temporarily, but the problem occurs again the second time I sync.
I am using the WebDav service of NutStore, so I am not sure if it is a problem with NutStore.
The other client is the latest version of OB for Android, which also relies on Remotely Save, but does not have this problem.

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

0.15.9

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by git10135405** [comment]
I have no problem with the phone, but the computer does not report the error as shown
![image](https://user-images.githubusercontent.com/35558611/194337580-a5d3018c-eca8-4180-a7c1-a2a1b7baedfe.png)

**Comment by CupidTian** [comment]
Me tooooooo!!
I have the same bug at my two devices(Android and iOS), both devices use JianguoYun webdev.

**Comment by BioinfoTongLI** [comment]
similar error on mac client.
Same Jianguoyun conneciton is working on Android side.
Tho, the error is slightly different. M
ine is stopped at the step3 
![Screenshot 2022-12-21 at 10 56 55](https://user-images.githubusercontent.com/9748580/208889217-b6f8b41b-235e-4ce3-930f-8644401e72d3.png)
Would be great to sort this out, since this is such a useful plugin!

**Comment by maxexcelsior** [comment]
我也出现这种情况，我笔记本点击remotely save的同步按钮就会出现503的报错，但是在手机上点同步之后，笔记本上修改的内容可以同步到手机端，而手机的同步则不会报503错误。虽然这个报错看着很不爽，但是内容倒是还能同步。

**Comment by HELLORPG** [comment]
如果有挂代理的话，将代理关掉试一下是否可以正常同步。
我关掉/换节点之后就可以了。

**Comment by idecimo** [comment]
各位问题是否解决了，我的方法是我把 发送到服务器的Depth header 选 支持depth='infinity 就OK了

If the problem is solved, my solution is that I send the Depth header to the server to support depth='infinity

**Comment by idecimo** [comment]
各位问题是否解决了，我的方法是我把 发送到服务器的Depth header 选 支持depth='infinity 就OK了

If the problem isn`t solved, my solution is that I send the Depth header to the server to support depth='infinity'

**Comment by yqygh** [comment]
> 各位问题是否解决了，我的方法是我把 发送到服务器的Depth header 选 支持depth='infinity 就OK了
> 
> If the problem isn`t solved, my solution is that I send the Depth header to the server to support depth='infinity'

thank you sooo much! I tried this and it worked! but the next time I tried to sync, the "503" appeared again...

**Comment by SWZ128** [comment]
> 各位问题是否解决了，我的方法是我把 发送到服务器的Depth header 选 支持depth='infinity 就OK了
> 
> If the problem isn`t solved, my solution is that I send the Depth header to the server to support depth='infinity'

帮了大忙！感谢！
Very helpful! grateful!

**Comment by fyears** [comment]
坚果云有 api 限制，调用过多会出错。

**Comment by OveDuke** [comment]
我修改了Depth header还是没有解决503报错，但是当把修改百分比改小一点就没有发生报错了。我从50%改成了30%
![image](https://github.com/user-attachments/assets/c626d9e3-aa75-450b-8839-5ff7739b6aac)

**Comment by fyears** [comment]
@OveDuke 你这个设置可能会导致该同步的不同步，从而不触发错误。建议换云端服务哈

**Comment by raven-chen** [comment]
不要使用坚果云来同步。。 会变得不幸..   Google Drive 的体验好太多了。
