### ISSUE TITLE
[Feature Request]:add options that enable force push and force pull

### ISSUE THREAD

**Issue by aiyolo** [remotely-save/remotely-save#202]
### What feature are you suggesting?

it is better that users can decide to force push all local files to remote and pull all remote files to locals

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
[A new beta version 0.4.1](https://github.com/remotely-save/remotely-save/releases/tag/0.4.1) has been released but you have to install it via [BART](https://github.com/TfTHacker/obsidian42-brat). It comes with force push and pull. This issue should be solved.
