### ISSUE TITLE
[Bug]: sync with S3(aliyun OSS)   request failed, status 403

### ISSUE THREAD

**Issue by MakiseSuki** [remotely-save/remotely-save#209]
### What happened?

aliyun OSS log shows "error_code:SignatureDoesNotMatch"
maybe this can help?  https://help.aliyun.com/document_detail/108790.html

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

v0.15.9

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
阿里云有网友可以设置成功的，看看网上的教程？大概率是key之类的设置不正确。
