### ISSUE TITLE
Disable SSL

### ISSUE THREAD

**Issue by petraxeman** [remotely-save/remotely-save#210]
### What feature are you suggesting?

I would like to know if there is any possibility to disable ssl (or disable ssl verification) when connecting to my own s3 server.  I can't connect to it because I have a self-signed certificate.

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by arwer13** [comment]
+1
Must-need option to disable certificate authority check to be able to use with custom server without built-in encryption.

**Comment by kamran-charles-nayebi** [comment]
+1

**Comment by dieterbaier** [comment]
+1

**Comment by fyears** [comment]
Obsidian api doesn't support bypassing bad ssl

![image](https://github.com/remotely-save/remotely-save/assets/1142836/b7aed4ed-cb18-4f76-9f06-d1ac742ba4f0)
