### ISSUE TITLE
[Bug]: Error: "/../OneDrive for Business/Notes" doesn't starts with "/Notes/"

### ISSUE THREAD

**Issue by Alex-coder251** [remotely-save/remotely-save#215]
### What happened?

![屏幕截图 2022-10-11 160150](https://user-images.githubusercontent.com/58896036/195032964-8fb0dc79-4233-47b9-aaf4-5f4a39cf0654.png)
I know remotely save doesn't support OneDrive for Business, so I turn it into WebDAV. But it seems remotely save does not fully support webdav.😭

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

0.15.9

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Alex-coder251** [comment]
没有解决，已经放弃了，直接用folder sync同步

**Comment by cxiaolng** [comment]
应该是目录地址不合法的问题，当webdav目录存在中文时同样出现问题。
通过使用urlencode进行转码后可正常使用。

同理
[r: "/../OneDrive for Business/Notes" doesn't starts with "/Notes/"](https://github.com/remotely-save/remotely-save/issues/215#top)
#215
地址中存在空格，会导致程序运行时不能获取地址。
你的地址 ”http://domain.com/OneDrive for Business/Notes“ 应该转成类似 "http://domain.com/OneDrive%20for%20Business%2FNotes"
即可。

**Comment by cxiaolng** [comment]
> 没有解决，已经放弃了，直接用folder sync同步

地址存在空格。做下URL编码就行了

**Comment by cxiaolng** [comment]
> 是这个插件本身的问题, 有人提

地址存在空格。做下URL编码就行了

**Comment by Alex-coder251** [comment]
> > 是这个插件本身的问题, 有人提
> 
> 地址存在空格。做下URL编码就行了

感谢, 问题解决了😍

**Comment by cxiaolng** [comment]
> > > 是这个插件本身的问题, 有人提
> > 
> > 
> > 地址存在空格。做下URL编码就行了
> 
> 我地址的确带中文, 转换了一下还是报同样的错误. 在插件设置界面测试可以连接上webdav服务器, 但就是无法同步, 一直报楼主图片的错误

我的也是带有中文。在chrome 浏览器上访问webdav进入到对应保存目录，直接copy地址链接（Chrome会自动进行转码）并粘贴到插件配置框里。

**Comment by Alex-coder251** [comment]
关门大吉

**Comment by Alex-coder251** [comment]
关门大吉

**Comment by fyears** [comment]
谢谢各位！我试试下一个版本加上 url encode 吧
