### ISSUE TITLE
[Bug]: Onedrive重新鉴权后不同设备远端同步文件夹不一致

### ISSUE THREAD

**Issue by foxdodo** [remotely-save/remotely-save#216]
### What happened?

插件提示长期未鉴权, 我在win10及安卓客户端分别进行重新鉴权后发现云端出现了2个文件夹, win端的默认文件夹是Obsidian  Vault, 安卓端是Obsidian.
尝试重新给2个客户端重置为默认文件夹还是一样, 这是需要手动设置一致的远端文件夹名吗? 我记得以前好像是不用的

### What OS are you using?

Windows, Android

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

0.15.9

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
要的。你的 Vault 名字是不是不一样。默认会按照 vault 名生成远端文件

**Comment by Coding-Yuan** [comment]
我也遇到了这个问题，修改了“远端基文件夹”，然后隔段时间重新鉴权后，远端目录又恢复成与笔记库一样的名字。

问题描述：

旧的远端目录因为有很多改名后的文件或文件夹未能同步成功，所以换了新的“远端目录”来保存最新版本，但是每次鉴权后又恢复默认的目录去同步旧的远端目录。

期望修复结果：

OneDrive 重新鉴权后依然能保留最后一次修改的“远端基文件夹”

其他问题：

1. 文件夹或文件改名后，同步有时未能同步更改
