### ISSUE TITLE
[Bug]: 409 Status code with Dropbox sync

### ISSUE THREAD

**Issue by hinzed1127** [remotely-save/remotely-save#217]
### What happened?

This seems to be similar to #10. Anytime I remotely save, I get an error of `remotely-save-1665688437595: abort sync, triggerSource=manual, error while syncing`, followed by `Icon: Response failed with a 409 code` (see screenshot below). However, as best as I can tell, the sync succeeds. My changes get uploaded to Dropbox, and nothing seems incorrect. I also have the Obsidian mobile app, and the same error does not show up when syncing from mobile, only on desktop.

![Screen Shot 2022-10-13 at 2 14 01 PM](https://user-images.githubusercontent.com/13280995/195713276-614f100d-1150-4bf4-8b12-49c4eb0e495d.png)

That leaves me with a few questions:

1. Is an error actually occurring, or is this a false alarm of sorts?
2. How do I resolve this error in either of those cases?

### What OS are you using?

macOS

### What remote cloud services are you using?

Dropbox

### Version of the plugin

0.3.25

### Version of Obsidian

1.0.0

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by yidianhongxin** [comment]
The same error occurred

**Comment by MikeTheGreat** [comment]
Same error occurred for me, too.
Also on MacOS, Obsidian 1.0.0, Remotely-Save 0.3.25

**Comment by yidianhongxin** [comment]
I found the reason, and it's because I changed the following Settings, restore the default Settings, and synchronize again without error. Of course, I reset the vault and then set up the plug-in, and there were no further problems.
I hope it helps
![2022-11-01 at 21 22](https://user-images.githubusercontent.com/11401362/199245046-2fcbfaf3-1387-495d-aea2-fa5c033a4b56.jpg)


> 我也发生了同样的错误。 同样在 MacOS、Obsidian 1.0.0、远程保存 0.3.25

**Comment by hinzed1127** [comment]
@yidianhongxin could you clarify on what you mean by "reset the vault"? The "Sync Config Dir" setting was already disabled for me.

**Comment by manontop** [comment]
I was getting this error:
![Screen Shot 2023-01-10 at 12 36 21 AM](https://user-images.githubusercontent.com/18553767/211395576-da0faef4-75a5-49d2-a6f0-da3ff7923de4.jpg)


After I turned Disabled the Sync Config Dir setting, it was fixed. I hope this issue gets fixed so that I can sync settings as well.

**Comment by hinzed1127** [comment]
@djipca that did it for me. It turned out to be an `Icon\r` Mac file that was hiding. I was able to find and fix the issue by running this node script from the root directory of my vault:
```node
const fs = require('fs')
const path = require('path')

function removeTrailingWhitespace(fileOrDirectory) {
  let newName = fileOrDirectory.trim()
  if (newName !== fileOrDirectory) {
    console.log(`Changed ${fileOrDirectory} to ${newName}`)
    fs.renameSync(fileOrDirectory, newName)
  }
  return newName
}

function recursiveRename(dir) {
  fs.readdirSync(dir).forEach(file => {
    let fileOrDirectory = path.join(dir, file)
    let stats = fs.lstatSync(fileOrDirectory)
    if (stats.isDirectory()) {
      recursiveRename(fileOrDirectory)
    } else if (stats.isFile()) {
      removeTrailingWhitespace(fileOrDirectory)
    }
  })
  removeTrailingWhitespace(dir)
}

recursiveRename('./')
```
Closing now that I've determined the cause with an appropriate fix.
