### ISSUE TITLE
[Bug]: 更新到OB1.0，PC端插件界面变成英文了~ 

### ISSUE THREAD

**Issue by i-iooi-i** [remotely-save/remotely-save#220]
### What happened?

问题1：
----
更新到OB1.0，PC端插件界面变成英文了~ 卸载重装也还是英文界面。🤣

在iphone上重新安装OB，再次安装插件，默认插件界面就是中文的。

问题2：
---
请问Webdav是推荐https访问还是http访问比较好呢？

我是在群晖设备上开了Webdav。（在某论坛看到有人说该插件仅支持Htpp连接~）

遇到以下问题 ：
同一个地址，在PC端插件界面使用Http无法连接，使用https却可以链接。
而在手机端，使用http链接就一切正常。

结果导致我现在PS端使用的是Https链接，而手机端使用的是Http链接。😼

感谢！💕

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.0

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
语言问题我用最新版 Obsidian （1.4.16）没问题啊，只要 Obsidian 是中文的话插件就是中文的，跟着走的，试试再更新一下（如果你还在用的话）。

此外推荐使用 webdav https。

如果最新版还有问题的话，欢迎重开 issue。
