### ISSUE TITLE
[Bug]: At HarmonyOS2, obsidian crash when download big file(my file is 28M) from aliyun OSS

### ISSUE THREAD

**Issue by zoanun** [remotely-save/remotely-save#222]
### What happened?

At HarmonyOS2, obsidian crash when download big file(my file is 28M) from aliyun OSS

### What OS are you using?

Android

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.0

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by zoanun** [comment]
change Obsidian from 1.0.0 => 1.4.0

**Comment by fyears** [comment]
The plugin runs inside the js environment. Maybe large file is not ok due to the limitations of mobile js. You can work around this by sett Skip Large Files.

插件是运行在 js 环境里的，很难在手机端处理大文件。可以设置里跳过大文件绕开这个问题，
