### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by christophberger** [remotely-save/remotely-save#224]
### What happened?

On macOS, when I enable Remotely Save, CPU load of the Obsidian core process increases to 60-90%. One of the Obsidian Helper (Renderer) processes increases to about 40%. 

Normal CPU usage (with Remotely Save disabled) is between 0.x% and 5%.

From time to time, CPU load drops to low levels for a few seconds, but then goes back to high levels.

<img width="477" alt="Screen Shot 2022-10-18 at 12 32 14" src="https://user-images.githubusercontent.com/3835890/196407647-b89bf272-e60a-476a-be44-e90d99c1a337.png">

The synchronization itself works fine, except that I get regular popups in the top-right corner saying something about remotely already running in stage synching. I connected RS to Filebase.com, an S3-compatible service.

### What OS are you using?

macOS

### What remote cloud services are you using?

others

### Version of the plugin

0.3.25

### Version of Obsidian

0.15.9 (installer 0.14.15)

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
the password mode encrypt the files using javascript which might be resource heavy. try to update Obsidian to the latest version and see if the web view is optimized.
