### ISSUE TITLE
[Bug]: not syncing text files

### ISSUE THREAD

**Issue by Zbrooklyn** [remotely-save/remotely-save#225]
### What happened?

on mobile and windows 10 when I sync folders to one drive it works but when I sync a text document either within a folder or not it will not sync even after a manual sync or opening and closing the application, I also went directly into one drive and still it doesn't show.

so, I ran another test I went to one drive and added a file and that synced to obsidian

Conclusion when I press sync from obsidian it will push folders to one drive but not files but when I add something directly within one drive it will push to obsidian.

### What OS are you using?

Windows, Android

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.0.0

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Likely the file being empty??? OneDrive doesn't support empty files. Feel free to reopen the issue if more reproducible steps/files could be provided.
