### ISSUE TITLE
[Bug]: sync with Synology NAS webdev request failed in iphone

### ISSUE THREAD

**Issue by ZhouQW2019** [remotely-save/remotely-save#227]
### What happened?

sync with Synology NAS webdev in my iphone request failed, 
Server address use "https", not "http". 
Connectivity Check is OK, 
error info:
remotely-save-166xxxxx: abort sync, 
triggerSource=manual, error while getting_remote_files_list
Request failed.

the plugin work good in my PC(win10) used the same setting .  and  Synology NAS webdev work good at Jplin in my iphone.

by the way,  sync successed only once,  I dont know what happed?

### What OS are you using?

iOS16.0 (iPhone, iPad)

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.0

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by wujcan** [comment]
I also tried syncing with Synology, but failed to get through **Connectivity Check**. Could you please tell me how to config your webdav service?

**Comment by fyears** [comment]
i donot have nas... is there any easy way to setup a Synology NAS webdev ...?

**Comment by fyears** [comment]
the new version greatly improve the webdav support and should fix some problems
