### ISSUE TITLE
[Bug]: 加密后的文件名字符长度超过256位导致无法在某些网盘同步

### ISSUE THREAD

**Issue by foxdodo** [remotely-save/remotely-save#228]
### What happened?

使用end-to-end encryption加密后的文件名会达到256位字符长度, 导致无法上传到某些网盘, Teracloud提示403, 另外一个网盘提示超出字符长度限制

### What OS are you using?

Windows, iOS (iPhone, iPad), Android

### What remote cloud services are you using?

OneDrive for personal, webdav, others

### Version of the plugin

0.3.25

### Version of Obsidian

1.0.0

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
谢谢。是的正如你所说。目前无解。
