### ISSUE TITLE
[Bug]: Special characters in the Directory "|" will failed in syncing

### ISSUE THREAD

**Issue by ZackYJz** [remotely-save/remotely-save#229]
### What happened?

If there is '|' in folder name, syncing to Android devices  will failed：
"FILE_NOTCREATE,too many errors,stop the remaining tasks"

### What OS are you using?

Android

### What remote cloud services are you using?

S3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
merged to #416

**Comment by fyears** [comment]
if the remote service doesn't support the special character, i am afraid that the plugin can do nothing except some notifications.
