### ISSUE TITLE
[Bug]: 同步中断

### ISSUE THREAD

**Issue by LYXhhhhh** [remotely-save/remotely-save#230]
### What happened?

![image](https://user-images.githubusercontent.com/116557423/197503514-a1f34d09-2f67-4b1c-85da-dea0527b4dc1.png)

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

Remotely Save(0.3.25)

### Version of Obsidian

v1.0.0

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
如果用坚果云的话，有同步 api 数量限制，插件无法绕过
