### ISSUE TITLE
[Bug]: Commit the old files to OneDrive

### ISSUE THREAD

**Issue by jerviscui** [remotely-save/remotely-save#233]
### What happened?

I've been using remotely-save for a few days. Thank you for the plugin. 

I used remotely-save sync files from two computers.
I use manual syncing. 
Whenever I upload the latest modified files from one computer, When I click Sync on another computer, it always uploads old files to OneDrive.

That the OneDrive file was contaminated. No file version control?
This is intolerable and there is no way to guarantee that I am syncing with the correct results.

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.0

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> Whenever I upload the latest modified files from one computer

how do you upload the files? by using onedrive official web site pages? the plugin compares the last modified time, may be manually uploading has something different on the modified time.
