### ISSUE TITLE
[Bug]: When file deleted via Obsidian desktop, remotely-save re-uploads local copy instead of deleting

### ISSUE THREAD

**Issue by RyanVerhey** [remotely-save/remotely-save#234]
### What happened?

I deleted a file using Obsidian desktop (v1.0.3) on my Linux machine. That change is synced to my Nextcloud instance via Nextcloud's desktop application.

When manually syncing on my iPhone (remotely-save v0.3.25, Obsidian mobile v1.4.0, iOS 16.1), remotely-save uploads the local copies of the files that were deleted from the desktop. Expected behavior would be that it would delete those local files.

### What OS are you using?

Linux, iOS (iPhone, iPad)

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25 on iPhone

### Version of Obsidian

mobile v1.4.0, desktop 1.0.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by stlehmann** [comment]
I have the same issue with Nextcloud (webdav):

**What remote cloud services are you using?**
webdav

**Version of the plugin**
0.3.25 on iPhone

Version of Obsidian
mobile v1.4.1, desktop 1.0.3

**Using password or not**
Yes

**1Ensure no sensitive information**
I ensure that no sensitive information is submitted in the issue.

**Comment by githubkoma** [comment]
I have the exact same problem :-(
For the time being i have to disable my Obsidian Mobile App

**Comment by fyears** [comment]
sometimes the webdav may read the metadata incorrectly. i update the code in new version (0.3.28) which will be released in next few days. please try again uaing the new version. Sorry for the issue.
