### ISSUE TITLE
[Feature Request]: 教育版A1账号就算管理员同意了请求依旧无法鉴权

### ISSUE THREAD

**Issue by CXido** [remotely-save/remotely-save#236]
### What feature are you suggesting?

因为有A1全局所以试了一下，IOS和PC端均卡在  正在连接OneDrive……请不要关闭此弹窗。

![PC](https://user-images.githubusercontent.com/55381745/198885103-65703401-cefe-441d-af16-297a8758ddfd.png)
![IOS](https://user-images.githubusercontent.com/55381745/198885105-9d30ab3d-a8c3-4d57-8808-dd3db44b4fa7.PNG)

测试了同域好几个账号都是一样，理论上E5和A1同理？？

---
另外丢一份管理员开启批准图
![Azure Active Directory](https://user-images.githubusercontent.com/55381745/198885611-f80effa7-e6f3-4939-9b8d-fb44f4905245.png)

然后打开Outlook批准就可以了
![Outlook](https://user-images.githubusercontent.com/55381745/198885540-5db9272a-2753-432f-a4f2-4a4e3529710b.png)

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by PassionPenguin** [comment]
@CXido as an E5 admin, I can grant consent to the user added the application, and once I granted consent and retry to auth (only need to clean the local cache for the credentials), it works well.

See #11

**Comment by fyears** [comment]
Thanks everyone. Dup of #11  so close this
