### ISSUE TITLE
[Bug]: Android Pad encounter 'failed to load plugin remotely-save'

### ISSUE THREAD

**Issue by smilesxsy** [remotely-save/remotely-save#239]
### What happened?

I have encountered this problem with my Xiaomi Android tablet.  In my tests, 0.3.14-0.3.16 can be used (less than 0.3.14 is unclear), 0.3.17 and later versions cannot enable the plugin

### What OS are you using?

Android

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25-0.3.17

### Version of Obsidian

1.4.1-1.3.1

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by ffxung** [comment]
我在我的iapd上(ios 14.4)复现了这个问题, 从0.3.17开始, 插件无法开启, 而0.3.16可以(但用这个版本的插件, 发现无法同步其他终端插件同步的最新版本文件,所以还是没办法用0.3.16版本).    0.3.17和0.3.16版本的差异是一个重要线索.
期待作者能修复这个问题.

**Comment by fyears** [comment]
ios 14 太旧了，手上没有设备可以测试和支持，
