### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by KurKuza** [remotely-save/remotely-save#240]
### What feature are you suggesting?

is it possible to sync via google drive?

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by rnd256** [comment]
Duplicate of https://github.com/remotely-save/remotely-save/issues/4.

**Comment by fyears** [comment]
Duplicate of https://github.com/remotely-save/remotely-save/issues/4.
