### ISSUE TITLE
[Feature Request]: `Region` should can be set as `NULL`

### ISSUE THREAD

**Issue by 1itt1eB0y** [remotely-save/remotely-save#244]
### What feature are you suggesting?

I'm using QuStorage as my S3 compatitive. It won't work properly if the `Region` section asked to be set. 
![图片](https://user-images.githubusercontent.com/29831189/201503995-c59992f3-84e8-4159-97f4-eb5437bd3555.png)

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by merlinuwe** [comment]
I think, this is the same issue:

Request failed:

![image](https://user-images.githubusercontent.com/4138869/201516979-29ae1665-4706-463c-8b1f-158c5356446c.png)

Region missing:

![image](https://user-images.githubusercontent.com/4138869/201516935-aeca1350-a58f-4878-ade5-9fef66ebfd84.png)

Windows 10, latest Obsidian, latest plugin

**Comment by davidohne** [comment]
Same here. Serverius Storage.

**Comment by fyears** [comment]
What's "QuStorage" (No result after some Internet searches) （中文是啥？）? I tested the plugin using Tencent Cloud COS and Backblaze and everything goes well.

@davidohne And for Serverius Storage, I am sorry but I don't have an account to test it. And according to the doc: ["The region field can be anything"](https://my.serverius.net/knowledgebase/136/Configuring-Veeam-Backup-and-Replication-to-use-Eurostack-S3-object-storage.html)

**Comment by 1itt1eB0y** [comment]
> What's "QuStorage" (No result after some Internet searches) （中文是啥？）? I tested the plugin using Tencent Cloud COS and Backblaze and everything goes well.
> 
> @davidohne And for Serverius Storage, I am sorry but I don't have an account to test it. And according to the doc: ["The region field can be anything"](https://my.serverius.net/knowledgebase/136/Configuring-Veeam-Backup-and-Replication-to-use-Eurostack-S3-object-storage.html)

Qnap的一个S3功能，就叫QuStorage😂

**Comment by fyears** [comment]
I search and find out that region is necessary for signing payload... is it possible to set it to something like `us-east-1` or `US`?

**Comment by fyears** [comment]
confirmed that aws sdk cannot unset the region parameter...
