### ISSUE TITLE
[Bug]: Failed to enable plugin in 1.0

### ISSUE THREAD

**Issue by StevenGann** [remotely-save/remotely-save#245]
### What happened?

**Describe the bug**
On startup Obsidian does not enable this plugin. Manually enabling on the list of installed plugins fails and shows a "Failed to enable plugin" toast. Going into the Community Plugin list and pressing the enable button there causes the same error, but the plugin enables and functions correctly despite the error.

**To Reproduce**
1. Install the latest Obsidian (1.0.3) on Windows or Linux
2. Install the latest version of this plugin
3. Attempt to enable the plugin
4. See error in console

```
app.js:1 Plugin failure: remotely-save DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at r4.<anonymous> (app://obsidian.md/app.js:1:1032505)
    at app://obsidian.md/app.js:1:235201
    at Object.next (app://obsidian.md/app.js:1:235306)
    at a (app://obsidian.md/app.js:1:234045)
```

### What OS are you using?

Windows, Linux

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.0.3

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
In the newer Obsidian (v1.5) the plugin is loaded correctly. Please try again using a newly created vault with latest Obsidian and the plugin.
