### ISSUE TITLE
[Bug]: It's a crap plug-in that doesn't sync files at all and instead deletes my files!!!

### ISSUE THREAD

**Issue by mingweme** [remotely-save/remotely-save#246]
### What happened?

![image](https://user-images.githubusercontent.com/28482653/202752631-e96d5eb3-cb6e-49a9-9e52-9bac63258ad1.png)
Request failed,status 503

### What OS are you using?

Windows, Android

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

v1.0.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by merlinuwe** [comment]
I can confirm.

1. I add some files to OneDrive Personal.
1. I start Obsidian
1. I press the button "remotely save" in obsidian. (All 8 steps are shown as a status.)
1. At this stage, no files are in the folder Obsidian_poco. I add 3 files. I see them on my Android in OneDrive personal.
1. I open Obsidian. The File explorer shows 0 files. I wait for a minute.
1. The 3 files are deleted, reproducable.

**Comment by fyears** [comment]
"getting remote files list" should not delete the files. 

"upload files manually in Onedrive then sync using the plugin" will not delete the files **unless the files were deleted before inside the Obsidian**

Lots of users successfully use the plugin to sync files and the files are uploaded/downloaded automatically normally. Backup manually are always strongly recommended everywhere in the plugin descriptions though.

Feel free to open a new issue if the problem can be reproduced in a **newly created** test vault with newly created files and init sync being triggered from Obsidian remotely-save.
