### ISSUE TITLE
[Bug]: obsidian crashes when syncing

### ISSUE THREAD

**Issue by janeilagan** [remotely-save/remotely-save#247]
### What happened?

Manual or by schedule syncing crashes Obsidian and ends up as a black screen
![image](https://user-images.githubusercontent.com/64050884/202880754-9b238181-7108-4471-a51b-378607e901d7.png)

if you open the dev console it shows up like this:
![20221120110713AM-Screenshot](https://user-images.githubusercontent.com/64050884/202880848-dc68796e-645f-4e2f-a1e5-6903ab74214c.gif)

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.0.3

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by INPoppoRTUNE** [comment]
+1 on this.

**Comment by KuiyueRO** [comment]
I've been experiencing this problem with Android. I've lowered "Concurrency" to below 5 and it's no longer crashing.Hope you found this useful!

**Comment by INPoppoRTUNE** [comment]
> I've been experiencing this problem with Android. I've lowered "Concurrency" to below 5 and it's no longer crashing.Hope you found this useful!

Unfortunately not working for me, event at 1 it keeps crashing.

**Comment by janeilagan** [comment]
> > I've been experiencing this problem with Android. I've lowered "Concurrency" to below 5 and it's no longer crashing.Hope you found this useful!
> 
> Unfortunately not working for me, event at 1 it keeps crashing.
> 
> ~Edit: setting "Concurrency" = 5 and hitting the "Reset Local Internal Cache/Databases" seems to have (at least temporarily) fixed the problem.~

tried "Reset Local Internal Cache/Databases" too but still didn't work. I did change the "Skip Large Files" to 5MB. It's not crashing now. Hope this helps you too.

**Comment by manasmgkar** [comment]
same issue on the latest 1.19 version + 3.25 version of plugin for mp4 files.
