### ISSUE TITLE
[Bug]: 总是同步到第二步就失败了，我就得“重设本地缓存和数据库”，然后重启应用才可以

### ISSUE THREAD

**Issue by chloe5685** [remotely-save/remotely-save#248]
### What happened?

总是同步到第二步就失败了，我就得“重设本地缓存和数据库”，然后重启应用才可以

### What OS are you using?

Android

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.1

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
什么webdav？坚果云吗？新的测试的vault可以复现吗
