### ISSUE TITLE
[Feature Request]: Git / FTP

### ISSUE THREAD

**Issue by muescha** [remotely-save/remotely-save#250]
### What feature are you suggesting?

there are some pure javascript implementations of git and ftp - maybe you can use them for ftp and git connections?

### What remote cloud services are you using, or suggesting adding the feature to?

others

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
I have done some serious research. 

But ftp (sftp) clients cannot run in a pure browser environment, so the plugin cannot (technically no way) to implement the feature. I would glad if someone points me to a pure browser js library!!!! 

And for git, I would personally suggest you use obsidian git plugin instead. git runs in a greatly different way.
