### ISSUE TITLE
[Bug]: 使用WebDav同步问题

### ISSUE THREAD

**Issue by hhun** [remotely-save/remotely-save#251]
### What happened?

使用WebDav同步时，本地删除插件和模板，WebDav服务器里面不会同步删除，反而还会把删除后的文件再同步到本地。

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

 remotely save

### Version of Obsidian

0.3.25

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by MortalKim** [comment]
插件删除无法被检测，所以插件卸载需要手动在所有端卸载插件，这个在同步插件的开关说明里。所以我没打开同步插件

**Comment by fyears** [comment]
插件文件夹没有删除信息，暂无更好办法因为 obsidian 没有直接的 api 检查这个文件夹的变更
