### ISSUE TITLE
[Bug]: 无法连接群晖Webdav服务器

### ISSUE THREAD

**Issue by phantasy36** [remotely-save/remotely-save#254]
### What happened?

使用RaiDrive连接群晖Webdav服务器没有问题。但是在remotely save插件中设置相同的地址，用户名和密码，却无法连接群晖的webdav服务器。
不管是basic鉴权类型还是digest鉴权类型都不行。
1、basic鉴权类型提示：      
<img width="238" alt="11111" src="https://user-images.githubusercontent.com/46774023/204533993-6bc48446-1d65-4bbf-9536-a1cba1a21ad2.png">
2、digest鉴权类型提示：
<img width="264" alt="2" src="https://user-images.githubusercontent.com/46774023/204534161-ab8ae7fd-d07e-49b2-8f9e-1ebeb8bc31df.png">

### What OS are you using?

Linux

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.0.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by MortalKim** [comment]
405是可能网址有问题，401是鉴权错误。
可以直接复制webdav地址到浏览器访问试试，验证一下是否是webdav问题

**Comment by phantasy36** [comment]
> 405是可能网址有问题，401是鉴权错误。 可以直接复制webdav地址到浏览器访问试试，验证一下是否是webdav问题

<img width="320" alt="111" src="https://user-images.githubusercontent.com/46774023/210569144-45b19943-a0be-4b59-b724-89bd8ea77ecf.png">
按照您的提示我使用网页浏览器进行了验证，提示不存在这个网址。
<img width="408" alt="222" src="https://user-images.githubusercontent.com/46774023/210569162-39dceecf-72b5-46c4-af06-c1fb0e4407f9.png">
但是使用RaiDrive，同样的网址却可以登录。

**Comment by MortalKim** [comment]
@phantasy36 在浏览器测试webdav的时候要加上路径，比如您发的两个截图的第二个，实际上访问的是http://192.168.88.16/   而不是http://192.168.88.16，带了一个路径“/”。

比如我的Webdav配置，就是 https://地址/Obisidian，加个文件夹路径进来，而且要已经存在的路径，这样才能正常访问。

针对你的实际情况，可以在浏览器测试一下http://192.168.88.16/ （注意结尾的“/”），如果弹出了账号密码认证的提示，就可以把它填写到Obsidian试试了

**Comment by phantasy36** [comment]
<img width="494" alt="无标题" src="https://user-images.githubusercontent.com/46774023/210604591-faf7c9aa-6ed7-4408-8874-0290586447b8.png">
http和https都试了，不行。都是提示同样的错误。而且两种方式RaiDrive同样都能登录。

**Comment by MortalKim** [comment]
可以尝试建立一个子文件夹，比如Obsidian，然后访问 http://192.168.88.16:5006/Obsidian
还是在浏览器尝试是一个很好的验证它是否有效的办法。另外，肯定是http，本地IP形式访问不会有Https

**Comment by phantasy36** [comment]
测试成功。感谢。看来真的要给个文件夹的路径。。。

**Comment by zen010101** [comment]
> @phantasy36 在浏览器测试webdav的时候要加上路径，比如您发的两个截图的第二个，实际上访问的是http://192.168.88.16/ 而不是[http://192.168.88.16，带了一个路径“/”。](http://192.168.88.16%EF%BC%8C%E5%B8%A6%E4%BA%86%E4%B8%80%E4%B8%AA%E8%B7%AF%E5%BE%84%E2%80%9C/%E2%80%9D%E3%80%82)
> 
> 比如我的Webdav配置，就是 [https://地址/Obisidian，加个文件夹路径进来，而且要已经存在的路径，这样才能正常访问。](https://%E5%9C%B0%E5%9D%80/Obisidian%EF%BC%8C%E5%8A%A0%E4%B8%AA%E6%96%87%E4%BB%B6%E5%A4%B9%E8%B7%AF%E5%BE%84%E8%BF%9B%E6%9D%A5%EF%BC%8C%E8%80%8C%E4%B8%94%E8%A6%81%E5%B7%B2%E7%BB%8F%E5%AD%98%E5%9C%A8%E7%9A%84%E8%B7%AF%E5%BE%84%EF%BC%8C%E8%BF%99%E6%A0%B7%E6%89%8D%E8%83%BD%E6%AD%A3%E5%B8%B8%E8%AE%BF%E9%97%AE%E3%80%82)
> 
> 针对你的实际情况，可以在浏览器测试一下http://192.168.88.16/ （注意结尾的“/”），如果弹出了账号密码认证的提示，就可以把它填写到Obsidian试试了

谢谢，按照你的方法果然成功了！虽然有待 Remotely Save 改进一下连接方式，但这个 workaround 足够用！

**Comment by fyears** [comment]
谢谢楼上给的解决方案！

**Comment by IAvision** [comment]
刚出现了同样的问题，用RaiDrive能登录WebDAV，但使用Remotely Save一直提示鉴权失败，请问有解决方案吗？
