### ISSUE TITLE
[Bug]: Synchronization failed

### ISSUE THREAD

**Issue by fallling** [remotely-save/remotely-save#255]
### What happened?

I have some image attachments that need to uploaded, but my remote cloud services does not have these attachments, so my local attachments will be deleted every time I synchronize.

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.0.3

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
please click "reset local internal cache/databases" button in remotely-save and reload the plugin.

and also delete the file _remotely-save-metadata-on-remote.{json,bin} in onedrive
