### ISSUE TITLE
Sync on exit (Mobile)

### ISSUE THREAD

**Issue by hubertsng** [remotely-save/remotely-save#256]
### What feature are you suggesting?

Is there a way to do this?
By exit, I would say whenever it's not the current application with probably a cooldown period so someone taking notes from another app and keeps switching would syncing hard.
I can press the sync button on exit but this, I think, would be convenient for lazy people like me. 
Auto sync works but I'm not sure if it needs to be on the foreground or not. The thing is that obsidian doesn't work in the background but what if we disable battery optimization or so? 

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> The thing is that obsidian doesn't work in the background

Exactly the problem.

And if Obsidian is allowed to run in background, then users can set remotely-save's auto running every x minutes. Actually no need to "save when exit".

**Comment by fyears** [comment]
@TCB13 

obsidian plugin is a js program running on the obsidian browser/ node environment with additional api. 

so the only hope is a feature request to obsidian official forum (to provide such api to plugins). plugin development itself can do nothing currently
