### ISSUE TITLE
[Bug]: Sync a large mp4 file causes Obsidian black screen

### ISSUE THREAD

**Issue by lwjmm** [remotely-save/remotely-save#257]
### What happened?

I insert a mp4(about 120M) into a page, it will be sync in the attachment fold.

About 10 seconds, the Obsidian turn into the black screen, I restart it and the issue will be happen, again and again.

If I insert it by Android, the Obsidian will be crashed.

If I insert the large mp4 file after close the Remotely-Save plugin, the Obsidian will be OK

I must remove the mp4 file in the fold, the Obsidian will work normally.

PS: I try to change the sync service, webdav and onedrive, use different large mp4 files, but the issue remains.

### What OS are you using?

macOS

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.0.3

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by manasmgkar** [comment]
same error,i even tried downgrading plugin still wont work.

**Comment by fyears** [comment]
The plugin uses JavaScript to process the file so large files may cause the crash. Skip Large Files should help.

Check out https://github.com/remotely-save/remotely-save/issues/265
