### ISSUE TITLE
[Bug]: Error: we meet file/folder and do not know how to deal with it: parentPath="/drive/root:/0collection/app/remotely-save", selfName="notes"

### ISSUE THREAD

**Issue by bushnerd** [remotely-save/remotely-save#258]
### What happened?

Remotely-save syncs failed, the log is as follows:
`plugin:remotely-save:216 remotely-save-1670154567593: abort sync, triggerSource=manual, error while getting_remote_files_list
eval @ plugin:remotely-save:216
s @ plugin:remotely-save:177
Promise.then (async)
u @ plugin:remotely-save:177
eval @ plugin:remotely-save:177
a @ plugin:remotely-save:177
syncRun @ plugin:remotely-save:216
eval @ plugin:remotely-save:216
eval @ plugin:remotely-save:177
a @ plugin:remotely-save:177
callback @ plugin:remotely-save:216
BB @ app.js:1
t.onChooseItem @ app.js:1
t.onChooseSuggestion @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
(anonymous) @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
plugin:remotely-save:216 Error: we meet file/folder and do not know how to deal with it:
parentPath="/drive/root:/0collection/app/remotely-save", selfName="notes"
    at qi (plugin:remotely-save:211:30516)
    at eval (plugin:remotely-save:211:246480)
    at Array.map (<anonymous>)
    at eval (plugin:remotely-save:211:246472)
    at Generator.next (<anonymous>)
    at a (plugin:remotely-save:177:280327)`

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using?

OneDrive for personal

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by 165056821** [comment]
我也遇到了同样的问题

**Comment by yunrr** [comment]
呃我的家庭版onedrive也会出这个问题，另一个号免费版的onedrive就能同步成功。。。

**Comment by fyears** [comment]
Are you using the “personal” version (the free product comes with any personal live mail account) or any other variant? I could not reproduce the error…

你们用的是“个人版”（申请 live 邮箱就有的）还是什么版本？无法复现。

**Comment by tiller2008** [comment]
> Are you using the “personal” version (the free product comes with any personal live mail account) or any other variant? I could not reproduce the error…
> 
> 你们用的是“个人版”（申请 live 邮箱就有的）还是什么版本？无法复现。

就是个人版，后来检查了一下，应用下面的文件夹必须时“remotely-saved”这个名字，给我搞了个“graph”导致不同步，自己改一下就好了

**Comment by Athelasss** [comment]
> > 您使用的是“个人”版本（免费产品附带任何个人实时邮件帐户）还是任何其他变体？我无法重现错误...
> > 你们用的是“个人版”（申请 live 邮箱就有的）还是什么版本？无法复现。
> 
> 就是个人版，后来检查了一下，应用下面的文件夹必须时“remotely-saved”这个名字，给我搞了个“graph”导致不同步，自己改一下就好了

我更改成了这个，但还是不行，还有什么办法吗？

**Comment by tiller2008** [comment]
> > > 您使用的是“个人”版本（免费产品附带任何个人实时邮件帐户）还是任何其他变体？我无法重现错误...
> > > 你们用的是“个人版”（申请 live 邮箱就有的）还是什么版本？无法复现。
> > 
> > 
> > 就是个人版，后来检查了一下，应用下面的文件夹必须时“remotely-saved”这个名字，给我搞了个“graph”导致不同步，自己改一下就好了
> 
> 我更改成了这个，但还是不行，还有什么办法吗？

写错了改为“remotely-save”就行了

**Comment by yunrr** [comment]
> Are you using the “personal” version (the free product comes with any personal live mail account) or any other variant? I could not reproduce the error…
> 
> 你们用的是“个人版”（申请 live 邮箱就有的）还是什么版本？无法复现。

**Comment by yunrr** [comment]
> Are you using the “personal” version (the free product comes with any personal live mail account) or any other variant? I could not reproduce the error…
> 
> 你们用的是“个人版”（申请 live 邮箱就有的）还是什么版本？无法复现。

我重新换了一个onedrive的账号，就可以正常使用了。看起来有一部分onedrive的账号存在问题，这与家庭版onedrive还是个人版onedrive无关，而这使得remotely-save无法成功建立名为remotely-save的文件夹，而是创建了graph文件夹。我还发现那个有问题的onedrive账号还存在无法手动上传文件的问题，联系了微软的工作人员也并没有找到问题的原因，应该就是有部分onedrive账号有问题

I switched to a new OneDrive account, and now I can use it normally. It seems that there are issues with some OneDrive accounts, regardless of whether they are Home edition or Personal edition. This is causing a problem where "remotely-save" cannot successfully create a folder with the same name and instead creates a folder named "graph". Additionally, I have noticed that the problematic OneDrive account also has an issue with manual file uploads. Even after contacting Microsoft's staff, they were unable to find the cause of the problem. It appears that there are some issues with certain OneDrive accounts.

**Comment by fyears** [comment]
might be related: https://learn.microsoft.com/en-us/graph/onedrive-addressing-driveitems

**Comment by fyears** [comment]
尝试增加了兼容， v0.3.36

**Comment by yangjie2270** [comment]
我也遇到了这个问题，显示错误如下：

1/2 RemotelySave 开始同步(onedrive)
file/folder, no idea how to deal with it withoutknown prefix:fullPathOriginal=/drive/root;/Application/remotely-save/Obsidian vaultmatchFirstPrefixRes=/drive/root:/Application/re
motely-save/matchFifthPrefixRes=null
matchSixthPrefixRes=nullmatchSixthV2PrefixRes=nullmatchSecondPrefxRes=nullmatchThirdPrefixRes=nullparentPath="/drive/root:/Application/remotelysave",selfName="Obsidian vault"
2/2 Remotely Save 已完成同步!
