### ISSUE TITLE
[Bug]: Ipad & Android Failed to load plugin

### ISSUE THREAD

**Issue by isNineveh** [remotely-save/remotely-save#259]
### What happened?

Installed the plugin successfully but failed to load it. Don't know why.

### What OS are you using?

iOS (iPhone, iPad), Android

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.1 (83) ipad   1.0.5 Android

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by SyncroIT** [comment]
In my case (iPhone 12, last version of iOS) it seems to work but actually it doesn't.
Files do not get synced.

**Comment by eenturk** [comment]
Same here for WebDAV on iPhone

**Comment by fyears** [comment]
Close because of lack of detailed information.
