### ISSUE TITLE
[Bug]: High cpu and energy consummation 

### ISSUE THREAD

**Issue by echo-saurav** [remotely-save/remotely-save#260]
### What happened?

When i enable remotely-save plugin on my m1 macbook, its started heating , and draining battery. 
### Without remotely
<img width="806" alt="Screenshot 2022-12-08 at 9 32 23 PM" src="https://user-images.githubusercontent.com/76121100/206499515-eea62256-8af2-4c15-98c5-08b145c0caf3.png">
<img width="806" alt="Screenshot 2022-12-08 at 9 32 36 PM" src="https://user-images.githubusercontent.com/76121100/206499649-f9f62817-be5b-4b3c-8413-d3dde5ac7caa.png">

### With remotely
<img width="806" alt="Screenshot 2022-12-08 at 9 31 28 PM" src="https://user-images.githubusercontent.com/76121100/206499889-0cd3bd3d-9391-4b7d-bc43-15991dc7bfdb.png">
<img width="806" alt="Screenshot 2022-12-08 at 9 31 43 PM" src="https://user-images.githubusercontent.com/76121100/206500004-caa081bc-a097-4f88-b9bf-ae289128b6fc.png">

### What OS are you using?

macOS

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.0.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by SyncroIT** [comment]
I'm running Obsidian on a MacBook Pro M1 (Intel silicon, ARM), saving with password on OneDrive and I'm not having this issue. 

Obsidian and plugin versions are the same.

**Comment by echo-saurav** [comment]
So I just made a new vault without any plugin , copied all old files, and its the same result for me. 
I set `schedule for auto run` 1 min. its says that battery might be impacted tho
I am suspecting that, every minute its scanning my whole vault for any changes, that scanning is bit resource hungry
My suggestion would be scan only opened file for changes

**Comment by SyncroIT** [comment]
@echo-saurav 
I actually have never set the schedule to auto run, that's probably why I was not getting the same issue.
How many files and folders do you have in the vault causing this problem to happen?

**Comment by echo-saurav** [comment]
Its not very big, about 390 notes with 45 images 
So you just manually run sync? 
i am thinking to automate the sync somehow cz i will totally forget to sync when i need. There should be a plugin to run command automatically

**Comment by PassionPenguin** [comment]
i strongly suspect that it was true... see #286

**Comment by PassionPenguin** [comment]
Thus, as what i would recommend, is that we may better use a third-party syncing service instead of relying on Obsidian, which is built in ts/js (not easy to debug the internal exceptions), to sync our files.

**Comment by fyears** [comment]
Hi the plugin relies on the [Obsidian api to return the files list](https://github.com/remotely-save/remotely-save/blob/b238988012f63f851c56496263cf469237e78a29/src/main.ts#L264C36-L264C53). And the remote http api to return the remote files list. So technically the plugin itself would not scan the whole disk to load the data for the meta data.
