### ISSUE TITLE
[Bug]: on Android client, remotely save will make obsidian crash

### ISSUE THREAD

**Issue by xie2339669496** [remotely-save/remotely-save#269]
### What happened?

When  I run remotely save on Android client, obsidian will crash.

### What OS are you using?

Android

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.1(83)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fakeYanss** [comment]
Same here for Android.

**Comment by fyears** [comment]
Likely dup of https://github.com/remotely-save/remotely-save/issues/265
