### ISSUE TITLE
[Bug]: The vault files wont open on another device.

### ISSUE THREAD

**Issue by Marsyle** [remotely-save/remotely-save#271]
### What happened?

Hi!
I tried using remotely save so that I can have my vault available across multipel devices.
So I save to OneDrive, go to my laptop, download the plugin there to, and open a vault, an theres nothing there. i'v tried downloading the files an opening them in obsidian but they just show up as the filenames with nothing in them. 

Help! What do I do?
Im not knowledgeable about this kind of stuff, i just want the plugin to work :'D.

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.0.3

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Please create a test vault and create some **not-empty** files and follow the doc to try again. The initial file uploads should happen inside Obsidian by this plugin and althe contents will be saved in /Apps/remotely-save instead of root dir in OneDrive.
