### ISSUE TITLE
[Feature Request]: select storage class

### ISSUE THREAD

**Issue by tiramiseb** [remotely-save/remotely-save#274]
### What feature are you suggesting?

I'm trying to use Scaleway object storage (S3-compatible). It works, but files are created with the "STANDARD" storage class. I would like to select another storage class.
(with scaleway, the one-zone class has a free tier of 75GB forever, therefore it would be perfect for completely free sync of obsidian data)

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Because the plugin has to scan at least the metadata of each file, so all the data should be treated as "hot" data (a.k.a. "STANDARD" storage class).
