### ISSUE TITLE
[Feature Request]: Improve syncing UX

### ISSUE THREAD

**Issue by ZeroEkkusu** [remotely-save/remotely-save#275]
### What feature are you suggesting?

Hi, @fyears,

This is a follow-up to #12.

Currently, multiple log messages are shown while syncing, which occupies screen space, most notably on mobile.

My proposal is to add an option to make logging less verbose:

- Show only `Remotely Save: Syncing` and `Remotely Save: Successful/Failed` (hide the logs in between)
- If the user taps on 🔄 while syncing, unhide the current log

This will also look prettier. Let me know what you think.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by jeffreyhu3** [comment]
Please add a switch in setting pages so that we can Disalbe notifications, however erros are still show as ontification even if enable  this setting. Currently, many logs pup up during we write docs if we setting sync interval as 1 minute.

**Comment by Sippelin** [comment]
I don't get notifications when syncing automatically at all. So I suggest that when synchronization is completed, a notification appears that "synchronization has been completed" and it does not disappear until the user clicks on it.

**Comment by fyears** [comment]
Ok the new version will reduce the notifications.
