### ISSUE TITLE
[Bug]: connect error using self-built s3 server(minio) with custom port

### ISSUE THREAD

**Issue by rewalax** [remotely-save/remotely-save#277]
### What happened?

i built my own s3 server with Minio(default server port is 9000), it works well with other software, but showed "Request failed, status 403" with remotely-save.
it turned out remotely-save doesnt support custom port. When i changed my server port to 443, it all run good.
plz fix this. Thank u.

and i found someone had reported this bug before,but it's still not fixed yet:
https://github.com/remotely-save/remotely-save/issues/195

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

1.0.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by LooseGU** [comment]
I have encountered the same issue as well.

**Comment by anschein** [comment]
Same here

**Comment by kimberxu** [comment]
the same

**Comment by cui-wei** [comment]
same here

**Comment by chujunliang** [comment]
the same

**Comment by kumaresh0** [comment]
<img width="306" alt="image" src="https://github.com/remotely-save/remotely-save/assets/117239791/24bcd72a-5e06-46cf-b057-e0de9a50d248">

**Comment by fyears** [comment]
merge to #416
