### ISSUE TITLE
[Feature Request]: Keep file copies when sync conflict

### ISSUE THREAD

**Issue by cpfy** [remotely-save/remotely-save#278]
### What feature are you suggesting?

First of all thanks for bringing this perfect plugin!

But during my use, I found that there are certain areas that can be improved. Especially when it comes to handling file conflicts

Given that git is not used for version control, I suggest that Evernote create "copies" of files that are detected to be in conflict between multiple devices, and notify the user to choose which version to keep

Hopefully, Remotely save plugin can be more and more complete and reliable~

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Sorry but not going to implement this in the near future.

By implementing the conflict files saving, the plugin needs to compare the file contents and decide how to compare them: If A is a super set of B and A is newer, overwrite B with A; else create a copied file. A typical substring problem: https://stackoverflow.com/questions/3183582/what-is-the-fastest-substring-search-algorithm

It requires a very big part of the complexity to the current implementation, and it's quite possible that the algorithm runs slowly on mobile. I am not clever enough to implement this without introducing more bugs...
