### ISSUE TITLE
[Bug]: if "Apps" folder already exists, an "Apps 1" folder is created (OneDrive for personal)

### ISSUE THREAD

**Issue by danielmunoz** [remotely-save/remotely-save#279]
### What happened?

# What happened?

When I set up syncing with OneDrive for personal, the resulting folder was `/Apps 1/remotely-save/[my-library-name]`.

# What did I expect?

I expected that the resulting folder were `/Apps/remotely-save/[my-library-name]`.

# Why did it happen?

Maybe because I already had a `/Apps/` folder, that contains other folders for other apps.

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.1 (83), API v1.0.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
It's created automatically by OneDrive (the special folder for third-party app). I am sorry but no way I could do here...

**Comment by danielmunoz** [comment]
Thank you, @fyears.
