### ISSUE TITLE
[Bug]: Android 13 CA issue

### ISSUE THREAD

**Issue by MortalKim** [remotely-save/remotely-save#281]
### What happened?

I got ` trust anchor for certification path not found` on android 13 MIUI 14 device.
It is a common issue on android when android version > 7.0.

I have a WebDav on qnap nas (by frp), and I tested this on web(Chrome/Edge), IpadOS, Windows and Mac, all works fine, So I'm sure this is an Android problem.

### What OS are you using?

Android

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.1

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
As you said, this is a ssl configuration problem. Check out the Internet for solutions like [this](https://stackoverflow.com/questions/6825226/trust-anchor-not-found-for-android-ssl-connection). No much I can do in the plugin.
