### ISSUE TITLE
[Bug]: 同步 readwise 内容时报错 403

### ISSUE THREAD

**Issue by Ton-yi** [remotely-save/remotely-save#282]
### What happened?

![image](https://user-images.githubusercontent.com/73752817/210719641-67912b57-736d-4368-ae99-8b5fce79edc3.png)
基本每次有新文章汇入obsidian时都如是，

我有尝试手动删除最近同步的文件（obsidian内删除后移至.trash文件夹）后使用win资源管理器手动从.trash文件夹移回原文件夹，得以成功同步

每次这么操作不现实

---
我使用群晖webdav，windows用的内网同步
![image](https://user-images.githubusercontent.com/73752817/210720964-4c6ff286-0fa6-472a-ae49-1fb3673b2b4f.png)

### What OS are you using?

Windows, iOS (iPhone, iPad), Android

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.1.9

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by ychy00001** [comment]
一样。。。解决不了

**Comment by fyears** [comment]
这个问题，可以新建一个空的 vault 随便写一些文件，同步一下试一下吗？确认是 readwise 导致的？使用的是 Obsidian readwise 插件？

**Comment by i-iooi-i** [comment]
![image](https://github.com/remotely-save/remotely-save/assets/1827701/79e1e786-dc07-40dd-9526-96ddc21acf66)
改成这样解决了。

**Comment by fyears** [comment]
看来 depth 1 很有必要设置成默认模式……蛋痛

**Comment by jokervTv** [comment]
> ![image](https://private-user-images.githubusercontent.com/1827701/296546396-79e1e786-dc07-40dd-9526-96ddc21acf66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTIwMDYsIm5iZiI6MTcwNzExMTcwNiwicGF0aCI6Ii8xODI3NzAxLzI5NjU0NjM5Ni03OWUxZTc4Ni1kYzA3LTQwZGQtOTUyNi05NmRkYzIxYWNmNjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMDU0MTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWEyZjI0YzAzZTJjOTA1NGQwYmQyYWFiZWFhMjBmNWU3MTgxMWJhNzlmMzNhYTM5ZTIxZmYwZjM4OWE2NmJjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G-hkhZ0lENGaTvWc9KIavkG1xzB3-BtAhH34GKqZSnI) 改成这样解决了。

有帮助!

**Comment by fyears** [comment]
新版本 depth 默认为 1 了
