### ISSUE TITLE
[Bug]: 坚果云的webdav会分页，导致获取到的文件数不全，每次重新下载一部分

### ISSUE THREAD

**Issue by keeyangyy** [remotely-save/remotely-save#284]
### What happened?

文件少的时候使用正常，文件多了之后就出问题。测试过1000个文件左右，每次同步都会重新上传100多个文件，即使没有修改文件直接进行同步也是如此。我开了坚果云的会员，是可以支持到半个小时1500次请求的。请求够次数之后是出现报错，无法同步，等半个小时之后又可以重新同步，跟这个分页机制是不太一样的。

从导出的同步计划里看，每次同步都会有一部分文件是存在在云端的，但是同步计划里显示云端不存在，因此又重新上传。

坚果云的webdav看官方说明说限制读取文件数，会分页，每次最多一页只能读750个文件，估计是这个的影响，剩下的文件没有读到，本地又重新上传一份。坚果云官网的原话是这样的：

> 同步目录数限制：目前坚果云的WebDAV协议单次请求文件数（包含文件和文件夹）为750个，支持分多页多次加载。如果您使用WebDAV的三方工具未实现按分页多次加载，可能会出现文件同步不完整的情况，建议您使用坚果云客户端进行直接同步。

经测试，更换teracloud使用webdav就没有这个问题。但是试了很多感觉还是坚果云速度最快最稳定，望作者修复，感谢！

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.1.9

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
调研了一圈，这问题 joplin 也遇到了： https://github.com/laurent22/joplin/issues/4294

找了一圈，标准 webdav 似乎没有分页之类的逻辑，可能实现比较困难。

**Comment by islent** [comment]
发现把 发送到服务器的Depth header 选 支持depth='infinity 就OK了

参考： 
- https://forum-zh.obsidian.md/t/topic/31274/6
- https://github.com/remotely-save/remotely-save/issues/201#issuecomment-1646565998

**Comment by fyears** [comment]
不对。infinity应该解决不了分页问题的

**Comment by fyears** [comment]
我试试

**Comment by fyears** [comment]
@islent 确认了是不行的。改回 depth=1 哈。目前只支持一层文件夹内有 749 或以下的文件。超过了会有出错提示。
