### ISSUE TITLE
[Bug]: 使用腾讯云COS的自定义源站域名，报404

### ISSUE THREAD

**Issue by lfk2458** [remotely-save/remotely-save#285]
### What happened?

使用腾讯云COS的自定义源站域名，报404

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

v1.1.9

### Version of Obsidian

0.3.25

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by eryajf** [comment]
I have the same problem.

**Comment by fyears** [comment]
我这里没有权限绑定自定义源站域名。有更加具体的错误显示吗？使用自带的 qcloud 域名是否正常呢？

我这边确认用默认域名是可以的： https://github.com/remotely-save/remotely-save/blob/master/docs/remote_services/s3_tencent_cloud_cos/README.md

**Comment by fyears** [comment]
没有回应，无法复现，关闭。
