### ISSUE TITLE
[Bug]: 附件无法添加回笔记 只要同步就会被删除

### ISSUE THREAD

**Issue by v423** [remotely-save/remotely-save#288]
### What happened?

用插件批量清除unlinked image 其中有一些是误删除 于是在在回收站里面恢复文件 
但是remotely依旧把这些图片视作需要删除的文件 每一次触发同步就会删除文件
本地清除同步计划 数据库之后同步也依然会触发删除 
现在确认本地文件是最准确的内容 需要能够强制覆盖云端类似 `push --force`

补充:
1. 回收站直接恢复文件不行
2. 从回收站剪切文件到asserts文件夹也不行

**问题演示视频** 
链接：https://share.weiyun.com/6pDhPARg 密码：zg255b 
链接：https://pan.baidu.com/s/1GnGJQX7lTgSfNXjYtLJFdg 提取码：w76v
垃圾微云在线看是黑屏 但是看本地文件没问题 不能看的话看百度云

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

1.1.9

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Sakura-Qy** [comment]
我也一样，在手机端同步就会上传到云端，电脑端同步就会恢复云端的文件，而把在电脑上修改的全部覆盖

**Comment by Null404bad** [comment]
我也一样，这个Bug还没修复吗

**Comment by fyears** [comment]
这里是判断修改时间的。有可能 obsidian 恢复文件不会更新修改时间。

可以点击设置里面的最低下的那个 reset （重设）按钮，这样就不会判断删除了。

**Comment by fyears** [comment]
此外也手动去远端把 remotely-save-metadata-on-remote* 文件删除即可
