### ISSUE TITLE
ios14.4 failed to load提示，你倒是修一下啊 多少人说过了 收费行不？[Bug]: 

### ISSUE THREAD

**Issue by yufanme** [remotely-save/remotely-save#289]
### What happened?

ios14.4 failed to load提示，你倒是修一下啊 多少人说过了 收费行不

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using?

webdav

### Version of the plugin

最新

### Version of Obsidian

最新

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Mr-deer99** [comment]
I also notice this problem,it seems appear when I interrupt the sync by switching vault.I can't find a way to solve it.The only way to use is to reinstall the plugin.

**Comment by fyears** [comment]
这位网友，ios 14 太老了（查了一下 ios 15 是 2021年9月，现在都快 2024 年了），我手上没有机器可以 debug ……猜测是不支持某些 api，很难办啊。

**Comment by guaguajflk** [comment]
> 这位网友，ios 14 太老了（查了一下 ios 15 是 2021年9月，现在都快 2024 年了），我手上没有机器可以 debug ……猜测是不支持某些 api，很难办啊。

我也是同样的问题 IOS设备不比Android和Windows  版本自己是做不了主的（升级后变卡又降不回去，只能用老版本）
其他插件直接就提示“该插件不支持你的设备”，  这个插件没有提示，但是安装完了预后就是无法启用@fyears
