### ISSUE TITLE
[Bug]: 群晖自建Cloudreve，用webdav连接时提示“No root multistatus found”

### ISSUE THREAD

**Issue by BoosterCore** [remotely-save/remotely-save#290]
### What happened?

用群晖Docker自建了Cloudreve网盘，用Ddnsto做了内网穿透，并用Alist的webdav挂载也正常，但用remotely-save的webdav连接就不行，提示“No root multistatus found”

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.1.9

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Lueric512** [comment]
我也遇到了相同的问题，在MacOS和Windows上通过更换ddnsto为http解决了。但是同样的方法在ipadOS上不奏效，请问现在有解决办法了吗？

**Comment by fyears** [comment]
新版的 webdav 有优化，用 alist 亲测没问题，可以更新0.3.28或以上试试
