### ISSUE TITLE
[Bug]: 使用nginx-proxy-manager反向代理并配置证书后，ios端无法成功连接。

### ISSUE THREAD

**Issue by Tenkodo** [remotely-save/remotely-save#292]
### What happened?

- 使用nginx-proxy-manager反向代理后（配置证书https），ios端（尝试过iPhone与iPad）均无法成功连接；
- 使用nginx-proxy-manager反向代理后（不配置证书，使用http），ios端可成功连接；
- 不使用nginx-proxy-manager，直接使用webdav并配置证书可成功连接；
- - 在PC端obsidian不论是否通过nginx代理只要配置了证书均可以成功同步（包括插件均无问题）。
（这里webdav均是使用威联通nas自带的webdav）

以下为问题截图：
![IMG_0042](https://user-images.githubusercontent.com/62917736/215961438-bee972cc-b477-4a3c-9c81-f240f1c417cf.jpeg)
![IMG_0041](https://user-images.githubusercontent.com/62917736/215961304-34b9cb94-3530-4c4a-9eab-52646db55f21.jpeg)

下面为排除影响，同时配置了CORS：
![IMG_0040](https://user-images.githubusercontent.com/62917736/215961185-539a734f-a15d-4ddf-b9c4-a6b5fcf01ecd.jpeg)

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.1 (83) API v1.0.3

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Tenkodo** [comment]
最后谢谢作者的辛苦工作，让我们用到这么好的同步工具。目前我直接不使用nginx反向代理，直连端口并配置证书使用。
希望这个问题能解决帮助到需要使用nginx-proxy-manager的人。

**Comment by fyears** [comment]
配置证书是自签的吗？自签的话 ios 系统应该不会通过的。（可以试试用 safari 直接访问看是否有告警）。

如果确认不是自签证书的问题，欢迎提供一下复现方法后重开 issue 。
