### ISSUE TITLE
[Feature Request]: Add checkbox to ignore ssl cert verify for WebDAv by https

### ISSUE THREAD

**Issue by gung-rgb** [remotely-save/remotely-save#294]
### What feature are you suggesting?

Add checkbox to ignore ssl cert verify for WebDAv by https

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
i am afraid it may cause some security issues and obsidian api doesn't support this. so this will not be implemented
