### ISSUE TITLE
[Bug]: Cannot connect to Dropbox

### ISSUE THREAD

**Issue by TGRush** [remotely-save/remotely-save#295]
### What happened?

I wanted to setup Remotely Sync on a new desktop using Dropbox, however, it simply fails saying "Something goes wrong while connecting to Dropbox". It does not give me any more information.

### What OS are you using?

Linux

### What remote cloud services are you using?

Dropbox

### Version of the plugin

0.3.25

### Version of Obsidian

1.1.9

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
No enough info and cannot reproduce the issue...

If you are still encountering the problem and would like to report it, please consider reading and following the "Advanced: Check Console Output Directly" section of https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/README.md
