### ISSUE TITLE
[Bug]: 连接威联通nas 测试连通性没问题，但是点击同步按钮后出现以下错误

### ISSUE THREAD

**Issue by tsaoshuang** [remotely-save/remotely-save#297]
### What happened?

![image](https://user-images.githubusercontent.com/7597482/219600850-e8d897cc-c82a-4619-ba4d-438945200061.png)

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.1.9

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by atnoir** [comment]
same issue with OneDrive, but despite this error message, everything is synchronized properly.

**Comment by zenz** [comment]
威联通nas自动会产生两个@开头的目录，用于记录状态，在删除文件后会产生desktop.ini文件，导致同步失败，把两个@目录中的对应文件删除即可。

**Comment by fyears** [comment]
新版 webdav 应该有些优化，可以更新到0.3.28 或更新再试试
