### ISSUE TITLE
[Bug]: Status Error 405 When Using "Sync Config Dir"

### ISSUE THREAD

**Issue by whitekr0w** [remotely-save/remotely-save#298]
### What happened?

Currently, when using the "Sync Config Dir" experimental feature, I am receiving a status error 405. 

I have confirmed that when disabling this feature, data is able to be read and written just fine. The following error occurs when the feature is enabled however.
![image](https://user-images.githubusercontent.com/104945272/220003123-e768b49b-e0a6-448e-88e2-8782fee1bb68.png)

Prior to the recent jump to Obsidian 1.0, this seemed to function fine, but could just be a coincidence. 

Things I have tried:
- Double checking read/write permissions of folders. (Full)
- Double checking read/write permissions of web user. (Full)
- Verifying access to the hidden directories on the WebDav page. (I am able to access .obsidian folder, with written data)
- Switching from different Auth Types, currently using Basic auth (Causes 401 error)
- Switch depth headers, currently using depth of one. (Causes a 403 error)
- Clearing database sync history
- Clearing local cache/database
- Reinstalling the plugin and re-importing the settings
- Trying syncs on different platforms (Windows, iOS, Linux)

It seems that when creating the first initial sync, all data is uploaded fine, but after this, the error appears when trying to sync again. I am running a WebDav server via Docker in this case.

The error seems to be regarding the .obsidian folder, I thought maybe it was due to a permissions issue on the WebDav side to this folder, but as it can be seen, it is fully accessible on the web-side.
![image](https://user-images.githubusercontent.com/104945272/220007255-b2d3c7d7-d832-47a1-aafc-3f66f712ea12.png)

### What OS are you using?

Windows, Linux, iOS (iPhone, iPad)

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.1.9

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by rabume** [comment]
Can confirm this. I also have this issue.
I also experienced that the first run was working. 

This is an error log of my WebDAV server running with nginx:
``` shell
2023/05/06 20:01:43 [error] 19445#19445: *295116 mkdir() "/var/share/obsidian/.obsidian" failed (17: File exists), client: XX.XX.XXX.XXX, server: some.cool.server, request: "MKCOL /obsidian/.obsidian/ HTTP/2.0", host: "some.cool.server"
```

**Comment by fyears** [comment]
It looks like you are using a custom webdave server, would you like to verify if uou can create or download the hidden folder using normal webdave client? I am guessing the webdave server disallow some operations on hidden files.

**Comment by fyears** [comment]
closed cuz no further info
