### ISSUE TITLE
[Bug]: Sync failed with jianguoyun webDAV

### ISSUE THREAD

**Issue by sdlllllll** [remotely-save/remotely-save#299]
### What happened?

![bugreport](https://user-images.githubusercontent.com/49221083/220942984-99294e98-74c8-4235-8291-4d19aa143801.png)

I tried deleting the folder on webDAV and syncing again. This will succeed. But this error occurs when I manually sync again. And I can't find the configuration .json file under webDAV folder.

### What OS are you using?

Windows, macOS

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.1.15

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by SenLief** [comment]
https://help.jianguoyun.com/?tag=webdav

> 第三方应用访问的限制

文件上传大小限制：当前 WebDAV 客户端和网页端上传大小的限制是一致的，默认为 500M（私有云可以通过相关设置调整）。

访问频率限制：由于WebDAV协议比较占用系统资源，免费版用户限制访问频率为每30分钟不超过600次请求。付费用户限制访问频率为每30分钟不超过1500次请求。

**Comment by sdlllllll** [comment]
整个库才不到80k

> 



> https://help.jianguoyun.com/?tag=webdav
> 
> > 第三方应用访问的限制
> 
> 文件上传大小限制：当前 WebDAV 客户端和网页端上传大小的限制是一致的，默认为 500M（私有云可以通过相关设置调整）。
> 
> 访问频率限制：由于WebDAV协议比较占用系统资源，免费版用户限制访问频率为每30分钟不超过600次请求。付费用户限制访问频率为每30分钟不超过1500次请求。

整个库还不到80K，且可以在把webDAV上的文件删除后完成首次上传同步，应该不是坚果云的问题。

**Comment by SenLief** [comment]
> 整个库才不到80k
> 
> > 
> 
> > https://help.jianguoyun.com/?tag=webdav
> > > 第三方应用访问的限制
> > 
> > 
> > 文件上传大小限制：当前 WebDAV 客户端和网页端上传大小的限制是一致的，默认为 500M（私有云可以通过相关设置调整）。
> > 访问频率限制：由于WebDAV协议比较占用系统资源，免费版用户限制访问频率为每30分钟不超过600次请求。付费用户限制访问频率为每30分钟不超过1500次请求。
> 
> 整个库还不到80K，且可以在把webDAV上的文件删除后完成首次上传同步，应该不是坚果云的问题。

不是容量，是请求次数限制。你换个 webdav 试试。

**Comment by sdlllllll** [comment]
> > 整个库才不到80k
> > > 
> > 
> > 
> > > https://help.jianguoyun.com/?tag=webdav
> > > > 第三方应用访问的限制
> > > 
> > > 
> > > 文件上传大小限制：当前 WebDAV 客户端和网页端上传大小的限制是一致的，默认为 500M（私有云可以通过相关设置调整）。
> > > 访问频率限制：由于WebDAV协议比较占用系统资源，免费版用户限制访问频率为每30分钟不超过600次请求。付费用户限制访问频率为每30分钟不超过1500次请求。
> > 
> > 
> > 整个库还不到80K，且可以在把webDAV上的文件删除后完成首次上传同步，应该不是坚果云的问题。
> 
> 不是容量，是请求次数限制。你换个 webdav 试试。

文件数总量也不过20，我是新用户，而且删除webDAV上的文件再上传可以成功这一操作可以重复多次，且每次都是上传后手动同步会报错。

**Comment by ckunkun** [comment]
插件设置里把发送到服务器的Depth header 设置成支持depth=infinity 就好了。

**Comment by fyears** [comment]
试试设置 depth=1
