### ISSUE TITLE
坚果云同步中断

### ISSUE THREAD

**Issue by kangkang111-777** [remotely-save/remotely-save#304]
### What happened?

remotely-save-1678276899265:中断同步，同
步来源=manual,出错阶段
=getting_remote_files_list
![image](https://user-images.githubusercontent.com/76606465/223708586-b29d061a-7c7f-45d2-a1e0-f0e1874f6acc.png)

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.1.16

### Using password or not

- [x] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by linwqwhu** [comment]
I also encountered this problem.

**Comment by lil-i321** [comment]
I also encountered this problem.

**Comment by guitarandherandher** [comment]
我也是这个问题，同步了一部分文件之后就报错

**Comment by nirvdrum** [comment]
An [HTTP 503 status code](https://developer.mozilla.org/en-US/docs/web/http/status/503) indicates an issue with the server you're talking to. I suppose the plugin could be sending a bogus request, but the server should respond with a different status code. Often times a 503 is a temporary code while the server is undergoing some issue. Are you still seeing it?

**Comment by deardeer7** [comment]
我目前用了onedrive 同步方案解决了，暂时不需要了，但是问题可能需要进一步明确发自我的 iPhone在 2023年5月1日，04:12，Kevin Menard ***@***.***> 写道：﻿
An HTTP 503 status code indicates an issue with the server you're talking to. I suppose the plugin could be sending a bogus request, but the server should respond with a different status code. Often times a 503 is a temporary code while the server is undergoing some issue. Are you still seeing it?

**Comment by ViCrack** [comment]
我也遇到了然后解决了，这应该是坚果云的bug，或许你们可以降低一下并行度，然后重试

**Comment by deardeer7** [comment]
我换了onedrive，目前一切良好发自我的 iPhone在 2023年5月11日，10:25，ViCrack ***@***.***> 写道：﻿
我也遇到了然后解决了，这应该是坚果云的bug，或许你们可以降低一下并行度，然后重试

**Comment by fyears** [comment]
Jianguoyun / Nutstore has api limits. Sometimes the plugin runs out of the limits so some errors occure. No way to work around except waiting for a few hours to retry.

坚果云有 api 限额，有时候插件运行会导致超过限额，导致出错。没办法，只能隔一段时间重试。
