### ISSUE TITLE
[Bug]: 同步后文件内容被清空，导致插件损坏无法启动

### ISSUE THREAD

**Issue by MetaphysicianLeo** [remotely-save/remotely-save#305]
### What happened?

之前一直认为是我误删了，后来发现并不是，在自动同步过程中有一定概率清空文件，不确定什么原因。
同时因为我开启了配置文件同步，remotely-save的插件文件夹中的main.js的内容也被清空了，导致Failed to load remotely-save
<img width="186" alt="a" src="https://user-images.githubusercontent.com/33951689/223978371-456e199d-9677-4071-a22e-d5b26bf61e20.png">

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.1.16

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
可能是 webdav 用了坚果云？是的话，无解。

https://github.com/remotely-save/remotely-save/issues/284
