### ISSUE TITLE
[Bug]: 同步报错，但vault其实是成功同步了。

### ISSUE THREAD

**Issue by atnoir** [remotely-save/remotely-save#306]
### What happened?

<img width="273" alt="Snipaste_2023-03-10_10-15-04" src="https://user-images.githubusercontent.com/59659718/224206277-42b561a5-ee54-42d6-81f0-1797ee1d2b37.png">
如图，前段时间的最后提示都是正常的“remotely save finishes”，最近成了这样的通知，但在文件夹里也找不到desktop.ini文件。即使出现了这个报错通知，文档在其他移动端都是同步过去了的，并且在移动端上也没有这样的报错情况。
想知道这个报错是什么意思？怎么修复为好？
谢谢。

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.1.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
这是系统文件，可能就是因为它是特殊的所以有权限问题

英文： https://helpdeskgeek.com/windows-11/what-is-the-windows-desktop-ini-file-and-can-i-delete-it/amp/

中文： https://juejin.cn/s/如何显示desktop.ini文件
