### ISSUE TITLE
[Bug]: Conflicted copies of notes with Dropbox [multi-platform]

### ISSUE THREAD

**Issue by AustinSanderson** [remotely-save/remotely-save#307]
### What happened?

The conflicted copies have occurred on both Windows and Mac OS, but not necessarily both of them are open. Usually, only one device is in use. 

### Problems:

1. Notes randomly but frequently create conflicted copies of themselves while I am typing mid-sentence. Then, the original note deletes itself, leaving the conflicted copy only, which then has some truncated text. I have observed this on both Windows and Mac.
3. I have also seen data.json just create multiple conflicted copies of itself in Dropbox when no notes are being typed into at all - Obsidian is open only on 1 device when this occurs.

Currently, I am running the latest version of Obsidian on the following platforms.

- iOS 16.2
- Windows 10
- Mac OS X Ventura

### Dropbox settings:

- All markdown files are kept on the local device (not stored as “online only”)
- All newly created files will be “available offline”
- Dropbox v 167.4.4719

### Enabled Obsidian plugins:

- remotely-save 0.3.25 (this is the only plugin enabled on iOS)
- Advanced Tables 0.18.1
- Advanced Slides 1.20.0
- Tag wrangler 0.5.6

### What I’ve tried:

- Updating all Dropbox settings to have Obsidian files stored on local machine (not stored as "online only"). All new files (notes created in Obsidian) are offline by default. I thought this would solve it because new notes more frequently had the issue, but no, it did not.
- Deleted workspace.json, closing Obsidian , and reopening on a single device to recreate the json.
- Deleted data.json
- Ensuring only one device is open on Obsidian at once
- Uninstalled/reinstalled Obsidian after the JSON deletions

### What OS are you using?

Windows

### What remote cloud services are you using?

Dropbox

### Version of the plugin

0.3.25

### Version of Obsidian

v1.1.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
are you changing the upper case to lower case of the file names? or lower case to upper case?

**Comment by fyears** [comment]
no response so far...
