### ISSUE TITLE
Failed to load plugin remotely-save on Android Device

### ISSUE THREAD

**Issue by D-Q-B** [remotely-save/remotely-save#308]
### What happened?

Failed to load plugin remotely-save on Android Device.At the same time, I checked that the installation directory contains the main. js file.But I still can't load the plug-in.
![S30312-10395505](https://user-images.githubusercontent.com/105706321/224523229-e5e65f56-1a09-4f0b-9e70-5e1dc3987876.png)
![S30312-10402819](https://user-images.githubusercontent.com/105706321/224523243-ddfb62f1-9dce-429b-ad35-2ea14674d707.png)

### What OS are you using?

Android

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.3（95）

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
（直接中文吧）

这里有没有操作系统和版本号？更新obsidian最新版试试？我自己手机无法复现

**Comment by Cloudptj** [comment]
我在更新到最新的0.3.35前是可以用的，更新插件后就开始报不能加载插件的错误。
然后在googple play里更新的OB，仍然无法加载插件

**Comment by Cloudptj** [comment]
刚刚将插件退回到0.3.25，安卓端可以加载插件。
不过PC端0.3.35有个getting_remote_files_list的错误，似乎不能同步valut，只能同步一个新的valut上去，有人报没？没人报，我再开个bug的issue。

**Comment by fyears** [comment]
能否更新一下 android web view 再试试

https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en_US&gl=US

**Comment by fyears** [comment]
@Cloudptj 0.3.37 更新了修复了一个 bug，可以试试是否还有 getting_remote_files_list 错误

**Comment by Cloudptj** [comment]
PC端还是一样，OB版本1.5.3，插件版本0.3.37，同步到坚果云时，只能把OB仓库同步到一个新的文件夹里，坚果云已存在的文件夹同步时，就会出现getting_remote_files_list错误。
安卓在0.3.25时，也出现getting_remote_files_list错误。
android web view不敢更新，之前更过一次，网页放个视频都卡。

**Comment by fyears** [comment]
这里不是fail to load了。我试试坚果云再看看什么问题。有使用新的测试vault，从零开始的从而稳定复现的步骤吗？

此外文件有超过1000个吗？

**Comment by Cloudptj** [comment]
没有1000，600多。
我刚刚用zotero同步文献也试了几次才成功，不会是坚果云的问题吧，囧。

**Comment by fyears** [comment]
所以其实是可以 load 进去，且没有 undefined adapter 错误了是吧？

坚果云会限制 api 连接次数，大概率是这个原因了

**Comment by Cloudptj** [comment]
好像还是有getting_remote_files_list的错误。
我刚把插件里自行同步给关了，zotero里的自动同步也关了。
明天再看看，到时候应该能排除限制api连接次数的问题。

我其实觉得应该不是限制次数的问题，zotero我可能不一直开。但OB我基本整天开着（10h以上），设置10min同步一次，要限制早限制了。

**Comment by Cloudptj** [comment]
今早试了，zotero同步没问题，OB报getting_remote_files_list错误。
console里的信息：
```
remotely-save-1705368873759：中断同步，同步来源=manual，出错阶段=getting_remote_files_list
Error: Request failed, status 503
    at new t (app.js:1:1762600)
    at gq (app.js:1:1762792)
    at app.js:1:1763469
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at a (app.js:1:236081)
```

**Comment by fyears** [comment]
zotero 只是同步了主要的数据库文件 sqlite 吧？那么只需要处理一个文件。

relotely save 同步的是所有文件，它至少需要读取所有文件列表和递归文件夹的列表，用的api数比较多。

503 就是请求数限制了

https://content.jianguoyun.com/1112.html

https://forum-zh.obsidian.md/t/topic/12463/3

**Comment by Cloudptj** [comment]
“30分钟不超过600次请求”

remotely save会一次就发出这么多请求吗

那看来只能用坚果云自己的同步了。

**Comment by fyears** [comment]
看你文件夹数量，每个文件夹读一次

**Comment by exoticknight** [comment]
考虑新增一个索引文件记录所有文件hash和结构，每次同步先看索引进行快速判断？
