### ISSUE TITLE
[Feature Request]: sync specific file type, not just `.md` and `/.obsidian`

### ISSUE THREAD

**Issue by yunyuyuan** [remotely-save/remotely-save#309]
### What feature are you suggesting?

Also support sync another files, e.g. `.html, .conf, .py`. Sometimes I just want to edit them as raw text(using https://github.com/MeepTech/obsidian-custom-file-extensions-plugin/)

By the way, I'm using VitePress to write a documentation website. It allows us to import code snippets in `.md` files (https://vitepress.dev/guide/markdown#import-code-snippets). I want to edit `.md` and other code files in Obsidian, sync them to my self-hosted WebDAV server, and then have the website automatically built with my file-watch script.

At the moment, I'm using [code-server](https://github.com/coder/code-server) for remote editing, but I think it would be better to integrate this with Obsidian.

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Hi.

Every file in your vault, except those starting with a dot or those larger than the value you set in the setting “Skip Large File”. 

If that’s not the case, you are welcome to create a detail issue with reproducible example.
