### ISSUE TITLE
[Feature Request]: Using a syncing icon when syncing

### ISSUE THREAD

**Issue by atmomomo** [remotely-save/remotely-save#310]
### What feature are you suggesting?

Thanks for developing this great plug-in. I wonder if it's possible to show the current syncing progress/status on the icon? 
I have OCD and worry about incomplete synchronization, so I repeatedly click the synchronization button many times 😜.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
If you are using pc the sidebar indeed changes the icon while syncing. But on mobile there is no position for the icon to show i am afraid
