### ISSUE TITLE
[Bug]: 电脑端直接用onedrive同步（未使用插件） 文件删除后，手机端无法同步删除

### ISSUE THREAD

**Issue by abingx** [remotely-save/remotely-save#312]
### What happened?

我在电脑端是直接用的onedrive的同步，未使用插件，在电脑上删除文件也完成onedrive同步，手机端再次同步不会删除相应文件，而是将文件再次同步回电脑端

### What OS are you using?

macOS

### What remote cloud services are you using?

OneDrive for personal

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by JunerLee** [comment]
一样的问题

**Comment by fyears** [comment]
目前无法解决。这是因为不经过插件删除的话，插件无法得知文件是被删除了（会以为手机是新增的文件）。
绕过的方法只有手机删除后出触发同步。
