### ISSUE TITLE
[Bug]: when using end-to-end encryption，some problems。

### ISSUE THREAD

**Issue by xingzou66** [remotely-save/remotely-save#313]
### What happened?

Good sir，

when using end-to-end encryption，If a file exists in S3（aliyun oss）, it will display "No Passward"（on computer） or "Get Remote File List Error"（on Android），No encryption or empty buckets are not a problem。

After trying, maybe it is caused by too many files after encryption（The number of documents exceeds one thousand）, I'm not sure.

thxs !

### What OS are you using?

Windows, Android

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

pc：1.1.16 ， Android：1.4.1

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Hi the encrypted files and folders should have the same amount as your original files and folders. Pay attention that in s3 the folder itself is treated as a file too.

And yes from no-password to password you have to reupload the files. Be sure to make a backup of your vault though.
