### ISSUE TITLE
[Feature Request]: Notifications can be resident after synchronization is complete

### ISSUE THREAD

**Issue by shuojie819** [remotely-save/remotely-save#314]
### What feature are you suggesting?

I want the notification to reside after the synchronization is complete.
I need to click on the notification to disappear.

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by shuojie819** [comment]
![image](https://user-images.githubusercontent.com/72399630/226393739-c5d196e8-88ec-4203-a2e7-c479a036a4ce.png)

If you don't keep an eye on him, sometimes you miss the notice.
So I don't know if the synchronization is complete.

> Whether you can show which files have changed, or how many files have changed.

**Comment by fyears** [comment]
新版本有 status bar 应该可以缓解这个问题，

如果这个要停留每次都要点击的话，太麻烦了
