### ISSUE TITLE
[Bug]: Parameter Exceeds Maximum Length

### ISSUE THREAD

**Issue by lijingjian001** [remotely-save/remotely-save#316]
### What happened?

When I was using a password to synchronize data to onedrive, a 400 error occurred. When I opened the console and checked the network records, I found that the API error prompt was' Parameter Exceeds Maximum Length '. However, when I did not use a password, there were no errors.
The api url is: https://graph.microsoft.com/v1.0/drive/special/approot:/obsidian-personal/xxxxxxx
The response value is:

{"error":{"code":"invalidRequest","message":"Parameter Exceeds Maximum Length","innerError":{"code":"parameterIsTooLong","date":"2023-03-24T10:28:09","request-id":"42a8003e-7571-4d49-8a2f-35f04396ccf2","client-request-id":"42a8003e-7571-4d49-8a2f-35f04396ccf2"}}}

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.1.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by M-MAD-Official** [comment]
It is happening to me right now.

**Comment by fyears** [comment]
While the files are encrypted, their names are encrypted too, and the encrypted one will be longer than the original one. So the only way is to shorten your files’ (and parent folders) lengths.
