### ISSUE TITLE
[Feature Request]: ProtonDrive Mobile Syncing

### ISSUE THREAD

**Issue by 4r7if3x** [remotely-save/remotely-save#317]
### What feature are you suggesting?

Is there any way to add ProtonDrive as a remote service on mobiles? As far as I know, there is no public API, but it adds itself to the list of cloud drives on the iOS Files, the same as iCloud Drive or Google Drive.

### What remote cloud services are you using, or suggesting adding the feature to?

others

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
protondrive doesn’t have public api and even rclone uses [go library to try to “guess” the calls](https://rclone.org/protondrive/)

I am afraid it’s too much work for me (one person!) But pull requests are always welcome.
