### ISSUE TITLE
[Feature Request]: 同步原理

### ISSUE THREAD

**Issue by shixing2** [remotely-save/remotely-save#319]
### What feature are you suggesting?

你好，请教个问题，插件每次都会拿着本地库所有的文件和OSS中修改时间做对比吗？这样是不是很耗费时间和电脑资源

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [ ] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
是的，如你所描述。obsidian 有 api 可以返回所有文件的修改时间，所以本地消耗应该还好。
