### ISSUE TITLE
increasing setting of obsidian folder

### ISSUE THREAD

**Issue by duoxun** [remotely-save/remotely-save#320]
### What feature are you suggesting?

HI, First appreciating you bring convenience through this plugin.....

Could you pls increase setting of bukcket folder? Inside same bucket, there are different repo which is matched to relevant repo of obsidian?? In this case I don't need to use too many buckets..... for this feature, is it convenient for you to make it true by $15.0 ??

Tks a lot for reply。。。。
Don

希望作者能够新增可以指定存储桶文件夹的配置，相当于是一个存储桶可以放入多个文件夹，每个文件夹可以对应一个obsidian的仓库，有的obsidian仓库其实不大，但是需要互相隔离，而且有可能用了一段时间就删除，节省建立大量存储的麻烦事！! 如果实现，我捐赠15美金表达谢意！

### What remote cloud services are you using, or suggesting adding the feature to?

HI , I use Tencent Cloud, COS service. 
CLOUD.TENCENT.COM

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by duoxun** [comment]
HI, I use TENCENT CLOUD. In fact there is nothing with this cloud server. Just put setting of indicated folder and it would be settled. I use other application OK since I can indicate which  folder I need to be sync. waiting for reply. TKS.

**Comment by duoxun** [comment]
HI, I use TENCENT CLOUD，COS. In fact there is nothing with this cloud server. Just put setting of indicated folder and it would be settled. I use other application OK since I can indicate which folder I need to be sync. waiting for reply. TKS.

**Comment by fyears** [comment]
I would try to add prefix support.

**Comment by duoxun** [comment]
OK，really appreciating supports. Already clicked star on the  github.

If you do have donate channel, let me know and do it.

Keeping touch about status.

DON













杨东升


***@***.***


13988888888







电子名片新出VIP模板啦，快来体验>>




扫一扫,


快速添加名片到手机




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: fyears  ***@***.***>
 

 
 发送时间: 2023-12-17 23:58:32
 

 
 收件人:remotely-save/remotely-save ***@***.***> 

 
 抄送:易东 ***@***.***>,Author ***@***.***> 

 
 主题: Re: [remotely-save/remotely-save] increasing setting of obsidianfolder (Issue #320)
 





 I would try to add prefix support.

**Comment by fyears** [comment]
合并到 #416 解决
