### ISSUE TITLE
[Bug]: 无法连接teracloud的 WebDAY 服务 

### ISSUE THREAD

**Issue by feiyu517** [remotely-save/remotely-save#321]
### What happened?

![截屏2023-04-04 23 40 36](https://user-images.githubusercontent.com/85143308/229847084-18aeba94-a788-4968-9693-f5fbd15744f2.jpg)

出现 401错误提示

### What OS are you using?

macOS

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.1.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Kanon1982** [comment]
我用黑群晖，也这样。之前同样的设置就没事，见了鬼

**Comment by fyears** [comment]
我自己也在用，确认可以连接的。试试是不是账号密码问题？
