### ISSUE TITLE
请问在iphone里怎么找到remotely-save的目录进去下载main.js呀？

### ISSUE THREAD

**Issue by wangminli** [remotely-save/remotely-save#322]
> > > 是缺少main.js。
> > 
> > 
> > 在插件社区里下载的压缩包解压后确实没有这个文件，感谢。
> 
> 所以应该怎么解决？我也面临着这个困难

下载 https://github.com/remotely-save/remotely-save/releases/download/0.3.25/main.js 手动添加到插件目录里。

_Originally posted by @aidoit in https://github.com/remotely-save/remotely-save/issues/75#issuecomment-1457412280_

**Comment by hoey94** [comment]
这是解决了？还是没解决，也没看到方案
