### ISSUE TITLE
[Bug]: The subdirectory has a. git folder, which cannot be synchronized correctly when encrypted

### ISSUE THREAD

**Issue by zynfly** [remotely-save/remotely-save#323]
### What happened?

![image](https://user-images.githubusercontent.com/14913548/232272512-58074a78-ab00-4274-87f4-db5c284afd33.png)
I use Git to version control certain folders in subdirectories, such as the wiki folder in the picture, but after synchronization, it becomes chaotic.

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

1.1.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
new version will try to explicitly skip this
