### ISSUE TITLE
[Bug]: Can not sync with S3

### ISSUE THREAD

**Issue by pure-maple** [remotely-save/remotely-save#325]
### What happened?

<img width="960" alt="Snipaste_2023-04-22_11-03-28" src="https://user-images.githubusercontent.com/54388301/233758553-3d978e4d-8d26-4786-a3a5-a3d70bcad6ff.png">
采用[缤纷云对象存储](https://www.dogecast.com/)
无法同步文件夹，需要手动在存储桶中新建文件夹才能同步库，否则报错：Request failed, status 404
确定Access_token已经将读写权限全部打开
<img width="389" alt="Snipaste_2023-04-22_11-09-11" src="https://user-images.githubusercontent.com/54388301/233758851-ee833f62-d949-467f-9e4e-b12c04a3993c.png">
下图中的文件夹为在存储桶中手动创建之后，可以同步，在Obsidian中再次新建文件夹则又无法同步
<img width="767" alt="Snipaste_2023-04-22_11-11-57" src="https://user-images.githubusercontent.com/54388301/233758960-38ada243-2463-4d62-8bcf-d70ebf20f4ac.png">

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

1.1.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by jungeee** [comment]
I'm also using dogecast.com and have the same problem, but the folders can be created once in a while, a small number of files can be uploaded.

**Comment by fyears** [comment]
具体是哪个文件夹？还是所有文件夹？

**Comment by fyears** [comment]
没有缤纷云账号，但是所有 s3 都是同一套服务。

腾讯云和 backblaze 是亲测可以的。如果用腾讯云或者 backblaze 可以稳定用新创建的测试 vault 复现的话，欢迎提供 case。
