### ISSUE TITLE
[Bug]: 标题以 # 开头会导致同步失败

### ISSUE THREAD

**Issue by jing8263xiao** [remotely-save/remotely-save#326]
### What happened?

如题

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.1.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by frankzhe** [comment]
同样问题。文件名中只要带了#就会失败。后来解决了吗？

**Comment by jing8263xiao** [comment]
应该还没有

在 2023年12月14日，14:17，frankzhe ***@***.***> 写道：

﻿

同样问题。文件名中只要带了#就会失败。后来解决了吗？
Same issue. Any file with a '#' in the filename fails. Has this been resolved?

**Comment by fyears** [comment]
合并到 #416
