### ISSUE TITLE
[Bug]: 使用minio作为S3存储时出现

### ISSUE THREAD

**Issue by wangzijian121** [remotely-save/remotely-save#327]
### What happened?

I created a bucket using minio chuang, and taking into account all permission issues, it has been set as public
![image](https://user-images.githubusercontent.com/40219314/233827424-256748d5-101e-4510-8af6-7026bf0afb3b.png)
![image](https://user-images.githubusercontent.com/40219314/233827478-e9ced739-e839-4a2e-9478-ea42caea87e3.png)
When I use Obsidian to connect, I get the following error "HEAD http://192.168.138.128:9000/wangzijian 403 (Forbidden)":
![image](https://user-images.githubusercontent.com/40219314/233827516-8c5636a9-765c-4472-8105-296485d3ee45.png)
Is this a bug, or did I misconfigure it?
In addition, I use the PicGo image bed to connect to Minio, and it works perfectly.

### What OS are you using?

Windows, Linux

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

V1.1.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by wangzijian121** [comment]
To add, this is the configuration I use for the PicGo image bed, and the exact same configuration will have this problem on Obsindian.
![image](https://user-images.githubusercontent.com/40219314/233827754-f3760a47-3666-4af6-af72-266ba148eef2.png)

**Comment by wangzijian121** [comment]
I used Joplin to verify my configuration again and found that there were no problems, and the documents and images were synced properly.
![image](https://user-images.githubusercontent.com/40219314/233828545-cac27747-f2cc-404c-b637-8ed39e4aee94.png)

**Comment by ingxhe** [comment]
同样

**Comment by kumaresh0** [comment]
<img width="306" alt="image" src="https://github.com/remotely-save/remotely-save/assets/117239791/abaa2f17-8186-48cc-b696-fee7a38c46b3">

**Comment by happyxhw** [comment]
same problem

**Comment by CoreJa** [comment]
same here, was using cloudflare R2(s3 compatiable)

**Comment by CoreJa** [comment]
> same here, was using cloudflare R2(s3 compatiable)

Problem solved by just hitting that sync button, regardless of whatever it says by that `check` button from the setting page. I tried check button with correct configurations, it still pops out 403 error. But get back to main GUI and hit that little sync button, it just works.

But I believe this error might be more related to issue #195 and #277

**Comment by wangzijian121** [comment]
目前我无奈的使用了 picgo作为中间介质，还没有解决这个问题

**Comment by zchcc** [comment]
same problem
同问题，minio，给其他客户端配置都正常，给remotely save配置就403

**Comment by dengh01** [comment]
same here

**Comment by fyears** [comment]
1. 首先请打开绕过cors
2. 此外检查连接用的是 headbucket 动作，确认一下是不是有权限限制没有允许这个操作？
3. 实际同步应该没有 headbucket，所以是有可能检查失败但是同步可行的。
4. 用了 play.min.io 确认可以连接可以同步。

如果检查了确实允许权限了但是还有问题，欢迎重开 issue 哈，谢谢各位

**Comment by fyears** [comment]
latest commit avoids the headbucket command and should really work
