### ISSUE TITLE
[Feature Request]: 能否双重备份？我想在OneDrive与S3存储桶中备份两次。

### ISSUE THREAD

**Issue by foreverlong** [remotely-save/remotely-save#329]
### What feature are you suggesting?

[Feature Request]: 能否双重备份？我想在OneDrive与S3存储桶中备份两次。

### What remote cloud services are you using, or suggesting adding the feature to?

S3, OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
出于可靠性问题，目前只打算一次支持一个远端。否则同步问题会变得很复杂。
