### ISSUE TITLE
[Feature Request]: enable notifications on automatic start-up

### ISSUE THREAD

**Issue by harjy02** [remotely-save/remotely-save#330]
### What feature are you suggesting?

I use the one drive sync option, when i sync manually by clicking the remotely save button a bunch of notifications show up and i can see the status of the sync, the problem is that these notification don't come up when the automatic start up is enabled, so when obsidian starts i don't know if the sync has finished and always have to double check by manually pressing the remotely sync button.
The auto start option i am talking about:
![image](https://user-images.githubusercontent.com/67744123/236621521-c8f0c8da-0dc9-44aa-8a2e-86c8561038cd.png)
The notifications i am talking about:
![image](https://user-images.githubusercontent.com/67744123/236621680-39510bab-9ca9-4e87-aa87-76491060bca3.png)

So i would like these notifications to be enabled also on automatic startup, or maybe an option to enable them.

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Too verbose. The desktop version will accept the pr from community showing status. This might be sufficient to solve op's issue.
