### ISSUE TITLE
[Bug]: 设置密码后同步出错

### ISSUE THREAD

**Issue by BaseBlank** [remotely-save/remotely-save#331]
### What happened?

![image](https://user-images.githubusercontent.com/105029447/236672374-7659f6c7-c050-4561-8571-39cfeefe2b6c.png)
在设置密码（端到端加密的密码）后同步出错，如上所示，密码为空时正常同步，S3为阿里云。
Thanks！

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

1.2.7

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
重设之后需要手动备份原来的vault，删除远程文件，重新备份。
