### ISSUE TITLE
[Feature Request]: Compatible bookmark function

### ISSUE THREAD

**Issue by ShawnKid** [remotely-save/remotely-save#332]
### What feature are you suggesting?

The bookmark function added in version 1.2.7, but the bookmarks can't be synchronized properly, you can hope to increase the synchronization of bookmarks.

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
It seems like "bookmark" doesn't generate any files inside the vault. So this plugin would not support this right now.
