### ISSUE TITLE
[Bug]: iPhone (version iOS 16.4.1) has no response after scan QR code and click link.

### ISSUE THREAD

**Issue by Huaweidev** [remotely-save/remotely-save#333]
### What happened?

在Windows端成功设置并同步了腾讯云存储桶，在插件里点击生成二维码，使用iphone手机（版本ios 16.4.1）的相机App扫描二维码后，点击跳转到Obsidian App没有任何反应，存储桶参数信息也无法成功导入。
Successfully set and synchronized Tencent Cloud bucket on Windows side. Clicked "generate QR code" in the plugin, scanned the QR code using iPhone (version iOS 16.4.1) camera app, but there was no response when clicking to jump to Obsidian App, and the bucket parameter information could not be successfully imported.

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

1.2.8

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
iphone 是不是没有安装本插件？需要先安装了才会接管二维码解析。

**Comment by fyears** [comment]
无更新进展，先关闭了
