### ISSUE TITLE
[Feature Request]: Sync other Dropbox app folders to custom root folder inside the vault.

### ISSUE THREAD

**Issue by INPoppoRTUNE** [remotely-save/remotely-save#335]
### What feature are you suggesting?

I have other apps syncing, like remotely-save, in Dropbox. I'd like to automatically import their output in a custom subfolder inside my vault.

## Dropbox apps
- remotely-save/my-vault
- another-app

Remotely save should be able to sync the 'another-app' folder and all of it's content in:

## Obsidian vault
/my-vault/custom/path/another-app-root-folder

Thanks for the great work, this is one of the must have plugins in all my vaults.

### What remote cloud services are you using, or suggesting adding the feature to?

Dropbox

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
dup of https://github.com/remotely-save/remotely-save/issues/293
