### ISSUE TITLE
[Bug]: Failed to load plugin remotely-save iOS 14.4.2

### ISSUE THREAD

**Issue by BobWs** [remotely-save/remotely-save#336]
### What happened?

 Failed to load plugin remotely-save

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using?

webdav

### Version of the plugin

latest

### Version of Obsidian

latest

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by seawin** [comment]
I meet the same bug.
same environment

ensure plugin files that are same as release asserts.

**Comment by fyears** [comment]
Sorry but the ios version is too low. Maybe upgrade the os?
