### ISSUE TITLE
[Bug]: Files are not synced if inside nested folders

### ISSUE THREAD

**Issue by kottofey** [remotely-save/remotely-save#338]
### What happened?

Hi! Cannot sync files on my devices :)
What I've done:
1) Installed fresh Obsidian on Windows, created new vault and few files and folders.
2) Installed Remotely Save on Windows Obsidian, synced with Yandex Disk (it's working, yes!) via WEBDAV
3) Checked that it really has files on Ya.Disk - it has
4) Installed Obsidian and Remotely Save on iPhone and Macbook. Synced there and only folders appear. Without files.

Just realised, it does not see files inside nested folders...

### What OS are you using?

Windows, macOS, iOS (iPhone, iPad)

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

Win 1.2.8; iOS: 1.4.4, MacOS: 1.2.8

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by edmundsong** [comment]
I got same issue reproduced in my configuration. i reproduced this issue in both Android phone and Linux OS. The version of remotely save plugin is 0.3.25.

**Comment by menlor-ru** [comment]
same problem. from subfolders is not downloaded from the server to the device

**Comment by huaqiu2lp** [comment]
This plug-in is an amazing work, I really like it. but I got the same issue as well. 

With the help of the Remotely Save plug-in, My Win10 PC syncs well with my Android phone(MIUI12.5.10; obsidian version 1.4.3(95); remotely save version (0.3.25)) (both files and the files in subfolders sync well).

However, my iPad (iPadOS version 16.2; obsidian version 1.4.6(105); remotely save version (0.3.25)) sufferred the same issue that files in subfolders cannot be synced with its parent folder. (i.e. only the folders are synced to the iPad, but the files inside of folder doesn't sync to the iPad).

Thanks for your wisdom and hard work for the plug-in, it is such an amazing work that help a lot of users in sync accross devices. Hope the issue will be resolved, thank you again!

**Comment by shishishiyi** [comment]
Try to change the “setting-remotely save-depth header sent to servers- depth=1

Should solve the problem

**Comment by edmundsong** [comment]
Amazing~~I did one quick try in my devices, and it works as expected! So, this configuration shall align with webdav server's configuration, right? I tried both options of "auto detect" and "depth='infinity'", but it never work.

**Comment by andyyang158** [comment]
same problem. I setup webdav service on my own OMV nas device within a docker container. subfolder and files in it can sync up to nas divice but can't sync down to Android/Windows PC, no matter "depth=1 or =infinity"

**Comment by kottofey** [comment]
Not sure what I've done but it now syncs well everywhere )maybe it was depth=1, maybe the moon was in its correct phase, who knows...

**Comment by antonkalmbah** [comment]
Choose Depth Header Sent to Server = only supports depth='1' and everything will work.

**Comment by fyears** [comment]
depth='1' should do the trick. Jianguoyun has similar issue
