### ISSUE TITLE
[Bug]: ERR-CONNECTION-RESET

### ISSUE THREAD

**Issue by Txin-Dr** [remotely-save/remotely-save#339]
### What happened?

Obsidian can be sync between phone and one windows computer through webdav, but when I want to sync it in another windows computer, it failed. it shows ERR-CONNECTION-RESET and too many erros task stop.

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

v1.2.8

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by JupiterOdyssey** [comment]
I have the same issue.

**Comment by xfnup** [comment]
I believe this is due to the nature of WebDAV itself, as when syncing on a new device, it can result in a large number of connections within a certain time period, causing the WebDAV server to return an error message saying "Too many requests..."

**Comment by godcreator02** [comment]
For me, even if only one new file needs to be synced, the problem still exists
