### ISSUE TITLE
[Feature Request]: iOS - request location services to perform sync in background

### ISSUE THREAD

**Issue by giovi321** [remotely-save/remotely-save#341]
### What feature are you suggesting?

Inspired by NextCloud app, I suggest to request access to location services in order to perform sync of notes in background on iOS devices.

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
the plugin is running inside the js environment provided by obsidian, so this feature is technically imposssible
