### ISSUE TITLE
[Bug]: webDAV error - Directory doesn't start with ...

### ISSUE THREAD

**Issue by madmath74** [remotely-save/remotely-save#345]
### What happened?

Switched the PlugIn from OneDrive to WebDAV (due to change of provider).
Configured the https-Link for WebDAV and tested it within the Plugin settings: Everrything worked fine, until here.
(The https-Link for WebDav contains several subdirectories)

Started to Sync manualley and got an error message.
Enabled detailled logging and logging to DB and exported the following Log-Messages:

> [2023-07-09T12:17:58+02:00] remotely-save-1688897878935: start sync, triggerSource=auto
> [2023-07-09T12:17:59+02:00] remotely-save-1688897879112: abort sync, triggerSource=auto, error while getting_remote_files_list
> [2023-07-09T12:17:59+02:00] ERROR! MESSAGE: "/../../../Carlo B. Stechlich/Documents/Obsidian/Michi" doesn't starts with "/Michi/", STACK: Error: "/../../../Carlo B. Stechlich/Documents/Obsidian/Michi" doesn't starts with "/Michi/"
>     at eval (plugin:remotely-save:211:238838)
>     at _v (plugin:remotely-save:211:238916)
>     at eval (plugin:remotely-save:211:245906)
>     at Array.map (<anonymous>)
>     at eval (plugin:remotely-save:211:245898)
>     at Generator.next (<anonymous>)
>     at a (plugin:remotely-save:177:280327)
> [2023-07-09T12:18:00+02:00] mkdir _debug_remotely_save

### What OS are you using?

macOS, Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

v1.3.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by madmath74** [comment]
On WebDAV the Vault-Directory was created:
<img width="488" alt="Bildschirmfoto 2023-07-09 um 12 46 50" src="https://github.com/remotely-save/remotely-save/assets/72024634/27b3a2bd-1236-4c34-b967-ab91623f98c8">

**Comment by madmath74** [comment]
Observation: I deleted the 'Michi' Folder on my webDAV Drive and tried to sync again.
The same error occured, but the PlugIn created another 'Michi' Folder on my webDAV Drive.
So the vault-Directory creation within the Plugin seems to work properly with the webDAV path given. _Only_ the sync of the vaults content seems to cause an error.

**Comment by NchuYJ** [comment]
the same problem as me

**Comment by zymbiosis** [comment]
I was experiencing the same issue, and found this solution: https://github.com/remotely-save/remotely-save/issues/215#issuecomment-1518984287

At least in these cases it had to do with spaces (or any not-encoded characters) in the "Server Address" configuration.  

Looking at OP's comment, they likely just need to change the `Carlo B. Stechlich` in their server address to `Carlo%20B.%20Stechlich`

**Comment by fyears** [comment]
Thanks everyone. I would like to add url encode in next version
