### ISSUE TITLE
[Bug]: cannot connect to Dropbox

### ISSUE THREAD

**Issue by Nakadroid** [remotely-save/remotely-save#347]
### What happened?

I can not connect to Dropbox on Windows. It works fine on my phone but when I do the same steps on windows it just tells me "Connecting to Dropbox... Please DO NOT close this modal.". It's been like that for over 10 minutes now and nothing is happening. 

### What OS are you using?

Windows

### What remote cloud services are you using?

Dropbox

### Version of the plugin

0.3.25

### Version of Obsidian

1.3.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Cannot reproduce it. May be change a web browser and try again?
