### ISSUE TITLE
[Bug]: could not sync .mdb file

### ISSUE THREAD

**Issue by Morganwan90** [remotely-save/remotely-save#349]
### What happened?

I installed the MAKE.md plugin that creates a folder Context in the root file of the vault with sqlite files like #tagname.mdb.
and it seems that remotely save could not sync any of these .mdb file and keep showing the error infomation below.

Can anyone help?

![截图_20230727021819](https://github.com/remotely-save/remotely-save/assets/61633409/cdc8b43e-4292-422c-b5b2-de85fcef9e60)

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.3.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
这里是因为井号问题，合并到这里来查 #416
