### ISSUE TITLE
[Bug]: If the title contains "%", an error occurs when using webdav to synchronize

### ISSUE THREAD

**Issue by sailcom** [remotely-save/remotely-save#350]
### What happened?

If the title contains "%", an error occurs when using webdav to synchronize.
```
Request failed, status 409
```
If I delete the "%" from title, the sync will be success.
(Use **onedrive** to sync is OK, and the above bug will not appear)

![Snipaste_20230728_132105](https://github.com/remotely-save/remotely-save/assets/42264621/a37e4f74-01bf-4b13-90a0-f25003eb580b)

### The setting options are shown in the figure below:

![Snipaste_20230728_132123](https://github.com/remotely-save/remotely-save/assets/42264621/8ec3eaa2-1ec1-496b-9e5c-959fb9b330a9)

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.3.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by obimg** [comment]
I found the same problem.

**Comment by fyears** [comment]
这里用了什么 webdav 服务器？我尝试复现一下

**Comment by sailcom** [comment]
> 这里用了什么 webdav 服务器？我尝试复现一下

InfiniCLOUD

**Comment by fyears** [comment]
合并到 #416
