### ISSUE TITLE
[Feature Request]: Read-only mode

### ISSUE THREAD

**Issue by danielmunoz** [remotely-save/remotely-save#353]
### What feature are you suggesting?

Dear remotely-save contributors,

I am sure many users would greatly appreciate the addition of a read-only toggle to the options.

This feature could prove valuable for individuals encountering syncing issues with OneDrive for personal use. Having read-only access to one's notes is preferable to risking potential mishaps when using remotely-save on the iPhone. In my case, I frequently face syncing issues, so, currently, it's better not to use remotely-save at all, given my circumstances.

Thank you.

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [x] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Hi. I am sorry you met some issues while syncing. Providing reproducible example of issues is always welcome.

That being said, it’s possible to trigger dry run in the plugin to debug the problem. Also if all you want is viewing files, doing so in Onedrive app or website are always the best official solutions…
