### ISSUE TITLE
[Feature Request]: Store encryption password in keychain

### ISSUE THREAD

**Issue by AfzalivE** [remotely-save/remotely-save#354]
### What feature are you suggesting?

I am a new Obsidian user so excuse me if this is already discussed or something.

Just saw the warning upon adding an encryption password and it says `The password itself is stored in PLAIN TEXT LOCALLY`. 

Just wondering if there's a straight-forward solution to this like storing the password in the Keychain (macOS/iOS), Credential Manager (Windows), Keyring (Linux), Keystore (Android). Has this been discussed?

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Sorry but it’s technically impossible because the plugin uses web js: https://stackoverflow.com/questions/1803855/can-i-access-keychain-from-a-webapp-javascript-on-the-iphone

**Comment by AfzalivE** [comment]
That's from 2009.

This exists for MacOS 
https://www.npmjs.com/package/keychain

**Comment by fyears** [comment]
that library requires nodesjs and command line calling, which doesn't work on mobile.
