### ISSUE TITLE
[Bug]: Won't Sync

### ISSUE THREAD

**Issue by pigarmahdar** [remotely-save/remotely-save#355]
### What happened?

Not sure but for some reason when I'm unable to sync and I get the following update on the UI.

![image](https://github.com/remotely-save/remotely-save/assets/93821354/1bc59139-aeb7-408c-9b7e-ec1fe2ac64ab)

### What OS are you using?

Windows, Linux, iOS (iPhone, iPad)

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

1.3.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by MATCHaB1** [comment]
I used the webdav service for synchronization, and I had the same problem

**Comment by caunus** [comment]
The nearly the same with stuts 401. When checking the connection in the setting I get following messages as well: `The webdav server cannot be reached (possible to be any of address/username/password/authtype errors). Error: Request failed, status 401`
On my iPad, Linux etc it works fine with the same setting. In the console I get theses error.
<img width="539" alt="Bildschirmfoto 2023-08-26 um 00 08 24" src="https://github.com/remotely-save/remotely-save/assets/26174521/33fdbe19-ad02-4a6c-b9e7-5170c453a79f">

**Comment by fyears** [comment]
net: err timeout usually means the network connection is not working. Please try another plugin that requires network and see whether the network connection in Obsidian is ok.

status 401 usually means the password is wrong. Please consider directly copy the data.json from another working machine and try again.
