### ISSUE TITLE
[Bug]: Android WebDAV error while syncing question mark in filename

### ISSUE THREAD

**Issue by skyqrose** [remotely-save/remotely-save#356]
### What happened?

I made a file whose name ended in a question mark on one device (Mac, Obsidian v1.3.5 plugin 0.3.25) and synced to my WebDAV folder.

Then, on an Android device (Obsidian v1.4.6 (105), plugin 0.3.25), I tried to sync, and got the following error message:

```
remotely-save-[numbers]:abort sync triggerSource=manual, error while syncing
my_file_name_with_a_question_mark?.md: FILE_NOTCREATED
```

On Mac, I removed the question mark from the filename, synced, and then the sync on android succeeded. On Mac, I tried adding the question mark back, and the android sync failed again. So it's definitely the question mark.

I found one related issue https://github.com/remotely-save/remotely-save/issues/145 , but it's a year old and resolved without comment so I'm opening a new issue.

I noticed that on Mac, if I use an illegal character in a filename, I get a red popup message
`Filename cannot contain any of these characters: \ / :` while on Android, the message is `Filename cannot contain any of these characters: \ / : * ? < >`.

I would expect any of:
- Android to allow question marks, so the file could successfully sync (probably the most difficult, but the most useful)
- Mac expand the illegal characters to match Android, and fail to sync/save a file with a useful error message. (Would be a breaking change. Maybe only do it for new files, or if both Mac knows that Android is syncing from the same place?)
- (Partial solution) Allow android to sync other files, while ignoring the one file that it can't handle.

This is not a major problem for me. There's an easy workaround to just remove the question mark from the filename. The main problem is that someone's cloud storage could end up in a state that Android can't sync from, and if the file was uploaded some time ago, they may not be able to trace the problem to the file with the question mark.

### What OS are you using?

Android

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.6 (105)

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Waffleophagus** [comment]
For what its worth, I also had the same issue with syncing  to Linux. iOS would sync it properly, but Linux pulling it down would error. Was the flatpak.

**Comment by fyears** [comment]
merge into #416
