### ISSUE TITLE
[Bug]: Remotely Save can't work in Windows

### ISSUE THREAD

**Issue by PaleMoon6875** [remotely-save/remotely-save#357]
### What happened?

![Snipaste_2023-08-16_22-17-45](https://github.com/remotely-save/remotely-save/assets/113691569/5795457e-f0da-46e2-b58f-9a543a1951d2)

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.3.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by PaleMoon6875** [comment]
Now the problem is solved, I can sync normally after deleting the extra folders on Windows.

**Comment by Crick-st00** [comment]
> Now the problem is solved, I can sync normally after deleting the extra folders on Windows.

Can you tell me how to solve it?

**Comment by PaleMoon6875** [comment]
> > Now the problem is solved, I can sync normally after deleting the extra folders on Windows.
> 
> Can you tell me how to solve it?
> OK.First of all I found that I couldn't sync after I created a new folder in obsidian, after I deleted the folder I was able to sync. I hope this helps you.
