### ISSUE TITLE
Encrypt an already synced vault

### ISSUE THREAD

**Issue by ceccadroid** [remotely-save/remotely-save#358]
### What happened?

Hi! It would be possible to encrypt an existing vault that is already in sync usin remotely-sync?
How can I do that?

### What OS are you using?

Android

### What remote cloud services are you using?

OneDrive for personal

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sugov5** [comment]
我猜是在设置密码后，对本地所有笔记文件进行加密，然后全量同步上传？

**Comment by fyears** [comment]
Sorry but you have to **make a backup**, delete the un-encrypted remote files, set a password locally, and sync again.

是的需要加密后重新全量同步上传。
