### ISSUE TITLE
[Bug]: 同步时候导致miui14的ob闪退崩溃，提示内存溢出

### ISSUE THREAD

**Issue by violentrant** [remotely-save/remotely-save#361]
### What happened?

[Bug]: 同步时候导致miui14的ob闪退崩溃，提示内存溢出

查看状态栏网速达到15mbs左右，占用太大内存，导致主程序缺乏内存崩溃。我的手机是8g内存，空间足够大

### What OS are you using?

Android

### What remote cloud services are you using?

S3

### Version of the plugin

最新版本

### Version of Obsidian

最新版本

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by tianjiaoshanzai** [comment]
可以参照这篇issue,不要同步大体积附件

**Comment by violentrant** [comment]
请问可以麻烦优化一下安卓么？ios ipad 电脑都没有这个问题。谢谢啦。



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月14日 10:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [remotely-save/remotely-save] [Bug]: 同步时候导致miui14的ob闪退崩溃，提示内存溢出 (Issue #361) |

可以参照这篇issue,不要同步大体积附件

**Comment by tianjiaoshanzai** [comment]
> 请问可以麻烦优化一下安卓么？ios ipad 电脑都没有这个问题。谢谢啦。 | | ***@***.*** | | ***@***.*** |
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年09月14日 10:47 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [remotely-save/remotely-save] [Bug]: 同步时候导致miui14的ob闪退崩溃，提示内存溢出 (Issue #361) | 可以参照这篇issue,不要同步大体积附件 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

我不是作者，也无能为力😢，只能禁用和注意尽量不上传大文件。听说有人用syncthing同步，你要是有需要可以整体迁移到其他软件。这个插件开发者已经不维护了

**Comment by violentrant** [comment]
好的，谢谢啦，我试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月14日(周四) 中午11:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [remotely-save/remotely-save] [Bug]: 同步时候导致miui14的ob闪退崩溃，提示内存溢出 (Issue #361)




  
请问可以麻烦优化一下安卓么？ios ipad 电脑都没有这个问题。谢谢啦。 | | @.*** | | @.*** |
 …
 ---- 回复的原邮件 ---- | 发件人 | @.&gt; | | 日期 | 2023年09月14日 10:47 | | 收件人 | @.&gt; | | 抄送至 | @.***@***.***&gt; | | 主题 | Re: [remotely-save/remotely-save] [Bug]: 同步时候导致miui14的ob闪退崩溃，提示内存溢出 (Issue #361) | 可以参照这篇issue,不要同步大体积附件 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
我不是作者，也无能为力😢，只能禁用和注意尽量不上传大文件。听说有人用syncthing同步，你要是有需要可以整体迁移到其他软件。这个插件开发者已经不维护了

**Comment by chengyuhui** [comment]
这个插件虽然上传操作是分块的，但是上传之前会把整个文件的内容读取到内存中（应该只是图省事），miui对内存的限制比较严格，所以就炸了。能修，但是也不见得好做

**Comment by violentrant** [comment]
好啊，搞得都不想用miui了，这个插件源代码有没有大佬能共享修复一下呢，太需要了，哈哈哈哈。




1527210351
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "remotely-save/remotely-save"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月19日(星期二) 上午10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [remotely-save/remotely-save] [Bug]: 同步时候导致miui14的ob闪退崩溃，提示内存溢出 (Issue #361)





 
这个插件虽然上传操作是分块的，但是上传之前会把整个文件的内容读取到内存中（应该只是图省事），miui对内存的限制比较严格，所以就炸了。能修，但是也不见得好做

**Comment by fyears** [comment]
@ chengyuhui 你说得对，obsidian api 应该只支持全文件载入 （`readBinary `函数）。所以不好做啊。

@violentrant 设置限制文件大小吧，没办法
