### ISSUE TITLE
[Bug] 404 error when saving notes with a question mark in the title

### ISSUE THREAD

**Issue by bovf** [remotely-save/remotely-save#362]
### What happened?

Description:
While using the "remotely-save" plugin for Obsidian on macOS, I encountered a 404 error when attempting to save notes that have a question mark (?) in the title.

Steps to Reproduce:

    Create a new note in Obsidian.
    Title the note with a string containing a question mark, for example, "Test?"
    Make sure the body of the note is not empty
    Attempt to save the note using the plugin.

Expected Behavior:
The note should be saved successfully without any errors.

Actual Behavior:
Received a 404 error when trying to save the note. The problem seems to be related to the presence of a question mark in the note's title.

Screenshots:

![09FF57B6-C36C-4DCD-AF36-749AB4093C28_1_201_a](https://github.com/remotely-save/remotely-save/assets/23377374/2c8a2fdb-dc3a-4e85-886e-8a017668d57a)

![D41D3CE9-CB12-41EA-86F5-6D19D7841DAE_1_201_a](https://github.com/remotely-save/remotely-save/assets/23377374/b8ee006f-55cb-4c67-90e7-8ca0e0b0d600)

System Information:

    Operating System: macOS 13.5.1 (22G90)
    Kernel Version: Darwin 22.6.0
    Model Name: MacBook Air
    Model Identifier: MacBookAir10,1
    Chip: Apple M1
    Memory: 16 GB

Additional Context:
This error might be related to how URLs are encoded/decoded, as question marks are special characters in URLs.

### What OS are you using?

macOS

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.3.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Sorry but Onedrive doesn’t support question mark in file name: https://support.microsoft.com/en-us/office/restrictions-and-limitations-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa#invalidcharacters

Rclone tries to replace the character: https://rclone.org/onedrive/#restricted-filename-characters

But currently remotely-save doesn’t plan to messy up with users’ file names. Sorry.
