### ISSUE TITLE
[Bug]: Plugin causes a crash of the mobile app

### ISSUE THREAD

**Issue by awrog** [remotely-save/remotely-save#363]
### What happened?

The plugin woks in the mobile app, but upon activation in the mobile app, the final stage (8/8 ....) is not shown, and causes the app to crash.
Nontheless, it looks like the sync does work.

### What OS are you using?

Android

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.5

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by 0uros** [comment]
Same issue, using Obsidian 1.4.9

**Comment by octrivera** [comment]
Crashes with onedrive

**Comment by bacox** [comment]
Same issue with Webdav

**Comment by fyears** [comment]
It’s a known issue that uploading large files on mobile may cause the crashes. There’s no easy way to fix this due to the limitations on mobile.

Feel free to create another issue if some reproducible examples other than large files are provided.

**Comment by Tealk** [comment]
> uploading large files

How many MB are we talking about here? Would it then make sense to preset "skip large files" to this size?
It just took me 10 attempts to make the setting because the app crashed too quickly.

**Comment by fyears** [comment]
It totally depends on your device. I don't have benchmarks. But prs, if any, are welcome.

I would suggest you: 

1. Lower down the upload parallelism in settings.
2. Try the large size file setting from smaller value to larger value.
