### ISSUE TITLE
[Feature Request]: Using hash for checking diff

### ISSUE THREAD

**Issue by ReactiveMatter** [remotely-save/remotely-save#367]
### What feature are you suggesting?

Hi,

I am trying to understand the working of the plugin. From what I understand, each time when the plugin is run either the files downloaded or upload, due to difference in mtime of the file. And every time, obsidian enters editing mode, the file is modified (even without any content changes).

Does this mean, even without any change, my file will be synced?

Is it possible to check the hash of the file before deciding whether the file need to be downloaded or uploaded? The plugin may save a list of hashes in the remove location on each sync.

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Yes the plugin uses mtimes.

The difficulty of using hash is that there’s no obvious way to get the hash of **remote** files.

Pull requests are welcome though.
