### ISSUE TITLE
[Feature Request]: I plan to use this plugin but not sure if you'll continue to maintain

### ISSUE THREAD

**Issue by GopherJ** [remotely-save/remotely-save#368]
### What feature are you suggesting?

Hi, I'd like to use this plugin with webdav, but I saw the last commit was 1 year ago, are you still maintaining it, does community members have the right to merge pull requests?

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by HarisDotParis** [comment]
Related to [Issue #280](https://github.com/remotely-save/remotely-save/issues/280).

@GopherJ Thank you for providing this plugin! It's a great help for many people, counting almost 250k downloads within Obsidian alone. Would you be able to appoint some more maintainers for this repository, so others can help with administering pull requests and issues and continuing developing this plugin?

**Comment by fyears** [comment]
Yes I continue to support this. Prs or even direct join in the members are welcome.
