### ISSUE TITLE
[Bug]: Not able to sync, status 504

### ISSUE THREAD

**Issue by DRay73** [remotely-save/remotely-save#369]
### What happened?

![2023-09-18_12-17](https://github.com/remotely-save/remotely-save/assets/85489863/b4c6c6bf-a7a3-44b6-a616-0003bbd780e4)
Getting this error whenever I try to sync

### What OS are you using?

Windows, Android

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.13

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Sgambe33** [comment]
I too have this error, is there any fix?

**Comment by fyears** [comment]
any way to reproduce the error using the newly created vault? By using filebase?

**Comment by fyears** [comment]
filebase has rate limit: https://docs.filebase.com/getting-started/service-limits

no way to workaround it. please try reduce the parallelism in the settings.
