### ISSUE TITLE
[Bug]: If a note has an image embeded the sync fails with json is invalid

### ISSUE THREAD

**Issue by t0lkman** [remotely-save/remotely-save#370]
### What happened?

If a note has an image embedded the sync fails with JSON is invalid.
so I have to remove image from the note to be able to sync

### What OS are you using?

macOS

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.14

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Would you like to provice a reproducible file(with images embedded)?

**Comment by fyears** [comment]
Closed of no further info
