### ISSUE TITLE
[Bug]: Remotely save keeps renaming my image attachments causing my notes to break

### ISSUE THREAD

**Issue by manontop** [remotely-save/remotely-save#371]
### What happened?

Remotely save keeps renaming my image attachments for no reason which is causing my notes to break.

For example: 
`Completion logs August 7  2023 onwards-1691406031787.jpeg` moved to trash and another copy created with 
`2023-08-22-1695884541072.jpeg` inside the attachments folder

Resulting in missing the image attachment in the MD files (now I have no idea which the actual file are and I have to attach one by one manually).

### What OS are you using?

macOS

### What remote cloud services are you using?

Dropbox

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.13

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
please click "reset local internal cache/databases" in the bottom of remotely-save settings and remove the _remotely-save-metadata-on-remote.{json,bin} on the remote if any
