### ISSUE TITLE
[Bug]: sync plans slowing down sync

### ISSUE THREAD

**Issue by Laharah** [remotely-save/remotely-save#372]
### What happened?

When there are many sync plans blobs in the app data, sync becomes *extremely* slow. Sometimes more than a minute or two. 

I have a moderately large library (125mb) and I've been using remote save for a little less than a year now. Every time I sync, a new 2.4mb `.blob` file is created in the IndexBd folder. The folder had grown to over 2.5 gb.

After cleaning up the sync plans history, my syncs are now only take a few seconds.

Is this a bug? Is there a benefit to keeping them all around?

I'd be happy to submit a PR with a fix or an option to automatically clean them up after a specified amount of time or syncs. 

### What OS are you using?

macOS

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.49

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Hi sync plan is for debugging. So if everything goes well it’s safe to delete them. I think a poper way to solve it is cleaning the sync plans older than x days automatically. Thanks for the report!
