### ISSUE TITLE
[Feature Request]: upload changed notes

### ISSUE THREAD

**Issue by cli-r** [remotely-save/remotely-save#373]
### What feature are you suggesting?

I use it to sync with Onedrive,when I run it,it would change all notes and upload.Can you make it upload only changed notes?

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
If you are using Obsidian **only**, the plugin would just upload the changed files except the first time.
