### ISSUE TITLE
[Bug]: When I sync the local file to OneDrive, I find that some files can not synchronize OneDrive when I manually click the sync button

### ISSUE THREAD

**Issue by jin-zi-han** [remotely-save/remotely-save#374]
### What happened?

When I sync the local file to OneDrive, I find that some files can not synchronize OneDrive when I manually click the sync button

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.3.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by jin-zi-han** [comment]
I know, is not to back up files with empty content, can you add this function, is to back up files with only the title but no content

**Comment by fyears** [comment]
Sorry but Onedrive officially do not support empty files
