### ISSUE TITLE
[Bug]: The synchronous content was overwritten by the unchanged content on the original phone.S3,Tencent Cloud Object Storage.

### ISSUE THREAD

**Issue by kive231** [remotely-save/remotely-save#376]
### What happened?

 It seems that there is an issue with synchronization. Yesterday, after finishing writing, I forgot to upload the file. I clicked on synchronization on my phone, and this morning when I clicked again on my computer, the file was overwritten by a blank one from before. Is there a solution to this problem?

### What OS are you using?

Windows, Android

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

v1.4.14

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
You have to set up the automatic sync in settings. In your case your phone file is “newer” so it overwrites the computer one, sorry.
