### ISSUE TITLE
[Feature Request]: 希望支持OneDrive for Business

### ISSUE THREAD

**Issue by viocha** [remotely-save/remotely-save#378]
### What feature are you suggesting?

开源笔记软件joplin已经支持OneDrive for Business的账号登录了，可以参考一下

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [x] I ensure that no sensitive information is submitted in the issue.

**Comment by sailcom** [comment]
参考这个：
https://github.com/remotely-save/remotely-save/issues/11

**Comment by fyears** [comment]
可以在 #11 讨论

最大的问题是我自己没有账号，测试不了

**Comment by PassionPenguin** [comment]
> 可以在 #11 讨论
> 
> 最大的问题是我自己没有账号，测试不了

haven't been using obisidian for long...you may register one yourself? at developer.microsoft.com.
