### ISSUE TITLE
[Bug]: Parameter is too long for Onedrive

### ISSUE THREAD

**Issue by skorphil** [remotely-save/remotely-save#379]
### What happened?

Hi, tried to sync files via oneDrive personal and keep getting tons of errors for PUT requests and sync is aborting.

Console:
```
plugin:remotely-save:216 AggregateError: 
    Error: Path/to/my/file.md: Request failed, status 400
        at eval (plugin:remotely-save:211:314339)
```

Onedrive response:
```
{
    "error": {
        "code": "invalidRequest",
        "message": "Parameter Exceeds Maximum Length",
        "innerError": {
            "code": "parameterIsTooLong",
...
```

How can I reduce the length of the parameter? Is there larger limits on parameter length in Dropbox?

### What OS are you using?

macOS

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

latest

### Version of Obsidian

1.4.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by skorphil** [comment]
Dropbox also respond with 409 error

```
{
    "error_summary": "path/malformed_path/.",
    "error": {
        ".tag": "path",
        "reason": {
            ".tag": "malformed_path"
        },
        "upload_session_id": "pid_upload_session:ABIG-0G28F83fICqhn8MoRTFEL5-BANk9dLS9F-GMhQ8RSJLYw"
    }
}
```

**Comment by skorphil** [comment]
Well, it is because of very strict limitations on file path length. Had to manually move some files in parent folders

**Comment by fyears** [comment]
Yes the length of path is limited on some platforms
