### ISSUE TITLE
[Bug]: Android Error: Icon : FILE_NOTCREATED

### ISSUE THREAD

**Issue by skorphil** [remotely-save/remotely-save#380]
### What happened?

I sync mac, ios and android via onedrive. 
Mac - OK
Ios - OK
Android - 
```
ERROR! MESSAGE: 
    Error: Icon
    : FILE_NOTCREATED
        at eval (plugin:remotely-save:211:314339), STACK: AggregateError: 
    Error: Icon
    : FILE_NOTCREATED
        at eval (plugin:remotely-save:211:314339)
    at eval (plugin:remotely-save:211:314499)
    at [Generator.next](https://generator.next/) (<anonymous>)
    at a (plugin:remotely-save:177:280327)
```

I don't have any file with name `Icon`

### What OS are you using?

Android

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

latest

### Version of Obsidian

1.4.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by muuky** [comment]
Same with me...
`Icon` file is from MacOS. `Icon` file contains custom icon information for directory in MacOS.
It should be exclude for sync.

**Comment by fyears** [comment]
After a few searching, indeed it's a special file on macos: https://superuser.com/questions/298785/icon-file-on-os-x-desktop

I will ignore this in next version.

**Comment by fyears** [comment]
#416
