### ISSUE TITLE
Incomplete sync

### ISSUE THREAD

**Issue by m47777** [remotely-save/remotely-save#381]
### What happened?

This plugin is soooooo powerful!!! But I had some problems... When syncing on the computer(Win), it shows that the sync is done, but only the first level of folders are synced, and their contents are not synced.

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
what webdav service are you using? Would you like to try some proved-to-work solution like [Infinite Cloud](https://infini-cloud.net/)?

**Comment by williamgurzoni** [comment]
I also had a partial sync when trying to add my vault to my mobile. Using S3 with AWS.
I could not get a pattern, some files were just missing, no special characters, nothing.
Thanks.

**Comment by williamgurzoni** [comment]
My problem was related with files containing `?`. By renaming the files, I could sync successfully.

**Comment by fyears** [comment]
setting depth header to 1 should solve the issue
