### ISSUE TITLE
[Bug]: invalid response: no root multistatus found

### ISSUE THREAD

**Issue by erikaemma** [remotely-save/remotely-save#383]
### What happened?

Win10上使用aLive搭建WebDav服务器，通过修改注册表关闭了https，无防火墙、组策略限制5244端口（通过手机可以访问alive的网页）。
然后，这个插件设置webdav后一直提示“invalid response: no root multistatus found”。

### What OS are you using?

iOS (iPhone, iPad), Android

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
电脑端有问题吗？alist 里面本来有文件吗？设置是怎么设置的？alist 搭建有简易教程吗？我得复现一下。

看上去用到的依赖有这个问题但是后来修复了：https://github.com/perry-mitchell/webdav-client/issues/218

**Comment by fyears** [comment]
alist 用最新版，插件用最新版 0.3.28，可以调通，优化了一下

**Comment by payprays** [comment]
alist v3.43.0
插件 0.5.25

http协议又遇到这个问题了 `invalid response: no root multistatus found`，而且似乎是偶发性事件
