### ISSUE TITLE
[Feature Request]: 是否有在手机端支持本地同步或Cryptomator/Boxcryptor等的计划？

### ISSUE THREAD

**Issue by erikaemma** [remotely-save/remotely-save#384]
### What feature are you suggesting?

我本人正在使用Cryptomator。
1. ios端的Cryptomator支持投射到文件管理器。不太了解ios的开发流程，不知道是否可以让obsidian像访问本地文件一样访问Cryptomator里的文件？这样能方便不少。
2. android端没办法，Cryptomator是一个加解密+文件管理器+文件查看器一体的app，如果这个插件可以同步Cryptomator再好不过了。

备注：我的Cryptomator使用onedrive或dropbox同步。

### What remote cloud services are you using, or suggesting adding the feature to?

others

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Lyeragain** [comment]
cryptomator是云端加密软件，remotely save也可以实现云端加密呀，也可以实现类似的效果，只是cryptomator可以加密本地文件，remotely save不能

**Comment by fyears** [comment]
不太行。cryptomator 是一整个库加密后上传的吧？无法做到文件增量同步。

**Comment by erikaemma** [comment]
> 不太行。cryptomator 是一整个库加密后上传的吧？无法做到文件增量同步。

很不幸不是，这个加密软件就是为了网盘而设计的，每个文件的路径+文件名+内容都加密了，然后存放于单独的加密文件内，以实现增量加密
