### ISSUE TITLE
[Feature Request]: Document permissions required for S3

### ISSUE THREAD

**Issue by bitwombat** [remotely-save/remotely-save#385]
### What feature are you suggesting?

Documentation for what S3 permissions are required would be really useful, as well as a procedure for how to set that up.

I have an IAM Policy attached to an IAM user as follows:

```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "Obsidian1a",
			"Effect": "Allow",
			"Action": [
				"s3:ListBucket"
			],
			"Resource": "arn:aws:s3:::somebucket/"
		},
		{
			"Sid": "Obsidian1b",
			"Effect": "Allow",
			"Action": [
				"s3:GetObject",
				"s3:PutObject"
			],
			"Resource": "arn:aws:s3:::somebucket/*"
		}
	]
}
```

I have a Bucket policy as follows:

```
{
    "Version": "2012-10-17",
    "Statement": [
         {
            "Sid": "Obsidian0a",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::33315:user/someuser"
            },
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::somebucket"
        },
        {
            "Sid": "Obsidian0b",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::33315:user/someuser"
            },
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::somebucket/*"
        }       
    ]
}
```

This took me time to figure out, and it's not quite right (The plugin uses another permission, so I ended up using `*Object` as my action).

Would be good to have this documented (and correct).

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by bitwombat** [comment]
I've actually left an error in the above, points to whomever spots it. I'll update it in a day to be correct.

**Comment by bitwombat** [comment]
Also, the debug output does not say what permission is being used. The three permissions I have above are not sufficient. I had to (temporarily) use `s3:*` to get around a 403 error.

**Comment by fyears** [comment]
I am not using aws actually but after reading ref doc (https://docs.aws.amazon.com/AmazonS3/latest/API/API_Operations.html) , I think it's a good idea to just allow `*Object` and `*Objects`. Because at least the plugin should be able to: get/head/list/listparts/put/uploadpart/delete, which covers many `*Object` and `*Objects` actions. Furthermore the actions might be changed (for optimizations, etc).
