### ISSUE TITLE
[Bug]: "Error: do not know which level for " when sync

### ISSUE THREAD

**Issue by chrvip** [remotely-save/remotely-save#388]
### What happened?

![image](https://github.com/remotely-save/remotely-save/assets/536916/c2c145ba-e350-4801-8c4b-9affabcfe486)

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

v1.4.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by YIRU69** [comment]
看看这个 https://github.com/sboesen/remotely-secure/issues/23 ，原主现在不更新这个插件了，有一个热心的老哥现在开始维护这个插件了

**Comment by fyears** [comment]
看了一眼隔壁的解法，是跳过了错误路径。个人觉得更好做法是查一下为什么。

s3 用的是什么服务？
截图里的文件“完美...”确实是在s3的根目录吗？确实是在本地 vault 的根目录吗？

**Comment by YIRU69** [comment]
> 看了一眼隔壁的解法，是跳过了错误路径。个人觉得更好做法是查一下为什么。
> 
> s3 用的是什么服务？ 截图里的文件“完美...”确实是在s3的根目录吗？确实是在本地 vault 的根目录吗？

大佬，你终于回来了！这个插件好久没更新了，求求了，更更新吧

**Comment by YIRU69** [comment]
隔壁的更新了应该挺多东西的，大佬，有考虑一起合并了吗

**Comment by fyears** [comment]
在看，在看，先解决这个问题，有什么办法稳定复现？

**Comment by YIRU69** [comment]
时间有点久，我记得是有一个人也提出这个问题，他用的是其他语言命名的文件夹导致了这个问题，我当时遇到的问题是因为某些文件的原因，没找到它们的共性，删掉就可以同步了

**Comment by YIRU69** [comment]
我自己觉得可以是同步冲突导致的，因为`tracked_files.json`这个文件是随时改变的，可能在同步的时候它中途改变导致，同步冲突？

**Comment by fyears** [comment]
新版本（0.4.12）应该修复了这个 bug ，如果还有的话，可以提新 bug
