### ISSUE TITLE
[Feature Request]: Add single file sync option

### ISSUE THREAD

**Issue by LazyCountry** [remotely-save/remotely-save#39]
### What feature are you suggesting?

Hi fyears,

I am using remotely-save on mobile, uring OneDriver for personal on PC.
I have too much files on my vault, If every time sync all files will used too much time.
I only need sync all file one time every day. 
Because most files are small.
I would really appreciate add two options:

1. open file sync option, only sync opened file
2. file changed sync option, only sync changed file

These are helpful when write or read something on mobile.

Thanks for this great plugin.

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
But, by design, after init full sync, only modified or created or deleted files are synced. Are you sure that every time this plugin syncs all files? That should be considered a bug.

**Comment by LazyCountry** [comment]
Oh my mistake, I just mean from start sync to uploaded changed need much time. 
The sync all files just mean always check all files, this cost much time.
I only change one line on 1KB file, from start sync to uploaded to OneDrive need one 1 minute.

I think again,
Because I have too much file(about 5000+), most time I need upload the change when I used on mobile,
 and when I open one file, hope this file is newest, if some other files are not newest when I read, this is acceptable.
If need, I will sync manually. 
When I edit the file on mobile, I want this upload immediately, maybe I next time edit on PC. PC OneDrive client will sync auto.

**Comment by fyears** [comment]
Is it useful enough, if I add a shortcut command to “upload current file”?

**Comment by LazyCountry** [comment]
Is the  “upload current file” is mean "sync current file"?
If is mean sync current file, it is useful enough.

**Comment by fyears** [comment]
No that’s not exactly the same.

1. upload current file means the local file will always overwrite the remote file.
2. sync current file means the file MIGHT be downloaded from the remote and overwrite the local one.

The first one is easier, and the second one is much harder

**Comment by LazyCountry** [comment]
It is better for "sync current file". Although is much harder.

**Comment by fyears** [comment]
I am sorry, but after careful consideration, "single file sync" would not be implemented. Currently, "auto sync", or "sync once after start up" should be close to meet your needs.

1. If you have already synced the full vault, then in next time, only metadata + modified files are exchanged. You can adjust the auto sync intervals.
2. If your "single file sync" is implemented, the plugin would need to IMMEDIATELY pull info while you open a file, and IMMEDIATELY download the remote file if the remote one is newer, BEFORE you make any modifications. I am afraid it's technically impossible to be reliable, unless there is some way to BLOCK your edit! And at the same time, the information needed to be download and upload, is not much less than the auto sync.
