### ISSUE TITLE
[Feature Request]: The ability to choose where to move deleted files (selecting the trash bin) after synchronization 

### ISSUE THREAD

**Issue by MartinJDavis93** [remotely-save/remotely-save#394]
### What feature are you suggesting?

Currently, the synchronization of deleted files is not very convenient. All deleted files on the computer are moved to the system trash, and this cannot be changed. Personally, I use the Obsidian trash in the Obsidian settings, which is much more convenient for me. It would be great if the extension took into account this selected parameter in Obsidian itself and synchronized the deletion content accordingly. If such implementation is challenging, then simply adding a corresponding parameter to the extension settings would suffice. This way, users could specify where to move files during synchronization if they have been deleted.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
done
