### ISSUE TITLE
[Bug]: remote_not_encrypted_local_has_password

### ISSUE THREAD

**Issue by ozturkberkay** [remotely-save/remotely-save#397]
### What happened?

Hi,
This is the error I'm getting when setting a password in Obsidian to enable end-to-end encryption. What do I have to change in the bucket settings to make this work?
![67460](https://github.com/remotely-save/remotely-save/assets/7548962/0fa12db9-41b1-4668-ac3c-0cfb3fa33fb6)

### What OS are you using?

macOS

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Hi you have to make a backup then remove the original unencrypted files in remote so that the plugin knows to upload the encrypted ones
