### ISSUE TITLE
[Bug]: Permisson denied because of file permissons 

### ISSUE THREAD

**Issue by da-the-dev** [remotely-save/remotely-save#398]
### What happened?

I have some other files in in vault, namely some `.venv` folder (I have uni projects and notes in the same vault) and because of these files the notes do not sync. Here's the error I recorded into DB:

```
[2023-11-28T18:30:45+03:00] ERROR! MESSAGE: 
    Error: IU Notes/Differential equations/Computational Assignments/1.1/venv/bin/python3.11: EACCES: permission denied, open '/home/sv-cheats-1/Documents/Knowledge Base/IU Notes/Differential equations/Computational Assignments/1.1/venv/bin/python3.11'
        at eval (plugin:remotely-save:211:314339)
    Error: IU Notes/Differential equations/Computational Assignments/1.1/venv/bin/python3: EACCES: permission denied, open '/home/sv-cheats-1/Documents/Knowledge Base/IU Notes/Differential equations/Computational Assignments/1.1/venv/bin/python3'
        at eval (plugin:remotely-save:211:314339)
    Error: IU Notes/Differential equations/Computational Assignments/1.1/venv/bin/python: EACCES: permission denied, open '/home/sv-cheats-1/Documents/Knowledge Base/IU Notes/Differential equations/Computational Assignments/1.1/venv/bin/python'
        at eval (plugin:remotely-save:211:314339)
    Error: too many errors, stop the remaining tasks
        at eval (plugin:remotely-save:211:314443)
        at Generator.next (<anonymous>)
        at a (plugin:remotely-save:177:280327), STACK: AggregateError: 
    Error: IU Notes/Differential equations/Computational Assignments/1.1/venv/bin/python3.11: EACCES: permission denied, open '/home/sv-cheats-1/Documents/Knowledge Base/IU Notes/Differential equations/Computational Assignments/1.1/venv/bin/python3.11'
        at eval (plugin:remotely-save:211:314339)
    Error: IU Notes/Differential equations/Computational Assignments/1.1/venv/bin/python3: EACCES: permission denied, open '/home/sv-cheats-1/Documents/Knowledge Base/IU Notes/Differential equations/Computational Assignments/1.1/venv/bin/python3'
        at eval (plugin:remotely-save:211:314339)
    Error: IU Notes/Differential equations/Computational Assignments/1.1/venv/bin/python: EACCES: permission denied, open '/home/sv-cheats-1/Documents/Knowledge Base/IU Notes/Differential equations/Computational Assignments/1.1/venv/bin/python'
        at eval (plugin:remotely-save:211:314339)
    Error: too many errors, stop the remaining tasks
        at eval (plugin:remotely-save:211:314443)
        at Generator.next (<anonymous>)
        at a (plugin:remotely-save:177:280327)
    at eval (plugin:remotely-save:211:314499)
    at Generator.next (<anonymous>)
    at a (plugin:remotely-save:177:280327)
```

### What OS are you using?

Linux

### What remote cloud services are you using?

others

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by da-the-dev** [comment]
It seems like this bug also blocks further sync, since changes are old when pulled on another device

**Comment by fyears** [comment]
It seems like your folder is `venv` not `.venv` (missing the dot).

It’s usually problematic to sync the virtual environment of python anyways. The executables have special permission I guess.

Would you like to change the folder name by adding the dot and try again so that the plugin could skip the folder?

**Comment by da-the-dev** [comment]
> It’s usually problematic to sync the virtual environment of python anyways. The executables have special permission I guess.

I think it's more of a permissions problem than a python venv problem. The plugin should check whether it has the permission read/write a given file scheduled for sync. If it does not have the necessary permissions, the file could be skipped and the user notified. Or maybe the user could be prompted to address the issue in some meaningful way.

> Would you like to change the folder name by adding the dot and try again so that the plugin could skip the folder?

I though about it, but I can't. Long story short - I can't do that, because one of the plugins I use demands the `venv` to have a dot, otherwise, it can't find the environment. If I could filter out the folder outright, the issue would be solved.

So, I think the best solution would be to check file permission and let the user to decide what to do if required permissions are not met (stop sync, skip a file/files, etc.)

I'm on uni winter break now, I think I have some time to look into this issue

**Comment by fyears** [comment]
Well file permissions are complicated and the plugin may not able to enumerate all the errors ahead. I need to think about it.

And in the meantime, the plugin is adding excluding regex, this should avoid the problem in an elegant way.
