### ISSUE TITLE
[Feature Request]: File filter

### ISSUE THREAD

**Issue by da-the-dev** [remotely-save/remotely-save#399]
### What feature are you suggesting?

Filter files and folders based on a name or regex. #398 would benefit

### What remote cloud services are you using, or suggesting adding the feature to?

others

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
I considered the idea earlier but I don’t know how to expose the configurations to users. Any ideas?

For example, what if users want to allow some regex and deny some regex? How many input fields should I  expose the users?

**Comment by da-the-dev** [comment]
> I considered the idea earlier but I don’t know how to expose the configurations to users. Any ideas?

I know a plugin [File Explorer ++](https://github.com/kelszo/obsidian-file-explorer-plus) that allows the users to add rules that define what files are hidden. Their implementation can be an inspiration.

> For example, what if users want to allow some regex and deny some regex? How many input fields should I expose the users?

A whilelist and a blacklist. If there's an intersection (I think intersection can be reliably found programmatically) tell the user to change the rules.

**Comment by fyears** [comment]
Let's add a deny list first. Community has a pull request and I am going to review it.

**Comment by fyears** [comment]
New version will have filters support. Issue closed.
