### ISSUE TITLE
GDrive support?

### ISSUE THREAD

**Issue by ashutoshsaboo** [remotely-save/remotely-save#4]
Thanks @fyears so much for building this plugin! It has all the features that I need! Would it be possible to add gdrive support as well (given it has a large/popular user-base too)?

**Comment by ashutoshsaboo** [comment]
Thank you so much @fyears ! More than Onedrive, I look forward to GDrive support. If you can do it sooner, that'd be awesome! :) 

Meanwhile, are you also planning to setup triggering auto sync in background after some delay similar to what this plugin does - https://github.com/ryanpcmcquen/obsidian-dropbox-backups ? @fyears With mobile especially, imo would help a large deal in improving user experience with auto background sync with some delay (as well as the current option of forced manual sync on clicking the button)!

**Comment by berot3** [comment]
Hi,

So no google drive support that is been working at, as of now? 🙁

maybe we should start a patreon or something like that to boost development? 😊

**Comment by sukumar1210** [comment]
Hi @fyears , is this repo dead or can i just contribute to it and add this feature? I started using obsidian lately and was thinking on making a similar plugin when i came across remote-save but i wanted to make something anyways at this point, will it be fruitful for me to add GDrive functionality to remote-save or should i just make a plugin of my own. I do not wish to work just for my PR to be left unreviewed like the 7 open PR as of now. Some are from 2022.

**Comment by fyears** [comment]
Hi the repo is not dead. Prs are welcome and I am going to review them in a few days. However gdrive is especially difficult to implement under the restriction of client side only.

**Comment by fyears** [comment]
Working on this. But the function needs a website to workaround. Some preparations are needed.

**Comment by fyears** [comment]
Finally, please check out version 0.5.3 .

Also the doc is here: https://github.com/remotely-save/remotely-save/blob/master/docs/remote_services/googledrive/README.md
