### ISSUE TITLE
[Bug]: Config Dir sync no longer working (Reported .DS_Store issue)

### ISSUE THREAD

**Issue by daledesilva** [remotely-save/remotely-save#400]
### What happened?

I've been syncing the config directory for a long time now, but have run into an issue today.
I get this message:

```
plugin:remotely-save:216 remotely-save-1701649036181: abort sync, triggerSource=manual, error while syncing
eval @ plugin:remotely-save:216

plugin:remotely-save:216 AggregateError: 
    Error: .obsidian/themes/.DS_Store: Response failed with a 409 code
        at eval (plugin:remotely-save:211:314339)
    Error: .obsidian/plugins/.DS_Store: Response failed with a 409 code
        at eval (plugin:remotely-save:211:314339)
    Error: .obsidian/.DS_Store: Response failed with a 409 code
        at eval (plugin:remotely-save:211:314339)
    Error: too many errors, stop the remaining tasks
        at eval (plugin:remotely-save:211:314443)
        at Generator.next (<anonymous>)
        at a (plugin:remotely-save:177:280327)
    at eval (plugin:remotely-save:211:314499)
    at Generator.next (<anonymous>)
```

## My setup
MacOS Sonoma 14.1.1 (Macbook Pro M1)
Obsidian 1.4.16 (Installer 1.4.14)
Remotely Save 0.3.25
Syncing to dropbox
Not using password

## What I've done to try and fix
- I've turned on hidden files and looked in .obsidian/ and .obsidian/themes and .obsidian/plugins. No .DS_Store files exist there.
- I've checked dropbox and found that none of those files exist there either.
- I did a bunch of tests were I delete files in remotely-save/vault-name on dropbox, uninstalled plugins, and resynced. Same issue. 

## Most revealing test
1. I then created a completely new vault and a few inital MD files (Just random typing).
2. I then installed Remotely Save through Obsidian.
3. I was able to sync the vault successfully to dropbox multiple times.
4. I then enabled Config Directory syncing.
5. I was able to sync the vault successfully multiple times.
6. I then installed a plugin ("Tasks" plugin)
7. I was able to sync the vault successfully multiple times.
8. I then added an empty folder inside the plugin directory to simulate another plugin existing.
9. I then was not able to sync - experiencing the error shown above
(Note that the .DS_Store files reported were still in the same location - ie. not listed as inside the folder I created)
10. I then deleted that folder (locally and on dropbox), but still got same error upon syncing.
11. I then reset and deleted all the settings in Remotely Save near the bottom of it's settings page. but still got the same error upon syncing.
12. I then deleted Remotely Save plugin folder (locally and on dropbox), and installed it again, but still got the error upon syncing.
13. I then 'uninstalled' Remotely Save plugin folder and installed it again, but still got the error upon syncing.

Note that it still appears to sync the plugins, but I'm unsure if it's syncing all files or only some before the error.
Also, if I turn off Config Dir syncing the error goes away while it's off and all works as normal until I turn it back on.

### What OS are you using?

macOS

### What remote cloud services are you using?

Dropbox

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.16 (Installer 1.4.14)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
[https://github.com/remotely-save/remotely-save/commit/6e282c86aff0b526514dbd71dc67d0b7bab2b113] should fix the issue in next public release.
