### ISSUE TITLE
[Feature Request]: sync the created time of file.

### ISSUE THREAD

**Issue by aaronisnothere** [remotely-save/remotely-save#402]
### What feature are you suggesting?

When a new files (or a file which name is changed) sync from obsidian to server, or sync from server to obsidian, the created time of the file will not sync with the file. 
So, it is inconvenient to sort by created time in obsidian, because the created time is changed.

### What remote cloud services are you using, or suggesting adding the feature to?

Dropbox

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Sorry but it’s hard or impossible because when the file is uploaded the metadata is destroyed…
