### ISSUE TITLE
[Bug]: Syncing to Minio

### ISSUE THREAD

**Issue by dcode** [remotely-save/remotely-save#403]
### What happened?

I configured MinIO in a local container on port 9002, created a test user called `obsidian` with the password of `obsidian`, which I've been able to successfully authenticate with from the MinIO client docker container. I attempted to configure Remotely Save to access the bucket using the same creds, but without success. Running the check command displays that it was a 403 response, but pressing the sync button in the main UI shows the response body.

![image](https://github.com/remotely-save/remotely-save/assets/171574/4c3748cb-8b3e-4947-a487-096deb642350)

I've tried with and without CORS bypass. I've captured the network traffic to inspect the request and response and got the following. 

First, here's a successful request using the minio client.

```
GET /obsidian/?location= HTTP/1.1
Host: 192.168.42.50:9002
User-Agent: MinIO (linux; amd64) minio-go/v7.0.65 mc/RELEASE.2023-12-02T11-24-10Z
Accept-Encoding: zstd,gzip
Authorization: AWS4-HMAC-SHA256 Credential=obsidian/20231207/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=ad5cd682974fa194fba825839c2f2f78707950272172f7ed5fa3945df2506310
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20231207T203505Z

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 137
Content-Type: application/xml
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
X-Amz-Request-Id: 179EA6FAC65FEB94
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Date: Thu, 07 Dec 2023 20:35:06 GMT

<?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/">us-east-1</LocationConstraint>

HEAD /obsidian/ HTTP/1.1
Host: 192.168.42.50:9002
User-Agent: MinIO (linux; amd64) minio-go/v7.0.65 mc/RELEASE.2023-12-02T11-24-10Z
Authorization: AWS4-HMAC-SHA256 Credential=obsidian/20231207/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=abf9817c9e7b55b684258304925898b3ef87cbe679cc3d28d927c879843ccac0
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20231207T203506Z

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 0
Content-Type: application/xml
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
X-Amz-Request-Id: 179EA6FB2E96E683
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Date: Thu, 07 Dec 2023 20:35:08 GMT
```

Then with Remotely Save, I get the following. I see you're using the AWS client, but a couple of differences that I see between the sessions:

- The MinIO client never lists options, but it does request the bucket location
- The MinIO client authenticates far fewer fields in the request
- The MinIO client puts a slash `/` at the end of the bucket name

I have a suspicion, that the issue is that MinIO server is hashing the `host` header with the port and the AWS client is not. I don't have anyway to verify that though. I've tried to calculate the signature using some online calculators, but wasn't able to reproduce or validate either requests.

```
OPTIONS /obsidian HTTP/1.1
Host: 192.168.42.50:9002
Connection: keep-alive
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US
Access-Control-Request-Headers: amz-sdk-invocation-id,amz-sdk-request,authorization,cache-control,x-amz-content-sha256,x-amz-date,x-amz-user-agent
Access-Control-Request-Method: HEAD
Origin: app://obsidian.md
Sec-Fetch-Mode: cors
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.16 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36

HTTP/1.1 204 No Content
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Amz-Sdk-Invocation-Id, Amz-Sdk-Request, Authorization, Cache-Control, X-Amz-Content-Sha256, X-Amz-Date, X-Amz-User-Agent
Access-Control-Allow-Methods: HEAD
Access-Control-Allow-Origin: app://obsidian.md
Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
Date: Thu, 07 Dec 2023 20:39:25 GMT

HEAD /obsidian HTTP/1.1
Host: 192.168.42.50:9002
Connection: keep-alive
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US
Origin: app://obsidian.md
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.16 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36
amz-sdk-invocation-id: 7ddd14b6-acc5-45ac-9df9-1c330ecfbfc7
amz-sdk-request: attempt=1; max=3
authorization: AWS4-HMAC-SHA256 Credential=obsidian/20231207/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date;x-amz-user-agent, Signature=c952774c5894c13782684808aea00419271e9c142251a99c310a2e2fb3522723
cache-control: no-cache
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20231207T203925Z
x-amz-user-agent: aws-sdk-js/3.87.0 os/Linux lang/js md/browser/Electron_25.8.1 api/s3/3.87.0

HTTP/1.1 403 Forbidden
Accept-Ranges: bytes
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: app://obsidian.md
Access-Control-Expose-Headers: Date, Etag, Server, Connection, Accept-Ranges, Content-Range, Content-Encoding, Content-Length, Content-Type, Content-Disposition, Last-Modified, Content-Language, Cache-Control, Retry-After, X-Amz-Bucket-Region, Expires, X-Amz*, X-Amz*, *
Content-Length: 0
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
X-Amz-Request-Id: 179EA7375452AE16
X-Content-Type-Options: nosniff
X-Minio-Error-Code: SignatureDoesNotMatch
X-Minio-Error-Desc: "The request signature we calculated does not match the signature you provided. Check your key and signing method."
X-Xss-Protection: 1; mode=block
Date: Thu, 07 Dec 2023 20:39:25 GMT
```

### What OS are you using?

Linux, Android

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by dcode** [comment]
I just tested from the Android client against MinIO's public test server (same version as my container) and I was able to connect just fine after disabling CORS bypass and using path-style URLs.

This config is public and not sensitive.

![Screenshot_20231207-151056.png](https://github.com/remotely-save/remotely-save/assets/171574/e43f44c0-d94e-411c-b663-24403d87dcba)

When I get time, I'll try to setup a reverse proxy to my personal instance and see if that fixes this issue.

**Comment by dcode** [comment]
Okay, I was able to set it up through a reverse proxy with TLS, those are the only two changes I made. It works flawlessly from Linux Flatpak and Android clients. Hopefully this helps figure out the root issue. I think it is the port number being stripped from the `Host:` header. My guess without looking at the code, it's doing a split on `:` and copying the second value in the array. This isn't an issue for any AWS properties because they all use the default HTTPS port of 443.

**Comment by fyears** [comment]
Thanks for providing a workaround.

But it’s quite strange that bypassing cors should always be better…

**Comment by fyears** [comment]
I also try the official play.min.io and connect to it successfully.

**Comment by fyears** [comment]
custom port also succeeded: https://github.com/remotely-save/remotely-save/blob/master/docs/remote_services/s3_minio/README.md
