### ISSUE TITLE
[Bug]: node_modules does not ignore

### ISSUE THREAD

**Issue by sonce** [remotely-save/remotely-save#405]
### What happened?

node_modules  in sub folder,had synced.

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
is it inside the root folder of your vault?

**Comment by sonce** [comment]
Root Dir
|--Blog
    |node_modules
|Note

Like this.

**Comment by fyears** [comment]
I will add a basic checking to skip the well known folder.

**Comment by fyears** [comment]
And a deny list support.
