### ISSUE TITLE
[Bug]: Case insensitive on some platforms

### ISSUE THREAD

**Issue by daledesilva** [remotely-save/remotely-save#407]
### What happened?

I sync with iOS and MacOs.
I've noticed that on MacOS I can't create two folders with the same name but different casing.
However, I can do this on iOS.

When trying to sync, no issue is reported, and one of the folders simply doesn't sync to dropbox (I"ve checked on dropbox online).

So this means it can invisibly not sync a file or folder without reporting any issue.

### What OS are you using?

macOS, iOS (iPhone, iPad)

### What remote cloud services are you using?

Dropbox

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
That's nothing this plugin can do: [MacOS is not a case sensitive file system by default. So you can't have two files named File. txt and file.](https://discussions.apple.com/thread/251191099?sortBy=best)

**Comment by daledesilva** [comment]
Thanks @fyears ,
I've purposely not specified what the plugin should do and focussed on only describing the issue.

If I were to make a suggestion, though, it would be that remotely-save should warn the user that a file wasn't synced and why. It doesn't need to do more than that.

At the moment it silently fails, which is an invisible problem for the user.


A notice like below would do the trick.m and is all that's needed.
 
"filename.txt was not synced as Filename.txt also exists and this operating system doesn't support multiple files with same name (irrelevant of casing)."

**Comment by daledesilva** [comment]
Or, if it can't even put it on the server, then the message would be slightly different...

"filename.txt was not synced as Filename.txt also exists and Dropbox doesn't support multiple files with same name (irrelevant of casing)."

**Comment by daledesilva** [comment]
> Or, if it can't even put it on the server, then the message would be slightly different...
> 
> 
> 
> "filename.txt was not synced as Filename.txt also exists and Dropbox doesn't support multiple files with same name (irrelevant of casing)."

This would prevent the plug-in from making any mistakes, and it would let the user know what to adjust (ie. change the filename)

**Comment by fyears** [comment]
yes sure, i would try to think about adding some capabilities
