### ISSUE TITLE
[Bug]: Port error problem for webdav

### ISSUE THREAD

**Issue by crotoc** [remotely-save/remotely-save#409]
### What happened?

Appreciate your effects to develop a great plugin. I have setup a webdav service on a server listening to 10080. But when I check the connection, it threw the err of "ERR_UNSAFE_PORT". Is there a way to work around? Thanks!

### What OS are you using?

Windows, Linux

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Sorry, but no way to get around this because it's blocked in browser level: https://www.bleepingcomputer.com/news/security/google-chrome-blocks-port-10080-to-stop-nat-slipstreaming-attacks/amp/

**Comment by fyears** [comment]
Please consider changing the port to other number.
