### ISSUE TITLE
[Feature Request]: Information in StatusBar

### ISSUE THREAD

**Issue by troilus** [remotely-save/remotely-save#41]
### What feature are you suggesting?

类似https://github.com/vrtmrz/obsidian-livesync的Information in StatusBar

Synchronization status is shown in statusbar.
Status
⏹️ Stopped
💤 LiveSync is enabled. Waiting for changes.
⚡️ Synchronize is now in progress.
⚠ Error occurred.
↑ Uploaded pieces
↓ Downloaded pieces
⏳ Count of the pending process

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
现在手动触发和自动触发，侧边工具栏的图标是会变动的，且鼠标点击之后可以看到对应所处的同步阶段。因此决定省略 status bar 的图案。
