### ISSUE TITLE
[Bug]: The said folder is not created in onedrive after running the plugin.

### ISSUE THREAD

**Issue by ly05772** [remotely-save/remotely-save#411]
### What happened?

I can't find the newly created folder inside the onedrive I linked to after running the whole plugin many times, the manual sync prompts for success but I still can't find the folder. 
Also what I want is to be able to edit on the Windows side and then sync to the Android side to read it, so I want to know what kind of sync logic the whole plugin has, is it syncing local files to the cloud or syncing cloud files to the local side?

### What OS are you using?

Windows, Android

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
`/Apps/remotely-save`
