### ISSUE TITLE
[Bug]: obsidian program halted

### ISSUE THREAD

**Issue by ta2lor** [remotely-save/remotely-save#413]
### What happened?

when i'm using remotely save with dropbox, it worked well before.
but now when i turn it on, the obsidian program is halted
<img width="1082" alt="스크린샷 2023-12-27 오후 7 25 32" src="https://github.com/remotely-save/remotely-save/assets/63273173/fa1658cf-9177-416d-9af2-fe9c0a513490">

after few minuits

<img width="1308" alt="스크린샷 2023-12-27 오후 7 26 01" src="https://github.com/remotely-save/remotely-save/assets/63273173/ea759f39-48fd-40fa-888b-5f21721d5ea3">

it happenes even Windows and MacOS

### What OS are you using?

Windows, macOS

### What remote cloud services are you using?

Dropbox

### Version of Obsidian

1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by clombt** [comment]
Same problem on iOS on v. 1.4.16, but no such problem exists on Obsidian v. 1.4.6 on Android.

**Comment by fyears** [comment]
Are you syncing big files? Would you like to set "Skip Large Files" and try again? Thanks!

**Comment by clombt** [comment]
That fixed it for me. Thanks a lot!

**Comment by pointlessone** [comment]
I'm having apparently the same issue on iOS. This happens on syncing a big file. Disabling big file sync is a workaround but I'd love my vault synced completely. Do I need to open a new issue or is this being addressed in a different way?

**Comment by fyears** [comment]
that depends on your mobile's memory and performance. 

the obsidian api returns all of the content in your memory. so if you want to deal with 500 mb file you will need **at least** 500 mb memory (**unavoidable!!!** unless obsidian has streaming api later). furthermore, my plugin needs some operations or some compatibility for third party api (like webdav), maybe there are some unnecessary copies introduced.

**Comment by pointlessone** [comment]
* This is an unconventional way to deal with large files. I mean, why does a video file have to be fully in memory in order to fully write it. Downloading chunks and writing directly to storage is the traditional approach since the dawn of computing.
* I have iPhone 15 Pro. It has 8 GB of RAM. It seems like 200 MB file can fit in memory at least sometimes (e.g. right after reboot when no other apps take all the RAM) but Remotely Save fails to sync it *extremely consistently*.

**Comment by fyears** [comment]
> Downloading chunks and writing directly to storage is the traditional approach since the dawn of computing.

yes sure i sincerely hope obsidian has such api... where could i raise a feature request...

> but Remotely Save fails to sync it extremely consistently.

are you using parallel uploading (in settings page)?

furthermore the whole plugin is run inside the browser js environment, so it's also limited by the browser js limitation.

i will try to reproduce it to be sure. but anyways i don't think i have any valid solutions until a streaming or chunking api introduced
