### ISSUE TITLE
[Bug]: onedrive auth

### ISSUE THREAD

**Issue by haha9527upup** [remotely-save/remotely-save#415]
### What happened?

![2024-01-01_23-23](https://github.com/remotely-save/remotely-save/assets/103400784/a61b5b42-3b2f-4a4a-b5c9-8d798f15c405)

onedrive登录授权后没有直接跳转回到插件设置界面，之前都能成功的，今天突然就直接回到这个打开仓库的界面

### What OS are you using?

Linux

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
是否从插件页发起的呢？重启obsidian还是可以稳定复现吗？有windows可以复现吗？linux是什么发行版和什么版本？

**Comment by haha9527upup** [comment]
> 是否从插件页发起的呢？重启obsidian还是可以稳定复现吗？有windows可以复现吗？linux是什么发行版和什么版本？

1、是的，从插件页点击链接自动跳转到浏览器。
2、昨天多次重启obsidian，今天重新打开电脑，在linuxmint下还是这样。应该是在更新插件后才出现，之前没出现过。
3、windows下插件无异常，能正常登录授权。
4、System:
  Kernel: 5.15.0-91-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 5.8.4
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy

**Comment by fyears** [comment]
更新插件？我还没发版本呢…… remotely-save 版本号确认一下是0.3.25？

**Comment by fyears** [comment]
obsidian 是什么版本？是自动升级还是重装了？

**Comment by haha9527upup** [comment]
> 更新插件？我还没发版本呢…… remotely-save 版本号确认一下是0.3.25？

5、卸载后重新从插件市场安装还是没解决呢。obsidian是自动升级，从1.4.16升级到1.5.3

**Comment by haha9527upup** [comment]
linuxmint系统下插件升级到0.3.24、更换firefox/chrome浏览器也还是没能跳转回鉴权界面，目前一个暂时的解决是把windows下的整个remotely-save文件夹复制过来（我两个系统的插件在不同文件夹）。

**Comment by danigamba** [comment]
same problem, ubuntu 23.10, obsidian v1.5.3, remotely save 0.3.38
opens a new window on authorization, obisidian installed as appimage

**Comment by danigamba** [comment]
Solved switching to Flatpak instead of AppImage, still worth investigating imho

**Comment by Khvalin** [comment]
As a workaround, it worked for me when I opened a link with an "unpacked" executable instead of .appImage itself. It's my understanding that app images are unpacked to /tmp/, that unpacked version will know about the auth callback pending and will handle it appropriately.

**Comment by fyears** [comment]
@Khvalin @danigamba @haha9527upup 

I do some experiments on Ubuntu (in virtualbox), and do not find a way to callback Obsidian (appimage) with combination of Onedrive and Obsidian... Basically it needs configuring `xdg-open` correctly and correct desktop environment, according to some Google search.

I am unable to install flatpack currently... Why, Linux, why...

Dropbox allows showing, copying and pasting the auth code, so it doesn't have to worry about calling back Obsidian. But Onedrive doesn't provide such a way.

One workaround is using a real website, eg, `https://remotely-save.com`, to catch the auth code from Onedrive and show up the code, then the user can copy and paste the code. It works universally but I have to show up a warning and prepare a privacy policy on the website. I am working on this.

Any other thoughts or suggestions?

**Comment by brunotenisi** [comment]
I had the same problem on ArchLinux, the solution was to install via Flatpak.

**Comment by fyears** [comment]
i give up and decide to add a hint to use flatpack version... thanks all!

**Comment by haha9527upup** [comment]
- 奇怪，onedrive网页版及outlook邮箱都能正常在浏览器上登录，但是想给remotely-save授权却卡在ERR_TIMED_OUT了。
- 在windows 和linuxmint系统上都是这样，这几天才出现，之前在windows上是能正常授权的。
- 卸载老版本并重新安装0.4.11版后问题仍存在。




![2024-03-27_01-13](https://github.com/remotely-save/remotely-save/assets/103400784/13fad378-3e27-46a5-861d-b28e10d0ea3c)


![2024-03-27_01-01](https://github.com/remotely-save/remotely-save/assets/103400784/de90fb93-74dc-4c8e-8663-f681e2913a2e)
![2024-03-27_01-02](https://github.com/remotely-save/remotely-save/assets/103400784/0cae1a03-1951-4e6a-9934-b0c45b225c69)

**Comment by zichen34** [comment]
I met the same problem on my Chromebook. I downloaded Obsidian from the Play Store. Although the Chrome browser jumps back to the plugin, there is no prompt about "successful authentication ...".

**Comment by fyears** [comment]
so are you using android obsidian? are you sure you can connect to onedrive in obsidian without proxy?

**Comment by zichen34** [comment]
> so are you using android obsidian? are you sure you can connect to onedrive in obsidian without proxy?

Dear fyears, 

Thank you for your timely reply. I installed Obsidian from the google Play Store:

<img src="https://github.com/remotely-save/remotely-save/assets/33821211/9035681a-0cd8-4334-9985-75f13d4a63ac" height=400>

When I don't use proxy, the authentication couldn't be completed either, after I clicked "Open" as shown below:

<img src="https://github.com/remotely-save/remotely-save/assets/33821211/cfdbeb0b-f135-4c9b-8ff0-1e9673576857" height=400>

It jumps back to Obsidian, but there is no notification about the authentication result.

<img src="https://github.com/remotely-save/remotely-save/assets/33821211/2d7a8ff1-a237-4137-9e0e-fdbaf09010b3" height=300>

Best Regards,
Zichen Wang

**Comment by fyears** [comment]
sorry but i do not have a chromebook to debug on. and i cannot reproduce the error on normal android.

please export the authorized onedrive setting from the first device (your pc/mac) with qr, then use your chromebook to scan the qr code (with the help of qrcode app like [BinaryEye](https://github.com/markusfisch/BinaryEye) to import the setting. you can find out import/export part in remotely save settings.

![zzz](https://github.com/remotely-save/remotely-save/assets/1142836/bb767195-b163-40e5-bbc5-a01bd6e4948f)

**Comment by zichen34** [comment]
> sorry but i do not have a chromebook to debug on. and i cannot reproduce the error on normal android.
> 
> please export the authorized onedrive setting from the first device (your pc/mac) to qr code, then use your chromebook to scan the qr code (with the help of qrcode app like [BinaryEye](https://github.com/markusfisch/BinaryEye)) to import the setting. you can find out import/export part in remotely save settings.
> 
> ![zzz](https://private-user-images.githubusercontent.com/1142836/328965257-bb767195-b163-40e5-bbc5-a01bd6e4948f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMDAyMjUsIm5iZiI6MTcxNTE5OTkyNSwicGF0aCI6Ii8xMTQyODM2LzMyODk2NTI1Ny1iYjc2NzE5NS1iMTYzLTQwZTUtYmJjNS1hMDFiZDZlNDk0OGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMjAyNTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjZkNjZlMTMxYzMwODk0ZTUyNTQ2OWJkOThmZTQ5MTJmYzkyNTBhNTUwMWZjNzdkMzk3NTUyYjM2NDkyODlmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2PClcSzwa_M7AcJ_6rlQtixYMWk_ENzS5LznN7xsLGU)

Dear @fyears, Thank you very much. This approach works for me. I exported the Onedrive URL from my iPhone and imported the link into my Chromebook.

**Comment by deepakdgupta1** [comment]
I just fed this bug to Claude Code. Took about 10 seconds to fix it. Here's the summary -
  Root cause: xdg-open resolves URI scheme handlers by looking up the MIME type         
  x-scheme-handler/obsidian in the system database — but it only indexes files in
  ~/.local/share/applications/. Your desktop file was on the Desktop, so it was         
  invisible to xdg-open.                                          

  Fixes applied:
  1. Copied obsidian.desktop → ~/.local/share/applications/obsidian.desktop
  2. Ran update-desktop-database to rebuild the MIME index
  3. Ran xdg-mime default obsidian.desktop x-scheme-handler/obsidian to explicitly
  register the obsidian:// handler

  Now when OneDrive redirects back with an obsidian://... callback URL, xdg-open will
  find and focus Obsidian, completing the Remotely Save authentication.
