### ISSUE TITLE
2024q1 plan

### ISSUE THREAD

**Issue by fyears** [remotely-save/remotely-save#416]
### What feature are you suggesting?

- [x] ignore git node_modules desktop.ini ds_store icon
- [ ] name: #%|?
- [x] reduce hints
- [x] status bar
- [x] sync on save
- [x] deletion in .obsidian
- [x] cannot load on android
- [x] webdav check and doc
- [x] s3 base path
- [x] s3 custom port
- [x] remote debug! 
- [x] force push (backup) and force pull mode
- [x] better deletion
- [x] encryption update

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by MikeWi11s0n** [comment]
Please consider including in your plan list fixes for faster auto-sync, as well as a fix for moving deleted files to the Obsidian Recycle Bin instead of the System Recycle Bin when selected in the settings. This was resolved in the Remotely Sync plugin. These are very necessary and important fixes that will make the plugin much more enjoyable.

**Comment by OzzmRT** [comment]
> Please consider including in your plan list fixes for faster auto-sync, as well as a fix for moving deleted files to the Obsidian Recycle Bin instead of the System Recycle Bin when selected in the settings. This was resolved in the Remotely Sync plugin. These are very necessary and important fixes that will make the plugin much more enjoyable.

I completely agree with you. Deleting files not to the Obsidian trash when it's selected in the settings is a really annoying bug. I really don't understand why the author didn't include this fix in the list, especially if it's already implemented.

**Comment by fyears** [comment]
@OzzmRT @MikeWi11s0n yeah sure why not. already implemented and will be released in a few days
