### ISSUE TITLE
[Bug]: Cannot Sync Cross Platform

### ISSUE THREAD

**Issue by VAC-Norland** [remotely-save/remotely-save#419]
### What happened?

I enabled and configured Remotely Save both on my iPhone and my Mac, but when I try to sync files on the 2 devices, it just creates 2 identical folders to my InfiniCloud. It's so weird and I can't solve it. Is it supposed to be like that? 

### What OS are you using?

macOS, iOS (iPhone, iPad)

### What remote cloud services are you using?

webdav

### Version of the plugin

0.325

### Version of Obsidian

1.53

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by VAC-Norland** [comment]
I just wanna have my phone and laptop synced with the same files so I can work seamlessly cross-platform. Is it possible?

**Comment by fyears** [comment]
your vault names should be the same

**Comment by VAC-Norland** [comment]
> your vault names should be the same

Sure, I set everything to be the same, but it ended up creating two identical folder with exact same name on my WebDAV. I dunno why folders with the same name can be created, yet here I am. It's baffling me.

**Comment by fyears** [comment]
@VAC-Norland that's totally unexpected. may i ask what webdav server are you using? i may be able to try to do some tests if that's easily installed

**Comment by fyears** [comment]
it seems to be a bug in some implementations? seriously i don't think my plugin could solve this... i always assume that the folder should only be able to be created once...

https://community.icedrive.net/t/resolved-duplicates-in-same-folder/335/3

https://help.nextcloud.com/t/possible-reason-why-duplicate-folders-are-automatically-created/75813

**Comment by fyears** [comment]
oh i see you are using inficloud. let me try

**Comment by fyears** [comment]
hi i am sorry but i could not create two folders with the same name together...

i go to <https://futtsu.teracloud.jp/browser/> and try to create a folder with a duplicated name, and the web page just disallows me to do so.

some suggestions:
1. create a folder with plain english manually in <https://futtsu.teracloud.jp/browser/>
2. **manually type the vault name on your mobile, and pc, ensure there are no empty spaces, not special characters, etc.**
3. and try to connect again.

**Comment by VAC-Norland** [comment]
Yeah thank you dude. I was using non-English latin names, now I renamed it and it totally worked!
