### ISSUE TITLE
[Bug]: The plugin doesn't update from version 0.3.25 to a newer one through the update search

### ISSUE THREAD

**Issue by OzzmRT** [remotely-save/remotely-save#420]
### What happened?

Judging by the plugin's manifest, the version remains 0.3.25. Presumably, this is done precisely to avoid updating the plugin because the stable release is not yet ready. Am I understanding it correctly? Because in all releases, there's a Pre-release tag, and it's absurd and only confusing. Perhaps, it would be helpful to add an additional note to releases that are not fully ready to somehow distinguish them.

### What OS are you using?

Windows, macOS, iOS (iPhone, iPad), Android

### What remote cloud services are you using?

OneDrive for personal

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
hi thanks for your interest in remotely-save.

1. don't worry, an officially announced new version will be released very soon in a week. the current versions these days are for myself to test, i need to upload it to github release to download it in my mobile.
2. may i ask how do you know that i upload many new releases these days? i admit that it has been updated for a long time, but i am rather glad that users are still paying attention to the new version!

**Comment by OzzmRT** [comment]
> hi thanks for your interest in remotely-save.
> 
> 1. don't worry, an officially announced new version will be released very soon in a week. the current versions these days are for myself to test (after two years of pausing), and i need to upload it to github release to download it in my mobile.
> 2. may i ask how do you know that i upload many new releases these days? i admit that remotely-save hasn't been updated for a long time, but i am rather glad that users are still paying attention to the new version!

Hi 👋

1. I thought so, that's why I'm closing this issue. Simply, it would be great if you would indicate in the notes that this is not a release version. Because it's not obvious at the moment.

2. I have been using remotely-save for quite some time. But not so long ago, I accidentally stumbled upon remotely-sync and saw that it fixed probably the most annoying bug for me, when files are deleted to the system trash, and not to the Obsidian trash, although this is selected in the settings. I also noticed in one of the topics, you mentioned that you will be releasing an update soon as well. So I'm currently waiting for you to fix it and for a new version to come out, so I'll check back from time to time to see how the development is progressing.
