### ISSUE TITLE
[Bug]: Minio first synchronization error

### ISSUE THREAD

**Issue by how1ewu** [remotely-save/remotely-save#421]
### What happened?

Each time a new folder is created for synchronization, because there is no corresponding folder in the minio bucket, synchronization will report an error: XXX/XXX/XXX UnkownError in the interface. After the error, I noticed that the relevant folder was created in the bucket, and the data exchange was aborted until the next synchronization. I think it's a mistake.
![](https://s2.loli.net/2024/01/06/Nhu3GkJenEVCfLS.png)

### What OS are you using?

Windows, Linux, macOS

### What remote cloud services are you using?

S3

### Version of the plugin

latest

### Version of Obsidian

latest

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by how1ewu** [comment]
There is also a problem. When I click check in the settings interface, the interface pops up: unable to access bucket and UnknownError

**Comment by how1ewu** [comment]
just like:
![](https://s2.loli.net/2024/01/06/hNmFDYac5AopvRZ.png)

**Comment by fyears** [comment]
（可用中文）

**新建一个测试 vault **，可以复现吗？我用官方的 play.min.io 没有问题，你这边可以用 **测试 vault** 和官方的复现出对应错误吗？ <https://github.com/remotely-save/remotely-save/blob/master/docs/remote_services/s3_minio/README.md>

**Comment by how1ewu** [comment]
重新尝试这个错误仍会出现，我怀疑可能跟minio自己部署有关（？），minio同步在思源笔记是正常的，通过不断地手动同步最终也能将数据上传并正常校验
![](https://img.wush.cc/202417214440-1704635079213?imageView2/0/format/webp/q/80)

**Comment by fyears** [comment]
依旧怀疑是权限问题。有没有特殊设置？我用官方的minio.exe 直接运行，是没问题的

**Comment by fyears** [comment]
无法复现，用本地的 minio 和官方 play 网站都是可以的。先关闭此 issue 了。
