### ISSUE TITLE
[Bug]: Comparing files solely by the file name has serious drawbacks

### ISSUE THREAD

**Issue by MartinJDavis93** [remotely-save/remotely-save#422]
### What happened?

Currently, file comparison is done only based on the file name. So, if you create a file on a device with the name File1, synchronize it across your devices, and then decide to rename it, for example, to File2, it won't actually be renamed to File2. Instead, the original File1 will be deleted (sent to the trash) because a file with that name no longer exists. File2 will be synchronized as a separate file, not connected to File1 in any way. And each subsequent renaming of the file will erase the previous file. So, if you later want to rename File2 to File3, you will already find File1 and File2 in the trash, which essentially are all the same; you just decided to rename them. And that's a problem. It would be more reasonable to compare files, for example, by the file hash or some other additional indicator besides the name, or assign a separate ID to each file, which would be stored in a separate file list.

### What OS are you using?

Windows, Android

### What remote cloud services are you using?

Dropbox

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> It would be more reasonable to compare files, for example, by the file hash or some other additional indicator besides the name, or assign a separate ID to each file, which would be stored in a separate file list.

i am aware of all the pitfalls you indicate in the very beginning.
the only partial solution is involving file hashes, which greatly increases the complexity of the plugin. i will try to think about it or refer to famous rclone's solution

**Comment by snrbrnjna** [comment]
@fyears why not directly use rclone bisync functionality in your plugin. Seems that this would make file-manipulation (renaming, deletion) also outside the obsidian client syncable. No?

**Comment by fyears** [comment]
because i need it to work on mobile especially on ios.

if users just want to sync on pc mac, rclone, syncthing, rsync, ... are just way better solutions

**Comment by snrbrnjna** [comment]
yes, indeed, i only need your great plugin for syncing to and from iOS. For syncing between other platforms i use the nextcloud client. 

My question was, if it would be possible to use rclone in your plugin on ios. Seems to me that the bisync functionality of rclone would make setups possible with the remotely-save plugin only installed on iOS. On most of the other platforms the syncing is done by the native sync clients.

**Comment by snrbrnjna** [comment]
@fyears any comment on my last comment? 😊

**Comment by fyears** [comment]
I believe the most hard problem is compiling rclone into js and make it run on iOS.

But sure, the bisync algorithm is worth reading and I am learning from it.

**Comment by snrbrnjna** [comment]
@fyears what about https://rclone.js.org/? Doesn’t that work out in iOS client?

**Comment by fyears** [comment]
> [org/](https://rclone.js.org/)? Doesn’t t

No. It's just a wrapper on rclone binary

**Comment by fyears** [comment]
comparing hashing && tracking rename has technical difficulties and performance issue especially on mobile. would not implemented in the near future.
