### ISSUE TITLE
[Bug]: Trying to connect to dropbox on linux tells me something went wrong

### ISSUE THREAD

**Issue by PWDSerialgamer07** [remotely-save/remotely-save#423]
### What happened?

I expected it to connect and sync my files already available on dropbox

### What OS are you using?

Linux

### What remote cloud services are you using?

Dropbox

### Version of the plugin

0.3.34

### Version of Obsidian

1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
hi i am sorry that something goes wrong...

but are you using dropbox or onedrive actually? (your title and your content are different)

any more details? what linux distribution and what version of obsidian and what version of plugin are you using? any way to stablely reproduce? are you using any proxy?

and could you reproduce the error on windows pc or mobile phone?

**Comment by PWDSerialgamer07** [comment]
Sorry, I'm using dropbox, I'm running on EndeavourOS which is based on Arch Linux, I've put both the versions of obsidian and the plugin in the post. I'm not using any proxy and I just tried it on Windows 11 and didn't get any error. 

The thing I noticed was different was that when doing it on linux, the auth page gave me a code to input in obsidian, but doing it on windows didn't give me a code and just directly logged me in.

**Comment by fyears** [comment]
> don't give me a code

that's an important hint! i will try to find out what's the differences behind the scenes

**Comment by fyears** [comment]
and may i ask for a screenshot of the error? please remember to remove any sensitive info

**Comment by PWDSerialgamer07** [comment]
I don't know what changed, but all of a sudden it works now

**Comment by fyears** [comment]
ok... wish you the best! feel free to reopen it if any further hints or the error occurr again
