### ISSUE TITLE
[Feature Request]: 提升手机同步速度

### ISSUE THREAD

**Issue by YIRU69** [remotely-save/remotely-save#424]
### What feature are you suggesting?

大大，我一个库有2450个文件，我手机修改了一个文件，进行同步，需要2分钟以上，可以提升一下同步速度吗？手机本来就是便捷编辑，进行同步指令后还要在这个界面等同步完成太麻烦了
我的是安卓机，手机不能后台进行同步

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
目前每次同步都要读一次全量远程文件。假如提供一个功能“只更新本文件”，可以解决你的问题吗？

**Comment by YIRU69** [comment]
不太清楚功能“只更新本文件”，是什么意思？我昨天睡觉的时候在想，如何提高速度，现在速度很慢应该就是要没个文件都要读一次，然后和之前的文件进行对比（我的理解）

我想是否可以这样：
1. 插件可以记录我的改动，或文件的改动，比如删除，移动位置
2. 在进行同步的时候，这些记录就可以直接用来同步，而不需要再一次进行全量对比，来去确认

我想这样的话应该可以达成加速同步的时间，但是不确定里面是否存在问题，我的大概思路就是把同步的步骤放一部分到自己没有进行同步的时候，这让我想起了一个类似的例子。以前我用了很多插件，导致开启ob的速度很慢，有一个策略是先关闭这些插件，等ob启动了再逐步开启插件，这样开启ob的速度就变快很多。这个例子，就是我对加速同步的启发，希望对作者有一定帮助。
电脑性能不好，每次等待同步确实是一件很痛苦的事情了。

**Comment by fyears** [comment]
可能会增加只同步本次修改文件。但是暂且没有好的解决方法
