### ISSUE TITLE
[Bug]: Error: region was not a valid DNS name

### ISSUE THREAD

**Issue by misakaikato** [remotely-save/remotely-save#425]
### What happened?

When I use sync, it will prompt: region was not a valid dns name.

![image](https://github.com/remotely-save/remotely-save/assets/12230661/6bd1ed09-e5f3-4d98-88b0-0166eb5d00ef)

ps: I use  aliyun oss

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.34

### Version of Obsidian

1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
怎么配置的？方便截图看看？记得把两个key以及你的vault name隐藏

**Comment by misakaikato** [comment]
> 怎么配置的？方便截图看看？记得把两个key以及你的vault name隐藏

你好，谢谢回复，我的配置：

![image](https://github.com/remotely-save/remotely-save/assets/12230661/6c1b8350-ba4d-4c95-ad39-17ef5cb73c14)

endpoint： oss-cn-beijing.aliyuncs.com
region：oss-cn-beijing-internal.aliyuncs.com

当时是参考这篇文章进行的配置：https://forum-zh.obsidian.md/t/topic/5362/85

前天还是可以正常使用的，但是这两天接连更新了两次插件后，就不能使用了。

我刚才尝试将 region 从 oss-cn-beijing-internal.aliyuncs.com 修改为 cn-beijing 或 oss-cn-beijing 后，发现又可以使用了。。。。很迷惑

**Comment by sdegongzuo** [comment]
我也是同样的问题，也是阿里云

**Comment by sdegongzuo** [comment]
把后面的-internal.aliyuncs.com删除也可以正常使用了

**Comment by fyears** [comment]
https://help.aliyun.com/zh/oss/user-guide/regions-and-endpoints

一般来说，region 是不带域名那一片 字符，此外从阿里云的文档来说，interal 是内网才能访问的。

所以你们的修改后配置才是对的，之前能运行可能是阿里云做了什么兼容
