### ISSUE TITLE
[Bug]: Error while syncing,  Request failed,status 404

### ISSUE THREAD

**Issue by ajmz** [remotely-save/remotely-save#427]
### What happened?

remotely-save-1704715350430:abort sync,
triggerSource=manual,error while syncing

"filename": Request failed,status 404

![PixPin_2024-01-08_20-03-35](https://github.com/remotely-save/remotely-save/assets/30185045/ef1dd127-ce10-4f95-9cfa-1e4934eb8a59)

But in fact, files other than the one reporting the error were synchronized normally.
The previous version of remote-save also reported the same error.
This only occurs in the Windows version, and there is no error message in the Android version.

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.34

### Version of Obsidian

1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
are there any special non english non number characters in your file name?

or is your file empty?

**Comment by ajmz** [comment]
> are there any special non english non number characters in your file name?
> 
> or is your file empty?

Yes, Chinese guillemet《》(punct. used for names of books etc) in the file name.
But in order to solve this problem, I have manually deleted this file long ago, but the same synchronization error still occurs.

**Comment by fyears** [comment]
hi you could click the "rest" button in the very end of the setting page of the plugin, and delete the _remotely-save-meta-data.json in the remote if any

**Comment by ajmz** [comment]
I did so, but the issue remains.

**Comment by fyears** [comment]
the last way to verify is using a new test vault and try that file again. if the error still occurs, that's because of the limitations of ondrive disallowing some special characters

**Comment by ajmz** [comment]
> the last way to verify is using a new test vault and try that file again. if the error still occurs, that's because of the limitations of ondrive disallowing some special characters

The question is  I have manually deleted this file a long time ago.

**Comment by fyears** [comment]
if the problem can be reproduced in a new vault, that should be the problem of file name. please checkout this https://rclone.org/onedrive/#restricted-filename-characters

**Comment by ajmz** [comment]
> if the problem can be reproduced in a new vault, that should be the problem of file name. please checkout this https://rclone.org/onedrive/#restricted-filename-characters

Thanks, but how to rebuild the filename database synchronized by remote-save without Restricted filename characters, which has manually deleted.

**Comment by fyears** [comment]
reseting in the settings page **and** deleting the meta file on the remote are sufficient

**Comment by ajmz** [comment]
I did so 3 days ago, but the issue remains.
Inside the remote onedrive folder, the file reporting error is not exist.
Other files with the same Chinese guillemets《》(punct. used for names of books etc) in the file name, are synchronized properly and no errors are reported.
Anyway, thanks for your help.
Hopefully the dev team will see this and look into the cause.

**Comment by ajmz** [comment]
> reseting in the settings page **and** deleting the meta file on the remote are sufficient

I did so 3 days ago, but the issue remains.
Inside the remote onedrive folder, the file reporting error is not exist.
Other files with the same Chinese guillemets《》(punct. used for names of books etc) in the file name, are synchronized properly and no errors are reported.
Anyway, thanks for your help.
Hopefully the dev team will see this and look into the cause.

**Comment by fyears** [comment]
thanks for providing helpful info!
