### ISSUE TITLE
[Bug]: can't overcome self-signed certificate error with NextCloud

### ISSUE THREAD

**Issue by jknGH** [remotely-save/remotely-save#429]
### What happened?

(not sure if you'd call this a bug or a feature)

I am trying to get up to speed with Obsidian (previously I have used Joplin). I  want to use remotely-save to sync Obsidian between machines running on my local network, including Nextcloud.

I can set the WebDAV URL and username/password etc. But when I "check" the connection I get an (expected...) error: "ERR_CERT_AUTHORITY_INVALID"

I presume this is due to my Nextcloud certificate being self-signed. If I try to use Joplin in a similar way (ie. to the same Nexcloud, different location of course!) I get a slightly different error: Code DEPTH_ZERO_SELF_SIGNED_CERT.

However Joplin has an option "Ignore TLS Certificate errors". When I select this I am able to sync with Joplin OK.

There appears to be no similar option for remotely-save. At the moment I am therefore unable to use Obsidian with remotely-save, I think.

I request that such a feature be added please.

### What OS are you using?

Windows, Linux

### What remote cloud services are you using?

others

### Version of the plugin

0.3.34

### Version of Obsidian

1.5.3

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
i am sorry but the plugin cannot bypass the certificate error. i would rather say it'sa feature of obsidian.

the plugin runs in an api provided by obsidian, which runs in obsidian's browser or electron environment and doesn't provide any way to invalid certificate. so my plugin can do nothing.

you best bet is using a trusted certificate, and there are some free options like let's encrypt or zerossl.
