### ISSUE TITLE
[Feature Request]: Ignore data.json by default

### ISSUE THREAD

**Issue by ras0q** [remotely-save/remotely-save#433]
### What feature are you suggesting?

Issue https://github.com/remotely-save/remotely-save/issues/163 and PR https://github.com/remotely-save/remotely-save/pull/414 allowed you to select files to ignore synchronization with a regular expression. But shouldn't we add `.obsidian/plugins/remotely-save/data.json` to the default options?

### What remote cloud services are you using, or suggesting adding the feature to?

Dropbox

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
let's leave this to the users because some of them what that file being synced...
