### ISSUE TITLE
[Bug]: PC端删除文件或文件夹的操作无法同步到移动端

### ISSUE THREAD

**Issue by zhigang-he** [remotely-save/remotely-save#435]
### What happened?

在PC端删除文件之后同步，移动端对应的文件不会删除；在PC端删除文件夹之后同步，则不仅移动端对应的文件夹没有删除，甚至会再次在PC端生成已删除的文件夹。

移动端的删除同步到PC端没有问题，增加文件或者文件夹的操作在两端也能够正常同步。

### What OS are you using?

Android

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.34

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
删除操作是在 obsidian 里面操作的吗？

**Comment by fyears** [comment]
如果是obsidian外删除，暂时无法同步。之后会发版本规避这个问题

**Comment by zhigang-he** [comment]
PC端在 Obsidian 里边和在资源管理器里边进行删除操作都无法同步到移动端。我的Obsidian库建在了 \OneDrive\Apps\remotely-save\ 下面，移动端安装了 remotely-save 插件，PC端没有安装。

**Comment by fyears** [comment]
这里原理是，插件通过 obsidian 的 api ，记录文件的变动。因此 pc 端没有通过安装了插件的 obsidian 删除的话，插件是记录不了删除步骤的。

近期会有新版本尽量解决这个问题

**Comment by zhigang-he** [comment]
清楚了，谢谢！
