### ISSUE TITLE
[Bug]: 移动端无法开启插件

### ISSUE THREAD

**Issue by sanshu3271** [remotely-save/remotely-save#436]
### What happened?

移动端无法开启插件

### What OS are you using?

Android

### What remote cloud services are you using?

webdav

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
请更新一下 webview 再试试，之前有用户反馈过这个问题

https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en&gl=US
