### ISSUE TITLE
[Bug]: PC : Can't reach the S3 bucket 

### ISSUE THREAD

**Issue by Zeredof** [remotely-save/remotely-save#437]
### What happened?

After the new update when i tried to use the plug-in it tell me this (see first image) but i didn't change anything. 
And I'm using this site for the cloud https://www.storj.io/

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using?

others

### Version of the plugin

0.3.34

### Version of Obsidian

1.5.3

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
sorry but no images here?

**Comment by Zeredof** [comment]
Oh yeah sorry it's here https://imgur.com/a/NQ7TgGA
![image](https://github.com/remotely-save/remotely-save/assets/111151379/8125c1df-9fe0-4e29-b0a8-21326979d5da)

**Comment by fyears** [comment]
what's your region setting?

**Comment by Zeredof** [comment]
Europe

**Comment by fyears** [comment]
please try: global

according to https://docs.storj.io/dcs/third-party-tools/splunk

**Comment by Zeredof** [comment]
Where can i put the region?

**Comment by fyears** [comment]
go to remotely-save setting page you will see that

**Comment by fyears** [comment]
doc: https://github.com/remotely-save/remotely-save/tree/master/docs/remote_services/s3_storj_io
