### ISSUE TITLE
[Bug]: Local changes don't sync

### ISSUE THREAD

**Issue by samolukadjo** [remotely-save/remotely-save#438]
### What happened?

If any local changes are made upon attempting to sync them, the process works fine until step 7/8 where I get the error:

 Cannot read properties of undefined (reading 'adapter')

No changes are made. If I use the "Reset local internal caches/databases" option in plugin settings, the next sync will use the remote to override the local, but no error appears.

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

0.3.35

### Version of Obsidian

v1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Have you changed any file from upper case to lower case?

**Comment by toyo2333** [comment]
`Cannot read properties of undefined (reading 'adapter')`

same issue as you after updated to 0.3.35

**Comment by Pongpun364** [comment]
"I faced the same problem: Cannot read properties of undefined (reading 'adapter'). After encountering this, I used the 'Reset local internal caches/databases' option and reloaded the plugin. Everything has been working fine so far. The remote and local systems are in sync and updated correctly."



//----------------------------------------//
What OS are you using?
Windows

What remote cloud services are you using? (Please choose the specified one if it's in the list)
Onedrive for personal

Version of the plugin
0.3.36

Version of Obsidian
v1.5.3

**Comment by fyears** [comment]
@samolukadjo @toyo2333 @Pongpun364  i found the bug! please upgrade to 0.3.37 for a fix. don't worry the bug doesn't cause data loss.

**Comment by samolukadjo** [comment]
There is very much still a bug here, local changes still get overridden if the file isn't moved somewhere else, and my (almost) entire vault just got deleted. I tried to do a first time sync to download everything to a Windows device. I'll restore a backup.
The plugin only seems to have this problem on Windows.  
Albeit, the error this report is about isn't present anymore, so these could be multiple separate bugs.

**Comment by fyears** [comment]
sorry to hear that! please make a backup of the vault, Reset local internal caches/databases, **and delete remote _remotely-save-metadata.json** to ensure a full reset.

i am hoping a new release with new sync algorithm can solve the syncing problem especially about deletions...
