### ISSUE TITLE
[Bug]: stops on connecting to dropbox DropboxResponseError 409

### ISSUE THREAD

**Issue by MoHoseinHabibi** [remotely-save/remotely-save#439]
### What happened?

i tried to authorize dorpbox on my android device but i after authorizing drop box it stops in this screen
<img src="https://github.com/remotely-save/remotely-save/assets/36450793/2a48737d-6244-4ce3-922c-70f7be5a974b" width="300"/>
i check connectivity on page and got this error on top of screen:
<img src="https://github.com/remotely-save/remotely-save/assets/36450793/77a54c7b-fc4f-4d17-9775-9281e98d5006" width="300"/>
I could authorize dropbox(logged in to site...) so I don't think I have connection issue to dropbox

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

0.3.35

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Please wait for a minute or two on "DO NOT close the modal". If any connection problems occur, it will show up the last error.

And do you have any proxy settings?

**Comment by fyears** [comment]
I just try my dropbox connection on android and nothing abnormal happened.

**Comment by MoHoseinHabibi** [comment]
I tried it again and waited 5 minutes but nothing showed up.
NO, i don't have proxy setting, i checked with vpn and without it too.
I used this plugin on window version and it's works without any problem but can't get it to work on my phone.

**Comment by fyears** [comment]
would you try to directly copy data.json from your computer to mobile to see if it's working?

**Comment by MoHoseinHabibi** [comment]
I could not find data.json on android to replace it. May you give me the location i should search?
I search obsidian vault location and android/data/md.obsidian but can't find the plugin folder.

**Comment by fyears** [comment]
please connect to pc or try to show the hidden folder

**Comment by MoHoseinHabibi** [comment]
I connected to pc to be able to access android/data folder
But i could find it
Also i tried searching folders using pc for remotly-save folder but with no success

**Comment by fyears** [comment]
i would suggest you try some search "show hidden folder in android" to find out the correct way of showing hidden folder on you device.

**Comment by ReYaNOW** [comment]
Hey! Just fixed this.

Check if your vault names are the same
mine on pc (where I downloaded it to dropbox was Vault1)

but was Obsidian on mobile

after I renamed it to Vault1 on mobile it worked!

![изображение](https://github.com/user-attachments/assets/5e73afeb-1cbd-4e58-8dd4-d3ae0f6350fd)
