### ISSUE TITLE
[Bug]: failed to load this plugin in Android

### ISSUE THREAD

**Issue by Cloudptj** [remotely-save/remotely-save#440]
### What happened?

Failed to load this plugin in Android. The plugin version is 0.3.35 and OB version is 1.4.16(newest available in google play).

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (坚果云 JianGuoYun/NutStore)

### Version of the plugin

0.3.35

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
what android version are you using?

**Comment by fyears** [comment]
dup of #308 please join the discussion there
