### ISSUE TITLE
[Bug]: Cannot red properties of undefined(reading 'adapter')

### ISSUE THREAD

**Issue by tryzang** [remotely-save/remotely-save#441]
### What happened?

![image](https://github.com/remotely-save/remotely-save/assets/129819850/43522c6a-dd44-4bfa-bf26-89f475e8094b)
After updating the plugin, it is normal to use. But after I changed the name of a folder, I got an error when I synced again.
(ps: The same thing happened on my Android tablet too.)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.3.36

### Version of Obsidian

1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
@tryzang i found the bug! please upgrade to 0.3.37. don't worry your data is not lost by this bug

**Comment by tryzang** [comment]
The problem was solved after the upgrade, thank you for the maintenance of the plugin.
