### ISSUE TITLE
[Bug]: webdav - Request failed, status 403

### ISSUE THREAD

**Issue by 906051999** [remotely-save/remotely-save#444]
## First: Android devide
- modify a md file
- choose the **remotely sync** 
- show the error info:
```
remotely-save-170***11354**：中断同步，同步来源=manual，出错阶段=syncing
text.md:Request failed, status 403
```
## Second: PC
- choose the **remotely sync** 
- show sync success
- show the modify content

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.3.34

### Version of Obsidian

1.4.16(114)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
用什么 webdav 服务器？

**Comment by 906051999** [comment]
> 用什么 webdav 服务器？

docker部署的bytemark/webdav:latest
http协议

**Comment by fyears** [comment]
depth header=1试试？

**Comment by 906051999** [comment]
> depth header=1试试？

设置了，目前状况是有些文件其实是同步成功了，但是一直会弹报错提醒
webdav的日志里会有不同文件请求时的报错`(13)Permission denied: [client 1**.*.*.1:*****] An error occurred while opening a resource.  [500, #0`

**Comment by fyears** [comment]
这里是不是有防火墙或者有限速或者有账号权限问题？

permission deny 很奇怪，没见过这个错误。

这个插件的原理是读服务器文件和本地的做对比，因此需要权限读取目录和所有子目录权限

**Comment by 906051999** [comment]
> 这里是不是有防火墙或者有限速或者有账号权限问题？
> 
> permission deny 很奇怪，没见过这个错误。
> 
> 这个插件的原理是读服务器文件和本地的做对比，因此需要权限读取目录和所有子目录权限

同样设备使用浏览器登录webdav就没问题。
有时候在obsidian上用正常，但是突然同步就开始报错，之后就恢复不了

**Comment by fyears** [comment]
浏览器登录，只是看一眼的话，也不会触发 webdav 限制嘛。插件会扫描文件列表做对比的，这里会有较多api请求

**Comment by fyears** [comment]
这个？ https://github.com/BytemarkHosting/docker-webdav

**Comment by 906051999** [comment]
> 这个？ https://github.com/BytemarkHosting/docker-webdav
> 

应该是的，我发的是docker官方库的查找名称
