### ISSUE TITLE
[Bug]: Failed to read the 'headers' property from 'ResponseInit': String contains non ISO-8859-1 code point

### ISSUE THREAD

**Issue by landandan** [remotely-save/remotely-save#447]
### What happened?

[2024-01-09T10:05:05+08:00] remotely-save-1704765905347：中断同步，同步来源=manual，出错阶段=syncing
[2024-01-09T10:05:05+08:00] ERROR! MESSAGE:
Error: 常用docker/: Failed to construct 'Response': Failed to read the 'headers' property from 'ResponseInit': String contains non ISO-8859-1 code point.
at eval (plugin:remotely-save:320:65306)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.3.34

### Version of Obsidian

1.5.3

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
用什么 webdav 服务器呢，文件名带中文？

**Comment by landandan** [comment]
> 用什么 webdav 服务器呢，文件名带中文？

使用docker ionelmc/webdav搭建的，文件名有包含中文

**Comment by fyears** [comment]
https://github.com/ionelmc/docker-webdav

**Comment by 1607941875** [comment]
用的可道云，也遇到了同样的问题

**Comment by fyears** [comment]
已经用可道云测试到问题。下一个版本会带上修复

**Comment by landandan** [comment]
> https://github.com/ionelmc/docker-webdav 这个吗
> 
> 这个怎么设置 uid？怎么暴露到公网上？怎么设置网址的？http://ip:port 就好了吗？

--env UID=$UID
电信网自带公网IP 使用nginx proxy  manager  https://xx.cc:port
