### ISSUE TITLE
[Bug]: onedrive 个人版 同步时报错

### ISSUE THREAD

**Issue by Sailingbon** [remotely-save/remotely-save#449]
### What happened?

同步时出现错误中断
报错内容如下：
remotely-save-1705398921186：中断同步，同步来源=manual，出错阶段=getting_remote_files_list

undefined is not an object(evaluating'e.fileSysteminfo.lastModifiedDateTime')

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.3.37

### Version of Obsidian

v1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
最新版应该修复了的
