### ISSUE TITLE
[Bug]: 阿里云S3同步报错

### ISSUE THREAD

**Issue by freezoc** [remotely-save/remotely-save#450]
### What happened?

原本通过阿里云oss能够正常同步，插件更新后无法同步。显示如图
![1705461091480](https://github.com/remotely-save/remotely-save/assets/20424296/217f2f57-98bc-4086-86cd-ece713f7ba17)
原region处填写内容为红色画圈部分：
![image](https://github.com/remotely-save/remotely-save/assets/20424296/dbf9596f-37c3-4b1e-a584-c68795b1a019)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.3.37

### Version of Obsidian

1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
oss-cn-hongkong-internal

**Comment by fyears** [comment]
region 不应该写域名呀，你们之前是看什么教程的？

**Comment by freezoc** [comment]
当时看的这篇，https://juejin.cn/post/7156922309733777422，之前用下来是没问题的。

**Comment by freezoc** [comment]
当时看的这篇 https://juejin.cn/post/7156922309733777422 去年4月份开始用，到近期插件升级前一直没什么问题的。

刚才把region改成oss-cn-hongkong-internal，好像还是不行。现在报错是这样
![image](https://github.com/remotely-save/remotely-save/assets/20424296/570929aa-40a3-41d9-8a3e-d1b65d77eb76)

endpoint填oss-cn-hongkong.aliyuncs.com应该没错吧

**Comment by fyears** [comment]
那就填没有 internal 后缀的呀

**Comment by freezoc** [comment]
感谢不厌其烦的解答

不过好像还是搞不定

在 endpoint 里填的 oss-cn-hongkong.aliyuncs.com

在 region 里尝试了 oss-cn-hongkong-internal 和 oss-cn-hongkong

但是重新设置并且check之后报错提示还是这样
![image](https://github.com/remotely-save/remotely-save/assets/20424296/f2d46770-8860-4c03-8666-0fe1c5c9a042)

还可能会有其他地方的设置导致出错吗？

**Comment by choi006** [comment]
你的region是oss-cn-hongkong

**Comment by choi006** [comment]
不应该使用内网域名

**Comment by choi006** [comment]
外网域名的前缀即为对应的region

**Comment by freezoc** [comment]
> 外网域名的前缀即为对应的region

大致明白你的意思

不过我上面想说的意思是，试过在 region 里填 oss-cn-hongkong，然后check。以及在 region 里填 oss-cn-hongkong-internal，然后 check。两种方式都还是会报同样的错误

**Comment by freezoc** [comment]
更新一下

我的 iOS 端与 windows 端同样的设置，插件版本为0.3.25，移动端obsidian版本为1.4.16（114）

在 region 处填写 oss-cn-hongkong-internal 或者 oss-cn-hongkong-internal.aliyuncs.com 然后check，都仍旧可以连接成功

**Comment by fyears** [comment]
> 然后把插件更新到0.3.37，region 处填写 oss-cn-hongkong-internal 或者 oss-cn-hongkong，可以连接成功（填写 oss-cn-hongkong-internal.aliyuncs.com 连接失败）


所以这个在 windows 是成功了还是失败了？在手机是成功了还是失败了？如果是一端成功另一端失败，能不能复制 data.json 或者扫描二维码或者复制导出链接试试是否可连接？

这里确实有点坑，我就更新了一下 aws sdk……

此外我没有阿里云账号，比较难测试，难顶

用这个，点开之后会有一个 copy 按钮：

![image](https://github.com/remotely-save/remotely-save/assets/1142836/92025d21-073e-4140-b231-20286ed6d5e5)

**Comment by choi006** [comment]
还有你不该使用内网地址

**Comment by choi006** [comment]
endpoint填oss-cn-hongkong.aliyuncs.com

**Comment by choi006** [comment]
region填oss-cn-hongkong

**Comment by moyongshi** [comment]
> 当时看的这篇 https://juejin.cn/post/7156922309733777422 去年4月份开始用，到近期插件升级前一直没什么问题的。
> 
> 刚才把region改成oss-cn-hongkong-internal，好像还是不行。现在报错是这样 ![image](https://private-user-images.githubusercontent.com/20424296/297310181-570929aa-40a3-41d9-8a3e-d1b65d77eb76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MjI3MzQsIm5iZiI6MTcwNTYyMjQzNCwicGF0aCI6Ii8yMDQyNDI5Ni8yOTczMTAxODEtNTcwOTI5YWEtNDBhMy00MWQ5LThhM2UtZDFiNjVkNzdlYjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAwMDAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZGU2OWY0ZjE0MWYyODZkM2VjMTIxZjQwNDdiYWE2NDQwYzM4ZTk4MTc1OTUwMmZkYzJkZDdiN2UxMDJjOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h0OvGxnm0RV8hN5SX__jtRWmEWYBYtx6USXzvkZcA3Y)
> 
> endpoint填oss-cn-hongkong.aliyuncs.com应该没错吧

我是用us-east-1也可以同步

**Comment by freezoc** [comment]
> 特意为你注册了阿里云香港节点。检查连接正常。同步也正常

感谢感谢

今天一早又试了下，什么设置都没调整，就连接成功了……

而且我也试了下region的两种填法，oss-cn-hongkong和oss-cn-hongkong-internal都能成功……见鬼了……

**Comment by freezoc** [comment]
> 所以这个在 windows 是成功了还是失败了？在手机是成功了还是失败了？

昨天是手机成功，windows不成功，不过今天一早就都成功了……

感谢相助，添麻烦啦

**Comment by geeklihui** [comment]
> region填oss-cn-hongkong

我遇到了和 po 主一样的问题，看的是同一篇教程，按照你说的（endpoint 地址教程和你说的一样）修改 region 就成功了
我这里是最新版 remotely save，也是升级后出现的问题，升级前没问题。
obsidian 本身是 mac 端，win 端晚点回家试一下。

**Comment by fyears** [comment]
这些楼上各位网友！

**Comment by l739217783** [comment]
感谢楼上各位解答，遇到同样问题，很久没更新
一更新从0.3.25版本升到0.4.16，没动配置发现链接不上了= = 

具体修改如下：

0.3.25版本配置如下（0.3.25可正常链接，0.4.16不行）：
Endpoint：oss-cn-shenzhen.aliyuncs.com
Region：oss-cn-shenzhen-internal.aliyuncs.com

0.4.16版本需要替换成如下：
Endpoint：oss-cn-shenzhen.aliyuncs.com
Region：oss-cn-shenzhen
