### ISSUE TITLE
[Bug]: plugin data.json file not being synced correctly

### ISSUE THREAD

**Issue by gdpdils** [remotely-save/remotely-save#452]
### What happened?

Hi,
I'm using Remotely-sync to keep in sync Obsidian on my two Mac and my iPhone. I use it with Dropbox.
So far the experience with the plugin is really good, thanks for you work!

Since I use many plugins, some of them written by myself and not yet published on the store, syncing the `.obsidian` folder is paramount to me. I've noticed that while it works nicely, it tends to have problem with the `data.json` within each plugin directory. That is, of course, the file that store the settings for the plugins. It's been constantly re-written and I keep on losing changes to it.

For instance, on a Macbook I set up a lot of icons for my files and folders with `https://github.com/FlorianWoelki/obsidian-iconize`, and as soon as I r-sync the valut on iOS the settings are lost for good.

It keeps on losing hotkeys settings as well. I'd love for you to check on this.

Thanks

### What OS are you using?

macOS, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

0.3.37

### Version of Obsidian

1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
maybe that's because data.json is usually not directly written by users and sometimes the "last modified time" runs into abnormal situations.

and maybe on device A you delete them then the deletions are synced into the device B

I hope in the near future a new release could resolve the conflicts more cleverly. i am planning on it
