### ISSUE TITLE
Connectivity check fails with more than one webdav vaults – but sync works!

### ISSUE THREAD

**Issue by franztv82** [remotely-save/remotely-save#453]
### What happened?

1. Create vault no. 1.
2. Config connection to webdav server no. 1.
3. Push Check Connectivity button --> "Great! The webdav server can be accessed".
4. Sync vault no. 1 --> sync works.

5. Create vault no. 2.
6. Config connection to webdav server no. 2.
7. Push Check Connectivity button:

![check_failed](https://github.com/remotely-save/remotely-save/assets/93776391/092f1831-4071-4e73-8e5e-e43af41493b3)

**But: Sync works!**

8. Enter vault no. 1 again.
9. Push Check Connectivity button again.
10. Result: see 7, error while checking, **but: Sync works!**

No problems on Windows 11 with same vault and server configuration.

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.3.37

### Version of Obsidian

1.4.16 (114)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
i have no clues on it... let me try to reproduce it when i have time.

and is there any differences (configurations, etc) between server 1 and 2?

**Comment by franztv82** [comment]
Thank you very much.
Both webdav servers are based on Apache/2.4.54 (Ubuntu). They are running with the same configuration (only differences are TLD and credentials).

**Comment by franztv82** [comment]
This behaviour is gone since update to 0.3.38.
