### ISSUE TITLE
[Bug]: Non emtpy folders cause error 404 with a Concurrency of 1

### ISSUE THREAD

**Issue by FelixGut** [remotely-save/remotely-save#456]
### What happened?

I tried manually syncing a new Vault via WebDav (concurrency set to 1 to match some server-side settings). It successfully synced one file before aborting with a 404 error. The console output shows that it attempted to sync files nested in a folder before the folder (file structure) was synced.
This can be circumvented by either syncing the folder while it is still empty first or by increasing the concurrency.

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (NextCloud)

### Version of the plugin

0.3.37

### Version of Obsidian

v1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
fixed in 0.3.38
