### ISSUE TITLE
[Bug]: remotely-secure-1705740530828:中断同步，同步来源=manual，出错阶段=checking_password

### ISSUE THREAD

**Issue by vsnote** [remotely-save/remotely-save#457]
### What happened?

PC端配置一样，同步是正常的，IOS 检查可否连接也是成功的。

![ae513864698bf73167ab8ae953be2e2](https://github.com/remotely-save/remotely-save/assets/8895379/319f4c25-09be-406d-ad9b-4da59e55dd98)

同步的时候报错

![9a92f83db0c14a3e6fc91c6325aed8e](https://github.com/remotely-save/remotely-save/assets/8895379/af6ce25a-8d4c-47e2-8ecb-9e72b0d481f0)

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (坚果云 JianGuoYun/NutStore)

### Version of the plugin

0.4.39

### Version of Obsidian

1.4.16（114）

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by vsnote** [comment]
是因为我一开始配置了端到端加密的密码，后面改成空之后才会出现这个情况

**Comment by Jonas266** [comment]
我也遇到了一样的问题，但是我没有配置端到端加密的密码  我是使用macos端出现的
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/64022846-13c3-43cd-8554-22096cb3cd8c">

**Comment by Jonas266** [comment]
> 我也遇到了一样的问题，但是我没有配置端到端加密的密码 我是使用macos端出现的 <img alt="image" width="1024" src="https://private-user-images.githubusercontent.com/48699655/362348835-64022846-13c3-43cd-8554-22096cb3cd8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NTg4NzUsIm5iZiI6MTcyNDg1ODU3NSwicGF0aCI6Ii80ODY5OTY1NS8zNjIzNDg4MzUtNjQwMjI4NDYtMTNjMy00M2NkLTg1NTQtMjIwOTZjYjNjZDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE1MjI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2OGJlNzZjMWU2MWUyYzNjNTI2ODUwNjQ2MWY4MjczZjFhZjk3ODZmMzJiNDY1NWIyYjgxNTkwMWNjMDQyYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0p6XAviHmlZNr3NJKLm2dZ0sIu1EVsM3wuiwbZXAoiY">

删除插件 重新设置过后解决了

**Comment by fyears** [comment]
> 是因为我一开始配置了端到端加密的密码，后面改成空之后才会出现这个情况

每次改密码，都要重新清空云端上已有的加密文件。
