### ISSUE TITLE
[Bug]: Error while getting remote files list, can't sync on desktop using the same exact settings on other devices where it works

### ISSUE THREAD

**Issue by oyes77** [remotely-save/remotely-save#458]
### What happened?

![image](https://github.com/remotely-save/remotely-save/assets/53545025/716b5535-8488-446a-8dcc-cf3da283d918)
I have the exact same region on my other devices (us1.storj.id) and credentials, they work but my desktop (win11) obsidian doesn't sync.
I'm not that tech savvy regarding servers so please be patient with me, thanks

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (Storj)

### Version of the plugin

0.3.37

### Version of Obsidian

1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by oyes77** [comment]
Update: tested updating the plugin on other devices from 0.3.25 to the newer version and got the same error, so It seems it's caused due to the new version, is there a way to fix that or install the old version?

**Comment by fyears** [comment]
could you please change the region to `us1` and try again? thanks!
