### ISSUE TITLE
[Feature Request]: Better deletion mechanism

### ISSUE THREAD

**Issue by jerrygreen** [remotely-save/remotely-save#459]
### What feature are you suggesting?

Current deletion mechanism doesn't fit my use-case, here's why. I have two devices: Desktop PC and mobile phone.

- On desktop, I have setup Nextcloud, where it's connected to my file system. I'm opening a local folder inside Obsidian, all the syncs are automatically handled out of the scode, by Nextcloud.
- On mobile, I have this plugin, Remotely Save, which is specifically setup to sync with Nextcloud via webdav. It kinda works except – it cannot handle deletions properly. If I delete files on desktop, then on my mobile device it just doesn't get deleted because it's solely relying on `_remotely-save-metadata-on-remote`, so it's pushing this deleted file into Nextcloud again. Damn.
- *I also have Nextcloud server, but it doesn't do much, just providing webdav for others to synchronise

I don't know _exactly_ what the better option would be but have a hunch: the plugin should somehow understand that the file was already in webdav (Nextcloud or whatever). For this, instead of comparing synced data to local files directly, the plugin should probably build some file tree from the last synced data (i.e. cache), and if upon syncing again if it isn't finding a file in a new sync while it's present in cache and in local files, – that means it got deleted from within Nextcloud, therefore should be deleted from local files. The new sync data becomes the new cache, problem solved.

I know the deletions are stored within `_remotely-save-metadata-on-remote` and should be transferred between all the devices, thus it has to be among normal files. But with this new approach where instead of deletions we store file-tree, metadata can be stored just locally – in plugin's directory. Which is good, means less clutter inside user files. Plus, it should solve my use-case.

For more visual understanding, here's are all the possible states:

| State  | Explanation  |
|---|---|
| File in sync, in cache, in local | nothing deleted; do content change comparison as normal |
| File in sync, in cache, not in local | deletion initialized by local change, send deletion to webdav |
| File in sync, not in cache, in local | possible conflict, but due to complexity of conflict resolution, might as well just get the sync data from server to local |
| File in sync, not in cache, not in local | file created from within webdav, just copy it to local files |
| File not in sync, in cache, in local | file deleted from within webdav, just delete it from local files |
| File not in sync, in cache, not in local | file got deleted from both local and on webdav server, just update cache and do nothing |
| File not in sync, not in cache, in local | file created from within local device, send file to webdav |
| File not in sync, not in cache, not in local | impossible event; listing it just for the full picture |

*file in sync - means file is present in new data that is currently coming from synchronisation
**file in cache - means file present in data that is cached from previous sync
***file in local - means file present physically in local files in Obsidian

And I know I mention «just» too often, just do this, just do that, like it's some simplest problem ever. I understand this is in overall a complex problem, but most of the complexity is of course resides in conflict resolution. At while deletions can be handled better than current approach, without involving too much of the complexity like conflict resolution – that's what I'm trying to say and to show here. I don't know much of the codebase, so for me it will be quite difficult to make corresponding changes, so all I can do is this table and sentences. Thanks.

### What remote cloud services are you using, or suggesting adding the feature to?

webdav (NextCloud)

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Yes! Yes! Yes!

Your idea is exactly the same as my initial thoughts after reading some other open source implementations. See [sync_algorithm_v3](https://github.com/remotely-save/remotely-save/blob/master/docs/sync_algorithm_v3.md) . I am so glad that you (as a remotely-save user ) raise up the same idea! LOL.

Good news: implementing. Stay tune!

**Comment by jerrygreen** [comment]
I don't want to look rude in any way, but can I ask you politely to not close this issue until it's actually solved?

I'm not using the extension currently, using just iCloud currently as alternative.
But I would like to keep an eye if anything changes here, and willing to switch to it if it handles deletions properly.
Just in case, I checked latest `0.3.40` version, it's still creating those deleted files, i.e. the issue is not solved yet.

Thanks in advance. @fyears

**Comment by fyears** [comment]
sure. i am developing on a branch syncv3 and everything seems to work now. so please expect the new version in a few days

**Comment by fyears** [comment]
[A new beta version 0.4.1](https://github.com/remotely-save/remotely-save/releases/tag/0.4.1) has been released but you have to install it via [BART](https://github.com/TfTHacker/obsidian42-brat). It comes with a better deletion detection. This issue should be solved.
