### ISSUE TITLE
[Bug]: ios14.7.1 failed to load plugin remotely-save with 0.3.37&0.3.38

### ISSUE THREAD

**Issue by sorhyu** [remotely-save/remotely-save#460]
### What happened?

After I installed the plugin, clicked enable and it was prompted that failed to load plugin remotely-save.

### What OS are you using?

iOS 14.7.1

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.3.37&0.3.38

### Version of Obsidian

1.4.16(114)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
sorry ios 14 is too old and i don't have device to debug on
