### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by erikaemma** [remotely-save/remotely-save#462]
### What happened?

Why the plugin always uploadLocalToRemote?
I have install the plugin, the first time I installed it was my first time using Obsidian, and the second time I had to reinstall and import data because my phone broke down.
I found that every time I need to first import data from PC into my phone, and then let the plugin synchronize it, and every time it is uploadLocalToRemote, which I think is correct because the newly copied file has a newer date than the one on the Dropbox. But why not compare the hash of the file first before making a judgment?
During the recent reinstallation, I tried to create an empty valut, but it could only synchronize (or download, downloadRemoteToLocal) a portion of the files and then failed. If I tried to synchronize again at this time, the operation would change to uploadLocalToRemote. If the files were complete, it would be fine, otherwise, the files that failed to synchronize last time would be uploaded.

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

0.3.38

### Version of Obsidian

1.4.16 (114)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> But why not compare the hash of the file first before making a judgment?

because initially i don't introduce this complicated algorithm.

> ... portion of the files and then failed. If I tried to synchronize again at this time, the operation would change to uploadLocalToRemote

because the file was failed so the plugin needs to upload the file again? i think that's normal?

**Comment by erikaemma** [comment]
> > But why not compare the hash of the file first before making a judgment?
> 
> because initially i don't introduce this complicated algorithm.
> 
> > ... portion of the files and then failed. If I tried to synchronize again at this time, the operation would change to uploadLocalToRemote
> 
> because the file was failed so the plugin needs to upload the file again? i think that's normal?

I am using MWeb on my iPhone and it does not have this issue.

I just tried Dropsync on Android and there were no issues with it

Among them, MWeb can automatically distinguish whether it is an upload failure or a download failure when it fails, and execute the corresponding plan when trying again. Dropsync is no exception.

In addition, I also found a very useful piece on Dropsync: download to internal storage instead of SD card, Android will force the file save date to be consistent with the cloud date. I don't think remote save has this feature.

**Comment by fyears** [comment]
Mweb and dropsync are standalone apps, which can fullly utilize  capabilities of OS to do deeper optimizations. Moreover they are **paid**, assuming full-time developed, and they lasts longer than remotely save.

Remotely save, on the other hand, is a **free** **part-time** **open source** plugin of Obsidian. It mainly focuses on supporting files sync inisde Obsidian, especially on iOS. It is limited by: the api of Obsidian, the js performance, the browser limitations, the http api limitations by remote services, etc. 

I am not surprised that mweb and dropsync are better than remotely save in some aspects.

That being said, I am optimizing sync algorithm these days. Hopefully every users will enjoy it later.


> will force the file save date to be consistent with the cloud date. I don't think remote save has this feature.

Remotely save **should** already support this (from the very beginning), unless there are some bugs.
