### ISSUE TITLE
[Feature Request]: OSS方式，可以同步“.zotero”系列文件么？

### ISSUE THREAD

**Issue by lcwalnut** [remotely-save/remotely-save#463]
### What feature are you suggesting?

使用OSS方式【阿里云OSS】，可以同步下“.zotero-*”系列文件么？
目前好像所有“.”开头的文件都不能同步

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
不可以，

1.首先目前所有点开头的都是隐藏文件，不太支持读取
2.其次这个是数据库文件，一般来说要整个同步，否则很容易出问题

建议用 zotero 自带功能同步哈
