### ISSUE TITLE
[Bug]: Failed to load plugin remotely-save in iOS obsidian v1.4.16

### ISSUE THREAD

**Issue by advancejar** [remotely-save/remotely-save#464]
### What happened?

Failed to load plugin remotely-save in iOS obsidian v1.4.16

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.3.38

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by advancejar** [comment]
在第三方市场里安装的

**Comment by advancejar** [comment]
现在没法访问里面的隐藏文件夹，请修正下市场里的，谢谢

**Comment by fyears** [comment]
什么叫第三方市场？哪里的？

ios 版本是什么？

什么叫访问不了隐藏文件夹？是特指 .obsidian 还是什么？

**Comment by advancejar** [comment]
iphone12 iOS版本14.6
安装方式：obsidian-第三方插件-社区插件市场-浏览-安装

在2023-04-13日安装的remotely save还是行的，有同步显示1-8步的，刚更新的新版本是显示1-2步
安装通过苹果自带app“文件”可以访问到obsidian文件夹及下面的笔记和附件等信息
插件是安装到同目录的.obsidian/plugins/xxx目录，在“文件”app里这个目录是隐藏文件，我想把remotely save版本换成在2023-04-13日安装也无法实施。

**Comment by advancejar** [comment]
我拿macos拷了东西出来，文件都没缺，应该是程序问题。重新拷了0.3.2.5进去，就没问题了。其他没macos的人就没法解决这个问题。

**Comment by fyears** [comment]
好的，感谢。其实另一种方法是用 bart 插件，它可以指定 remotely save 的版本安装。

其实我想修复这个问题，但是没有旧的手机，实在无法 debug
