### ISSUE TITLE
[Feature Request]: webdev sync to user defined folder

### ISSUE THREAD

**Issue by A-sunny-boy** [remotely-save/remotely-save#465]
### What feature are you suggesting?

Thanks for remotely-save, i can safely save and sync docs on my own NAS. 

At present, webdev sync cannot choose the repo position on webdev device, the default is webdev/repo_name. 

Hope to add this feature and user could assign the root path for remotely-save, which will keep nas clean and easy to manage. 

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
firstly make a backup of your vault

secondly change your webdav server as : http://.../webdav/sub/sub/sub

and try.

in other words, you should be able to configure the subfolders by setting the web address
