### ISSUE TITLE
[Bug]: 威联通Quobject的S3对象存储无法使用

### ISSUE THREAD

**Issue by hxer520** [remotely-save/remotely-save#466]
### What happened?

我使用的S3存储是威联通自带的QuObjects。
用插件配置好后显示可以正常访问存储桶，但是同步的时候却不行，看到存储桶里有笔记的文件夹，但是md格式的文件无法同步，且调试模式显示以下内容：

![image](https://github.com/remotely-save/remotely-save/assets/12802662/ff4fbba3-4ad0-41fe-9caf-aae367905004)

![image](https://github.com/remotely-save/remotely-save/assets/12802662/5235c49c-975a-4291-9d7b-257ebe973983)

已确定内容： 存储桶测试为可用状态，JOPLIN也可正常同步
这个是存储桶公开桶的访问链接：
https://fengtuan.work:8081/v1/AUTH_QuObjects/Obsidian/5%E8%81%8A%E5%A4%A9%E5%9B%BE%E7%89%87.jpg

![image](https://github.com/remotely-save/remotely-save/assets/12802662/de501d72-1937-4c40-8f58-45461dae8427)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3

### Version of the plugin

0.3.38

### Version of Obsidian

1.15

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
首先确认一下你这个链接是可公开的对吧（不行的话记得修改掉）

其次没什么头绪，网上搜索，503应该是请求太多了，试试去 remotely save 设置页，将 parts concurrency 和 concurreny （两个不同设置来的）降低，看是否 ok？这里控制了并行度

**Comment by hxer520** [comment]
@fyears 
我的分块并行度是
![image](https://github.com/remotely-save/remotely-save/assets/12802662/074e500f-1ab3-4d6e-96b1-7b53ff3e7896)

![image](https://github.com/remotely-save/remotely-save/assets/12802662/23a8af34-dd8c-4ff2-93e5-92b534e2fb3f)

并行度也已经调到最大试过，最小试过，默认也试过

后台bug日志显示都是一样的：

```
"1.1【WEB项目】/服务器管理.canvas": {
      "key": "1.1【WEB项目】/服务器管理.canvas",
      "existLocal": true,
      "mtimeLocal": 1702346480026,
      "mtimeLocalFmt": "2023-12-12T10:01:20+08:00",
      "sizeLocal": 1546,
      "existRemote": false,
      "decision": "uploadLocalToRemote",
      "decisionBranch": 4
```
![image](https://github.com/remotely-save/remotely-save/assets/12802662/d401a0bd-87c9-4282-93f7-cbf14edf965e)

PS：链接是可公开的，是为了佐证这个存储库是可正常访问

我在思考是不是因为remotely save 对QuObjects的适配问题呢？  joplin是可以正常同步的，而Obsidian只可以同步文件夹目录，但是无法同步MD，我也没头绪~

**Comment by fyears** [comment]
黄色提示是没关系的，不影响成功失败。

从你原来帖子的失败的提示来看，是不能同步文件夹的样子。

方便新建vault，然后只新建一个文件夹，（空的即可），然后同步看是否可以吗？

**Comment by fyears** [comment]
对于文件夹，插件会建立一个 object，key 是 aaa/ 结尾有斜杠

**Comment by hxer520** [comment]
我已经测试过了  还是出现一样的情况
![image](https://github.com/remotely-save/remotely-save/assets/12802662/e3aa79b8-ace8-4b32-8c69-3ea19bbcccfd)
![image](https://github.com/remotely-save/remotely-save/assets/12802662/b9a233ff-3664-4729-89da-0e719483f99d)
 我新建的一个测试仓库 第一次能拉取了

**Comment by fyears** [comment]
那就是威联通不支持结尾有/符号的 object...

**Comment by yanliang-wang** [comment]
> 首先确认一下你这个链接是可公开的对吧（不行的话记得修改掉）
> 
> 其次没什么头绪，网上搜索，503应该是请求太多了，试试去 remotely save 设置页，将 parts concurrency 和 concurreny （两个不同设置来的）降低，看是否 ok？这里控制了并行度

我试了将并行度修改为1就没有报503的问题了，谢谢

**Comment by fyears** [comment]
> 对于文件夹，插件会建立一个 object，key 是 aaa/ 结尾有斜杠

所以这个其实是成功了还是失败了？又或者去威联通的管理端可以看到这个 object 吗

**Comment by hxer520** [comment]
我将并行度修改为1后 还是会出现一样的问题
![image](https://github.com/remotely-save/remotely-save/assets/12802662/aefd96e8-a818-43e6-a632-bd4268235dc8)

是属于失败的状态，威联通还是只能同步文件夹 里面无MD文件

**Comment by hxer520** [comment]
> 那就是威联通不支持结尾有/符号的 object...

如果是威联通不支持的情况下，是否remotely并不能适配威联通的S3服务呢？

**Comment by fyears** [comment]
这里应该反过来说，威联通没有正确地实现 s3 协议，其他 aws/腾讯云/阿里云/minio/storj 都是可以传带 / 结尾的 object 的。

我想想怎么解决吧，不过我得先找人借威联通来 debug。这块优先级比较低。

一个绕过的方式是，使用 remotely save 加密，加密之后没有了文件夹概念。代价就是无法直接网页端明文看到文件了

**Comment by hxer520** [comment]
期待F大的debug效果~

**Comment by fyears** [comment]
0.4.17 已支持
