### ISSUE TITLE
[Bug]: 工作区的同步存在部分异常【使用数据桶作为同步工具】

### ISSUE THREAD

**Issue by hellofreud** [remotely-save/remotely-save#467]
### What happened?

感谢作者进行了更新，遇到了一些以前没有存在的bug，期望能够帮助定位到问题。
更新到0.3.38版本后，插件的删除似乎可以同步到不同设备，但是关于obsidian本身的设置并不能正常同步，目前遇到的问题有以下几个
1、存档新建笔记的文件夹进行修改后，总是会被重置为一个很早以前设置的文件夹
2、最新的布局总是被重置为更新到0.3.38之前的最后一个布局，怀疑是.obsidian文件夹同步出了问题
3、开启保存时同步（实验性质）后，右上角总是会出现同步中的提示，问题在于，部分文件名并不在自己的文件列表中，可能很早以前有，但最新的文档中是没有的。例如我很早以前运用过百度云进行同步，我发现有一次的提示中，文件名包含了baiduyun同步的过程文件，但通过everything检索并没有对应的文件存在

再次感谢

### What OS are you using?

Windows, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (腾讯云 COS Tencent Cloud COS)

### Version of the plugin

0.3.38

### Version of Obsidian

1.5.3（安装程序版本1.4.16）

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by hellofreud** [comment]
此外，还有个问题关于插件同步，今天删除了一个插件又安装了一个插件，手机端打开后应该是有1秒后自动同步的，md文件已经正常同步，但插件并未同步，进行一次手动同步后，插件成功同步过来了

**Comment by hellofreud** [comment]
![image](https://github.com/remotely-save/remotely-save/assets/17267947/27bdba1b-490e-40db-86ae-7f3bcc7a6904)

截到图了，目前并没有使用百度云进行同步

**Comment by fyears** [comment]
一个一个来，

同步obsidian文件夹问题，可能是文件夹的更新时间不正常。你可以手动去s3上手动删除这个文件夹，然后删除 .metadata-remotely-save.json 文件

百度云文件，提示的意思是之前删除过，这里保留删除记录，没问题。

更好的同步算法在路上了，再等等吧
