### ISSUE TITLE
[Bug]: Puts the remote deletes back 

### ISSUE THREAD

**Issue by gerroon** [remotely-save/remotely-save#472]
### What happened?

I use `rclone.exe serve webdav --addr IP:8080 "C:\SYNC"` to serve a local webdav server. From plugin  to webdav sync seems to work, however I cant get the changes I do on the webdav end to be reflected back in my obsidian via this plugin.

Basically if I delete files on the webdav side using file explorer, this plugin puts those files back on the server after a sync.

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.3.38

### Version of Obsidian

Windows 1.5.3 

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
right bow the only way is deleting the files also in the vault.

a new algorithm is being developed and the issue will be resolved. please stay tuned.

**Comment by DarkWiiPlayer** [comment]
Since you said "stay tuned", could this issue be re-opened until the new feature is actually implemented? That way it would be possible to subscribe and get a notif once it's closed for good 😉

**Comment by Micha12323** [comment]
The same happens when you sorted one file into a folder. Just to mention that 😊

**Comment by fyears** [comment]
[A new beta version 0.4.1](https://github.com/remotely-save/remotely-save/releases/tag/0.4.1) has been released but you have to install it via [BART](https://github.com/TfTHacker/obsidian42-brat). It comes with a better deletion detection. This issue should be solved.
