### ISSUE TITLE
[Feature Request]:  建议打开Wiki， 把配置教程归档下

### ISSUE THREAD

**Issue by valuex** [remotely-save/remotely-save#473]
### What feature are you suggesting?

建议打开Wiki， 把配置教程归档下。
[论坛](!https://forum-zh.obsidian.md/t/topic/5291) 中这句话说的不是很清晰。
注意的是**创建的笔记库的名称要和想要同步的库的名称一样。**
换成【各个终端（手机端、PCB端）的Valut的名称需一致】会不会更好些。

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
论坛的文档不知道哪一个，我好像没写过中文的。不过，总之，先在 READEME 里加上了

https://github.com/remotely-save/remotely-save/commit/f6ea9938d16b53df359766cc3e6d61349918b3a1
