### ISSUE TITLE
[Bug]: OneDrive（个人版）Auth Fail 鉴权失败

### ISSUE THREAD

**Issue by ChrisGray0626** [remotely-save/remotely-save#474]
### What happened?

![image](https://github.com/remotely-save/remotely-save/assets/41218402/80107a2f-6181-46b1-804b-253d02005d2e)
点击后 Obsidian 消失，但是并没有主动跳转。手动访问链接，完成鉴权后，返回 Obsidian 时返回如下报错：

```
OneDrive的回调请求有点异常。您是否拒绝了鉴权？
Error: Request  failed, status 400
```

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.3.38

### Version of Obsidian

1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by ChrisGray0626** [comment]
重装之后，问题解决。但问题并没有定位到。

**Comment by fyears** [comment]
估计就是网络问题了。插件的授权部分没有改动过。
