### ISSUE TITLE
[Bug]: 与nas部署的minio配合，开启后，图片不能正常显示。

### ISSUE THREAD

**Issue by leoleelxh** [remotely-save/remotely-save#475]
### What happened?

与nas部署的minio配合，开启后，图片不能正常显示。
大家有遇到这个问题嘛？
图片原来存在于图床里面的。
未开启同步时是正常显示的：
![image](https://github.com/remotely-save/remotely-save/assets/4277749/5c86ddfd-c5ea-4a00-b999-30308a77e87c)
链接成功：
![image](https://github.com/remotely-save/remotely-save/assets/4277749/ed92eef0-7a0c-4e63-966c-f5656faa64c3)

同步后就变成这样了：
![image](https://github.com/remotely-save/remotely-save/assets/4277749/395da822-3d98-42f8-b14b-88bfe1529602)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (MinIO)

### Version of the plugin

0.3.38

### Version of Obsidian

1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by leoleelxh** [comment]
需要删除此目录的文件，卸载插件，重新打开ob，才能恢复正常。
![image](https://github.com/remotely-save/remotely-save/assets/4277749/9afa641b-19ae-4583-9a9c-d343b672dccf)

**Comment by fyears** [comment]
图片本来是图床里的话，本插件根本不会动图片内容……而且插件也不会改文件内容，因此不会破坏链接的。建议看看是不是其他问题或者什么设置原因。

> 需要删除此目录的文件

截图这个目录，不知道是什么来的，本插件也不会生成。建议排查一下 nas 设置

**Comment by leoleelxh** [comment]
> 图片本来是图床里的话，本插件根本不会动图片内容……而且插件也不会改文件内容，因此不会破坏链接的。建议看看是不是其他问题或者什么设置原因。
> 
> > 需要删除此目录的文件
> 
> 截图这个目录，不知道是什么来的，本插件也不会生成。建议排查一下 nas 设置

是的，挺神奇的，思源笔记同样用这个部署的s3没问题。
文件夹是ob 在系统appdata 的文件夹，有可能是ob 的问题吧。
