### ISSUE TITLE
[Feature Request]: 增加s3 反向代理配置

### ISSUE THREAD

**Issue by adensW** [remotely-save/remotely-save#476]
### What feature are you suggesting?

使用aliyun 的 OSS ,并且有一个aliyun的ECS服务器可以走内网通道节省流量.
是否可以增加一个反向代理的配置.使用反向代理的url地址替换掉s3的endpoint生成的地址.

### What remote cloud services are you using, or suggesting adding the feature to?

S3 (阿里云 OSS Alibaba Cloud OSS)

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
这里建议自行搭建服务器并设置好暴露的网址。插件本身做不了这事

**Comment by adensW** [comment]
抱歉.我描述的不够详细.我现在就已经使用nginx在内网环境搭建了一个反向代理,由于这个buket是私有读写的,需要一些认证和校验.如果直接使用反向代理的地址校验会失败.需要使用aliyun的oss地址进行签名操作,但是发送的url就需要改成反向代理的地址.目前s3Client是直接发送到endpoint的地址的.
我可以提pr增加这个功能.
