### ISSUE TITLE
[Bug]: EISDIR:illegal operation on a directory

### ISSUE THREAD

**Issue by OvenGuo0224** [remotely-save/remotely-save#477]
### What happened?

我使用的是阿里云的OSS对象存储，测试链接没有问题，当我开始同步文件的时候报错，我文件夹的权限没有问题
<img width="395" alt="image" src="https://github.com/remotely-save/remotely-save/assets/16708636/5ab72344-d870-4e98-831c-3d73f6e51dc4">

### What OS are you using?

macOS

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3

### Version of the plugin

0.3.38

### Version of Obsidian

v1.5.3

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
https://stackoverflow.com/questions/20417118/using-node-js-i-get-error-eisdir-read

这个 `Java学习`是文件还是文件夹？有没有改过？重启 obsidian 试试是否 ok？

**Comment by OvenGuo0224** [comment]
是文件夹，作为obsidian的valut使用
<img width="912" alt="image" src="https://github.com/remotely-save/remotely-save/assets/16708636/a7b20bd5-b39d-44ea-990e-1eb6fd8ab8d2">

**Comment by fyears** [comment]
rs 配置是怎样的呢

**Comment by fyears** [comment]
新建一个测试vault，随便新建一些非空文件，可以复现这个问题吗？

**Comment by fyears** [comment]
去 rs 设置页，将 log level 改成 debug，触发一下同步，看出错再哪一步？

**Comment by OvenGuo0224** [comment]
<img width="852" alt="image" src="https://github.com/remotely-save/remotely-save/assets/16708636/f3fa475d-ac10-4b9e-86f4-d03403482db4">

**Comment by OvenGuo0224** [comment]
新创建的vault也复现了

**Comment by OvenGuo0224** [comment]
<img width="815" alt="image" src="https://github.com/remotely-save/remotely-save/assets/16708636/4dc80716-e621-491f-a20a-d557604cf151">
<img width="332" alt="image" src="https://github.com/remotely-save/remotely-save/assets/16708636/e5bd7927-e3c0-4242-bc4a-921ec8d66818">

**Comment by OvenGuo0224** [comment]
我找到问题了
<img width="841" alt="image" src="https://github.com/remotely-save/remotely-save/assets/16708636/bc20f60f-5e00-4251-8e7b-a47f75705b7b">
我这里配置了路径
导致了上述问题
现在配置改为空 使用根路径就可以正常同步了

**Comment by fyears** [comment]
路径试试格式 `aaa/bbb/ccc/`

**Comment by OvenGuo0224** [comment]
> 路径试试格式 `aaa/bbb/ccc/`

这个格式可以
