### ISSUE TITLE
[Feature Request]: Can WebDAV support storage in a specified path?

### ISSUE THREAD

**Issue by smilesxsy** [remotely-save/remotely-save#478]
### What feature are you suggesting?

If you want to specify a specific path for webdav, you can only store it in the root directory

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
please try to add sub folder paths directly in your webdav web address. something like `https://example.com/dav/sub1/sub2` should work
