### ISSUE TITLE
[Feature Request]: Small UX improvments

### ISSUE THREAD

**Issue by ZeroEkkusu** [remotely-save/remotely-save#481]
### What feature are you suggesting?

Hi, @fyears,

Here are three suggestions regarding the new UX:

<br>

- The status bar on desktop says: `Synced less than a minute ago`
- I'd find it useful if it transitioned from `Syncing...` → `Synced just now` → `Synced less than a minute ago`

<br>

- The console logs are: `1/2 Remotely Save Sync Start Running (destination)` and `2/2 Remotely Save finish!`
- Make it prettier if setting `Console Log Level` is set to `info`: change to `🔄 Remotely Saving` and `✅ Remotely Saved`

<br>

As always, thanks for the amazing plug-in.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Merged #492 with release 0.3.40

And I agree with @vijayasantham12 not modifying notifications. Because emoji may not show up nicely especially on Linux.
