### ISSUE TITLE
[Bug]: 同步的时间太漫长，希望缩短同步的时间

### ISSUE THREAD

**Issue by FEI352** [remotely-save/remotely-save#482]
### What happened?

不知道为啥，我明明只修改了一个文件，但是同步的时间从开始到完成却需要3分20秒。

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.3.38

### Version of Obsidian

1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by FEI352** [comment]
插件是不是会把所有的文件都给扫一遍，不然不至于这么慢。

**Comment by fyears** [comment]
会把所有文件的元数据（例如创建日期等）扫一次，但不会扫内容。试试同步一次之后的增量同步吧，以及检测一下网速

**Comment by FEI352** [comment]
> 会把所有文件的元数据（例如创建日期等）扫一次，但不会扫内容。试试同步一次之后的增量同步吧，以及检测一下网速

插件第一次同步的时候会上传所有的元数据，第二次同步随便修改一个原本的文件还是会卡在4444/4445 这样我这个3分钟的时间就是第二次同步造成的，第三次同步创建了一个新的文件，已经是增量同步了，不过我还是觉得很慢，中间我换到过其他的同步，感觉没有以前文件少的时候用的快。
  
  1. 不打开“准确的文件修改时间”同步一次需要45s，开了V2rayN
  2. 不打开“准确的文件修改时间”同步一次需要45s59，关闭V2rayN
  3. 打开“准确的文件修改时间”同步一次需要1minute21s，开了V2rayN
  4. 打开“准确的文件修改时间”同步一次需要1minute16s，关闭V2rayN

**Comment by fyears** [comment]
> 插件第一次同步的时候会上传所有的元数据

这里描述并不精确。

实际上，每次同步都会扫描本地所有元数据和**s3上的所有元数据**，因为插件无法保证网盘上有没有来自别的地方的变更。

> 打开“准确的文件修改时间”
这里还有额外的请求，因为s3 里面要逐个 object 读取里面的信息。


此外，文件内容的上传下载按道理是增量的。

**Comment by fyears** [comment]
你这里是 4555 个文件？按道理也不是十分多……确认网络没问题吗

**Comment by FEI352** [comment]
> 你这里是 4555 个文件？按道理也不是十分多……确认网络没问题吗

你把我和其他人记混了吧，我从来没有说过同步有过十分多。第一次同步的时候反而很快，比官方同步体验好多了，五六分钟就能上传完所有的文件。官方的反而要好几个小时。

网络应该是没问题的，也是增量同步，我感觉应该是获取元数据的时间花费的长。

![Pasted image 20240203010807](https://github.com/remotely-save/remotely-save/assets/104716040/0ad4b233-15fa-4123-be5f-79a6b1231842)

**Comment by YIRU69** [comment]
@fyears 我正要反馈相同的问题，修改了一个文件，同步都非常的慢，我的文件大概只要3000+个

我个人对比了 https://github.com/sboesen/remotely-sync 和 https://github.com/remotely-save/remotely-save 两者插件的速度，很明显，在3000+ 文件的测试下， remotely-sync 的速度要比 remotely-save 的速度要快。

这个问题我也提到过，如果更改了很少的文件，同步过于的长是相当恼人的。而且如果我使用公司的电脑（配置不好的电脑），这个时间还更加的长，可能长到5分钟以上！

如果手机在同步中，需要那么长时间，您可以想象一下，自己看着自己的手机，一遍遍的电亮屏幕（如果ob 应用不是前台，同步就会中止）

肯请您重视这个问题！

**Comment by YIRU69** [comment]
> 你把我和其他人记混了吧，我从来没有说过同步有过十分多。第一次同步的时候反而很快，比官方同步体验好多了，五六分钟就能上传完所有的文件。官方的反而要好几个小时。

我是同样的，我认为在第一次同步，不需要遍历检查文件的“状态”，主要的时间用在了文件的对比上。

**Comment by FEI352** [comment]
> > 你把我和其他人记混了吧，我从来没有说过同步有过十分多。第一次同步的时候反而很快，比官方同步体验好多了，五六分钟就能上传完所有的文件。官方的反而要好几个小时。
> 
> 我是同样的，我认为在第一次同步，不需要遍历检查文件的“状态”，所以速度很快，而速度慢应该主要的时间用在了文件的对比上。

其实这个速度不算慢，我用OneDrive+FolderSync，FolderSync同步一次需要7分钟，增加MD校检的话会延长到12分钟，但是FolderSync不需要一直在前台啊。

我觉得Rmotely Save 适合PC端同步，特别是文件小于1000个，如果文件多了，就算是S3用起来也非常的一般。
