### ISSUE TITLE
[Bug]: mac 段新建的笔记，只有一个标题内容为空笔记不能同步到安卓手机端，

### ISSUE THREAD

**Issue by m1509001** [remotely-save/remotely-save#485]
### What happened?

[Bug]: mac 段新建的笔记，只有一个标题内容为空笔记不能同步到安卓手机端，

mac 上创建的笔记或者链接自动生成的文件，由于内容还为空，在手机上同步后找不到该文件

我有好几个文件同步不了都是因为内容为空导致的

我看了下，是应为 mac 端没有同步到云端（onedrive）

### What OS are you using?

macOS, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
onedrive 不允许传空文件。无法解决
