### ISSUE TITLE
[Bug]: Failed to load plugin remotely-save

### ISSUE THREAD

**Issue by XII012** [remotely-save/remotely-save#489]
### What happened?

I used the iPad Pro 11-inch (2nd generation), iOS 14.8.1. I installed the plugin and failed to open it.
Could you help me to make this compatible with iOS 14.

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.3.38

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
It's an asked feature. However I don't have any device running iOS 14 so I am unable to debug or support.
