### ISSUE TITLE
[Bug]: The version in the manifest is 0.3.38, not 0.3.39

### ISSUE THREAD

**Issue by MartinJDavis93** [remotely-save/remotely-save#493]
### What happened?

The version in the manifest remained 0.3.38. Сonsequently, updates via the update search cannot be performed, only manually. This is not good.

### What OS are you using?

Windows, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
yes i am aware of it. but i don't have a pc on my hand today. i will fix it in tomorrow when i have a pc back

**Comment by fyears** [comment]
fixed. new version 0.3.40
