### ISSUE TITLE
[Bug]: ios version crushes all the time

### ISSUE THREAD

**Issue by Skefflock** [remotely-save/remotely-save#494]
### What happened?

Obsidian ios version crushes all the time. It happens literally on every sync cycle. Is there a way to find out what happens and how to fix this since as I understand there's no access to console output, so no debug information is available.
Thanks for any help.

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.3.38

### Version of Obsidian

1.4.16 (114)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
I suggest you try out the remotely save setting "skip large file". Usually it's because of the large files.
