### ISSUE TITLE
[Feature Request]: Allow syncing of .dotfiles and .dotfolders

### ISSUE THREAD

**Issue by FairyHmm** [remotely-save/remotely-save#498]
### What feature are you suggesting?

Hi.

Recently, I have reorganised my folder structure. In the process, I have made several folders like `.resources` and `.templates`. That's when I found out that they wouldn't be synced.

> By default, all files or folder starting with `.` (dot) or `_` (underscore) are treated as hidden files, and would NOT be synced.

> In the latest version, you can change the settings to allow syncing `_` files or folders, as well as `.obsidian` special config folder (but not any other `.` files or folders).

While I could rename all of my `.dotfolders` to `_underscoredfolders`, it, in my opinion, does not look as pretty.

My proposal: a whitelist or blacklist, allowing certain `.dotfiles` and `.dotfolders` to be synced, by path or regex.
This way, the `.trash` folder could be synced as well.

Thanks in advance!

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
.trash should not be synced, really. It's the last rescue if anything goes wrong.

And how do you manage other dot files, since obsidian doesn't show up them natively?

**Comment by fyears** [comment]
Sorry but after considerations this feature is not implemented in the near future. PRs are welcome though.

**Comment by the-snesler** [comment]
Should this be considered again, I'd like to note that the [make.md](https://www.make.md/) plugin primarily saves user settings in files stored in the `.space` folder inside a given folder. Something like this: `Obsidian Vault\School\2024-25 Spring\.space`
Yes, this folder name can be changed, but then it becomes visible, even though it's supposed to be an invisible config directory like `.obsidian`.

**Comment by Nihilentropy-117** [comment]
I would like this to be an option as well. Several plugins (such as smart-connections) utilize a .dotfolder to store their data. Even just an ability to manually include them one at a time would be great
