### ISSUE TITLE
[Feature Request]: bypass large files

### ISSUE THREAD

**Issue by fyears** [remotely-save/remotely-save#50]
### What feature are you suggesting?

bypass large files

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by MeerOst** [comment]
+1

**Comment by ColColonCleaner** [comment]
+1

**Comment by fyears** [comment]
[（實驗性質）](https://github.com/remotely-save/remotely-save/releases/tag/0.3.22)
