### ISSUE TITLE
[Feature Request]: Show when sync finishes

### ISSUE THREAD

**Issue by ZeroEkkusu** [remotely-save/remotely-save#501]
## Problem

When an option such as `Run Once On Start Up Automatically` or `Sync On Save` is running, the logs don't show up.

This is good.

However, let's say I open Obsidian (on mobile) and tap the ribbon icon to manually start a sync. Because `Run Once On Start Up Automatically` started it before me, I'll get a log that it's already running. The problem is that it won't show a log when it finishes.

## Solution

If a sync was started by an option such as `Run Once On Start Up Automatically`, but the user tries syncing manually in the meantime, show a log when it finishes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> show a log when it finishes

hard to estimate the remaining time in an easy way. 

currently a file progress x/y should be shown and i think it's the best accurate information it could get

**Comment by ZeroEkkusu** [comment]
Hi, @fyears,

Sorry, I wasn't clear enough:

Console log that the sync **has finished**.

E.g:
- A sync starts automatically
- The user tries syncing manually in the meantime
- A log is displayed saying it's already running
- Nothing is displayed once it's done

Instead:
- Display the log (if the user tried synching manually while an automatic process was running)

**Comment by fyears** [comment]
> Nothing is displayed once it's done
