### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by JustAStudentOfTechnology** [remotely-save/remotely-save#504]
### What happened?

Remotely Save is causing the Obsidian app to go completely black and renders the program unusable. To test all plugins were disabled and only Remotely Save was enabled.

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.3.40

### Version of Obsidian

1.5.3

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by exoticknight** [comment]
what do you mean by saying 'go completely black'? the whole Obsidian app is black?

**Comment by fyears** [comment]
And please try setting "skip large file" in the settings. It's usually because the js environment cannot deal with large files.

**Comment by JustAStudentOfTechnology** [comment]
Apologies for the late reply. The entire screen turns black with the border still the default obsidian color and the window is not selectable/movable. This is with a 2GB file. What is the limit on the file size? Finally, what would I need to do to request that the plugin splits the file in the background when syncing and then re-assembles it on the far side? I anticipate large files being a requirement for my note taking flow in the future.
![Obsidian Sync Error](https://github.com/remotely-save/remotely-save/assets/37562747/dacc7b89-e4d0-431b-b9c2-617fa523980e)

**Comment by fyears** [comment]
Sorry but it needs Obsidian to support reading files by chunks. 

https://forum.obsidian.md/t/feature-request-add-apis-about-reading-and-writing-binary-by-chunks/77384
