### ISSUE TITLE
[Bug]: Daily notes and sync algorithm

### ISSUE THREAD

**Issue by riton** [remotely-save/remotely-save#505]
### What happened?

First of all, this is **not** a real bug, but IMHO a consequence of the current sync algorithm.

### Context

I'm using your plugin to sync between my Phone and my Laptop.
Both my editors are configured to _Open Daily Note on Startup_

![obsidian_daily_notes_on_startup_settings](https://github.com/remotely-save/remotely-save/assets/553730/5adacc91-deee-45c2-9744-fd6fc34fb1f7)

#### Configuration

I'm using _WebDAV_ to synchronize my files.

<details>

<summary>Remotely save sync settings on my Laptop</summary>

![obsidian_remotely_save_settings](https://github.com/remotely-save/remotely-save/assets/553730/80b26205-4e90-42f9-a478-5864bc13b362)

</details>

### How the "problem" was identified ?

This very morning, at `9:00 AM` I've added a note on my Phone in my _daily journal_ named `journals/2024-02-18.md`. I've manually triggered a _sync_ and everything went ok.

A little later, I've turned on my computer. The file `journals/2024-02-18.md` did **not** exist at this moment.
I've launched Obsibian as usual, and landed on my _Daily journal note_ for the current day  `journals/2024-02-18.md` .

On startup, this file **does not** exist and Obsidian creates an empty note file.
Then, synchronization is triggered and the file `journals/2024-02-18.md` present on my Laptop is compared to the _remote version_ of the same file (uploaded by my Phone). The local empty version of the file was created with a more recent timestamp and thus is keeped. Consequence: the note on my Phone is lost.

We can see that in the debug logs of my Computer:

![obsidian_remotely_save_journal](https://github.com/remotely-save/remotely-save/assets/553730/73d136bb-12bb-434f-96ff-c5bd84ee8b99)

Decision: `uploadLocalToRemote`

I know this is expected behavior. You have clearly described how your sync algorithm is working :heavy_check_mark: 

Do you see any workaround for such behavior ? Has anyone already reported something similar ?

### What OS are you using?

Linux

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.3.40

### Version of Obsidian

1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by riton** [comment]
An immediate _workaround_ I'm using is to disable the `Open daily note on startup` option. On startup, I'm then waiting for the sync to occur and then open my _daily note_ as usual.

**Comment by fyears** [comment]
I am considering adding “keep large file if conflict” may be it should partially solve the problem

**Comment by fyears** [comment]
> > I am considering adding “keep large file if conflict” may be it should partially solve the problem
> 
> 
> 
> I think "keep both and rename" when conflict is a great solution at the moment. I don't see the reason for just large files. Small files with just some text are threatened by this too. 

I mean, "keep **larger** files" while conflict by comparing files locally changed and remotely changed. keeping both and renaming is indeed a good solution but it needs extra very complex development that i have to wait and think carefully about it.

**Comment by nallebrean** [comment]
Now I see! I would not like that my self.

I would prefer this developing steps:

1. Just NOT sync conflicting times. Just to make sure there is no data
loss.

2. Then tell the user about it in some way. Preferably in the same release
as step 1.

3. Rename and sync.

4. In the future. Combine differences with diff sync. But this will not
always work so step 3 needs to be fall back.

But you know what's easier and not.

Den lör 16 mars 2024 02:37fyears ***@***.***> skrev:

**Comment by fyears** [comment]
[A new beta version 0.4.1](https://github.com/remotely-save/remotely-save/releases/tag/0.4.1) has been released but you have to install it via [BART](https://github.com/TfTHacker/obsidian42-brat). It contains "keep larger files" functionality.

**Comment by nallebrean** [comment]
I accidentally installed 0.4.4 and for some reason the sync stopped
syncing.

Den sön 17 mars 2024 17:12fyears ***@***.***> skrev:

**Comment by fyears** [comment]
any further information?

**Comment by nallebrean** [comment]
There was no error report, things looked fine. The time sense last sync
just ticked with the time going. I tried to force sync and not just by auto
time sync but no difference.

Onedrive couldn't open the "app" mapp or if it was the vault mapp online
due to "some unknown error".

Maybe just some glitch in onedrive?

The problem was both on my Android and windows.
I use sync on start up and every minute. Default conflict handeling and not
largest file.

Den mån 18 mars 2024 11:32fyears ***@***.***> skrev:

**Comment by fyears** [comment]
maybe you could use a new vault and try again?

**Comment by nallebrean** [comment]
An empty new vault or just remove the sync on OneDrive and start syncing
again?

Den mån 18 mars 2024 14:08fyears ***@***.***> skrev:

**Comment by fyears** [comment]
And empty new vault and some test files.

**Comment by nallebrean** [comment]
new empty vault and some test files works client to onedrive.


MVH

Björn Jonsson

---------------------
Adress: Börjegatan 54B lgh 1302, 752 29 Uppsala
Epost: ***@***.***
Mobil: +46 (0) 70-393 08 68



Den mån 18 mars 2024 kl 16:01 skrev fyears ***@***.***>:

**Comment by fyears** [comment]
So I have no clues yet. You could do a hard rest. The following steps help you upload your vault to onedrive again.

1. backup your vault manually
2. go to onedrive website, delete /App/remotely-save/<your vault name>
3. go to https://www.microsoft.com/consent revoke the auth for remotely save
4. on you mobile, go to remotely save settings page, scroll to the very end, "Delete Prev Sync Details In DB", click delete button.
5. revoke your auth in remotely save setting.
6. auth 
7. Sync again.

**Comment by nallebrean** [comment]
Well I am back on stable version and now it work 0.3.40 after resync and so
on.

Den tis 19 mars 2024 05:17fyears ***@***.***> skrev:
