### ISSUE TITLE
[Bug]: iphone sync bug 

### ISSUE THREAD

**Issue by joanwu95** [remotely-save/remotely-save#506]
### What happened?

when I sync on my iphone, it always went a blank and failed sync. When it went blank, I cannot use obsidian app any more, also, no data was synced.

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
please try to set "skip large file" in the settings. It's usually because the js environment cannot deal with large files.
