### ISSUE TITLE
[Bug]: Version 0.3.40 not compatible with https://www.storj.io/ because of Region

### ISSUE THREAD

**Issue by mrszop** [remotely-save/remotely-save#507]
### What happened?

I have been using Remotely Save 0.3.25 for a while now. Today I had to setup a new laptop and installed 0.3.40 on Linux. Unfortunately it is not compatible with https://www.storj.io/ s3 protocol like it used to be. Error message is: "region was not a valid dns name" for eu1.storj.io. Since I am running another instance of Obsidian Remotely Save (0.3.25) on Mac, I decided to downgrade. Version 0.3.25 works fine with https://www.storj.io/ and region named eu1.storj.io

### What OS are you using?

Linux, macOS

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (Storj)

### Version of the plugin

0.3.40

### Version of Obsidian

1.5.3

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
No need to downgrade, please change your region to `global`.

And here is the doc: https://github.com/remotely-save/remotely-save/blob/master/docs/remote_services/s3_storj_io/README.md
