### ISSUE TITLE
[Feature Request]: Support for Yandex disk Webdav

### ISSUE THREAD

**Issue by d4rk5eed** [remotely-save/remotely-save#508]
### What feature are you suggesting?

Hi, I consider making extension Yandex disk Webdav. The main difference of former (remotely-safe) webdav feature is authorization via api token (Authorization oAuth instead of basic auth) instead of password.
So what is the better way implement feature?
1. Make separate modal class with oAuth support
2. Or add oAuth support to basic/digest authorization list

thanks in advance

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
I think the second should be sufficient and very easy to implement, because the library supports it. Do you want to submit a pr or wait for my implementation? And is it free to register and use yandex disk?

**Comment by d4rk5eed** [comment]
Think, I'll manage to implement pr.
yandex disk cloud provides 5gig free and up-to 3tb premium

**Comment by fyears** [comment]
ok sure. i checkout the doc and find it not as easy as it seems. the main pain point is obtaining and maintaining the oauth info.

**Comment by fyears** [comment]
and it’s report that yandex disk is supported out of the box (maybe by using password or app password)

would you like to give it a try firstly?

https://github.com/remotely-save/remotely-save/issues/338

**Comment by fyears** [comment]
I suddenly realize that it's improper to implement "universal" oauth-based webdav because each web service requires different client id.

Furthermore, actually yandex.disk has [rest api](https://yandex.com/dev/disk/api/concepts/about.html) besides webdav api. I prefer the rest api because it provides more flexibility and allow setting custom meta data (especially modify time). 

So I change my mind and suggest implementing feature using a new remote service yandex.disk, and using the rest api.

If you think it's too much work, I could implement it myself because I find the doc is clear enough and have applied for an oauth app now.

**Comment by d4rk5eed** [comment]
> and it’s report that yandex disk is supported out of the box (maybe by using password or app password)
> 
> would you like to give it a try firstly?
> 
> #338

Yes, it's . Currently I'm using password auth, but it's so unsafe.



> I suddenly realize that it's improper to implement "universal" oauth-based webdav because each web service requires different client id.
> 
> Furthermore, actually yandex.disk has [rest api](https://yandex.com/dev/disk/api/concepts/about.html) besides webdav api. I prefer the rest api because it provides more flexibility and allow setting custom meta data (especially modify time).
> 
> So I change my mind and suggest implementing feature using a new remote service yandex.disk, and using the rest api.
> 
> If you think it's too much work, I could implement it myself because I find the doc is clear enough and have applied for an oauth app now.

It'd be great! Be so kind as to implement it at your discretion

**Comment by fyears** [comment]
> Yes, it's . Currently I'm using password auth, but it's so unsafe.

Could you please firstly write a tutorial in the doc to show how to connect it via password?

**Comment by fyears** [comment]
a yandex disk feature is implemented
