### ISSUE TITLE
[Bug]: 部分文件同步不成功

### ISSUE THREAD

**Issue by amnesiamber** [remotely-save/remotely-save#512]
### What happened?

<img width="388" alt="截屏2024-02-23 下午4 21 39" src="https://github.com/remotely-save/remotely-save/assets/95481276/8aa796db-d082-4f98-b890-412db156bbc8">
如图 onedrive设置好了同步 但是有一些同步不了 是什么问题呢

### What OS are you using?

macOS, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.3.40

### Version of Obsidian

1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
onedrive 不支持文件名的一些特殊字符。你可以试试将失败的那些直接用 onedrive 网页版，应该也是上传失败的。

唯一的解决方案是改文件名

**Comment by wdjoys** [comment]
![微信截图_20240409172601](https://github.com/remotely-save/remotely-save/assets/35288624/aff25d95-be3f-47d7-b1bf-877f382a3d5a)

webdav有同样问题，服务端有相关文件，本地同步不下来。

**Comment by fyears** [comment]
@wdjoys能提供一下完整的文件名吗？之前这些文件是怎么上传的呢，是同一台设备上传的吗？

**Comment by Veinsvx** [comment]
我认为是最新版的问题，我之前也是同步没有任何异常，11版本是正常的，今天我更新到了16版本后，在上传文件后有一定几率会出现这种报错问题。

**Comment by wdjoys** [comment]
文件夹存在，我是通过浏览器插件保存文章到webdav服务器，然后通过您开发的插件同步到本地。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: fyears ***@***.***>
发送时间: Tuesday, April 9, 2024 10:00:13 PM
收件人: remotely-save/remotely-save ***@***.***>
抄送: wdjoys ***@***.***>; Mention ***@***.***>
主题: Re: [remotely-save/remotely-save] [Bug]: 部分文件同步不成功 (Issue #512)


00-QuickNote 这个文件夹存在吗？

―

**Comment by fyears** [comment]
@Veinsvx @wdjoys 再次检查了一下，显然就是 Obsidian 或者操作系统不允许创建的问题。

比如说，你们可以手动在 Obsidian 创建文件，或者在 windows 创建文件，然后尝试改名为带有竖线 `|` 的文件。会出现错误提示的，唯一的办法是改文件名绕开特殊字符。

![Weixin Image_20240427122948](https://github.com/remotely-save/remotely-save/assets/1142836/e680f0a3-230d-47c2-b2d1-a4db026a0b0a)
