### ISSUE TITLE
[Bug]: 同步完成后，提示词应该为 “finished”（过去式）

### ISSUE THREAD

**Issue by amluckydave** [remotely-save/remotely-save#513]
### What happened?

![image](https://github.com/remotely-save/remotely-save/assets/45121260/e639a54d-d4e9-4aeb-94fe-ebc06eb23ad7)
提示词 是否应该修改为 “Remotely Save Finished!”

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
fixed in https://github.com/remotely-save/remotely-save/commit/97f4c0c427e28af837dccfca48a02d1781b7965b
