### ISSUE TITLE
[Bug]: WebDAV Sync Failing on iOS only

### ISSUE THREAD

**Issue by nf032** [remotely-save/remotely-save#514]
### What happened?

Currently getting sync failures on iOS only using identical settings from a desktop setup of remotely-save. iOS returns error "request failed" when attempting a connection check

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.3.4

### Version of Obsidian

1.5.8 (126)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Please upgrade to the latest version and ensure all the input fields are exactly the same. (Or you can use the export function to generate a QR code and use mobile phone to scan it to import the settings)

**Comment by fyears** [comment]
What ios version and obsidian version are you using?

Are you using Obsidian from app store or testflight?

**Comment by nf032** [comment]
> Please upgrade to the latest version and ensure all the input fields are exactly the same. (Or you can use the export function to generate a QR code and use mobile phone to scan it to import the settings)

All done - error still occurring

> What ios version and obsidian version are you using?
> 
> Are you using Obsidian from app store or testflight?

Currently on iOS 17.4 Beta (Build 21E5209b) and the latest Obsidian Version from the App Store (v1.5.8, Build 126)

**Comment by elgatho** [comment]
Confirm issue persits on ios 17.3.1

**Comment by wyf115** [comment]
Similar problem. But I used S3. It worked fine before Obsidian updated. Now it says The S3 bucket cannot be reached.

**Comment by kceiw** [comment]
Same here. I'm using ios 17.3.1. Remotely-save version 0.3.40. My setting isn't changed but sync stopped working about two days ago. I think I also update remotely save to 0.3.40 around the day but I don't remember the exact time. When I check the connection from option, it shows "The webdav server cannot be reached" (note I don't change the setting at all)

**Comment by fyears** [comment]
> Currently on iOS 17.4 Beta (Build 21E5209b) and the latest Obsidian Version from the App Store (v1.5.8, Build 126)
> 

@nf032 do your end point supports https?

@elgatho what's your current endpoint or web address setting? `https://example.com` or `http://example.com` or `example.com` (no http(s) prefix)? does your service support https? are you using stable ios 17.3.1 not beta?

@wyf115 what's your current endpoint or web address setting? `https://example.com` or `http://example.com` or `example.com` (no http(s) prefix)? does your 群晖 support https? are you using stable ios 17.3.1 not beta?

@kceiw what's your current endpoint or web address setting? `https://example.com` or `http://example.com` or `example.com` (no http(s) prefix)? does your service support https? are you using stable ios 17.3.1 not beta?


The main pain point is that I am also using latest stable ios 17.3.1 and obsidian 1.5.8(126) and cannot reproduce all your issues... s3 and webdav works fine. Though they all support https

**Comment by Skywind5487** [comment]
Same problem.
Using the newest obsidian, plugin.
I think trying the alist service will help.
The port test is good. 

The plugin is working on my laptop(old version). However, I can't use them on my iPhone or iPad.

**Comment by fyears** [comment]
> Same problem.
> 
> Using the newest obsidian, plugin.
> 
> I think trying the alist service will help.
> 
> The port test is good. 
> 
> 
> 
> The plugin is working on my laptop(old version). However, I can't use them on my iPhone or iPad.
> 
> 
> 
> 

what's your current endpoint or web address setting? https://example.com or http://example.com or example.com (no http(s) prefix)? does your service support https? are you using stable ios 17.3.1 not beta? @Skywind5487

**Comment by wyf115** [comment]
> > Currently on iOS 17.4 Beta (Build 21E5209b) and the latest Obsidian Version from the App Store (v1.5.8, Build 126)
> 
> @nf032 do your end point supports https?
> 
> @elgatho what's your current endpoint or web address setting? `https://example.com` or `http://example.com` or `example.com` (no http(s) prefix)? does your service support https? are you using stable ios 17.3.1 not beta?
> 
> @wyf115 what's your current endpoint or web address setting? `https://example.com` or `http://example.com` or `example.com` (no http(s) prefix)? does your 群晖 support https? are you using stable ios 17.3.1 not beta?
> 
> @kceiw what's your current endpoint or web address setting? `https://example.com` or `http://example.com` or `example.com` (no http(s) prefix)? does your service support https? are you using stable ios 17.3.1 not beta?
> 
> The main pain point is that I am also using latest stable ios 17.3.1 and obsidian 1.5.8(126) and cannot reproduce all your issues... s3 and webdav works fine. Though they all support https

My desktop uses "http://example.com" and it works find. My iPhone and iPad use the same setting, but it says request failed. I also tried "example.com","https://example.com", they all says request failed. I use iOS 17.3.1, iPadOS 17.3,

**Comment by Skywind5487** [comment]
> > Same problem.
> > 
> > Using the newest obsidian, plugin.
> > 
> > I think trying the alist service will help.
> > 
> > The port test is good. 
> > 
> > 
> > 
> > The plugin is working on my laptop(old version). However, I can't use them on my iPhone or iPad.
> > 
> > 
> > 
> > 
> 
> what's your current endpoint or web address setting? https://example.com or http://example.com or example.com (no http(s) prefix)? does your service support https? are you using stable ios 17.3.1 not beta? @Skywind5487 

Http.
Not bata.

**Comment by fyears** [comment]
I think the bug comes from the obsidian api, not able to send http request on ios now: https://forum.obsidian.md/t/bug-ios-17-and-obsidian-1-5-7-cannot-send-http-request-now/77508

@nf032 @elgatho @wyf115 @kceiw @Skywind5487 Any of you are using https?? I believe the problem coming from the http (no s) requests.

**Comment by elgatho** [comment]
> I think the bug comes from the obsidian api, not able to send http request on ios now: https://forum.obsidian.md/t/bug-ios-17-and-obsidian-1-5-7-cannot-send-http-request-now/77508
> 
> @nf032 @elgatho @wyf115 @kceiw @Skywind5487 Any of you are using https?? I believe the problem comes from the http (no s) requests.

Yes I confirm on https it is working

**Comment by Skywind5487** [comment]
Finally...
Https is work for me.
For those who use alist , just go to /data/config and set the https port in "scheme".And do some portforwarding later.

**Comment by nf032** [comment]
> > Currently on iOS 17.4 Beta (Build 21E5209b) and the latest Obsidian Version from the App Store (v1.5.8, Build 126)
> 
> @nf032 do your end point supports https?

My endpoint does not support https, will configure now and report back (although I suspect already that will work from the other replies in here)

**Comment by wyf115** [comment]
> I think the bug comes from the obsidian api, not able to send http request on ios now: https://forum.obsidian.md/t/bug-ios-17-and-obsidian-1-5-7-cannot-send-http-request-now/77508
> 
> @nf032 @elgatho @wyf115 @kceiw @Skywind5487 Any of you are using https?? I believe the problem comes from the http (no s) requests.

It's OK now. There's something wrong with my minio setting, I changed it and now https will be OK

**Comment by wyf115** [comment]
> > I think the bug comes from the obsidian api, not able to send http request on ios now: https://forum.obsidian.md/t/bug-ios-17-and-obsidian-1-5-7-cannot-send-http-request-now/77508
> > @nf032 @elgatho @wyf115 @kceiw @Skywind5487 Any of you are using https?? I believe the problem comes from the http (no s) requests.
> 
> Yes I confirm on https it is working


It's OK now. There's something wrong with my minio setting, I changed it and now https will be OK

**Comment by nf032** [comment]
> > > Currently on iOS 17.4 Beta (Build 21E5209b) and the latest Obsidian Version from the App Store (v1.5.8, Build 126)
> > 
> > 
> > @nf032 do your end point supports https?
> 
> My endpoint does not support https, will configure now and report back (although I suspect already that will work from the other replies in here)

HTTPS working for WebDAV endpoints

**Comment by Sen-Yao** [comment]
Same problem. iOS 17.1.2 + Obsidian 1.5.8 + Remotely Save 0.3.40

My host is http only, so I use http://example.com instead of https. But when I try to replace http with https anyway, the error message "request failed" will show up a little bit later than http situation.

As @fyears mentioned, I believe that this bug is caused by obsidian api, not able to send http request.

**Comment by kceiw** [comment]
I don't use beta version ios. My endpoint is http only. I set up Nextcloud on my local network. And set up a local DNS name using pihole. It has an https endpoint using a self signed certificate. The set up work because I can connect to it using to local DNS name in Nextcloud client on ios. 

I couldn't use https on here because Obsidian doesn't support self signed certificate.

**Comment by kceiw** [comment]
If it's because Obsidian doesn't support http, that must be a change in their recent update.

**Comment by fyears** [comment]
wait for obsidian's fix

https://forum.obsidian.md/t/bug-ios-17-and-obsidian-1-5-7-cannot-send-http-request-now/77508/2
