### ISSUE TITLE
[Bug]: iOS won't sync

### ISSUE THREAD

**Issue by LonglegsP** [remotely-save/remotely-save#515]
### What happened?

After IOS is upgraded to the latest version, check the link and prompt: The corresponding bucket cannot be reached. Both MacBooks and Windows PCs have normal access to sync.

I use the export function to generate a QR code and use mobile phone to scan it to import the settings。

Here's a screenshot from my phone
![image](https://github.com/remotely-save/remotely-save/assets/38206253/7fa0d0d5-b037-44bb-bf24-ef7cea9264f2)
Here's a screenshot from my MacBook
![image](https://github.com/remotely-save/remotely-save/assets/38206253/2ba938fd-8640-43bd-989f-34ee263e9b87)

### What OS are you using?

Windows, macOS, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (腾讯云 COS Tencent Cloud COS)

### Version of the plugin

0.3.40

### Version of Obsidian

1.5.8（126）

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
endpoint 是 `cos.<region>.myqcloud.com` 这样吗？（不需要 `https://` 也不需要 bucket name）

region是 `ap-nanjing` 这种吗？

没理由啊，代码都是一样的…… 我自己也是最新版本。

你的 ios 是什么版本？

**Comment by fyears** [comment]
会不会是网络不通，确认手机的网络是好的吗

**Comment by fyears** [comment]
奇怪看上去和 #514 很像

**Comment by LonglegsP** [comment]
> endpoint 是 `cos.<region>.myqcloud.com` 这样吗？（不需要 `https://` 也不需要 bucket name）
> 
> region是 `ap-nanjing` 这种吗？
> 
> 没理由啊，代码都是一样的…… 我自己也是最新版本。
> 
> 你的 ios 是什么版本？

解决了 把`endpoint`里的 `http:// ` 删除就可以连接了，感谢。
