### ISSUE TITLE
[Bug]: 同步不了文件到OneDrive，但是是连接成功的 | cannot sync to onedrive

### ISSUE THREAD

**Issue by Yf-Faina** [remotely-save/remotely-save#517]
### What happened?

![屏幕截图 2024-02-29 211637](https://github.com/remotely-save/remotely-save/assets/138426732/d4323ef9-e23d-4fd7-b25a-890bb9104f56)
![屏幕截图 2024-02-29 150720](https://github.com/remotely-save/remotely-save/assets/138426732/363c05b8-00df-4819-8c82-49ccdd259e6d)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.3.40

### Version of Obsidian

v1.5.8

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
你用的是最普通的个人版本 onedrive 吗？还是 onedrive dor business / e5 / 教育版 / 世纪互联？

**Comment by Yf-Faina** [comment]
> 你用的是最普通的个人版本 onedrive 吗？还是 onedrive dor business / e5 / 教育版 / 世纪互联？

学生版本是要用教育邮箱注册的吧？我不是使用的edu.cn后缀的邮箱注册的onedrive，不是商业版。是可以从onedrive.live.com登录上去的，所以应该也不是世纪互联的版本。

**Comment by fyears** [comment]
在 onedrive 网页登录，并在网页里查看一下，

1. 请问可以看到 Application 或者 应用 这个文件夹吗？
2. 点进去之后，请问可以看到有文件夹叫做 remotely-save 或 Remotely Save 或 Graph 这个文件夹吗？
3. 假如有的话，点进去之后，请问可以见到 MyText 这个文件或者文件夹吗？
4. 这个 MyText 是你之前手动或者自动上传的吗？

**Comment by Yf-Faina** [comment]
> 在 onedrive 网页登录，并在网页里查看一下，
> 
> 1. 请问可以看到 Application 或者 应用 这个文件夹吗？
> 2. 点进去之后，请问可以看到有文件夹叫做 remotely-save 或 Remotely Save 或 Graph 这个文件夹吗？
> 3. 假如有的话，点进去之后，请问可以见到 MyText 这个文件或者文件夹吗？
> 4. 这个 MyText 是你之前手动或者自动上传的吗？

可以看到Application这个文件夹，且也能看到Graph文件夹，再点击也能看到MyText。OneDrive中的MyText文件夹不是我手动新建的。但是点开MyText中内容是空的。

**Comment by fyears** [comment]
这里我就不知道怎么解决了，按道理，这里应该有一个叫做 remotely save 的文件夹而不是 graph。删除这个文件夹后，obsidian 重新授权 remotely save 试试？

**Comment by Yf-Faina** [comment]
> 这里我就不知道怎么解决了，按道理，这里应该有一个叫做 remotely save 的文件夹而不是 graph。删除这个文件夹后，obsidian 重新授权 remotely save 试试？

![屏幕截图 2024-03-01 075421](https://github.com/remotely-save/remotely-save/assets/138426732/e8561b79-5d48-4824-9a16-702379bfd664)
![屏幕截图 2024-03-01 075510](https://github.com/remotely-save/remotely-save/assets/138426732/915c5010-b6a7-4c41-85e6-0c35b3aa27c9)
![屏幕截图 2024-03-01 075517](https://github.com/remotely-save/remotely-save/assets/138426732/3ed88958-1332-42a9-ac08-a5926afd9bcf)
删掉Graph以后，重新进行鉴权，还是自动出现Graph文件夹，没发生什么改变。

**Comment by fyears** [comment]
@Yf-Faina @822283285 @Ecank-Officials

我试过了，试试这样直接解决是否可以！

1. 备份你的文件
2. 去 onedrive 网页（<https://onedrive.live.com/>），重命名 `Application/Graph` 为 `Application/remotely-save` （右键点击文件夹，有重命名按钮）然后尝试触发一下同步！

I tried and come up with a simple solution: 
1. backup the vault
3. go to onedrive website (<https://onedrive.live.com/>), and rename `Application/Graph` to `Application/remotely-save` (right click on the folder and you will see rename option), and try to sync!

**Comment by Yf-Faina** [comment]
> @Yf-Faina @822283285 @Ecank-Officials
> 
> 我试过了，试试这样直接解决是否可以！
> 
> 1. 备份你的文件
> 2. 去 onedrive 网页（https://onedrive.live.com/），重命名 `Application/Graph` 为 `Application/remotely-save` （右键点击文件夹，有重命名按钮）然后尝试触发一下同步！
> 
> I tried and come up with a simple solution:
> 
> 1. backup the vault
> 2. go to onedrive website (https://onedrive.live.com/), and rename `Application/Graph` to `Application/remotely-save` (right click on the folder and you will see rename option), and try to sync!

![屏幕截图 2024-03-18 160328](https://github.com/remotely-save/remotely-save/assets/138426732/c3c6fb80-300d-4033-b52f-719278b7e83a)
谢谢成功解决了

**Comment by fyears** [comment]
谢谢，那么这个问题修复了

**Comment by zsabra** [comment]
Noticed something which might add some clarity to this mystery. The folder name appears to be localized. I have a swedish account and my folder is called `Appar` which is Swedish for Apps.
