### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by HWiwoiiii** [remotely-save/remotely-save#518]
### What happened?

This message shows up when I sync a video across my devices. I understand what it means, but how do I fix it? It stucks at that video and won't sync other files. I tried to change Concurrency to 5 and not working still
这条消息出现在我跨设备同步视频时。我理解它的意思，但我该如何修复呢？它卡在那个视频上，无法同步其他文件。我尝试将并发设置为5，但仍然无效。

Any help is greatly appreciated
非常感谢任何帮助。

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

newest

### Version of Obsidian

newest

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
没有截图？此外可以用 skip large files 避开

**Comment by HWiwoiiii** [comment]
Sorry no screenshots for now. I've 'fixed' the issue by ignoring all video file extensions in the regex. 'Skip large files' could be a solution, but there are some large zip files I still want to sync (They might also generate this error message, but I haven't encountered any so far)
抱歉，暂时没有截图。我通过在正则表达式中忽略所有视频文件扩展名来"解决"了这个问题。"跳过大文件"可能是一个解决方案，但我仍然想同步一些大型zip文件。(它们也可能生成这个错误消息，但到目前为止我还没有遇到过)

**Comment by HWiwoiiii** [comment]
ios sucks

**Comment by fyears** [comment]
the resources on mobile is rather limited so it's a bad idea to sync large files anyway. the plugin is also limited to the ability provided by obsidian so no better optimization can be done currently
