### ISSUE TITLE
How to exclude folder or file path using regex?

### ISSUE THREAD

**Issue by HWiwoiiii** [remotely-save/remotely-save#519]
### What feature are you suggesting?

For instance, if I have a folder named CODE in the root, I know that I can exclude it by simply filling in CODE/ in the settings. What if I want to sync all the markdown files in that folder but not the attachments? I was thinking of using ^CODE\/(?!.*\.md$).*$, but it doesn't work.
例如，如果我在根目录下有一个名为CODE的文件夹，我知道我可以通过在设置中简单地填写CODE/来排除它。如果我想同步该文件夹中的所有Markdown文件但不包括附件，我考虑使用^CODE/(?!..md$).$，但它并不起作用。

Any help is appreciated.

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
After searching and reading this: <https://stackoverflow.com/questions/16398471/regex-for-string-not-ending-with-given-suffix>, the following solution works:

```javascript
^CODE/.+(?<!\.md)$
```

Some tests:

```javascript
const XRegExp = require('XRegExp');

XRegExp(String.raw`^CODE/.+(?<!\.md)$`).test('CODE/hey.mdx');
// true
XRegExp(String.raw`^CODE/.+(?<!\.md)$`).test('CODE/hey.7md');
// true
XRegExp(String.raw`^CODE/.+(?<!\.md)$`).test('CODE/');
// false
XRegExp(String.raw`^CODE/.+(?<!\.md)$`).test('CODE/hey.md');
// false
XRegExp(String.raw`^CODE/.+(?<!\.md)$`).test('CODEhey.md');
// false
XRegExp(String.raw`^CODE/.+(?<!\.md)$`).test('aaa/CODE/hey.md');
// false
```

**Comment by chocolate-byte** [comment]
eg ^_index.*\\.md$
