### ISSUE TITLE
[Bug]: 配置并不能完全同步

### ISSUE THREAD

**Issue by qiekqiek** [remotely-save/remotely-save#520]
### What happened?

同步配置文件夹的时候，应该让两地的库完全一样，但实际上并没有，快捷键、插件设置等都没同步。

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.3.40

### Version of Obsidian

1.5.8

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
快捷键什么的，是文件格式存储的吗？

**Comment by fyears** [comment]
（没有进一步反馈先关闭了）
