### ISSUE TITLE
[Bug]: plugin file couldn't be moved because don't have permission to access ".trash"

### ISSUE THREAD

**Issue by HWiwoiiii** [remotely-save/remotely-save#521]
### What happened?

```
remotely-save-1709272829496: abort sync,
triggerSource=manual, error while syncing

.obsidian/icons/feather-icons/Check.svg:
"Check.svg" couldn't be moved because you
don't have permission to access ".trash"
```
I'm using ios device I guess this has something to do with the file privilege of ios system, A big thank you if someone can teach me how to fix it
我正在使用iOS设备，我猜这可能与iOS系统的文件权限有关。如果有人能教我如何修复，我将不胜感激。

![image](https://github.com/remotely-save/remotely-save/assets/103039908/8a95d957-9400-4a07-8b84-0c8eb769abbd)

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

newest

### Version of Obsidian

newest

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
无法复现。新建 vault 看看是否有问题呢

**Comment by fyears** [comment]
无法复现，先关闭了。况且没权限这个问题确实也修复不了……
