### ISSUE TITLE
[Bug]: File Lost When Syncing Large File

### ISSUE THREAD

**Issue by HWiwoiiii** [remotely-save/remotely-save#522]
### What happened?

When Syncing Large Video Files From Windows to IOS devices, the action was canceled as suggested [Out of Memory · Issue #518 · remotely-save/remotely-save](https://github.com/remotely-save/remotely-save/issues/518), however it also deletes those large files in my windows folder

I have added `(swf|avi|flv|mpg|rm|mov|wav|asf|3gp|mkv|rmvb|mp4)+` on regex ignore in the middle of the whole vault syncing, I would suggest that is also related somehow.

在将大型视频文件从Windows同步到iOS设备时，根据建议取消了操作[Out of Memory · Issue #518 · remotely-save/remotely-save](https://github.com/remotely-save/remotely-save/issues/518)，然而它还会删除我Windows文件夹中的这些大型文件。

我已经在整个保险库同步过程中的正则表达式忽略中添加了(swf|avi|flv|mpg|rm|mov|wav|asf|3gp|mkv|rmvb|mp4)+，我认为这也可能与此有关。

Thank you~

Below are my rs settings 
![image](https://github.com/remotely-save/remotely-save/assets/103039908/e7039c68-d508-4cd5-92c0-dad3226c8eab)
![image](https://github.com/remotely-save/remotely-save/assets/103039908/569c56d0-fcb5-46e0-b802-a519f0c95258)
![image](https://github.com/remotely-save/remotely-save/assets/103039908/6deec392-5304-4935-b5b6-71669defb229)

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

newest

### Version of Obsidian

newest

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by HWiwoiiii** [comment]
To be honest i really don't think the plugin is the issue here, ios just broke my heart

**Comment by fyears** [comment]
ok... sorry to hear that.

and actually please **always do a manual backup**
