### ISSUE TITLE
[Bug]: webdav handshake error while using digital certificate issued by Nya Labs CA

### ISSUE THREAD

**Issue by neooier** [remotely-save/remotely-save#523]
### What happened?

Everything was fine until I replaced the website's digital certificate.
Now when I use the same configuration on windows it's no problem, only on android I have this problem.

![image](https://github.com/remotely-save/remotely-save/assets/53945377/4260459a-cfcc-4862-9e25-010f4fba6c52)

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (Cloudreve)

### Version of the plugin

0.3.40

### Version of Obsidian

1.5.8(126)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Would you please try directly connect to your webdav server directly using web browser (like your os web browser, usually Chrome on android)?

Remotely Save doesn't deal with https certificates directly, and it just uses underlying web component.

**Comment by neooier** [comment]
I tried to directly connect using the browser and the Windows version of Obsidian, and there were no issues.
Where should I report this issue to?...

**Comment by fyears** [comment]
it should be a general question about ssl certificates. may be you cand find some helps on the internet: https://stackoverflow.com/questions/6825226/trust-anchor-not-found-for-android-ssl-connection
