### ISSUE TITLE
[Feature Request]: 开App自启动，同步结束后能弹出提示

### ISSUE THREAD

**Issue by BitComing** [remotely-save/remotely-save#526]
### What feature are you suggesting?

在移动端，开App自启动插件，有提示会更加显著。
![Screenshot_2024-03-06-23-10-55-431_md obsidian](https://github.com/remotely-save/remotely-save/assets/68539160/8bf1d362-66eb-4a67-bc30-031eaffa4b22)

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
其实这样子的话很打扰的，暂无此计划
