### ISSUE TITLE
[Bug]: Not updating any file because of the updated date in cloud

### ISSUE THREAD

**Issue by MAGLeb** [remotely-save/remotely-save#529]
### What happened?

I encountered an issue related to file synchronization with Dropbox due to a discrepancy in the system time on my local machine. Here are the details of the issue:

1. A file was saved to Dropbox at the time displayed on my local machine, which was 12:07 PM. However, this time was incorrect; the correct local time was actually 11:07 AM.
2. Despite the incorrect local time, the file metadata in Dropbox reflected the save time as 12:07 PM.
3. After realizing the time discrepancy, I corrected my local machine's time to the accurate 11:07 AM.
4. Subsequently, I faced a bug where modifications to the file were not being saved or synchronized to Dropbox.

**OPTIONAL SOLUTION:**
In light of the synchronization issue encountered due to the discrepancy in system time, I'd like to propose a couple of potential solutions to mitigate similar problems in the future:

**Implementing File Versioning:** By introducing a versioning system for files stored in the cloud, more complex conflicts can be managed effectively. With versioning, each modification creates a new version of the file, allowing for better tracking of changes and easier resolution of conflicts.

This solution could provide a robust way to handle file modifications and ensure that synchronization issues, like the one encountered, are less likely to occur. Implementing file versioning could enhance the overall reliability of file storage and synchronization processes.

### What OS are you using?

Linux

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

0.3.38

### Version of Obsidian

1.5.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
however versions are only comparable if the time over different machines are the sync, **or** introducing hashing / commits which is similar to git. i am not smart enough to develop a git-alike system.

Though in the near future some versions concepts will be introduced, but it will still require correct time.
