### ISSUE TITLE
[Bug]: 配置群晖的WebDAV地址一直提示鉴权失败net::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by IAvision** [remotely-save/remotely-save#530]
### What happened?

配置群晖的WebDAV地址一直提示鉴权失败net::ERR_CERT_AUTHORITY_INVALID
但是相同的配置使用RaiDrive或者nPlayer是可以连接的。
![Snipaste_2024-03-08_01-32-48](https://github.com/remotely-save/remotely-save/assets/6058326/90e1ed78-eec6-4780-932d-b92d99967296)
![Snipaste_2024-03-08_01-33-14](https://github.com/remotely-save/remotely-save/assets/6058326/967ee378-5924-4f08-bff8-6d5df46f5683)

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.3.10

### Version of Obsidian

1.4.14

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by IAvision** [comment]
将Obsidian更新到1.5.8仍然提示这个错误

**Comment by TSsimeon** [comment]
> 将Obsidian更新到1.5.8仍然提示这个错误

iphone 同样的问题，windows没问题

**Comment by IAvision** [comment]
> > 将Obsidian更新到1.5.8仍然提示这个错误
> 
> iphone 同样的问题，windows没问题

我是windows、iphone、android都一样，但是用其他WebDAV工具能连。

**Comment by TSsimeon** [comment]
> > > 将Obsidian更新到1.5.8仍然提示这个错误
> > 
> > 
> > iphone 同样的问题，windows没问题
> 
> 我是windows、iphone、android都一样，但是用其他WebDAV工具能连。

现在我改成https就可以了。我看issue是http再obsidian的某个版本出现了bug

**Comment by IAvision** [comment]
> > > > 将Obsidian更新到1.5.8仍然提示这个错误
> > > 
> > > 
> > > iphone 同样的问题，windows没问题
> > 
> > 
> > 我是windows、iphone、android都一样，但是用其他WebDAV工具能连。
> 
> 现在我改成https就可以了。我看issue是http再obsidian的某个版本出现了bug

我是http和https都不行

**Comment by ilcxyz** [comment]
我用的威联通布置的Webdav，现在有两种状态：
1. 内网连接：win11, android, iphone均可以在http下连接成功，并正常同步。
2. 外网连接（NPS）：win11, android均可以在http下连接成功，并正常同步，但是iphone始终连接失败。

**Comment by chen-mumu** [comment]
> 我用的威联通布置的Webdav，现在有两种状态：
> 
> 1. 内网连接：win11, android, iphone均可以在http下连接成功，并正常同步。
> 2. 外网连接（NPS）：win11, android均可以在http下连接成功，并正常同步，但是iphone始终连接失败。

一模一样 win成功 iphone不行

**Comment by IAvision** [comment]
原来是我群晖的webdav service 证书选择错误了，导致SSL一直没有握手...

**Comment by suktry** [comment]
请问楼主怎么配置证书？

**Comment by fyears** [comment]
谢谢反馈，不过，同问是怎么解决的。别的 issue 也有类似的问题。

**Comment by fyears** [comment]
http iphone 肯定是不行的了，要正确配置 https

**Comment by chen-mumu** [comment]
是的，之前可以，近期不行了，iphone上换成HTTPS就好了

**Comment by IAvision** [comment]
> 请问楼主怎么配置证书？

群晖有专门的证书管理界面

**Comment by Black-233** [comment]
我用的是自签证书，可以给obsidian加一个启动参数 "--ignore-certificate-errors"，但不知道会不会有安全问题

**Comment by fyears** [comment]
> 我用的是自签证书，可以给obsidian加一个启动参数 "--ignore-certificate-errors"，但不知道会不会有安全问题

当然有问题了……搞个letsencrypt吧

**Comment by magicum-sidus** [comment]
> 我用的是自签证书，可以给obsidian加一个启动参数 "--ignore-certificate-errors"，但不知道会不会有安全问题

怎么添加启动参数呢

**Comment by magicum-sidus** [comment]
> > 我用的是自签证书，可以给obsidian加一个启动参数 "--ignore-certificate-errors"，但不知道会不会有安全问题
> 
> 当然有问题了……搞个letsencrypt吧

不知道为什么letsencrypt证书也鉴权失败，浏览器可以但是obsidian就是不行

**Comment by Black-233** [comment]
> > 我用的是自签证书，可以给obsidian加一个启动参数 "--ignore-certificate-errors"，但不知道会不会有安全问题
> 
> 怎么添加启动参数呢

就是改快捷方式，原来是"xxxx/obsidian" 改成 "xxxx/obsidian --ignore-certificate-errors"
不过我找到一个新的解决方式，是把自签的证书安装到系统受信任区里，然后就可以了。
