### ISSUE TITLE
[Feature Request]: Use AWS profile

### ISSUE THREAD

**Issue by superuser5** [remotely-save/remotely-save#532]
### What feature are you suggesting?

Incorporating support for AWS profiles alongside direct credentials would significantly enhance our operational security (OPSEC) and mitigate risks associated with locally stored credentials. AWS profiles not only bolster security through the potential integration of two-factor authentication (2FA) (IAM roles with 2FA) but also offer the advantage of using temporary credentials, providing an additional layer of protection.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
the plugin must work with mobile especially on ios so in my opinion there is no universal way to support aws profile in a reliable way
