### ISSUE TITLE
[Bug]: 同步出错：remotely-save-1710205771735:中断同步，同步来源=manual，出错阶段=gettingremote files list

### ISSUE THREAD

**Issue by 822283285** [remotely-save/remotely-save#534]
### What happened?

在进行同步的时候，弹出提示：remotely-save-1710205771735:中断同步，同步来源=manual，出错阶段=gettingremote files list，we meet file/folder and do not know how to deal with it: parentPath="/drive/root/应用/Graph", selfName="知识库"
![image](https://github.com/remotely-save/remotely-save/assets/77655199/69b7f846-e218-4d1e-a0d0-9e8ef0a2aba8)

### What OS are you using?

Windows, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.3.40

### Version of Obsidian

1.5.8

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by 822283285** [comment]
在one driver中有 应用/Graph/知识库 路径存在
![image](https://github.com/remotely-save/remotely-save/assets/77655199/6ae7da89-2943-41ee-af5c-7662d745d515)

**Comment by Ecank-Officials** [comment]
I have the same problem ,what should I do?

**Comment by godliam** [comment]
i have same problem too.

**Comment by fyears** [comment]
dup of #517

**Comment by fyears** [comment]
我试过了，试试这样直接解决是否可以！

备份你的文件
去 onedrive 网页（https://onedrive.live.com/），重命名 Application/Graph 为 Application/remotely-save （右键点击文件夹，有重命名按钮）然后尝试触发一下同步！
I tried and come up with a simple solution:

backup the vault
go to onedrive website (https://onedrive.live.com/), and rename Application/Graph to Application/remotely-save (right click on the folder and you will see rename option), and try to sync!
