### ISSUE TITLE
[Bug]: Origin OS 1.0 无法使用

### ISSUE THREAD

**Issue by ka1rosm** [remotely-save/remotely-save#535]
Remotely-save 0.3.28 and 0.3.40 FAIL on Origin OS 1.0 (Android 11). 0.3.25 works fine, sync success. OB version 1.5.8. 
0.3.40 works fine on Origin OS Ocean (Android 12).

**Comment by ka1rosm** [comment]
The latest version i can use on Origin OS 1.0 (Android 11) is 0.3.25. Sync success. 0.3.28 and 0.3.40 failed.

**Comment by fyears** [comment]
没有手机可以测试。无法使用是什么症状？能否升级 android web view 试试？

**Comment by ka1rosm** [comment]
> 没有手机可以测试。无法使用是什么症状？能否升级 android web view 试试？

"Failed to load plugin remotely-save"。我试试升级android web view。

**Comment by ka1rosm** [comment]
> 没有手机可以测试。无法使用是什么症状？能否升级 android web view 试试？

将Android system webview由83升级到122，问题解决，0.3.40可以正常在originos 1.0上使用。

**Comment by ka1rosm** [comment]
将Android system webview由83升级到122，问题解决，0.3.40可以正常在originos 1.0上使用。

**Comment by ka1rosm** [comment]
非常感谢！
