### ISSUE TITLE
[Bug]: WebDAV使用https后，服务器上的中文库名会被转码

### ISSUE THREAD

**Issue by IAvision** [remotely-save/remotely-save#537]
### What happened?

WebDAV使用https后，服务器上的中文库名会被转码。
如图：
![Snipaste_2024-03-14_00-34-48](https://github.com/remotely-save/remotely-save/assets/6058326/a3b766dc-88d5-47d0-8542-c3631babda9b)
![Snipaste_2024-03-14_00-32-46](https://github.com/remotely-save/remotely-save/assets/6058326/17253af6-10e1-4bd8-89ad-ee1042bd9a45)

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.3.40

### Version of Obsidian

1.5.8

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
服务器是什么呢？群晖吗

**Comment by IAvision** [comment]
> 服务器是什么呢？群晖吗

服务器是群晖，群晖自带的WebDAV Sserver 。
目前是使用IOS，HTTPS连接，进行连接检查后会在群晖创建文件夹，但是会将中文转码，然后通过插件同步后会提示目录有问题，查不到对应的中文目录。

**Comment by fyears** [comment]
> ，群晖自带的WebDAV Sserver 。
> 目前是使用IOS，HTTPS连接，进行连接检查后会在群晖创建文件夹，但是会将中文转码，然后通过插件同步后会提示目录有问题，查不到对应的中文目录

@IAvision 那么不用 https 而用 http 会有这个问题吗

**Comment by fyears** [comment]
此外，用ios触发同步（上传），以及用电脑（pc, mac），都会看到被转码了吗？

我这里用群晖似乎无法复现

**Comment by IAvision** [comment]
> > ，群晖自带的WebDAV Sserver 。
> > 目前是使用IOS，HTTPS连接，进行连接检查后会在群晖创建文件夹，但是会将中文转码，然后通过插件同步后会提示目录有问题，查不到对应的中文目录
> 
> @IAvision 那么不用 https 而用 http 会有这个问题吗

IOS 无法使用http连接，只有https可以连接服务器成功。



> 此外，用ios触发同步（上传），以及用电脑（pc, mac），都会看到被转码了吗？
> 
> 我这里用群晖似乎无法复现

经测试，IOS的服务器地址不包含中文时，文件名正常，但是地址含有中文后，文件名会被转码，但PC和安卓不会。

**Comment by IAvision** [comment]
> > ，群晖自带的WebDAV Sserver 。
> > 目前是使用IOS，HTTPS连接，进行连接检查后会在群晖创建文件夹，但是会将中文转码，然后通过插件同步后会提示目录有问题，查不到对应的中文目录
> 
> @IAvision 那么不用 https 而用 http 会有这个问题吗

IOS无法使用http连接，但是PC和安卓可以。

**Comment by IAvision** [comment]
@fyears 以上

**Comment by fyears** [comment]
我试试吧，我也得搭建一个 https 环境供 ios 测试……

**Comment by IAvision** [comment]
> 我试试吧，我也得搭建一个 https 环境供 ios 测试……

有群晖的话，直接在群晖上的webdav server 启用HTTPS就可以了。

**Comment by fyears** [comment]
android 和 windows ，用 http 和 https，一共四种组合，都不会乱码，对吗？

**Comment by IAvision** [comment]
> android 和 windows ，用 http 和 https，一共四种组合，都不会乱码，对吗？

对

**Comment by fyears** [comment]
我用最新版 ios 17 和插件的最新版（beta 0.4.x 和稳定版 0.3.40），都试过了，没有乱码。

我用的是 dsm 7。没有 reverse proxy

暂无排查新思路。

你可以先安装brat，然后用 brat 安装 remotely save beta 版本，然后再安装 obsidian://show-plugin?id=logstravaganza ，触发 webdav 同步，查看一下有什么 log

**Comment by IAvision** [comment]
> 我用最新版 ios 17 和插件的最新版（beta 0.4.x 和稳定版 0.3.40），都试过了，没有乱码。
> 
> 我用的是 dsm 7。没有 reverse proxy
> 
> 暂无排查新思路。
> 
> 你可以先安装brat，然后用 brat 安装 remotely save beta 版本，然后再安装 obsidian://show-plugin?id=logstravaganza ，触发 webdav 同步，查看一下有什么 log

BRAT是用哪个链接安装beta版？
我用了以下两个链接都不能下载

https://github.com/remotely-save/obsidian42-brat
https://github.com/remotely-save/obsidian42-brat.git
![Uploading IMG_3868.png…]()

**Comment by IAvision** [comment]
![IMG_3868](https://github.com/remotely-save/remotely-save/assets/6058326/69022b02-66eb-4be4-a923-56f6882f3bdb)

**Comment by fyears** [comment]
安装了 brat （看你截图是安装了的），然后 输入 `remotely-save/remotely-save` 即可

**Comment by IAvision** [comment]
> 我用最新版 ios 17 和插件的最新版（beta 0.4.x 和稳定版 0.3.40），都试过了，没有乱码。
> 
> 我用的是 dsm 7。没有 reverse proxy
> 
> 暂无排查新思路。
> 
> 你可以先安装brat，然后用 brat 安装 remotely save beta 版本，然后再安装 obsidian://show-plugin?id=logstravaganza ，触发 webdav 同步，查看一下有什么 log

我觉得应该是charset的问题

`| 2024-03-20T08:43:48.622Z | s@ | log | rspHeaders |
| 2024-03-20T08:43:48.625Z | s@ | log | {"Keep-Alive":"timeout=5, max=100","Connection":"Keep-Alive","Server":"Apache","Content-Length":"196","Date":"Wed, 20 Mar 2024 08:43:48 GMT","Content-Type":"text/html; charset=iso-8859-1"} |
| 2024-03-20T08:43:48.685Z | s@ | log | rspHeaders |
| 2024-03-20T08:43:48.686Z | s@ | log | {"Date":"Wed, 20 Mar 2024 08:43:48 GMT","Keep-Alive":"timeout=5, max=99","Location":"https://nas.ker.center:46802/Home_Files/410-%e6%b5%8b%e8%af%95/IA-%25E7%25AC%2591%25E7%25AC%25912/","Connection":"Keep-Alive","Content-Length":"285","Server":"Apache","Content-Type":"text/html; charset=ISO-8859-1"} |
| 2024-03-20T08:43:48.741Z | s@ | log | rspHeaders |
| 2024-03-20T08:43:48.741Z | s@ | log | {"Content-Length":"899","Date":"Wed, 20 Mar 2024 08:43:48 GMT","Server":"Apache","Content-Type":"text/xml; charset=\"utf-8\"","Connection":"Keep-Alive","Keep-Alive":"timeout=5, max=98"} | `

**Comment by fyears** [comment]
1. 我帮你修改了网址，之后记得修改一下避免泄漏
2. 这里还是有点抽象，能不能这样：
  1. 记得备份一下
  2. 删除 server 上整个 vault 文件夹
  3. 删除本地那个 log 文件
  4. 去 remotely save 设置里面点击 check connections，这时候应该会尝试在服务器上创建一个文件夹
  5. 看看这个文件夹是不是乱码。是的话，看看本地的 log 文件，把 request 和 response 部分都贴出来


非常感谢你的配合 debug！没办法，我自己的群晖没问题的……

**Comment by IAvision** [comment]
> 我帮你修改了网址，之后记得修改一下避免泄漏。
> 
> charset 没问题的其实。
> 
> 上述 log 还是有点抽象，能不能这样：
> 
> 1. 记得备份一下
> 2. 删除 server 上整个 vault 文件夹
> 3. 删除本地那个 log 文件
> 4. 去 remotely save 设置里面点击 check connections，这时候应该会尝试在服务器上创建一个文件夹
> 5. 看看这个文件夹是不是乱码。是的话，看看本地的 log 文件，把 request 和 response 部分都贴出来
> 
> 非常感谢你的配合 debug！没办法，我自己的群晖没问题的……

图1：在群晖新建的“测试”文件夹
![图1：在群晖新建的“测试”文件夹](https://github.com/remotely-save/remotely-save/assets/6058326/91b43b23-16cd-4974-a1cb-13e328511cb4)

图2：iPhone新建的“测试”vault
![图2：iPhone新建的“测试”vault](https://github.com/remotely-save/remotely-save/assets/6058326/f1f178fe-0de0-4570-9a23-4f255950be44)

图3：安装好插件后录入的https地址
![图3：安装好插件后录入的https地址](https://github.com/remotely-save/remotely-save/assets/6058326/0e869011-6255-44cf-9398-a54a20dac039)

图4：“检查可否连接”提示连接成功
![图4：“检查可否连接”提示连接成功](https://github.com/remotely-save/remotely-save/assets/6058326/80605df3-b8a4-4a7e-91ce-a254ad8d65ef)

图5：运行remotely-save插件提示
![图5：运行remotely-save插件提示](https://github.com/remotely-save/remotely-save/assets/6058326/1b74bd53-f9dd-4b46-9868-a4cb96c7cd40)

图6：群晖对应文件夹乱码的图
![图6：群晖对应文件夹乱码的图](https://github.com/remotely-save/remotely-save/assets/6058326/84a9b6d9-7368-4658-9015-886d4c60cdd3)

以下是Log
[LOGGING-NOTE (iPhone).md](https://github.com/remotely-save/remotely-save/files/14667112/LOGGING-NOTE.iPhone.md)


我看了一下Log，连接检查时charset=iso-8859-1 ，执行同步时charset=\"utf-8\"

**Comment by IAvision** [comment]
@fyears 
以下是同一个vault在同一服务器路径为英文时的测试结果。

图1：在群晖新建的“测试”文件夹
![图1：在群晖新建的“测试”文件夹](https://github.com/remotely-save/remotely-save/assets/6058326/20db7e5f-f3ba-44e0-a5a3-58b4b4cb467d)

图2：修改https地址
![图2：修改https地址](https://github.com/remotely-save/remotely-save/assets/6058326/d366db8c-4252-4a41-9e70-67b7addde968)

图3：“检查可否连接”提示连接成功
![图3：“检查可否连接”提示连接成功](https://github.com/remotely-save/remotely-save/assets/6058326/a604d885-4d19-4dae-b6ba-110613c28559)

图4：运行remotely-save插件提示成功
![图4：运行remotely-save插件提示成功](https://github.com/remotely-save/remotely-save/assets/6058326/d6c58c8f-8910-45e5-9bba-087f805161c4)

图5：群晖显示正常中文文件夹
![图5：群晖显示正常中文文件夹](https://github.com/remotely-save/remotely-save/assets/6058326/b913cb91-c77e-4c49-a4e0-88797cdd47af)

图6：群晖显示正确同步的文件
![图6：群晖显示正确同步的文件](https://github.com/remotely-save/remotely-save/assets/6058326/d1c3e57c-badc-4495-8c0a-38e416234551)

以下是Log：
[LOGGING-NOTE (iPhone).md](https://github.com/remotely-save/remotely-save/files/14667260/LOGGING-NOTE.iPhone.md)

**Comment by fyears** [comment]
@IAvision

**Comment by fyears** [comment]
已经修复。可以用 brat 安装 0.4.8 来试用。谢谢你提供的 case！

**Comment by IAvision** [comment]
> 已经修复。可以用 brat 安装 0.4.8 来试用。谢谢你提供的 case！

如何安装这个版本？
![1](https://github.com/remotely-save/remotely-save/assets/6058326/7a9487db-4f04-481c-b7e3-e5d22846bb2f)
![2](https://github.com/remotely-save/remotely-save/assets/6058326/19b9be30-3bdb-4bcd-a0c8-85bebe11390c)

**Comment by fyears** [comment]
你好，已更新，现在安装了。可以在 brat 里重试
