### ISSUE TITLE
[Bug]: overwrite files syncing android and windows.

### ISSUE THREAD

**Issue by valuables3327** [remotely-save/remotely-save#538]
### What happened?

i create a vault in windows then install remotely save plugin then connect it to onedrive then add some notes with some attachments like photos and video (totally 10mb), then create a  new vault in android and install remotely save plugin then connect it to onedrive then manual sync. it tryes to download notes, when it fineshed i try to sync manually in android again, logically it shoulnd do anything again, but it tries to upload files from android to onedrive (why ?). and this action make pc also to upload and overwrite files in onedrive again. in whole of this issue loop i didnt do ANY modificatoin my files. what should i do ?

### What OS are you using?

Windows, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.3.40

### Version of Obsidian

1.5.8

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
a new version in a few days should fix this

**Comment by fyears** [comment]
I **think** that's because of some bugs in time comparation. But in the new version 0.4.x the bug **should** be fixed. Right now the version is of beta and you need to install it via BRAT.
