### ISSUE TITLE
[Bug]: ios系统，群晖WebDAV同步bug

### ISSUE THREAD

**Issue by wwwliyelinhot** [remotely-save/remotely-save#539]
### What happened?

我使用旧版本的obsidian，更新了0.3.40版本的remotely-save，同步成功。
使用1.5.8新版本的obsidian，0.3.40版本的remotely-save，同步就失败了。

填写地址的地方，使用域名来填写地址本地或者远程都会同步失败
使用ip来填写本地同步就会成功。
同样的填写方式，更新最近版本的obsidian与remotely-save，android、PC都没有问题，可以本地或者远程同步。
![1](https://github.com/remotely-save/remotely-save/assets/32222343/ee53bad0-dd02-49f0-b381-f4d0c322ed2d)
![2](https://github.com/remotely-save/remotely-save/assets/32222343/c7e672f7-d4c6-41e6-a2f6-f08f0b724fb1)

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.3.40

### Version of Obsidian

1.5.8

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
最新版 obsidian 不支持 http 连接了。需要自己签上合法的 https 证书
