### ISSUE TITLE
[Bug]: A lot of blank editing pages will open

### ISSUE THREAD

**Issue by shuishuijiao** [remotely-save/remotely-save#540]
### What happened?

after click sync button, close Obsidian app and open it again, then, you will You will see a lot of blank pages
![image](https://github.com/remotely-save/remotely-save/assets/98439380/d07814cb-0325-437e-a5ee-ca5d333e724c)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (腾讯云 COS Tencent Cloud COS)

### Version of the plugin

0.3.40

### Version of Obsidian

1.5.8

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Are you using any other plugins?
