### ISSUE TITLE
[Feature Request]: Can I add a sync status on the mobile version?

### ISSUE THREAD

**Issue by smilesxsy** [remotely-save/remotely-save#541]
### What feature are you suggesting?

I want to know if the sync has been done on the mobile version, and how long it has been synced

### What remote cloud services are you using, or suggesting adding the feature to?

webdav (NextCloud)

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
latest beta version 0.4.x allows setting status bar on mobile. you could install brat then install beta remotely save to try. or wait for the stable release
