### ISSUE TITLE
iOS: WebDAV Obsidian folder in Files app missing

### ISSUE THREAD

**Issue by thgie** [remotely-save/remotely-save#542]
### What happened?

I used the plugin for a while now, Linux on one side, and iOS on the other. Everything still works well. But I used to have access to the synced Obsidian folder in the iOS Files app. 

This is no longer the case and I suspect iOS moved the folder. The plugins output says the folder is at

- capacitor://localhost/_capacitor_file_/var/mobile/Containe%0Ars/Data/Application/11DEF213-5E96-41F6-A577-%0ADFOEF18B9543/Documents/Agenda

Sync still works fine. The problem is that I used this Obsidian vault to sync some additional files that I accessed from another iOS app (todo.txt), which doesn’t work anymore now. 

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.3.40

### Version of Obsidian

1.5.11 (133)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
hi but i don't understand you questions clearly. so do you mean you vault cannot be accessible in ios Files app anymore?

I checkout my iPhone, and I can access the vault in Files app -> Browse tab -> On my iPhone (in Locations section) -> Obsidian -> all vault folders are there

**Comment by thgie** [comment]
Exactly! I used to have my Vault folder in that location that you pointed out now. But it's no longer there. I can't manually access the folder through the iOS Files app anymore. But the sync to webdav still works fine.

**Comment by thgie** [comment]
Addendum: Syncthing has the same issue. Folder between two machines is syncing, but on iOS I can't access the syncthing folder through the Files app. So it's an iOS thing.

**Comment by fyears** [comment]
i am sorry to hear that.

but the situation is like what you said, it's likely to be an ios thing. maybe you can double check your files app carefully (are you inside the icloud folder, etc) or ask the question in the obsidian forum.

the plugin solely relies on obsidian's api to operate on the files **in** the vault, and it's **unable** to change the location of the vault itself at all.
