### ISSUE TITLE
[Bug]: Failed to fetch error while getting_remote_extra_meta on mobile

### ISSUE THREAD

**Issue by weebkent** [remotely-save/remotely-save#544]
### What happened?

Error code:

remotely-save-1711287246507: abort sync, triggerSource=manual, error while getting_extra_meta
Failed to fetch

Desktop Obsidian synced fine, mobile has this error for me

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

0.3.40

### Version of Obsidian

1.5.11 (133)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
maybe you could check your network connection?

**Comment by weebkent** [comment]
My network is fine, I even did the Check Connectivity in the plugin with no issues. It just gets stuck on step 4 for syncing and fails.

**Comment by fyears** [comment]
no clues yet. but don’t need to wipe obsidian, would you like to try to create another vault and create some non empty test files and try to sybc?

**Comment by weebkent** [comment]
So I've opened my secondary vault that went unused, updated the plugins for both the desktop and mobile version, and it worked just fine. Did a test sync with an image attached to a note. I forgot to mention on the original bug report, in the main vault I tried to troubleshoot by uninstalling and reinstalling the plugin in case it was just a bad update (as in download interrupted and breaking it) and that doesn't seem to be the case.

Also, unfortunately I can't check the logs. I do know how to do USB debugging since I rooted my phone, but the port got physically broken a while back and now I can't transfer data using wires.

As I'm writing this right now it seems like the plugin just fixed itself and I'm not sure why. Pretty sure plugin settings/updates are separated by vault so I doubt updating the plugin then re-authenticating in the secondary vault fixed the issue in the primary vault. Will update if it stops working again.

**Comment by fyears** [comment]
oh well. that's mysterious.

in fact you could use the plugin Logstravaganza to directly view the log on your phone.

but anyways, good news is that it gets work now. let me close this issue. feel free to create a new one if any other problems occur.

and **always remember to backup your vault manually**
