### ISSUE TITLE
[Bug]: 群辉webdav，同步成功，但是文件未同步

### ISSUE THREAD

**Issue by anooki-c** [remotely-save/remotely-save#545]
### What happened?

连接检测也通过，点击同步也提示同步完成，但是文件未同步
![image](https://github.com/remotely-save/remotely-save/assets/55230532/857958d6-3fa2-4d43-8bda-f3732916d88f)
![image](https://github.com/remotely-save/remotely-save/assets/55230532/721a3169-9dd6-4b21-acdd-dacd9afe0b10)
远程地址：/webdav/Obsidian/aaa
插件中服务地址https://群辉地址:5006//webdav/Obsidian/aaa

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.3.40

### Version of Obsidian

1.5.11

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
文件未同步，是什么症状呢？

**Comment by anooki-c** [comment]
> 文件未同步，是什么症状呢？

就是远程群晖文件夹里有很多笔记，但是同步完成之后，本地还是没有任何笔记文件，依然是空的

**Comment by PhoenixPtt** [comment]
我用的是坚果云webdav
单向同步：从电脑同步到云端是正常的，但是从云端拉取到手机失败了
![Screenshot_20240325_104352](https://github.com/remotely-save/remotely-save/assets/68508116/257eb879-c331-4e64-bfd4-4bb9b3f74e1c)

**Comment by PhoenixPtt** [comment]
我用的是坚果云webdav
单向同步：从电脑同步到云端是正常的，但是从云端拉取到手机失败了
![Screenshot_20240325_104352](https://github.com/remotely-save/remotely-save/assets/68508116/efd2d238-0100-4762-b8eb-6aa1beaf7e74)

**Comment by PhoenixPtt** [comment]
从电脑端到坚果云端：
每次更改一个文件，上传时会把所有文件再重新上传一遍。因为检测结果是都发生变更了。

**Comment by fyears** [comment]
坚果云的 webdav 有限制，拉取不了完整版的列表，无法修复的。可以试试 infinicloud 是否有同样的症状

**Comment by anooki-c** [comment]
> 我用的是坚果云webdav 单向同步：从电脑同步到云端是正常的，但是从云端拉取到手机失败了 ![image](https://private-user-images.githubusercontent.com/68508116/316378644-bd455975-23a2-4b55-b582-a88ad9a11b97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNDM1MDksIm5iZiI6MTcxMTM0MzIwOSwicGF0aCI6Ii82ODUwODExNi8zMTYzNzg2NDQtYmQ0NTU5NzUtMjNhMi00YjU1LWI1ODItYTg4YWQ5YTExYjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA1MDY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MjM5NzM4MmIwYzI5OWNmOGMyZWMzZWQ0MjU0MmI4NzFmZmU1YWVmNjI1YjUzZjRkZjRlNmY5NTM5YmQ1MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IYfYnzn6TW3qnL0fk05esR8OcRwE6284V-GVFwmy7D8)

我发现我也是这样的，能上传到云端，不能从云端同步到本地，之前iphone可以同步，现在也不行了

**Comment by PhoenixPtt** [comment]
> 坚果云的 webdav 有限制，拉取不了完整版的列表，无法修复的。可以试试 infinicloud 是否有同样的症状
有国内的网站可以选择吗？担心国外网站的速度

**Comment by fyears** [comment]
> > 我用的是坚果云webdav 单向同步：从电脑同步到云端是正常的，但是从云端拉取到手机失败了 ![image](https://private-user-images.githubusercontent.com/68508116/316378644-bd455975-23a2-4b55-b582-a88ad9a11b97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNDM1MDksIm5iZiI6MTcxMTM0MzIwOSwicGF0aCI6Ii82ODUwODExNi8zMTYzNzg2NDQtYmQ0NTU5NzUtMjNhMi00YjU1LWI1ODItYTg4YWQ5YTExYjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA1MDY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MjM5NzM4MmIwYzI5OWNmOGMyZWMzZWQ0MjU0MmI4NzFmZmU1YWVmNjI1YjUzZjRkZjRlNmY5NTM5YmQ1MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IYfYnzn6TW3qnL0fk05esR8OcRwE6284V-GVFwmy7D8)
> 
> 
> 
> 我发现我也是这样的，能上传到云端，不能从云端同步到本地，之前iphone可以同步，现在也不行了

我有空试试先。这里描述还是有点抽象

**Comment by anooki-c** [comment]
> > > 我用的是坚果云webdav 单向同步：从电脑同步到云端是正常的，但是从云端拉取到手机失败了 ![image](https://private-user-images.githubusercontent.com/68508116/316378644-bd455975-23a2-4b55-b582-a88ad9a11b97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNDM1MDksIm5iZiI6MTcxMTM0MzIwOSwicGF0aCI6Ii82ODUwODExNi8zMTYzNzg2NDQtYmQ0NTU5NzUtMjNhMi00YjU1LWI1ODItYTg4YWQ5YTExYjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA1MDY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MjM5NzM4MmIwYzI5OWNmOGMyZWMzZWQ0MjU0MmI4NzFmZmU1YWVmNjI1YjUzZjRkZjRlNmY5NTM5YmQ1MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IYfYnzn6TW3qnL0fk05esR8OcRwE6284V-GVFwmy7D8)
> > 
> > 
> > 我发现我也是这样的，能上传到云端，不能从云端同步到本地，之前iphone可以同步，现在也不行了
> 
> 我有空试试先。这里描述还是有点抽象

我把同步链接改了一下，原来链接是这样写的：
公司电脑：https://群辉地址:5006//webdav/Obsidian/，可以正常同步到云端。
Obsidian下面有个文件夹aaa，然后家里的电脑同步链接到aaa文件夹，
https://群辉地址:5006//webdav/Obsidian/aaa，这样就无法同步了（本地已经有空的aaa文件夹了）
最后是把云端所有文件都删了，
家里电脑和公司电脑的链接都改成https://群辉地址:5006//webdav/Obsidian/aaa。
然后这样就解决了

**Comment by fyears** [comment]
那可能就是一些奇怪的权限设置问题了，按道理对于插件来说目录有多少层都是等价的。

既然问题解决了，那么先关闭此 issue 了，谢谢你！
