### ISSUE TITLE
[Bug]: 更新后，无法连接webdav

### ISSUE THREAD

**Issue by hanzch** [remotely-save/remotely-save#547]
### What happened?

你好，似乎是因为windows电脑端obsidian主程序自动更新（1.5.3~1.5.11）后，插件似乎出现了问题，更新提示失败。
测试了一下，检查连接，已经连接失败了！但在此之前，我确认一切都是好的。

![image](https://github.com/remotely-save/remotely-save/assets/1555910/a531468c-02fe-4459-b1a1-a7999e04bef4)

同时，手机端目前依旧可以连接成功，并使用同步功能。
于是我更新了插件版本，0.3.x -> 0.4.10 ，但是问题依旧。
期间，未安装任何插件，未更改任何设置。

我尝试卸载新版本，回退到1.5.3的版本，但使用1.5.3安装包完成后，自动会变为1.5.11

感谢

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.3.x ~ 0.4.10

### Version of Obsidian

1.5.11

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
是坚果云吗？

**Comment by fyears** [comment]
你在用 catalyst 版本？

**Comment by hanzch** [comment]
> 是坚果云吗？

不是坚果云，非catalyst ，用的公开版本，我这里显示我的安装程序是1.5.3，程序自动更新到1.5.11

**Comment by fyears** [comment]
seafile 不是很懂如何部署，需要 linux 服务器吗？或者你有没有注册 infinicloud 或者坚果云是否可以访问？

此外，试试将手机端的 data.json 导入到电脑端？排查配置不一致的情况？如果不知道如何复制的话，remotely save 有一个倒出二维码或者链接的方法。

此外，可以看看有什么错误提示？https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/check_console_output.md

**Comment by hanzch** [comment]
找到问题了，我填的地址，通过hosts文件映射了本地局域网的地址，但新版本似乎跳过这个解析过程，所以失败了。
再次感谢您的帮助，和开放这个好用的插件！祝一切顺利！~
