### ISSUE TITLE
[Bug]: 设置跳过大文件后无法同步

### ISSUE THREAD

**Issue by jedy** [remotely-save/remotely-save#549]
### What happened?

生成同步计划时就中断了。
![image](https://github.com/remotely-save/remotely-save/assets/1589263/f13e1aab-40f2-4fea-a851-77c9dab2d6d5)

### What OS are you using?

macOS, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.4.10

### Version of Obsidian

1.5.11

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
收到，我有空的时候尝试看一下。你这个问题可以用 “忽略的文件”（设置里面）填入文件名 xxx.pdf 暂且跳过

**Comment by fyears** [comment]
此外这个文件在远端本来就有的吗？还是本来没有的？

**Comment by jedy** [comment]
都测试过，不管有没有都会报错。

**Comment by fyears** [comment]
设置了文件黑名单后，又是什么错呢？

**Comment by fyears** [comment]
fixed in https://github.com/remotely-save/remotely-save/releases/tag/0.4.11

**Comment by jedy** [comment]
测试没问题了，谢谢
