### ISSUE TITLE
[Bug]: 不支持又拍云

### ISSUE THREAD

**Issue by svcvit** [remotely-save/remotely-save#550]
### What happened?

I am using Upyun's S3. Data synchronization on the Mac is working fine, but there is an error when pulling data on the mobile device.

So I opened a new vault on the Mac side and tested this error. The error message is shown in the following image.

### What OS are you using?

macOS, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3, others

### Version of the plugin

0.4.10

### Version of Obsidian

1.5.11

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
有设置忽略文件吗？

新建库也拉不下来吗？

**Comment by fyears** [comment]
这些文件夹里，有文件吗？此外上传这些文件夹到又拍云，是怎么上传的呢？又拍云有生成 `文件夹名称/` 这种 object 吗？

**Comment by svcvit** [comment]
> 这些文件夹里，有文件吗？此外上传这些文件夹到又拍云，是怎么上传的呢？又拍云有生成 `文件夹名称/` 这种 object 吗？

文件夹里有文件，都是一些图片。我开始以为是路径中文名问题，后来全部替换了英文路径。还是无法拉下来，上传都是正常的。
又拍云上面看是这样的。

![Xnip2024-03-25_20-32-52](https://github.com/remotely-save/remotely-save/assets/3839507/1eb6250b-941c-48b6-bd5c-29c0a8348837)

**Comment by svcvit** [comment]
> 有设置忽略文件吗？
> 
> 新建库也拉不下来吗？

没有设置忽略文件夹，新库拉不下来。

**Comment by fyears** [comment]
上传也是用 remotely save 上传的吗？

我得注册一个又拍云试试，这个有免费额度吗？

**Comment by fyears** [comment]
blog_source 是你的 bucket 名称，还是 vault 名称？

很奇怪，在你的最后一幅截图里，文件夹路径没有这一部分？是省略了显示还是真的没有？

**Comment by svcvit** [comment]
> blog_source 是你的 bucket 名称，还是 vault 名称？
> 
> 很奇怪，在你的最后一幅截图里，文件夹路径没有这一部分？是省略了显示还是真的没有？

blog_source 是我第一次上传文件的主目录，因为怎么拉取都不行，我后来删了这个目录。第二张图是我删了这个主目录，删了中文路径，重新上传之后截的图。因为折腾了好几遍 ：）。又拍云以前有免费额度的，现在不知道有没有了。如果需要的话，我可以提供一个子账户。我的邮箱 svcvit@gmail.com

**Comment by fyears** [comment]
已测试并确认了又拍云的支持有问题，看看怎么解决

**Comment by fyears** [comment]
此外，又拍云这里我看到都是公有文件，上传笔记到这里会有风险，请注意

**Comment by fyears** [comment]
0.4.17 已支持

**Comment by fyears** [comment]
https://github.com/remotely-save/remotely-save/blob/master/docs/remote_services/s3_upyun/README.zh-cn.md
