### ISSUE TITLE
[Bug]: 修改百分比保护去除失效

### ISSUE THREAD

**Issue by keeyangyy** [remotely-save/remotely-save#551]
### What happened?

同步的时候即使把修改百分比设置到100(去除此保护)，在百分百修改的时候依旧同步不了，这时显示不允许>=100%的变更，应该改成不允许>100%变更吧。出现在了安卓和ipad上。

还有一个小bug，ipad端更新后，插件内设置点检查连接会显示 

> your s3 endpoint could only be https, not http, because of the IOS restriction. 

ipad版本是17.3.1，用的阿里云oss，但是实际上同步发现是正常的。

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.4.10

### Version of Obsidian

最新版

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
1. 所以实际上有多少变更呢？全都变了吗？为什么会有这种场景？是日期更新有问题吗？
2. 你的 ipad 的 obsidian 更新到最新版了吗？你的 endpoint 是 https 开头还是 http 开头还是都不是（而是纯域名）？

**Comment by keeyangyy** [comment]
1.实际上全部变更。这个是在我其中一个库上出现，因为用了加密，所以把阿里云oss远端库清理干净，这时候PC先更新(上传到远端)，一切正常，这时候再用ipad和安卓去更新，就会出现需要全部变更的情况。以前在安卓上似乎也出现过类似的情况，好像第一次更新安卓会先download所有文件，第二次更新会再次upload所有文件，然后后面就是正常更新了。
2.ipad的obsidian是先更新到最新版的，endpoint填了纯域名。

**Comment by keeyangyy** [comment]
我试了一下把域名补全，就没有报错了，这个设置以前一直沿用下来，所以没注意到

**Comment by keeyangyy** [comment]
我的另一个库没有加密，所以不用因为改加密而清除远端库，更新后所有同样的设备都工作正常。另外这里感觉新版本同步速度明显加快了，把metadata删了也没有影响。

**Comment by fyears** [comment]
fixed in https://github.com/remotely-save/remotely-save/releases/tag/0.4.11
