### ISSUE TITLE
[Bug]: Allowed Ratio Property is not disabled when set to 100%

### ISSUE THREAD

**Issue by Wistelle** [remotely-save/remotely-save#553]
### What happened?

The Abort Sync If Modification Above Percentage will always trigger, regardless of the setting.

![image](https://github.com/remotely-save/remotely-save/assets/18022945/28c68163-cade-4916-ac4b-3ce5ed49e81c)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.4.10

### Version of Obsidian

1.5.11

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
how many files in your local vault? how many files in your remote service? are they share the same names but different contents? i am looking for ways to construct the reproduction

**Comment by Wistelle** [comment]
At the time, apart from the .obsidian folder, I had 2 files in my local vault as seen in the screenshot

MD Basic is just some basic markdown

Tasks was a repo that contained a code block for another plugin `Tasks`.

After deleting and recreating `Tasks` it now works as expected.

My guess to the cause was that the Tasks Plugin was not being called correctly.
