### ISSUE TITLE
[Bug]: After updating to the latest version, remotely-save cannot detect the rename operation.

### ISSUE THREAD

**Issue by langshangyuan** [remotely-save/remotely-save#554]
### What happened?

After updating to the latest version and keep the local and remote data identical, I perform the rename folder operation. Then after I run the start sync command manually, the original folder name will be downloaded from the remote. That is, my vault contains two folder, one is the folder with old name, and one is the folder with new name.

### What OS are you using?

Linux

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3

### Version of the plugin

0.4.10

### Version of Obsidian

1.5.11

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
that's not expected. do you have synced at least once before the rename operation?

**Comment by langshangyuan** [comment]
Yes, I have synced at least once before the rename operation. Then, I delete the local database, and delete the remote storage, and start a fresh sync. Now the sync opertion aborts and I get the following error message (part of the error message).

```
Error: Space/Computer Science/Computer Programming/Programming Language/Lisp/Lisp Documentations/: ENOENT: no such file or directory, rename '/home/langshang/Dropbox/Desktop/Brain/Space/Computer Science/Computer Programming/Programming Language/Lisp/Lisp Documentations/' -> '/home/langshang/Dropbox/Desktop/Brain/.trash/Lisp Documentations 2'
        at eval (plugin:remotely-save:313:120663)
```

**Comment by fyears** [comment]
have you enabled the settings  "delete empty folders"?

**Comment by langshangyuan** [comment]
Yes, I have enabled this option.

**Comment by fyears** [comment]
**should** be fixed in https://github.com/remotely-save/remotely-save/releases/tag/0.4.11
