### ISSUE TITLE
[Bug]:  abort Syncing triggerSource=manual, error while generating plan

### ISSUE THREAD

**Issue by Zyrron** [remotely-save/remotely-save#555]
### What happened?

I receive this error Message. any help?

1/2 Remotely Save starts running (onedrive)

remotely-save-1711441327999: abort sync,
triggerSource=manual, error while
generating_plan

Cannot read properties Of undefined (reading
'endsWlth')

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.4.10

### Version of Obsidian

1.5.11

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
do you have screenshot?

**Comment by fyears** [comment]
fixed in https://github.com/remotely-save/remotely-save/releases/tag/0.4.11
