### ISSUE TITLE
[Bug]: Enabling delete empty folders on local and remote will abort sync. 

### ISSUE THREAD

**Issue by ashrudral** [remotely-save/remotely-save#556]
### What happened?

Error:
Abort sync, error while syncing. The source folder doesn't exist.

This happens when you delete or move any folder on the local device. The plugin thinks there is no source folder, but there in a remote folder. So it aborts sync.

As you said, the new version don't know what is a folder, it only deals with files. This is a problem because sync won't happen when "delete empty folders" is enabled.

This happens on both windows and android. 

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

1.4.10

### Version of Obsidian

1.5.11

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> This is a problem because sync won't happen when "delete empty folders" is enabled.


so you've enabled this, right? let me try to debug it when i am free.

**Comment by ashrudral** [comment]
Yes I have enabled "delete empty folders".

When you debug, the problem will happen when you move or delete a folder on local device. Because plugin will see that folder in the remote, but not on source. It will give error :

"abort sync. Error while syncing. The source folder don't exist."

**Comment by fyears** [comment]
fixed in https://github.com/remotely-save/remotely-save/releases/tag/0.4.11

**Comment by ashrudral** [comment]
The sync is not aboring now. But the new update 0.4.11 has caused another bug #558 in the delete empty folder feature.
