### ISSUE TITLE
[Bug]: 同步失败，无法加密？

### ISSUE THREAD

**Issue by YIRU69** [remotely-save/remotely-save#557]
### What happened?

我使用新的库来在进行同步的时候，无法进行同步，测试了很多遍，发现自己的库很多文件都出现了这个问题

![image](https://github.com/remotely-save/remotely-save/assets/48148292/09e68bb2-08ad-41cd-a71a-c9049d17dc4b)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (腾讯云 COS Tencent Cloud COS)

### Version of the plugin

4.1

### Version of Obsidian

1.5.10

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by YIRU69** [comment]
[无法加密的文件.zip](https://github.com/remotely-save/remotely-save/files/14759403/default.zip)
这是其中的一个文件，您可以看看

**Comment by fyears** [comment]
您是不是已经在别的设备的旧版本加密过，然后这个设备安装了新版本？

请去设置，将加密方式改为 openssl enc 再试试

**Comment by YIRU69** [comment]
不太明白。
我想说的是，我通过一个新的ob库，以及新的远程仓库，对这个无法加密的文件进行同步测试。结果和我预期的一样，发生的同样的错误。所以我认为这个错误是否是因为当前的算法（默认推荐的）是不能对这个文件进行加密呢？

我理解的您的意思是如果文件进行了二次加密就会出现这样的错误对吧。所以我的回答是一个新的ob库，以及新的远程仓库会过程二次加密的情况吗？当然要声明一下，我的新的远程库我只是把里面的文件都清空了。

**Comment by YIRU69** [comment]
我补充一下，可能我的截图产生了误导，这个截图是我在发生错误后，第二次运行 save 的结果。第一次的截图是显示这个文件无法被加密。您可以根据我提供的无法加密文件测试一下是否可以进行同步。

**Comment by fyears** [comment]
找到了一些 bug，可能是加密方式有点混乱。请更新一下新版本 0.4.11 试试呢

**Comment by YIRU69** [comment]
同样的问题，这是测试文件的同步

![image](https://github.com/remotely-save/remotely-save/assets/48148292/1d3cedbf-e148-4e54-a23a-c923d7f3a6ba)

**Comment by fyears** [comment]
> 我认为这个错误是否是因为当前的算法（默认推荐的）是不能对这个文件进行加密呢？

是的。用 openssl enc 试试

**Comment by YIRU69** [comment]
我切换了新的同步方法，现在可以正常同步的。（我前面描述的同步方法是openssl enc）
