### ISSUE TITLE
[Feature Request]: Confirm before quitting (to sync)

### ISSUE THREAD

**Issue by anandkumar89** [remotely-save/remotely-save#559]
### What feature are you suggesting?

If it were possible to pop-up a dialog to confirm before quitting on desktops - would be useful. 

It may be difficult to implement on mobile (can be implemented when user tries to go back (back gesture)) but could be possible to push an app-notification when app is closed/minimized.

I'm just trying to think of ways to avoid conflicts - I (and possibly many) work on one device at a time with few minutes of gap before using obsidian on other device. Ensuring sync every time we're done with obsidian is nice way to keep things fresh across all devices. startup sync is first step, second is close-time sync. Hence this request.

### What remote cloud services are you using, or suggesting adding the feature to?

webdav, others

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
sorry but no, no reliable way to do that. 

believe me, i also have thought about this.

you can think of obsidian as a special web browser like chrome, with different set of api.

other plugins don't have solutions too. https://github.com/denolehov/obsidian-git/issues/13 

the only workaround is using scheduled auto sync with short intervals which currently can be set in the settings

**Comment by fyears** [comment]
currently the plugin already has the feature showing status in status bar (contributed by community). you could have a look at at
