### ISSUE TITLE
[Bug]: 跳过50m的文件设置失效

### ISSUE THREAD

**Issue by qiekqiek** [remotely-save/remotely-save#560]
### What happened?

之前会正常跳过超过50m的文件，现在不会了，说不知道怎么做。
![image](https://github.com/remotely-save/remotely-save/assets/49683931/fa2a4dbc-67c5-4c63-a007-628735dfa223)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.4.11

### Version of Obsidian

1.5.11

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
更新一下最新版
