### ISSUE TITLE
[Bug]: "#" cannot be used in the folder name, otherwise, sync will fail

### ISSUE THREAD

**Issue by xiezhensheng** [remotely-save/remotely-save#562]
### What happened?

I am using OneDrive to store the Obsidian files. And on iOS devices, I am using remotely-save to sync my notes.
The sync was consistently failed "url must be provided, and it must be a string"
Later, I realized if I change one of the folder's name from "C#" to "CSharp". The sync issue will be fixed.

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

any version

### Version of Obsidian

any version

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
will be fixed in the 0.4.12
