### ISSUE TITLE
[Bug]:设置了七牛云s3域名报错 plugin:remotely-save:318 remotely-save-17**********：中断同步，同步来源=autoOnceInit，出错阶段=syncing

### ISSUE THREAD

**Issue by haha4445** [remotely-save/remotely-save#563]
### What happened?

设置了七牛云对象存储(有S3地址  文档 https://developer.qiniu.com/kodo/4088/s3-access-domainname )，同步时连接服务器也是可以的，控制台输出如图，报错信息不知是我设置问题还是与七牛云的兼容问题，如果无兼容问题我再排查下
![2024-03-28](https://github.com/remotely-save/remotely-save/assets/30338449/65f75c43-07d1-4efe-90fc-b2b06e2ede89)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3

### Version of the plugin

0.4.11

### Version of Obsidian

1.5.11

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
没用过七牛。这个注册后要实名吗？有免费额度吗？得查一下

**Comment by fyears** [comment]
S3 URL Style 可以改一下用 path stule 试试
