### ISSUE TITLE
[Bug]: AWS S3 user's policy configuration gives me 403

### ISSUE THREAD

**Issue by Hamza-Megahed** [remotely-save/remotely-save#564]
### What happened?

Followed the steps in S3 setup guide for user's policy configuration in https://github.com/remotely-save/remotely-save/blob/master/docs/remote_services/s3_general/s3_user_policy.md but hit `An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied`

This policy fixed it for me:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ObsidianObjects",
            "Effect": "Allow",
            "Action": [
                "s3:HeadObject",
                "s3:ListBucket",
                "s3:PutObject",
                "s3:CopyObject",
                "s3:UploadPart",
                "s3:UploadPartCopy",
                "s3:ListMultipartUploads",
                "s3:AbortMultipartUpload",
                "s3:CompleteMultipartUpload",
                "s3:ListObjects",
                "s3:ListObjectsV2",
                "s3:ListParts",
                "s3:GetObject",
                "s3:GetObjectAttributes",
                "s3:DeleteObject",
                "s3:DeleteObjects"
            ],
            "Resource": [
                "arn:aws:s3:::my-bucket",
                "arn:aws:s3:::my-bucket/*"
            ]
        }
    ]
}
```

I added `s3:ListBucket` because it's required by `ListObjectsV2` according to official manual https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html , then added `arn:aws:s3:::my-bucket` to apply the policy to the bucket itself

**Comment by fyears** [comment]
thanks for reporting! and i will update the doc according to your description. i don't use official aws personally so no way to get the full picture...

so it seems that that difference is `"arn:aws:s3:::my-bucket",`?

**Comment by Hamza-Megahed** [comment]
I added `s3:ListBucket` because it's required by `ListObjectsV2` according to official manual https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html , then added `arn:aws:s3:::my-bucket` to apply the policy to the bucket itself

**Comment by fyears** [comment]
thx
