### ISSUE TITLE
[Bug]: Error "Invalid response: 405 Method not allowed" with Webdav sync

### ISSUE THREAD

**Issue by ibox0** [remotely-save/remotely-save#565]
### What happened?

When i try to sync from Linux i get a 405 Method not allowed error

webdav server is apache, working with other versions of the plugin

### What OS are you using?

Linux

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.3.40

### Version of Obsidian

1.5.11

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
any way to reproduce the error? and would you like to update the plugin to latest version 0.4.10 and try? thank you!

**Comment by ibox0** [comment]
Hi, 
i've updated to versiojn 0.4.11 and the issue is not present anymore, you can close the issue.

Thanks for your quick support.

Best regards

**Comment by ibox0** [comment]
Fixed in 0.4.11
