### ISSUE TITLE
[Bug]: 移动笔记至其它文件夹，会新同步（复制）一份笔记回原文件夹

### ISSUE THREAD

**Issue by jimchik** [remotely-save/remotely-save#566]
### What happened?

版本：0.4.10
操作：将obisidian 某文件夹的笔记移动至新的文件夹
结果：新的文件夹中有一篇被移动过去的笔记；但是，又会同步一篇同样的笔记到旧文件夹，造成笔记重复。

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (腾讯云 COS Tencent Cloud COS)

### Version of the plugin

0.4.10

### Version of Obsidian

1.5.11

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
请更新到最新版，然后去设置接近最下方的“重设之前同步记录”，进行一次同步，再往后的同步应该正常了。issue 里有其他同事也反映过这个问题

**Comment by fyears** [comment]
如果这样还不行的话，试试新建 vault 复现一下哈
