### ISSUE TITLE
[Bug]: Cannot connect to webdav server on ios with https

### ISSUE THREAD

**Issue by HWiwoiiii** [remotely-save/remotely-save#569]
### What happened?

WebDAV and SSL certificate has been set up properly. I can connect to the https address on my iPhone using https://apps.apple.com/app/id382551345 and many other WebDAV-supported applications. However, when I check the connection, it gives an error.
"Checking...
The webdav server cannot be reached (possible to be any of address/username/password/authtype errors).
Error: Request failed."

The https connection won't work on my windows as well but I can still use http connection 

Any help is appreciated 

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

Latest 

### Version of Obsidian

Latest 

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by HWiwoiiii** [comment]
The https connection won't work on my windows as well

**Comment by fyears** [comment]
are you using a self-signed certificate? obsidian and the plugin doesn't support self-signed.

**Comment by HWiwoiiii** [comment]
> are you using a self-signed certificate? obsidian and the plugin doesn't support self-signed.

I use the SSL certificate generated by Synology through Let's Encrypt. Is this certificate considered self-signed? Also, could you please provide a link to a tutorial for configuring a certificate for this plugin?

Thanks a lot

**Comment by HWiwoiiii** [comment]
> are you using a self-signed certificate? obsidian and the plugin doesn't support self-signed.

I have checked and it seems that the certificate from Let's Encrypt is not self-signed. Are there any other possibilities that the plugin gives this error? Thank you.

**Comment by fyears** [comment]
let's encrypt, when configured correctly, is not self-signed.

please try to follow https://github.com/remotely-save/remotely-save/tree/master/docs/remote_services/webdav_synology_webdav_server and see **any steps or settings** are different? 

only possible difficulties i could image, is the share folder being different, or forget to change the port number while switching http to https

**Comment by HWiwoiiii** [comment]
I kinda start to understand the issue here. I think it's still an SSL certificate problem. My SSL certificate is applied for my DDNS domain (host name?), but I don't really need to connect to my NAS from external connections. So, I ignored the port forwarding and these kinds of stuff. 

But here is an issue: even though I have set up my DDNS domain and applied a certificate from Let's Encrypt to it, I cannot access the domain on the browser (however, pinging it gives a reply). So I can't use the free domain that synology provided.

Then I realized if I don't have the need to access from external connections, I don't need to set up DDNS. However, SSL from Let's Encrypt can only apply for domain names, not my IP address. Is there a way that I don't need to set up external connections (DDNS and router configuration) and such to use remotely save on iOS? (As self-signed certificates and HTTP connections cannot be approved by Obsidian on iOS)

Thanks a lot

**Comment by fyears** [comment]
> I cannot access the domain on the browser (however, pinging it gives a reply). 

here is the key point. why can't you access the domain in the browser? what's the error returned by the browser?

using ddns is fine, and using https://example.com for internal address is also fine, really.

**Comment by HWiwoiiii** [comment]
The browser simply gives 
"This page isn’t working 
axs.synology.me is currently unable to handle this request.
HTTP ERROR 502" 

I will try to figure that out
Thank u

**Comment by HWiwoiiii** [comment]
> > I cannot access the domain on the browser (however, pinging it gives a reply).我无法在浏览器上访问该域（但是，对其进行 ping 操作会得到回复）。
> 
> here is the key point. why can't you access the domain in the browser? what's the error returned by the browser?这是关键点。为什么浏览器无法访问域名？浏览器返回的错误是什么？
> 
> using ddns is fine, and using https://example.com for internal address is also fine, really.使用 ddns 很好，使用 https://example.com 作为内部地址也很好，真的。

The browser simply gives 
"This page isn’t working 
axs.synology.me is currently unable to handle this request.
HTTP ERROR 502" 

I will try to figure that out
Thank u

**Comment by HWiwoiiii** [comment]
> > I cannot access the domain on the browser (however, pinging it gives a reply).
> 
> here is the key point. why can't you access the domain in the browser? what's the error returned by the browser?
> 
> using ddns is fine, and using https://example.com for internal address is also fine, really.

The browser simply gives
" 
This page isn’t working
asweee.synology.me is currently unable to handle this request.
HTTP ERROR 502
"
I will try to figure that out
Thank u

**Comment by HWiwoiiii** [comment]
https://kb.synology.com/en-us/DSM/tutorial/I_cannot_connect_to_my_Synology_device_via_DDNS

> Try connecting to the External IP address at the locations listed below. If the connection is successful, go through the Preliminary checks section again. If the connection fails, contact your router’s manufacturer to check if your parent router/modem supports the NAT loopback function.3 4

I saw this on synology official, could it be that the router's doesn't support "NAT loopback" function?

**Comment by HWiwoiiii** [comment]
I just turned off my proxy and tries to access the domain again, surprisingly the browser gives
```
Your website is not set up yet.
Web Station has been enabled. To learn more about hosting a website, refer to the "Web Station" section of DSM Help.
```
instead of 
```
This page isn’t working
asweee.synology.me is currently unable to handle this request.
HTTP ERROR 502
```
Why does it have any thing to do with my VPN settings?

EDIT:
After I added a port number after the domain, the site became accessible. Hurray!

**Comment by HWiwoiiii** [comment]
All works fabulous now, though I'm still a bit confused by the proxy setting on my laptop stops me from accessing DDNS set up on my NAS. thank you again for your help!

**Comment by fyears** [comment]
great. glad to hear that
