### ISSUE TITLE
[Feature Request]: Add setting to hide other mobile status bar items

### ISSUE THREAD

**Issue by kadisonm** [remotely-save/remotely-save#572]
### What feature are you suggesting?

Add a setting to hide other mobile status bar options. This way if the user wants, the status bar won't go off the screen displaying the word count and character counts but only show the sync status.

I added this into Remotely Sync, I can try and make a PR if you would like here. Not sure how different the structure is though.

### What remote cloud services are you using, or suggesting adding the feature to?

Dropbox

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Hi, thank you for considering submitting a PR!

But I think the bug for the mysterious margin on iPhone is more serious. I do not have sufficient css knowledge to fix it. Please see the screenshots below.

1. If the input area is not activated, the status bar position is ok.
2. If the input area is activated, the status bar position has more-than-needed margin...... which makes the visual effect undesirable.

The code is here https://github.com/remotely-save/remotely-save/blob/b674dd0f10c266229215b6af0756ef8797883d4d/src/misc.ts#L520 

Screenshot 1:
![f261f7efe1a8d61f89e5e824875a552](https://github.com/remotely-save/remotely-save/assets/1142836/a374f654-8261-4610-9231-e41b8f944d0a)

Screenshot 2:
![765979c774593ffc205c6bf0c2100f9](https://github.com/remotely-save/remotely-save/assets/1142836/c8b1e292-9736-46e6-a633-439ddf32b511)

**Comment by kadisonm** [comment]
I'll have a look on my pc later but maybe the toolbar has a different height or margin to the navbar.

Might need to check whether the navbar or toolbar is displayed and adjust the height accordingly.

**Comment by kadisonm** [comment]
It does seem like the heights are different. Might be why it's too far up when the toolbar shows.

![explorer_r94oBzkhTm](https://github.com/remotely-save/remotely-save/assets/134670047/685d0aea-b766-4cd2-afcb-d42fc67d1be3)

![explorer_unOS3F2bo2](https://github.com/remotely-save/remotely-save/assets/134670047/7f09e927-2c47-48ad-bf36-340d565e4741)

You can add a mutation observer for the creation of the navbar or toolbar. Then get its height and change the status bar's margin.

**Comment by fyears** [comment]
may i ask how to obtain the mobile view on pc?

**Comment by kadisonm** [comment]
Under console do 'this.app.emulateMobile(true)'

**Comment by fyears** [comment]
while the status bar is usable now, but I don't feel the urgency to hide other items. (why need to hide? i am afraid of too many configuration options now)

this issue is closed for now. feel free to submit a pr when you are not busy. thanks!

**Comment by kadisonm** [comment]
> this issue is closed for now. feel free to submit a pr when you are not busy. thanks!

No worries, will do. :)

> while the status bar is usable now, but I don't feel the urgency to hide other items. (why need to hide? i am afraid of too many configuration options now)

Mostly because it takes up a lot of space and you can't use other plugins to hide them since it will hide for desktop too. (I assume, maybe some plugin has mobile only options)
