### ISSUE TITLE
[Feature Request]: Hide unimportant notifications

### ISSUE THREAD

**Issue by john-walks-slow** [remotely-save/remotely-save#573]
### What feature are you suggesting?

It would be nice to have an option to hide unimportant notifications. Currently, notifications are shown quite frequently, which could be disturbing. 

![image](https://github.com/remotely-save/remotely-save/assets/34511166/14a041a3-1864-4147-b7bc-95bf4268b683)
> For example, I see notifications like this every 30 seconds.

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
are you using sync on save or auto scheduled sync?

**Comment by john-walks-slow** [comment]
I'm using sync on save.

**Comment by fyears** [comment]
new version 0.4.13 should fix this
