### ISSUE TITLE
[Bug]: remotely-save-1711892147574:中断同步，同 步来源=manual,出错阶段=syncing

### ISSUE THREAD

**Issue by leiman147** [remotely-save/remotely-save#574]
### What happened?

同步文件时出错，大部分是图片。报错 request failed stat
![20240331_092233](https://github.com/remotely-save/remotely-save/assets/63769905/32d75e23-ce8c-48a2-a188-b1188293739d)
us 409

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.3.37

### Version of Obsidian

1.5.11

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by yuyuzeiqi** [comment]
更新啥呀？obsidian还是插件？
