### ISSUE TITLE
[Bug]: 同步速度变慢

### ISSUE THREAD

**Issue by keeyangyy** [remotely-save/remotely-save#576]
### What happened?

0.4.11同步很快一切正常，更新0.4.12后同步速度明显变慢，不做修改多次同步依旧很慢，这是正常的吗？

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.4.12

### Version of Obsidian

v1.5.11

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
你好，

可能受到这个 bug 影响： https://github.com/remotely-save/remotely-save/issues/575

请更新 0.4.14 试试。如果还是有问题的话，可以重开 issue。
