### ISSUE TITLE
[Bug]: how to handle empty folders

### ISSUE THREAD

**Issue by daledesilva** [remotely-save/remotely-save#578]
### What happened?

I have a vault on my iPad and on my Mac laptop. After updating to 0.4.12 and syncing both devices, I found that several files on my iPad don't sync even those the plugin reports syncing successfully on both devices. I've tried syncing multiple times and also tried deleting the Sync plans and Sync details but the same result occurs. the details 

Screenshot from desktop after sync and exported sync plan:

<img width="737" alt="Desktop files" src="https://github.com/remotely-save/remotely-save/assets/18710973/0e04bdd2-66e5-4790-b448-0b4bba502dd1">

---

Screenshot from iPad after sync and exported sync plan:

### What OS are you using?

macOS, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

0.4.12

### Version of Obsidian

1.5.11

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Hi @daledesilva 

Thanks for your report!

(I've commented out your link to sync plan for safety)

It seems that the folders being skipped, are the folders that contain no files recursively. 

For example, `Assets/` seems to be containing `Assets/Ink/` and `Assets/Ink/Writing/`, **but no actual files inside**. So the folders are skipped. You can create any non-empty files inside the folder, and then the files as well as the folders, will be synced or created respectively. `Quick Note/` is another example, containing only sub folders but no files.

Or, if you are sure you have some actual files before but they are not synced, please point it out and I will try to investigate the problem with your sync plan files.

**Comment by daledesilva** [comment]
Thanks for responding. I just checked and you're correct, they are all empty.
I'm assuming that not transferring empty folders is a technical limitation?
I would have hoped they would transfer.

Considering they don't, I've had a look at the settings and I think the **Action For Empty Folders** could be worded a little differently to avoid confusion. But I'd like to clarify one of the settings first.

I created a folder with a file in it on my desktop.
Then I sync'd it to my ipad.
Then I deleted the file and left the empty folder on my desktop.
I sync'd again to confirm both devices now had empty folders.
I then changed the setting to "**Delete local and remote**" for empty folders (_on my desktop_).
Then I sync'd again, however, while the folder was deleted from my desktop, it was never deleted from my iPad.

So my question is,
"Does it actually tell the remote device to delete? It doesn't seem to, so what does this setting mean?"

I ask because I'd like to help refine the wording with a pull request, but want to clarify the meaning and behaviour first.

**Comment by fyears** [comment]
The new algorithm is more of a "FILE sync algorithm", where folders are created or manipulated based on the files. That's kind of a technical decision or limitation like what you said.

> "Does it actually tell the remote device to delete? It doesn't seem to, so what does this setting mean?"

1. If, a sync would cause the deletions of all the files in the folder, then the folder (locally and remotely) would be deleted too.
2. In your case, because the sync doesn't touch any files in the folders (because they were already empty before the sync), so the algorithm doesn't know about or do anything on the empty folders.

**Comment by fantuyuan** [comment]
If you change the folder name, the old folder in the cloud will become an empty folder and will not be deleted.

**Comment by fyears** [comment]
> If you change the folder name, the old folder in the cloud will become an empty folder and will not be deleted.

yeah you need to enable "delete empty folder"

**Comment by fantuyuan** [comment]
> > If you change the folder name, the old folder in the cloud will become an empty folder and will not be deleted.如果更改文件夹名称，云中的旧文件夹将变为空文件夹，不会被删除。
> 
> yeah you need to enable "delete empty folder"是的，您需要启用“删除空文件夹”

但是我希望保留我的空文件夹，他们是有结构信息的，需要被删除的是被改名的旧文件夹。

**Comment by fyears** [comment]
> 但是我希望保留我的空文件夹，他们是有结构信息的，需要被删除的是被改名的旧文件夹。
暂无办法区分

**Comment by fyears** [comment]
the original question is resolved. closing for now.
