### ISSUE TITLE
[Bug]: Sync does not work for files containing parentheses in file name

### ISSUE THREAD

**Issue by dmassoo** [remotely-save/remotely-save#579]
### What happened?

I have found that note with parentheses  in the title cannot be synced:
![image](https://github.com/remotely-save/remotely-save/assets/62523113/5509a921-7c3d-4e5f-87f8-67e1292d5b0d)

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3, others

### Version of the plugin

0.4.13

### Version of Obsidian

1.5.11

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
may i ask:

1. what s3 service are you using?
2. could you show up an example file name?
3. could you try to **directly upload the file with parentheses in your s3 service's web page**? may be, or may be not, your s3 service doesn't support these file names

**Comment by fyears** [comment]
close due to no response
