### ISSUE TITLE
[bug] sync plans containing files outer the vault

### ISSUE THREAD

**Issue by fyears** [remotely-save/remotely-save#580]
I exported the sync plan, and what I found was
- plan is very big, 240MB plan for ~ 1000 md files
- plan contains a lot of files outside the Vault from my User directory (Vault is in `~/Documents/Obsidian/Myname`, and this has files in `~/dev/some-repo` etc).

Example (changed for privacy)

```json
"Users/my-name/dev/some-thing/": {
    "key": "Users/my-name/dev/some-thing/",
    "prevSync": {
      "key": "Users/my-name/dev/some-thing/",
      "keyEnc": "Users/my-name/dev/some-thing/",
      "keyRaw": "Users/my-name/dev/some-thing/",
      "size": 0,
      "sizeEnc": 0,
      "sizeRaw": 0,
      "etag": "id:9nVrBPjixXUAAAAAAAAGxA\t"
    },
    "decisionBranch": 105,
    "decision": "folder_to_skip"
  },
``` 

What I noticed is that these paths from outside the Vault were not random, but typically some that I had referenced in a note (or their parent folder) with a `file://` link.

I tried downgrading to the first version after the refactoring (`0.4.10`), but that didn't help either. It used to work before, and on my other machines (another Mac and an Android phone) I have no such issues.

_Originally posted by @joerghaubrichs in https://github.com/remotely-save/remotely-save/issues/575#issuecomment-2031910267_

**Comment by fyears** [comment]
>  with a `file://` link.

@joerghaubrichs 

Could you please provide a full example of the link? I never realized Obsidian can link files outer the vault

**Comment by joerghaubrichs** [comment]
@fyears Oh sure, it's normal Markdown syntax for a link, but using the `file://` prefix.

Example: 

```markdown

Here is my [PDF file](file:///Users/myname/documents/some-pdf-I-use.pdf).
```

I use this quite a bit when writing notes about documents I read, so that I can open them directly.

**Comment by fyears** [comment]
Unfortunately, I am using a Windows, and cannot reproduce it:

```markdown
my [file](file://E:/sample1.md)
my [file2](file://E:/sample2.pdf)
```

I can click the link, etc. But the sync plan generated is normal, without anything introduced by `file://`.

Would you like to make sure you do not have any special plugins, any os symlinks, etc? Or, can you reproduce the sync plan, with a new **test vault** with some test files, linking to your another test files outside the vault, with only remotely-save plugin enabled?

**Comment by joerghaubrichs** [comment]
@fyears After upgrading my main vault to the latest plugin, this behavior disappeared as well. Before, it was also local to this one Mac, on my other Mac I didn't observe it (which also didn't have the "too many changes" problem).

I created a test vault with the old version of the plugin as only plugin, and couldn't reproduce the behavior there either. 

So looks like this must have been somehow connected to the old issue, but only under special conditions.

**Comment by fyears** [comment]
ok.

the plugin reads the vault file list, totally dependent on the single api returned by obsidian, not any complex logic on the plugin side. maybe something strange happened in the past..

let's close this issue right now. in case you re-meet the problem or find a way to reproduce it, feel free to re-open the issue.

**Comment by fyears** [comment]
if the latest sync plan doesn't contain the files outside the vault, at least those files should be safe because the plugin would only read-write the files in the sync plan

**Comment by joerghaubrichs** [comment]
> the plugin reads the vault file list, totally dependent on the single api returned by obsidian, not any complex logic on the plugin side. maybe something strange happened in the past..

Ah, that would make sense. Thanks for the explanation and for looking into it!
