### ISSUE TITLE
[Bug]: on mobile the app continuosly crash

### ISSUE THREAD

**Issue by progressify** [remotely-save/remotely-save#582]
### What happened?

https://github.com/remotely-save/remotely-save/assets/11472632/64d4c2f8-0035-4785-9638-5c2d8a4cbd9d

In my vault I have circa 1400 files and 169 folders.
The entire vault is circa 1.5gb
As I showed in the video, when I start the synchronization the plugin start to download some files, but apparently at random time the app crash.
After some retrying I have completed all my vault sync... 

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

others

### Version of the plugin

latest

### Version of Obsidian

latest (on android)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
the plugin is limited by the browser-alike environment provided by obsidian, and the technology is using js. the resources are limited especially in mobile.

maybe you can set “skip large files” or “Regex of path to ignore” to skip some files, as a workaround

**Comment by Blue-Kim** [comment]
I have also the same problem on the android phone, while the problem does not appear with the previous remotley-save plugin. The problem suddenly shows up after update the plugin yesterday. What's the problem?

**Comment by fyears** [comment]
> I have also the same problem on the android phone, while the problem does not appear with the previous remotley-save plugin. The problem suddenly shows up after update the plugin yesterday. What's the problem? 
> 
> I didnot change any setting after the update.

the version yesterday fix a bug but should not be relative with the crash. would you like to check whether you have any large files from yesterday?

**Comment by progressify** [comment]
I haven't any feedback about previcious update, I have installed remotely save yesterday for first time

**Comment by progressify** [comment]
I have cleared the bucket, reset completely the plugin and now I have this error on my desktop:

![image](https://github.com/remotely-save/remotely-save/assets/11472632/0f81fc53-16ea-4a85-b3fd-232aa343de95)

In my case, the largest file is circa 50mb length and it's a video but in the regexp section I have excluded the videos and now I have only the images.
The images aren't bigger than circa 5 mb.

**Comment by fyears** [comment]
http2 ping failed, is likely the error from your web server. will you like to check whether your server is configured correctly?

**Comment by fyears** [comment]
I don't have cubbit account and it doesn't support long term trial...

I've tested on backblaze b2 and cloudflare r2, and all of them seem to be ok. Would you like to try to reproduce the error using backblaze b2? (will offers free quota)? if not, i am afraid that's something strange on the cibbit side

**Comment by progressify** [comment]
If I remember good, now have changed their plan and you can have 10 gb for free with cubbit ds3 service

I will try to test other s3 services

**Comment by progressify** [comment]
I have asked information to Cubbit support and they say me they have some maintenance in. Now the maintenance is ended and the `HTTP2_PING_FAILED` isn't showed.
I always see in console the warning:

```
Are you using a Stream of unknown length as the Body of a PutObject request? Consider using Upload instead from @aws-sdk/lib-storage.
```
I don't know if it is a real problem, if someone know more than me about that tells me how I can fix it

**Comment by fyears** [comment]
no it's not a problem, just ignore it.

so i think no remaining issue here, thus i am closing the issue now. enjoy you journey with remotely save!
