### ISSUE TITLE
[Feature Request]: 更好的状态栏提示 better status bar

### ISSUE THREAD

**Issue by YIRU69** [remotely-save/remotely-save#583]
### What feature are you suggesting?

可能这个问题不是很紧急，但是如果可以改善这一点明显能增加使用的舒适感和对同步的清晰程度。

现在状态栏的提示，唯一的作用是看上一次自己同步的信息，而不能通过状态栏实时观察同步的情况。

我认为可以进行这样的改进：
1. 当插件在进行同步的时候，最好保持一直处于同步中的提示。就我的库来说（3000+笔记），我进行同步，会在同步中和不同完成之间有一段空隙。
2. 显示同步文件的个数和进度。在状态上实时显示同步的文件进度状态会极大增强同步体验，这也对自己同步的信息有一个明显的了解，如果自己文件更改不多却看到同步文件个数过多就更容易发现问题。
3. 虽然我不使用实时同步，但是建议可以在状态栏上区分同步的类型，比如实时同步的时候增加一个标识。

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by kadisonm** [comment]
Sorry if I misunderstood anything, used Google translate.

I also think the status bar is a bit lacking in terms of information. I'm also finding it's switching to 'synced less than a minute' ago before it even finishes syncing then shows 'Synced just now' when it does.

Think this could be reworked like mentioned above.

**Comment by fyears** [comment]
在 0.5.7 更新了。

Updated in 0.5.7.
