### ISSUE TITLE
[Bug]: Failed to load plugin remotely-save

### ISSUE THREAD

**Issue by xueke114** [remotely-save/remotely-save#584]
### What happened?

我使用的是魅族20Pro，remotely-save显示已安装，但无法启用。

我用Chrome的远程调试发现了问题。问题是安装时下载到本地的文件不完成，缺少了文件体积`main.js`。

所以提供一种新的思路，Failed to load plugin remotely-save 的原因，除了之前大家在issues中的报告，还可能是因为网络问题导致的文件缺失。

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.4.14

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by xueke114** [comment]
安卓上的Obsidian安装了`remote-save`插件后，启用时报错`Failed to load plugin remote-save`，我就去`remote-save`的github仓库看issue，看了诸如[#440](https://github.com/remotely-save/remotely-save/issues/440)、[#308](https://github.com/remotely-save/remotely-save/issues/308)，`remote-save`的维护者[fyears](https://github.com/fyears)让去谷歌商店更新WebView，这个我肯定是做不到的。于是想着Android Obsidian怎么Debug查看日志。在Obsidian的中文论坛找到了[能看到obsidian的错误日志或debug的信息吗?](https://forum-zh.obsidian.md/t/topic/6438)，说按`Ctrl+Shift+I`能进DevTools看Console（当然这是针对桌面端说的），我才恍然想起来Obsidian是基于Electron构建的，能进Chrome的DevTools，自然插件的log也会打印到Console，那么安卓端怎么进DevTools呢？我没有移动端的Web开发调试经验，于是在谷歌找到了[Show javascript console from Android phone](https://forum.obsidian.md/t/show-javascript-console-from-android-phone/49353)和[远程调试 Android 设备](https://developer.chrome.com/docs/devtools/remote-debugging?hl=zh-cn)，将基本步骤总结如下：
1. 安装adb。我也没有安卓App的开发经验，没装Android Studio，adb只能求助于`scoop`，直接用`scoop install adb`安装了。
2. 数据线连接手机和电脑，手机开启USB调试
3. 电脑在控制台运行`adb devices`，检查连接状态，我的输出如下：
```bash
❯ adb devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
391QYFCK224UF   device
```
4. 手机打开Obsidian。打开电脑的的Chrome，进入`chrome://inspect#devices`，发现可以识别到我的手机，也能识别到打开的Obsidian。
![Pasted image 20240403084452](https://github.com/remotely-save/remotely-save/assets/46664191/651e934a-713e-4c1f-8e86-0e0ace180dec)
5. 点击`inspect`，然后直接打开了新世界的大门！进到了DevTools，看到了Console，甚至还能预览界面。
![Pasted image 20240403084727](https://github.com/remotely-save/remotely-save/assets/46664191/960148b9-dfa0-422c-90ae-89a7205c6e90)
看到了`remote-save`的报错，说是`File does not exist`，会是什么文件缺失呢？在[#308](https://github.com/remotely-save/remotely-save/issues/308)中有展示`remote-save`的在设备上的根目录（顺便说[#308](https://github.com/remotely-save/remotely-save/issues/308)的截图风格看着也是魅族🤭），我想会不会是因为我的网络原因，在安装插件的时候下载的文件有缺失？于是找到`remote-save`在本地的文件夹一看，发现缺了最重要的`main.js`😂
![微信图片_20240403085258](https://github.com/remotely-save/remotely-save/assets/46664191/42ad1a37-348e-4485-a5f8-113e62996b85)
这还了得，于是直接从`remote-save`的Release页，下载了最新的`main.js`, `manifest.json`, `styles.css`，进行了替换。然后就可以顺利启动了。
![e2f76c330fb449715cc11354ec2397e](https://github.com/remotely-save/remotely-save/assets/46664191/1757c135-678d-4129-a719-cff35b0b73ee)


最后一丢丢建议，应该改善判断`插件安装成功`的机制，文件不完整不能算安装成功。

**Comment by fyears** [comment]
好的，谢谢你！
