### ISSUE TITLE
[Bug]: 同步速度还是变慢了

### ISSUE THREAD

**Issue by keeyangyy** [remotely-save/remotely-save#586]
### What happened?

在这里提过 #576 

更新到0.4.14没有什么变化。

我仔细对比了0.4.11和0.4.14，我的库大概有1500左右文件，当全部文件状态是都同步的时候，再次执行同步，打开debug信息查看，使用0.4.11，这8步几乎是连续的执行下来，不超过1s，当换成0.4.12和以后的版本，会在第5步正在获取本地上一次同步的元数据卡1s左右，在第7步开始发生数据交换这里卡2到3s左右。我删除上次同步历史，重设数据库缓存，都没有什么作用。

![屏幕截图 2024-04-03 112835](https://github.com/remotely-save/remotely-save/assets/58218054/87a5973a-b551-46ac-9e50-b384ca9d0db2)

我创建了一个新的库测试，只有少数几个文件，这时候这两个版本插件的速度区别就不大。

这个问题其实不是很大。我也看了同步计划，没有实际发生数据交换，但是数据交换这里也卡了两三秒，所以觉得可能有异常，就把信息提供出来看看是不是还有小bug。

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3

### Version of the plugin

0.4.11-0.4.14

### Version of Obsidian

v1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
你好，

同步计划全部搜一下，看有没有 push 或 pull 等关键词。

如果没有的话，那么就是没有上传或下载。

读取本地同步历史，没理由卡啊……这个就是本地数据库，应该是飞速的。


下一个版本我试试加一些统计时间的代码吧，没头绪

**Comment by keeyangyy** [comment]
我又做了一些测试，都是在文件全同步状态下，再次进行同步操作。（正常情况应该是很快没有发生传输的）

0.4.11插件版本，同步速度很快，第1步到第8步几乎是秒速，整体不超过1s，导出同步计划，全部搜索，没有pull和push匹配，equal搜索匹配1477个。

更新到0.4.14版本，同步速度变慢，在第5步和第7步发生卡顿，有时候甚至会分别卡4~5s，导致整体用时有时候最多会接近10s，导出同步计划，全部搜索，没有pull和push匹配，equal搜索匹配1477个，这里同步计划结果和0.4.11版本一致。删除上次同步历史，重新测试，情况没有变化。

回退0.4.11版本，方法是用0.4.11版本的 main.js manifest.json style.css 覆盖掉新版本的。此时同步速度也变慢，在第5步出现了类似0.4.14的卡顿，卡顿时长也类似，但是在第7步没有卡顿，和正常速度一样。此时删除上次同步历史，重新测试，同步卡顿消失，恢复到了初始0.4.11版本的正常速度。

我目前回退到0.4.11版本使用，目前感觉同步都是正常的。

**Comment by keeyangyy** [comment]
文件是全同步状态，更新到0.4.15版本，然后触发三次同步，导出性能数据，如下（这里第一次同步时的step5卡顿消失）
[profiler_results_exported_on_1712240954644.md](https://github.com/remotely-save/remotely-save/files/14872848/profiler_results_exported_on_1712240954644.md)

删除上次同步历史，然后触发三次同步，导出性能数据，如下（会导出5条数据，看最新的3条）（这里第一次同步时的step5卡顿消失）
[profiler_results_exported_on_1712241106141.md](https://github.com/remotely-save/remotely-save/files/14872872/profiler_results_exported_on_1712241106141.md)

改动一个文件，然后触发三次同步，导出性能数据，如下（会导出5条数据，看最新的3条）（这里没有变化，即两处都卡顿）
[profiler_results_exported_on_1712241314789.md](https://github.com/remotely-save/remotely-save/files/14872879/profiler_results_exported_on_1712241314789.md)

**Comment by fyears** [comment]
这里可以看到，最耗时的是这两步（最后一个文件的第 1 部分）：

```
...
[finish step5 (prev sync)]: 2913.8ms  <- 读取本地历史
...
    [doActualSync: step 0 end]: 3798.5ms <- 写入本地历史
...
```

它们分别就是读取本地历史数据，和写入本地历史数据（为了保障同步正确性）。0.4.11 vs 0.4.14 确实是[差异多了这部分](https://github.com/remotely-save/remotely-save/compare/0.4.11...0.4.14#diff-1b0cb46cd1fcdaacf73c771bf7eed6e00a12ee030da1dbcca4ae12842e1ecd81R1097)，这是为了保障同步准确性的。

这里离谱之处在于，读取这个本地历史，居然用了接近 3 秒，比读取网络历史（`[finish step2 (listing remote)]: 390.6ms`）还要慢。。。

我先试试创建 1500 个文件，看看测试一下写入速度吧。你这 1500 个文件是平铺还是大概多少个文件夹有多少层的？

写入部分可以优化，下一个版本会跳过某些写入。

**Comment by fyears** [comment]
（难道你还是 hdd 硬盘）

**Comment by fyears** [comment]
此外，你有多个vault吗？

**Comment by keeyangyy** [comment]
去年才买的笔记本，固态硬盘。我在另一台台式PC上，也是固态硬盘，也出现了类型卡顿的情况。两台都是0.4.11很快的，快得一匹，后面的版本就出现卡顿。不过我移动设备没试过。

**Comment by keeyangyy** [comment]
我有两个vault，另一个文件比较少，也很少用，没有在那个vault验证过，但是应该不会互相影响吧，不是同时打开的。

文件结构部分，我查看了一下，我总共1500左右文件，以根目录为第一层的话，附件1200个左右，图片为主，在第二层（即一个专门的附件文件夹里），其余是md文件，300个左右，主要分布在第三、第四层，我文件夹深度最多就是第四层了。第一层即根目录是纯文件夹没有文件。我好像文件夹确实有点多，因为我是文件夹跟双链共存模式，文件夹负责大类快速筛选，双链负责细分连接，难度是跟这个有关系吗？

**Comment by keeyangyy** [comment]
大佬这个代码我确实不太懂，但是我记得是在0.4.12就开始出现了同步变慢了。

文件夹数量我查了一下，有61个文件夹，第一层就有7个，其余都是子文件夹。

**Comment by fyears** [comment]
你好，请更新到 0.4.16 ，再试试同步，并看看性能数据。

暴力优化了一波，应该上面说的两个步骤都有超大改善了。我本地测试是 3 秒变 300 毫秒。

**Comment by keeyangyy** [comment]
大佬好猛！解决了！0.4.16上面那两步分别只有75ms和4ms了，现在同步又猛地一匹了。

（我刚弄完一个新库测试，根目录平铺1500个文件，旧版本发现同样问题，这边就更新解决了，大佬猛！）
