### ISSUE TITLE
[Feature Request]: string method to export setting

### ISSUE THREAD

**Issue by xwxb** [remotely-save/remotely-save#587]
### What feature are you suggesting?

instantly, I find that the qrcode isn't work well on my android. (if needed, I'll start a new issue)
maybe is specific problem for me, but I think string method sounds good to be a alternative when qrcode can't work.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
On android, you can use the open source app: Binary Eye, to scan the QR code. I found it work.

**Comment by xwxb** [comment]
> On android, you can use the open source app: Binary Eye, to scan the QR code. I found it works.

Untill scan and open obsidian android it's np, but after opening obsidian there's not the setting being imported

**Comment by xwxb** [comment]
Yean I tried binary eye and copy it in via browser, it can open obsidian but not having imported the setting

**Comment by fyears** [comment]
Well, so I am implementing a manual copy and paste function, which will be released in next version.

**Comment by xwxb** [comment]
> Well, so I am implementing a manual copy and paste function, which will be released in next version.

Thx for hardworking 🥰

**Comment by fyears** [comment]
Implemented in https://github.com/remotely-save/remotely-save/commit/0fc0dcad64fe7a257e3647fb58119ee4aaefb1ec

Will be released in next version.
