### ISSUE TITLE
[Bug]: Vault settings keep getting overwritten

### ISSUE THREAD

**Issue by kadisonm** [remotely-save/remotely-save#588]
### What happened?

When syncing a new vault, I think the new vault's default configurations are newer resulting in them being pushed instead of pulling the ones from the cloud.

Additionally, even after changing config on one device, and syncing to the second device. The second device seems to overwrite it still.

By the config files I mean `app.json`, `appearance.json`, `workspace.json`, etc.

I believe Remotely Sync fixes this by skipping these files if the plugin's last synced is null and they exist on the remote. Since that means the vault is new and shouldn't push.

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> Additionally, even after changing config on one device, and syncing to the second device. The second device seems to overwrite it still.

Does it happen on normal files? the "newer version wins" logic applies to normal files and .obsidian files together. So I suspect actually Obsidian itself is changing the config files by some reasons

> by skipping these files if the plugin's last synced is null and they exist on the remote.

Our plugin also applies the logic to the whole vault. For example, if you sync, clear local vault, then the plugin will download everything from remote, instead of clearing remote.

**Comment by kadisonm** [comment]
Odd, it happened again where my settings didn't save. I feel like when Obsidian is opened the settings are modified like workspace etc, before a sync is ran. Making them seem newer.

For example `Files and Links > Default Location For Notes` won't change for me even though I changed it and synced on another device. Keeps going back to default.

However it seems like plugin json files work fine.

**Comment by fyears** [comment]
yeah you can export the sync plans to verify. i agree with your guessing, and currently no way to "correctly" sync these special files.

however the plugin allows setting the deny list, you could just exclude the special files

**Comment by kadisonm** [comment]
> however the plugin allows setting the deny list, you could just exclude the special files

Will do that thanks.

**Comment by schemen** [comment]
Sorry for commenting on a closed ticket, but I did figure out some method to ensure proper syncing here:

Obsidian seems to modify those files on start up. We can use this mechanic to ensure the latest settings are correctly synced when a new client joins by doing the following:

* Ensure on the primary client all the settings are correct and good. Export the Remotely Save settings to easily sync a new vault. 
* Then close the primary client, ensuring it's offline.
* Open secondary client, add new vault, apply the settings and do a first sync. 
* After the first sync is finished, keep Obsidian open on the new client and open Obsidian on your primary client and do a sync. This ensures the primary client has the latest setting files.
* Sync on the secondary client

and now all should be in sync.

**Comment by fyears** [comment]
> Obsidian seems to modify those files on start up. 

the settings file? i suspect not all the files are modified and it's easier to just ignore the specific files that would be touched each time of start up

**Comment by schemen** [comment]
> the settings file? i suspect not all the files are modified and it's easier to just ignore the specific files that would be touched each time of start up

Ignoring the settings file is bad though, I want those synced. Things like Themes, editor settings, links, etc. etc. With the steps above, this is solved (Albeit a bit clunky). Maybe it could be assisted with code?

**Comment by kadisonm** [comment]
You could probably check for if the file exists on the remote and if the local file is the default then skipUploading it and download it instead.

That would make new vaults download them instead of upload them.

**Comment by fyears** [comment]
what are the "default"?

**Comment by kadisonm** [comment]
> what are the "default"?

You could probably determine it by if the file's date created is equal to the date modified. Would mean the file is just created and 'default'

**Comment by schemen** [comment]
I checked, and it looks like indeed Obsidian is modifying the file on each start. Though it's not changing any of it's content. I don't know why it does that though.



> what are the "default"?

The default of the file is empty essentially. Any changes to the default configs are recorded there.
