### ISSUE TITLE
[Feature Request]: Support for CouchDB

### ISSUE THREAD

**Issue by tionis** [remotely-save/remotely-save#59]
### What feature are you suggesting?

Couchdb Support would be great, as couchdb databases are very easy to selfhost

### What remote cloud services are you using, or suggesting adding the feature to?

others

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Please consider another awesome plugin (not developed by me) https://github.com/vrtmrz/obsidian-livesync

**Comment by tionis** [comment]
I already looked at it, but aren't those two kinda different use cases?  
This plugin for sharing single files and the obsidian-livesync for whole vault syncing?

**Comment by fyears** [comment]
This plugin is also syncing the whole vault, but it do this by uploading or downloading file by file.

**Comment by tionis** [comment]
I see, it seems I misunderstood the purpose of this plugins.  
Well, in this case excuse my redundant feature request and best of luck.
