### ISSUE TITLE
[Bug]: obsidian 缓存文件特别大

### ISSUE THREAD

**Issue by fbhyc** [remotely-save/remotely-save#590]
### What happened?

obsidian 缓存文件特别大；C:\Users\Lenovo\AppData\Roaming\obsidian 这个文件夹时间长会有7G那么大
删除同步计划历史 后会变小，

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (Cloudflare R2)

### Version of the plugin

最新版

### Version of Obsidian

最新版

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> 删除同步计划历史 后会变小

会变小到多少呢？此外，现在已经缩短了对应的保存时间，只保留最近 20 条了，请更新新版本。

**Comment by fbhyc** [comment]
> > 删除同步计划历史 后会变小
> 
> 会变小到多少呢？此外，现在已经缩短了对应的保存时间，只保留最近 20 条了，请更新新版本。

2g左右

**Comment by fyears** [comment]
本插件只会占用 `%AppData%\obsidian\IndexedDB` 的**其中一部分**。如果是可以看看是不是别的插件或者别的地方占用的哈。
