### ISSUE TITLE
[Bug]: 无法同步插件配置

### ISSUE THREAD

**Issue by anschein** [remotely-save/remotely-save#593]
### What happened?

<img width="545" alt="截屏2024-04-07 15 59 48" src="https://github.com/remotely-save/remotely-save/assets/49552476/87092fd2-cac9-48bc-a676-4da3dc8b4e58">
开启同步`.obsidian`目录后出现错误停止同步，似乎使用加密能够正常同步，不确定是否因为文件名的问题

### What OS are you using?

Windows, macOS

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (MinIO)

### Version of the plugin

0.4.16

### Version of Obsidian

1.5.11

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by anschein** [comment]
已测试，开启加密后能够正常同步

**Comment by fyears** [comment]
你用的是自建的 minio ？有做什么特殊权限处理吗？

**Comment by anschein** [comment]
> 你用的是自建的 minio ？有做什么特殊权限处理吗？

群晖上自建，手动上传没有问题，开了加密也没有问题，目前就是不开加密的情况下上传插件文件夹会出错

**Comment by fyears** [comment]
我用 windows 的 minio 确认是可以创建成功的。这里不是插件的问题，建议检查一下 minio 和 服务器（linux？）和 webserver （apache？）的权限问题，有可能是不允许隐藏文件的写入。

**Comment by anschein** [comment]
测试了威联通自带的对象储存，一样的报错，我不确定是nginx反代处理的问题还是什么，请问大佬有没有思路？我觉得应该不是权限问题，手动能够上传

**Comment by fyears** [comment]
新建一个测试vault只安装一个插件，可用吗？

你的linux是如何配置的呢？详细给一下可复现的说明？

**Comment by anschein** [comment]
> 新建一个测试vault只安装一个插件，可用吗？
> 
> 你的linux是如何配置的呢？详细给一下可复现的说明？

测试了内网地址可以正常同步，问题应该是出在反代上面了，与插件无关，要是有结果我会继续回复
