### ISSUE TITLE
[Feature Request]: Want more detailed schedule runs

### ISSUE THREAD

**Issue by xwxb** [remotely-save/remotely-save#594]
### What feature are you suggesting?

Not sure if it's more of a personalized requirement, but my personal hope is that there's a custom interval here to allow for larger intervals to be set up

<img width="289" alt="image" src="https://github.com/remotely-save/remotely-save/assets/77780051/59ac1206-fc13-4ef6-9cec-3c2c629bad11">

And maybe I need to configure a cron run schedule. simply can also be which time of the day to plan to run.
e.g. my personal needs are every day at 18:00 home from work to run once, and maybe also want to run every day at 12 noon

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
the plugin cannot auto start the obsidian. and i think it might be too complicated to add such customized options...

is it good enough to add hard-coded hour options?

**Comment by xwxb** [comment]
> the plugin cannot auto start the obsidian. and i think it might be too complicated to add such customized options...
> 
> is it good enough to add hard-coded hour options?

yeah, maybe, no problem. I'll learn to use cli to achive this, it's also good idea, thx for replying
