### ISSUE TITLE
[Bug]: Creating or deleting notes does not trigger sync on save.

### ISSUE THREAD

**Issue by lyiton** [remotely-save/remotely-save#599]
### What happened?

Creating or deleting notes does not trigger sync on save. I don’t know if it’s set up this way or if it’s a bug. I have seen the same function in remotely-syns. The plugin triggers synchronization when notes are created and deleted.

### What OS are you using?

Windows, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.4.16

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
it's a lack of features. will be implemented in a few days

**Comment by fyears** [comment]
0.4.17 fixes this.

**Comment by lyiton** [comment]
In version 0.5.5, I found that renaming files would not trigger synchronization either.

**Comment by fyears** [comment]
ok, it can be implemented too

**Comment by fyears** [comment]
It will be release in this weekend

**Comment by lyiton** [comment]
再报告一个bug：删除文件也不会触发“保存时同步”。

![PixPin_2024-06-25_15-57-05](https://github.com/remotely-save/remotely-save/assets/76651858/970b1882-2982-4cde-b172-5a6fb822fc55)

**Comment by fyears** [comment]
删除应该有的，是不是同步太快了

**Comment by lyiton** [comment]
> 删除应该有的，是不是同步太快了

我有在代码里看到delete的部分，但实际好像没效果，创建和重命名笔记都能很快触发同步了，感觉不是你说的这个原因。

**Comment by lyiton** [comment]
再报告一个bug：重命名文件也不会触发“保存时同步”。

**Comment by fyears** [comment]
我知道了。原始设计，这个 sync on **save** 是**当前文件**被保存或者修改时候，判断修改时间，然后触发同步。

然而，删除和重命名，并不是一个**当前文件**的**save**操作。实际上，当前文件没有了（被删除了！）。所以不会触发后继逻辑。

所以大家想要的是 vault 内任意地方变动都触发修改吗。。。。

**Comment by lyiton** [comment]
如果是我的话，我希望是任意地方变动都能触发同步。
这样的话，我只需要设置一种同步类型（即保存时同步）就可以满足同步需求，而不用再设置每隔一段时间自动同步（即自动运行）。
