### ISSUE TITLE
[Bug]: creating a new folder gives 405 method not allowed

### ISSUE THREAD

**Issue by minkoonim** [remotely-save/remotely-save#600]
### What happened?

new file is totally ok,
but when creating a new folder locally and syncing this activity,
I get 405 method not allowed,
I thought it should be ownership problem of server directory
```
sudo chmod -R 777 /opt/webdav
```
but didn't have any luck with it.

remote server is my own openwrt webdav server.
mostly it works with charm, only the folder creation gives this error.

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.4.16

### Version of Obsidian

1.5.12

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> my own openwrt webdav server

what sever software are you using? can you create folders by using web browsers?

**Comment by fyears** [comment]
it's likely to be a mis configuration on your server software

**Comment by minkoonim** [comment]
> it's likely to be a mis configuration on your server software

I'm running GoWebDev on openwrt

**Comment by fyears** [comment]
are you referring to this?: https://github.com/117503445/GoWebDAV

**Comment by minkoonim** [comment]
> are you referring to this?: https://github.com/117503445/GoWebDAV

yes this is the one,
no proxy involved in my case,
port 6086 directly opened
