### ISSUE TITLE
[Feature Request]: 增加文件属性的同步功能

### ISSUE THREAD

**Issue by spiritnew** [remotely-save/remotely-save#601]
### What feature are you suggesting?

A设备同步(上传)文件到服务器，B设备从服务器上同步（下载）内容到本地电脑，这时B电脑上看到文件的创建日期就是同步日期而不是实际的创建日期（感觉就像是从服务器复制文件到本地），是否可以同步文件的创建日期，这样方便管理文件创建记录，用于创建时间追溯，修改记录追溯。

1,on PC1,  create a file on 2024-04-01,  sync (upload) to server,
2, on PC2, 2024-04-02, sync (download) from server, 
now check file on PC2, create time is 2024-04-02, seems like copy from server, 
if i sync (download) form server after a long time, all the new synced files will be create at the same day, this is not what i want,
i want to check all file status (like create time, modify time), so can you sync the file create time,or other attribution.

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
webdav 做不了，这个协议不支持这种操作

**Comment by rcsoul** [comment]
请问Remotely save目前有哪种方式支持文件属性的同步功能？

**Comment by fyears** [comment]
目前其他三种都支持同步最后修改时间。s3技术上可以支持创建时间但是现在还没有支持

**Comment by SunSwallow** [comment]
请问作者最近有支持s3服务同步创建、修改时间的计划吗
