### ISSUE TITLE
[Bug]: sync fails due to URI mismatch (webdav apache)

### ISSUE THREAD

**Issue by LackingCats** [remotely-save/remotely-save#604]
### What happened?

When going to sync, the plugin creates the vault folder perfectly fine. However, it cannot create the subfolders of the vault, giving an Error 400: bad request
※ This only occurs when using the digest authentication, not basic.

Here is my apache log: 
[date] [auth_digest:error] [pid ******:tid ******] [client ****:****] AH01786: uri mismatch - </webdav/name-vault> does not match request-uri </webdav/name-vault/>

### What OS are you using?

Linux

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.4.16

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Gurundud** [comment]
I'm also having this error.

From time to time, hitting the remotely save button gave me error 400: bad request.

Upon inspection what happened was, I have a folder and note on my local, but that particular folder and file is not present at my webdav server.

So In order to resolve this error, I would need to upload manually so the structured is the same both local and server.

The way I set up my webdav is using Unraid, with Apache WebDav, normal installation really.

**Comment by fyears** [comment]
i don't have unraid nas. would you like to provide any tutorial about installing apache webdav on linux?

**Comment by ssalinasfe** [comment]
i have the same problem. Did you fix it?

**Comment by LMRW** [comment]
Same issue here - Nextcloud WebDav
Let me know if I can help

**Comment by fyears** [comment]
> i have the same problem. Did you fix it?

no. because no users provide a complete reproducible steps.

> Same issue here - Nextcloud WebDav
Let me know if I can help

sure. are you using nexcloud only or are you also using apache or nginx as a reverse proxy? could you please provide a complete reproducible steps about installing the software and reproducing the error on linux?

**Comment by fyears** [comment]
> I'm also having this error.
> 
> 
> 
> From time to time, hitting the remotely save button gave me error 400: bad request.
> 
> 
> 
> Upon inspection what happened was, I have a folder (say Gpt Prompt) and note on my local, but that particular folder and file is not present at my webdav server.
> 
> 
> 
> So In order to resolve this error, I would need to create folder (Gpt Prompt) on my webdav server, and after that everything will synced up.
> 
> 
> 
> The way I set up my webdav is using Unraid, with Apache WebDav, normal installation really.

are you using basic oauth or digest auth? can u reproduce the error using basic auth if you are encountering error using digest auth?

**Comment by ssalinasfe** [comment]
> > i have the same problem. Did you fix it?
> 
> no. because no users provide a complete reproducible steps. and are you using basic auth or digest auth? can you reproduce the error using basic auth or digest auth? are you using apache or any sotfware?

Oh I'm sorry. I tried to do a first sync with my 3.5 gb vault to a WebDav server in my homelab 

The docker image I use for the webdav server is: https://hub.docker.com/r/bytemark/webdav

**Comment by fyears** [comment]
> > > i have the same problem. Did you fix it?
> > 
> > 
> > no. because no users provide a complete reproducible steps. and are you using basic auth or digest auth? can you reproduce the error using basic auth or digest auth? are you using apache or any sotfware?
> 
> Oh I'm sorry. I tried to do a first sync with my 3.5 gb vault to a WebDav server in my homelab
> 
> The docker image I use for the webdav server is: https://hub.docker.com/r/bytemark/webdav



are you using basic or digest? can uou reproduce the error in both auth method? are you using https? do you have any other reverse proxy?

**Comment by Gurundud** [comment]
> > I'm also having this error.
> > From time to time, hitting the remotely save button gave me error 400: bad request.
> > Upon inspection what happened was, I have a folder (say Gpt Prompt) and note on my local, but that particular folder and file is not present at my webdav server.
> > So In order to resolve this error, I would need to create folder (Gpt Prompt) on my webdav server, and after that everything will synced up.
> > The way I set up my webdav is using Unraid, with Apache WebDav, normal installation really.
> 
> are you using basic oauth or digest auth? can u reproduce the error using basic auth if you are encountering error using digest auth?

I'm using digest (gave me error when the folder is not present on the server). When I switch to basic ( both with my webdav server and remotely save), the error is now gone and it sync just fine.

**Comment by fyears** [comment]
it looks like some other people in the internet meets the same issue:

https://forums.zotero.org/discussion/111707/webdav-sync-error-with-self-hosted-http-apache2-server

https://www.spinics.net/lists/apache-users/msg115715.html

https://m.bilibili.com/opus/877880685280362499

i still have no clue and it seems to be some trailing slash problem. 

please consider using **https** and basic auth.

**Comment by LMRW** [comment]
Nextcloud no proxy basic auth and server has HTTPS

**Comment by fyears** [comment]
@LMRW do you mean ubuntu snap install?

**Comment by fyears** [comment]
i fixed the bug in the weekend. in 24 hours a new release will fix this problem.

**Comment by LMRW** [comment]
Yes that's right and glad to hear fixed now thank you!
