### ISSUE TITLE
[Bug]: 更新之后无法同步阿里云

### ISSUE THREAD

**Issue by ysc2** [remotely-save/remotely-save#606]
### What happened?

更新了版本之后，同步时报错：
![批注 2024-04-14 154916](https://github.com/remotely-save/remotely-save/assets/89937434/9f5462ad-1a69-4dc7-868b-6b7788988deb)
更新前后没有更改设置.

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.4.16

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
region 填写地域，不要填网址。

例如：填写 `oss-cn-hangzhou` 而不是 `oss-cn-hangzhou.aliyuncs.com`
