### ISSUE TITLE
[Bug]: Remotely Save with S3 failed sync when new document added.

### ISSUE THREAD

**Issue by Zenuncl** [remotely-save/remotely-save#609]
### What happened?

Recently i noticed some issue when add a new note or modify some new note, Remotely-save cannot sync the document properly.

**Error message:**
```
plugin:remotely-save:330 remotely-save-1713201856208: abort sync, triggerSource=manual, error while syncing
plugin:remotely-save:330 AggregateError: 
    Error: NewFolder/NewDoc (Private) Design - Whatever.md: Request failed, status 403
        at eval (plugin:remotely-save:325:126505)
    at eval (plugin:remotely-save:325:126665)
    at Generator.next (<anonymous>)
    at s (plugin:remotely-save:181:301241)
```

It looks like it's due to some kind of conflict during sync, specially if somehow the syncing was disturbed and stopped, some meta data will corrupted and cause the sync failed.

In addition, because I am syncing between three device, iPhone, iPad and macOS, if any part of these three device isn't update-to-date, it will cause the same problem

The issue happened when you add and/or delete some notes as well. For example, the filename showing on the error message was renamed to `NewDoc (Private) Design Whatever.md` on macOS, but probably not up-to-date on iPad. And now, all three device failed.

**Only known solution**
Whenever it happens, I have to completely remove the entire S3 folder then re-sync. But sometime the issue happen again.

### What OS are you using?

macOS, iOS (iPhone, iPad), Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3

### Version of the plugin

latest

### Version of Obsidian

v1.5.12

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> some meta data will corrupted and cause the sync failed.

not likely.

would you like to change the file name to contain only english letters and spaces and try again?

**Comment by fyears** [comment]
and what s3 service are you using?

**Comment by Zenuncl** [comment]
AWS S3,

I just removed the entire bucket again and re-synced, also changed filename. I'll test it for few days.

**Comment by fyears** [comment]
No further info. Close for now.
