### ISSUE TITLE
[Bug]: 更新到0.4.16后，提示报错，无法同步

### ISSUE THREAD

**Issue by YakshaChien** [remotely-save/remotely-save#610]
### What happened?

更新到最新版本后，会出现截图上的报错，手机端跟PC端出现同样的错误，无法理解是什么问题导致的。
使用的是阿里云的同步。
![微信截图_20240417001155](https://github.com/remotely-save/remotely-save/assets/50524581/fc6e4a9c-2993-4137-ae32-8e145ac81b63)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.4.16

### Version of Obsidian

1.5.12

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
加密方式请改成 openssl
