### ISSUE TITLE
[Bug]: Error: do not know which level for //Breadcrumbs.csv

### ISSUE THREAD

**Issue by luzhe610** [remotely-save/remotely-save#614]
### What happened?

Error when syncing

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (腾讯云 COS Tencent Cloud COS)

### Version of the plugin

0.4.16

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
would you please provide a screenshot?

do you have this breadcrumbs.csv locally?

do you have this breadcrumbs.csv remotely on s3?

can you please open your console (press ctrl+shift+i) and input `app.vault.getAllLoadedFiles()` and see the ouput? (remember to remove any sensitive info)

**Comment by luzhe610** [comment]
> would you please provide a screenshot?
> 
> do you have this breadcrumbs.csv locally?
> 
> do you have this breadcrumbs.csv remotely on s3?
> 
> can you please open your console (press ctrl+shift+i) and input `app.vault.getAllLoadedFiles()` and see the ouput? (remember to remove any sensitive info)

Thank you for your reply. I've tried "Delete Sync Plan Details" and "Reset Local Internal Cache/Databases", then the error was gone.

**Comment by fyears** [comment]
ok
