### ISSUE TITLE
[Bug]: android xiaomi9 手机emotely-save failed to load plugin remotely-save，华为手机尝试是可以的

### ISSUE THREAD

**Issue by farons** [remotely-save/remotely-save#615]
### What happened?

# remotely-save failed to load plugin remotely-save,
我在华为尝试是可以的，小米这个手机如何都是这个，我试了其他插件例如tasks是可以正常安装成功
YSTEM INFO:
	Operating system: android 11 (Xiaomi MI 9)
	Obsidian version: 1.5.12 (134)
	API version: v1.5.12
	Login status: not logged in
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 1
		1: Tasks v7.0.0

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.4.16

### Version of Obsidian

1.5.12 (134)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
请网上搜索如何更新 android system webview 组件哈

**Comment by farons** [comment]
感谢，可以正常使用了
