### ISSUE TITLE
[Feature Request]: 是否可以在使用自建WebDAV服务时，增加HTTPS的证书错误的忽略选项？

### ISSUE THREAD

**Issue by zskies** [remotely-save/remotely-save#616]
### What feature are you suggesting?

使用自建WebDAV服务时通常用户没有可信的证书，是否可以在使用自建WebDAV服务时，增加HTTPS的证书错误的忽略选项？

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
抱歉，不能，因为这个受限于系统 api 。

此外无论如何建议签上正式证书，内外网只要有域名的话都是可行的。
