### ISSUE TITLE
[Feature Request]: 同步的附件占用存储空间比较大,能否只在服务器存储,其他的设备只需要附件的时候点击就可以下载

### ISSUE THREAD

**Issue by Fowindy** [remotely-save/remotely-save#617]
### What feature are you suggesting?

![image](https://github.com/remotely-save/remotely-save/assets/45205351/33dac3b6-6adf-426a-9f51-6a3033bd0cb8)
首先,感谢作者的付出,插件非常好用,现在我有一个应用场景功能:
1. 我们使用Obsidian都是多端使用,现在基本上所有的工作生活的附件(压缩包,软件,pdf文档等等)都会在写文章的时候粘贴在文章中,这样日积月累,附件就会非常的多,可能几百个G;现在的同步是每一台设备都会下载这几百G的附近到该设备的本地,导致该设备的存储空间十分堪忧;而且加载也会很慢;,其实我们很多附件虽然上传上去了,只是为了存储起来,以后某天需要的时候直接点击就可以从服务器(云盘)下载下来就可以;

2. 针对上面的处境,我想到了这样一个需求,就是能否请作者帮忙在现有插件的基础上开发一个开关,比如[仅云端存储],这个开关默认关闭,也就是所有设备都同步所有附件,如果我把这个开关打开了,那么我的所有设备(如果能单独可选那最好了)本地就不存储附件了,我添加了一个附件,比如[chatgpt使用手册.zip],那么你就上传到云盘活服务器,然后只留chatgpt使用手册.zip这几个字,最后这几个字可以按tab缩进,这几个字是一个超链接,超连接内容是这个文件上传到云盘的下载链接,我点击了就自动下载,不点击,加载本页内容就只加载这个附件对应的超链接;

3. 同时也希望作者能实现Onedrive Business的功能,十分感谢您的聆听;

### What remote cloud services are you using, or suggesting adding the feature to?

S3 (腾讯云 COS Tencent Cloud COS)

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
你好，暂无此计划，过于复杂了，为什么不手动上传一些附件到网盘里呢。插件现在有跳过大文件或忽略某些文件的功能，可以试试。

此外 onedrive for business 支持不了，主要是我没有对应账号。
