### ISSUE TITLE
[Bug]: MIUI10, 0.3.25之后的版本安装后无法开启，0.3.25同步无提示信息

### ISSUE THREAD

**Issue by lazycatme** [remotely-save/remotely-save#618]
### What happened?

红米 K20 Pro，MIUI10.4.1, 
0.3.25之后的版本安装后无法开启，点击开启按钮又关闭
安装版本0.3.25，填好设置后点“检查“按键没有弹出提示信息，点击“Remotely Save”同步后没有弹出提示信息

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
请网上搜索如何更新 android system webview
