### ISSUE TITLE
[Bug]: remotely-save + logstravaganza "debug" bug.

### ISSUE THREAD

**Issue by buckssss** [remotely-save/remotely-save#620]
### What happened?

When you set log level to info or debug it is always logs "debug" level messages. 
Logs, created with logstravaganza, are too big — **each** sync with cloud gives about 4mb of logs.
I have about 400 files in vault (notes + attachments) and when sync is started plugin **always** logs list of files in one message with "debug" level.
this message takes 90% of all log file. if you set logstravaganza to create .md, this md note just doesn't load and syncing is too long.
message is like this:
```ndjson
{"timestamp":"2024-04-21T10:41:29.565Z","level":"debug","sender":"plugin:remotely-save:330:83281","args":[[[{"keyRaw":".obsidian/","mtimeSvr":1712408388000,"mtimeCli":1712408388000,"sizeRaw":0,"etag":null},{"keyRaw":".trash/","mtimeSvr":1712262126000,"mtimeCli":1712262126000,"sizeRaw":0,"etag":null},{"keyRaw":"Docs/...}]]]}
```
even if you set log level to info.
is there a way to turn off debug messages or turn off logging from remotely-save completely (without turning off logstravaganza)?

### What OS are you using?

Windows, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal, webdav

### Version of the plugin

0.4.16

### Version of Obsidian

1.5.12

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
But may I ask why do you use logstravaganza?

If you are developing another plugin, just use a test vault and don't need Remotely Save in your test vault. If you are debugging Remotely Save, then the massive debug info *might* be helpful.

And admittedly the output of Remotely Save is too verbose (the plugin outputs the file lists). I reduces the output in new version.

**Comment by buckssss** [comment]
> But may I ask why do you use logstravaganza?

I just like logging everything (profession demands). I like to know when, why and what is happened (not paranoic) =)
On android I can't see console logging, so I use logstravaganza (like it said in this plugin's Wiki).

**Comment by fyears** [comment]
I add a pr to https://github.com/czottmann/obsidian-logstravaganza/pull/12 , where user can get different log level output.

**Comment by buckssss** [comment]
> I add a pr to [czottmann/obsidian-logstravaganza#12](https://github.com/czottmann/obsidian-logstravaganza/pull/12) , where user can get different log level output.

Thank you!
