### ISSUE TITLE
[Bug]: Pixel 3, Android, Dropbox error code 409 on connectivity check

### ISSUE THREAD

**Issue by dzianisv** [remotely-save/remotely-save#621]
### What happened?

The plugin fails to connect to Dropbox on Android 12, Pixel 3.
See attached screenshots.
I tried with and without VPN.

![Screenshot_20240421-223827](https://github.com/remotely-save/remotely-save/assets/2119348/20b7e207-8378-4894-b6bb-a069bb5b545c)
![Screenshot_20240421-223837](https://github.com/remotely-save/remotely-save/assets/2119348/ac5cae5d-0bd8-4f19-b6d1-6d715a281f76)

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

0.4.16

### Version of Obsidian

1.5.12 (134)

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
can you establish the connection on pc/mac? if yes, can you please try to export the pc setting and import the setting on mobile and try again?

no clues yet. never encountered the problems

**Comment by dzianisv** [comment]
@fyears , yes, I managed to connect to the dropbox from macOS, that is connected to the same wifi network.

**Comment by dzianisv** [comment]
When I copy-paste the dropbox export URI into the mobile app, it says: 
Errors while parsing settings:
```
{"func":"settings","version":"0.4.16","vault":"Notes","data":{"dropbox":""}}
```

**Comment by fyears** [comment]
l

**Comment by dzianisv** [comment]
It works after I exported dropbox from macBook.
