### ISSUE TITLE
[Bug]:this plugin fail to load in HUAWEI Harmony OS 4.0，the apk version obsidian 1.5.1+.

### ISSUE THREAD

**Issue by doriszhang2020** [remotely-save/remotely-save#622]
### What happened?

![微信图片_20240422125118](https://github.com/remotely-save/remotely-save/assets/104901283/3a7742b3-51cd-4ded-8ac0-a08077571e5e)
the plugin fail to load in HUAWEI Harmony OS 4.0，the apk version obsidian  1.5.1+.but it can load in win11.

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

others

### Version of the plugin

0.4.16

### Version of Obsidian

1.5.11 and 1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
请网络搜索更新 huawei webview

**Comment by doriszhang2020** [comment]
> 请网络搜索更新 huawei webview

熬，其他插件可以加载，为何唯独这个需要huawei webview？

**Comment by doriszhang2020** [comment]
其他插件可以加载，只有此插件无法加载



---Original---
From: ***@***.***&gt;
Date: Mon, Apr 22, 2024 13:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [remotely-save/remotely-save] [Bug]:this plugin fail to load in HUAWEI Harmony OS 4.0，the apk version obsidian 1.5.1+. (Issue #622)




 
请网络搜索更新 huawei webview

**Comment by fyears** [comment]
因为这个插件比其他插件复杂，或者需要更加新的 web 技术，所以依赖更新的 webview

**Comment by doriszhang2020** [comment]
华为系统已经更新到了最新了 仍然无法加载



---Original---
From: ***@***.***&gt;
Date: Mon, Apr 22, 2024 17:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [remotely-save/remotely-save] [Bug]:this plugin fail to load in HUAWEI Harmony OS 4.0，the apk version obsidian 1.5.1+. (Issue #622)




 
因为这个插件比其他插件复杂，或者需要更加新的 web 技术，所以依赖更新的 webview

**Comment by doriszhang2020** [comment]
可以啦，因为华为默认的webview是谷歌，需要改成huawei webview谢谢



---Original---
From: ***@***.***&gt;
Date: Mon, Apr 22, 2024 17:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [remotely-save/remotely-save] [Bug]:this plugin fail to load in HUAWEI Harmony OS 4.0，the apk version obsidian 1.5.1+. (Issue #622)




 
因为这个插件比其他插件复杂，或者需要更加新的 web 技术，所以依赖更新的 webview

**Comment by fyears** [comment]
其实也可以考虑把谷歌 webview 升级，思路是相同的。不过能解决就好。

**Comment by lalala951** [comment]
> 可以啦，因为华为默认的webview是谷歌，需要改成huawei webview谢谢
> […](#)

您好，是在开发者选项中设置吗，我也是这种情况，我开发者选项中就是huawei webview，只有这一个选择，15.0.4版本的webview，还是显示插件加载失败
