### ISSUE TITLE
[Bug]: 插件无法启用 HUAWEI Harmony OS 4.0，obsidian 1.5.12.

### ISSUE THREAD

**Issue by doriszhang2020** [remotely-save/remotely-save#623]
### What happened?

![微信图片_20240422140214](https://github.com/remotely-save/remotely-save/assets/104901283/057418c3-4474-48b2-a088-fe73fda71716)
其他插件正常下载启用！
![微信图片_20240422125118](https://github.com/remotely-save/remotely-save/assets/104901283/f53d0b22-7c1b-4891-a521-5bdf79336afa)

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

others

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
请不要重复提交哈，在原来那个跟进
