### ISSUE TITLE
[Bug]:  Obsidian is freezed after a few hours

### ISSUE THREAD

**Issue by FlameInBrains** [remotely-save/remotely-save#625]
### What happened?

While using this plugin, obsidian freezes after a few hours of working(4-5 hours) on one of the synced computers.

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (ownCloud)

### Version of the plugin

0.4.16

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
do you have large files? please try to configure skip large files in the settings

**Comment by FlameInBrains** [comment]
The max size of one file is up to 5MB, but their overall quantity is around 2k

**Comment by FlameInBrains** [comment]
Turning off the plugin solves this issue

**Comment by fyears** [comment]
have you enabled auto sync?
