### ISSUE TITLE
[Feature Request]: Config files for mobile and mac

### ISSUE THREAD

**Issue by rjborba** [remotely-save/remotely-save#626]
### What feature are you suggesting?

Hi. I'm using currently three devices. A Macbook, an Ipad and an iphone. I would like to have different config files. One for the desktop and another for the iphone and Ipad.

It seems that dot files are not synced and obsidian requires a .something in order to override the default .obsidian folder. I could not find a way around it. Is this possible with Remotely Sync or is it indeed a feature request form my end? 

Thanks!

### What remote cloud services are you using, or suggesting adding the feature to?

S3 (Cloudflare R2)

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Hi,

Please be aware that the plugin is called Remotely **Save**. 

> "I would like to have different config files" 

You can achieve this by change the Obsidian config folder: https://help.obsidian.md/Files+and+folders/Configuration+folder#:~:text=Obsidian's%20configuration%20folder%20contains%20all,to%20change%20your%20config%20folder. You can, say, change the folder name to `.obsidian-mobile` on your mobile, and `.obsidian-pc` on your pc.

> It seems that dot files are not synced

Go to Remotely Save settings, "Advance Settings" -> "Sync Config Dir" -> "Enable".

Combining two steps above you should be able to sync config folders and do not messy them up on different machines.
