### ISSUE TITLE
[Bug]: 腾讯云pc端无法访问存储桶

### ISSUE THREAD

**Issue by Lingwuxin** [remotely-save/remotely-save#628]
### What happened?

腾讯云cos，相同的配置，在安卓平板上可以正常同步，但是在windows pc上无法访问存储桶

![image](https://github.com/remotely-save/remotely-save/assets/57278566/29b89758-9d41-4472-acd6-184fbdc2ea9e)
![image](https://github.com/remotely-save/remotely-save/assets/57278566/ba16ed9b-1b39-4acb-9bd7-76000c078e52)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (腾讯云 COS Tencent Cloud COS)

### Version of the plugin

0.4.16

### Version of Obsidian

v1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Lingwuxin** [comment]
这是在平板上检查同步时的提示信息
![Screenshot_2024-04-25-23-21-29-957_md obsidian-ed](https://github.com/remotely-save/remotely-save/assets/57278566/fb4d2439-beb2-4d4d-a3dd-347f4929231a)
在尝试通过腾讯云控制台上传文件之后，在安卓端能够正常访问cos并且同步文件。

**Comment by Lingwuxin** [comment]
发完issue发现刚发布的issue变成了半个小时前发布的。
嘿，您猜怎么着，原来是pc的时钟坏了，同步时间之后就能正常访问了
尴尬

**Comment by fyears** [comment]
谢谢你，提供了新的思路！我没想到这也会导致错误。
