### ISSUE TITLE
[Feature Request]: bypass dropbox 429 too many requests

### ISSUE THREAD

**Issue by fyears** [remotely-save/remotely-save#63]
### What feature are you suggesting?

bypass dropbox 429 too many requests

### What remote cloud services are you using, or suggesting adding the feature to?

Dropbox

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
add exponential back off in https://github.com/remotely-save/remotely-save/commit/ba6e8be30409b6e4d46cf3d0f561663728f850a9

**Comment by ksdavidc** [comment]
I am still getting a lot of these on a mac with latest version installed. What is the cause of this? Is there a way to avoid this, say by restructuring the vault?
