### ISSUE TITLE
[Bug]: Alist 配置的 webDav 在 Ios 手机端连接不上

### ISSUE THREAD

**Issue by zhanglingde** [remotely-save/remotely-save#630]
### What happened?

Ios 手机端连接 alist 配置的 webDav 报错，如下图（PC 端和 IOS 之前 0.3.25 版插件可以连接成功）
![IMG_3572](https://github.com/remotely-save/remotely-save/assets/51218642/df1bbe8f-f24b-4a37-a6ab-ec40217372a0)

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (AList)

### Version of the plugin

0.4.16

### Version of Obsidian

ios 最新版

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
正如错误提示所提示，
新版本的 iOS Obsidian 不允许 http 链接了。
你需要一个合法的 https 证书配置到你的 webdav server 上，
然后修改 Remotely Save 设置里的链接地址为 https://...

**Comment by zhanglingde** [comment]
相同版本的 Obsidian，我有两个仓库，另一个仓库的 remote save 是 0.3.25 版本的，还是可以连接上 webdav 的

**Comment by zhanglingde** [comment]
@fyears 相同版本的 Obsidian，我有两个笔记仓库，另一个笔记仓库的 remote save 还是 0.3.25 版本的，还是可以连接上 webdav 的

**Comment by fyears** [comment]
你的 obsidian 是什么版本呢？

**Comment by zhanglingde** [comment]
@fyears 是 ios 1.5.12 版本的

**Comment by fyears** [comment]
别纠结了，还是配置上 https 吧，大势所趋。
