### ISSUE TITLE
[Bug]: 手动点击同步后，弹出消息异常重复。

### ISSUE THREAD

**Issue by lyiton** [remotely-save/remotely-save#631]
### What happened?

![Screenshot_2024-04-27-23-25-50-289_md obsidian](https://github.com/remotely-save/remotely-save/assets/76651858/45d82cf0-7f9e-4e87-9b31-8c25ea11c717)
手动点击同步后，弹出消息异常重复。

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.4.18

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
已知问题。0.4.19 已解决。
