### ISSUE TITLE
[Feature Request]: a new option to avoid conflicts when Sync Config Dir is on

### ISSUE THREAD

**Issue by hao-yg** [remotely-save/remotely-save#632]
### What feature are you suggesting?

Add an option in Sync Config Dir .obsidian: enable (but exclude 'remotely save' config), to avoid some conflicts. For example, I choose 'incremental push only' for sync direction on my mobile device, while if Sync Config Dir is on, the option will be set as bidirectional (default), which may make some mistakes.

### What remote cloud services are you using, or suggesting adding the feature to?

S3 (阿里云 OSS Alibaba Cloud OSS)

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
I don't think it's a good idea. I am afraid currently the settings are complex enough.
