### ISSUE TITLE
[Bug]: The certificate for this server is invalid (local area network minio)

### ISSUE THREAD

**Issue by asinwang** [remotely-save/remotely-save#634]
### What happened?

In Windonws System ,I can use minio https://192.168.1.249:9000.
Then share QR code import my ios system,get error:

Error: Request failed. The certificate for this server is invalid. You might be connecting to a server that is pretending to be "192.168.1.249" which could put your confidential information at risk.

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (MinIO)

### Version of the plugin

0.4.19

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [x] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
As the error suggests, you have to configure your http**s** certificate correctly.

**Comment by asinwang** [comment]
证书是使用mkcert生成的，mkcert -instal有一个CA证书，PC需要安装CA证书后，浏览器端使用就不会报证书不信任问题了，然后PC端的remotely-save里可以正常运行https了，IOS端也需要安装这个CA证书，应该在这一步出问题了，IOS端不清楚是怎么使用CA证书的。
https://stackoverflow.com/questions/43665243/invalid-self-signed-ssl-cert-subject-alternative-name-missing这里提到的方案我还在测试，采纳的答案貌似不行，这个问题本质是CA证书的问题

**Comment by asinwang** [comment]
> As the error suggests, you have to configure your http**s** certificate correctly.
证书没有问题，PC端浏览器remotely-save里都可以正常运行https的

**Comment by fyears** [comment]
mkcert 本质上就是本地生成了一个根证书并安装信任啊，iOS 当然是不会自动信任的。
我没试过，但是看到 mkcert 官网是支持安装 profile 到 iOS 的，你试试呢，mobile device 段落 ：<https://github.com/FiloSottile/mkcert?tab=readme-ov-file#mobile-devices>

**Comment by fyears** [comment]
另外，也可以考虑用 tailscale，也有多种方法为内网增加 `*.ts.net` 域名并增加“真正的” https 证书。我在群晖也实验成功的。

**Comment by asinwang** [comment]
> mkcert 本质上就是本地生成了一个根证书并安装信任啊，iOS 当然是不会自动信任的。 我没试过，但是看到 mkcert 官网是支持安装 profile 到 iOS 的，你试试呢，mobile device 段落 ：https://github.com/FiloSottile/mkcert?tab=readme-ov-file#mobile-devices

可以了，这里有两步，安装和信任，之前我只做了安装。
