### ISSUE TITLE
[Bug]: Filenames with " and ? characters throws FILE_NOTCREATED error on Android

### ISSUE THREAD

**Issue by BenyAlbatross** [remotely-save/remotely-save#635]
### What happened?

When running remotely save on Obsidian on Android, filenames with " and ? throw the following error:
"xxx".md: FILE_NOTCREATED 
xxx?.md: FILE_NOTCREATED

### What OS are you using?

macOS, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.4.19

### Version of Obsidian

1.5.12 (both macos and android)

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
it is likely to be prohibited to create file names with these special characters on android. no way for the plugin to fix this

**Comment by Nik-mmzd** [comment]
Actually, you can workaround this by saving mappings aka "local: xxx_.md => remote xxx?.md" and syncing using these mappings.
I think smth simular happens on Windows when using symbols like <>*? in title/filename (only macOS and Linux have no weird filename restrictions)

**Comment by fyears** [comment]
no. it adds more complexity and users will be confused.

**Comment by Nik-mmzd** [comment]
Maybe add an opt-out warning to prevent user from creating it then?
Most users will be more confused with unsyncable files IMHO, so, this plugin should try to prevent or workaround such cases.
It'll be better to get a warning on file creation/first sync and rename a file before any sync errors happen that discover required file cannot be synced to weird OS/FS limitations when there are no PC nearby to rename this file

**Comment by nuf0n** [comment]
I second this. It's unreasonable to expect the typical user being sufficiently technically knowledgable to diagnose then resolve issues like this. It's a unique edge-case that's straightforward to address at the plugin layer via UI notices and/or simple checkboxes in the settings. 

To confirm for anyone having similar issues, I needed to remove the question mark from just the filename on Mac and rerun sync on both ends to successfully copy the files. My storage of choice is Dropbox - never have had issues with it.
