### ISSUE TITLE
[Feature Request]: Synchronization is missing to specify a folder, existing plugins are creating a folder

### ISSUE THREAD

**Issue by qinyonghello** [remotely-save/remotely-save#636]
### What feature are you suggesting?

OneDrive Sync, the plugin's sync is creating a folder under /app/ ，but I want to sync inside a specified folder. 

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Sorry, currently is not possible. It's a protection rather than a limitation. So that the plugin will not messy up your other files unintentionally.

The feature may be implemented in the future.
