### ISSUE TITLE
[Bug]: 手机端无法同步到电脑，会变成乱码

### ISSUE THREAD

**Issue by VinceAixingueluo** [remotely-save/remotely-save#64]
### What happened?

电脑端![image](https://user-images.githubusercontent.com/32014745/161020416-8e17c783-4551-4871-96ca-987887787ade.png)
手机端
![QQ图片20220331171251](https://user-images.githubusercontent.com/32014745/161020761-fbe22ef3-be70-4e5f-81d8-48a31093d5d3.jpg)

### What OS are you using?

Windows, Android

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.14

### Version of Obsidian

电脑0.14.2 安卓1.1.1

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
请问你是否用了其他的插件？能否新开一个测试的vault，只安装remotely save来看看能否复现？

之前有用户反馈和 day planner 冲突

**Comment by VinceAixingueluo** [comment]
> 请问你是否用了其他的插件？能否新开一个测试的vault，只安装remotely save来看看能否复现？
> 
> 之前有用户反馈和 day planner 冲突

电脑测试库
![image](https://user-images.githubusercontent.com/32014745/161122729-25c42e69-e68e-4d5f-995b-187e24ca6da6.png)
![image](https://user-images.githubusercontent.com/32014745/161121769-16043d35-3921-45f7-a7b1-9266a214b03f.png)
手机测试库
![QQ图片20220401021219](https://user-images.githubusercontent.com/32014745/161122811-6e241bac-ed05-46a2-9dcd-57e68b8141f8.jpg)
由此可见并不是插件冲突问题
我猜想可能的原因是JSON问题应为我也出现了Unexpected token e in JSON at position 0这个问题我根据这个回复删除文件后
就出现问题了
![image](https://user-images.githubusercontent.com/32014745/161123719-7e173f4c-46f4-4d94-9dd4-eb5c9d7d4972.png)
回复网址https://github.com/remotely-save/remotely-save/issues/57

**Comment by fyears** [comment]
和那个文件无关。麻烦直接在onedrive网页版下载下来，看看是否乱码？麻烦看看直接下载下来的文件，编码和 line ending 是什么？谢谢！

**Comment by fyears** [comment]
我尝试复现一下

**Comment by VinceAixingueluo** [comment]
电脑端同步正常
![tmpBF64](https://user-images.githubusercontent.com/32014745/161189650-649983d4-3b61-4b55-8199-c28c81d10e41.png)
手机端同步不正常网页版onedive变成了乱码
![tmpBF64](https://user-images.githubusercontent.com/32014745/161189697-9e5a1298-7515-4420-99a8-fcebc2263047.png)
手机端同步的的整个库文件
[folder.zip](https://github.com/remotely-save/remotely-save/files/8394470/folder.zip)
另外的一些问题
![image](https://user-images.githubusercontent.com/32014745/161189813-74af96d1-6d6b-4404-a41f-6d68fafa92c9.png)

**Comment by fyears** [comment]
unexpected token，应该也是因为同步上去的 json 有问题（变成base64），从而出错，也就是说他是结果，而不是原因。

谢谢详细信息，我找个android复现一下

**Comment by fyears** [comment]
此外你两幅截图是同一副？

**Comment by VinceAixingueluo** [comment]
上传错了这个才是手机端同步照片
![tmpF14F](https://user-images.githubusercontent.com/32014745/161207467-73ba52c3-6194-4f56-a4a1-3ce2d3b75927.png)
![QQ图片20220401111342](https://user-images.githubusercontent.com/32014745/161207561-aad44325-dcb8-4990-a232-e64360e53cd4.jpg)
希望能尽快修复谢谢

**Comment by fyears** [comment]
Android 可以重现此 bug，但是同样的代码在 iOS 和 Windows 是没问题的。。。

我用了另一个方式绕开了这个 bug，在 Android 测试 ok 了。

请尝试新版本 https://github.com/remotely-save/remotely-save/releases/tag/0.3.15

因为这个 bug 应该已被 fix 了，所以我就关闭这个 issue 了。如果还有相同的 bug，可以重开此 issue。

**Comment by fyears** [comment]
遗憾的是，需要先把 OneDrive 里乱码的那个资料库文件夹删除掉，然后重新开始全量同步。
