### ISSUE TITLE
[Bug]: The cloud and local files are the same, but the parameters calculated by the algorithm are different, so it prompts that files above 0.95 must be modified.

### ISSUE THREAD

**Issue by JONYS18** [remotely-save/remotely-save#642]
### What happened?

I am using OSS and can access the bucket correctly. When uploading the window file to OSS and then downloading it to the iPad, if I click sync without making any changes, it will prompt that all 0.95 files will be modified. The following is the synchronization logging

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.4.19

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
for example, look at the file in 000Support/020Templates

the remote file has newer dates. it seems that your windows and ipad have both files aready but windows  update the files the ipad think the file is newer on s3.

Make a manual backup of your vault,then relax the protection on ipad and let ipad sync. then **re enable** the protection on ipad.
