### ISSUE TITLE
[feature request]: shorten text "synced less than a minute" 

### ISSUE THREAD

**Issue by nallebrean** [remotely-save/remotely-save#645]
### What happened?

When status bar are changed to "synced less than a minute" the bar gets from 2 to 3 rows and create a disturbing flicker.

I suggest it's changed to the shorter "synced last minute".

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.4.19

### Version of Obsidian

1.5.12 (134)

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
changed in 0.4.20
