### ISSUE TITLE
Plugin and config synchronization

### ISSUE THREAD

**Issue by JEONGHA-SHIN** [remotely-save/remotely-save#647]
### What feature are you suggesting?

From what I understand, It shoud be possible to synchronize plugins and settings by turning on the "Sync Config Dir" setting. But even though the synchronization is succeeded, it seems that installed plugins and settings are not being synchronized. 

What am I missing?

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by JEONGHA-SHIN** [comment]
> do you find out the synced folder being in onedrive website?

Yes, I confirmed that they are saved in the remote-save folder. 
In particular, I also checked the files in the .obsidian folder.

**Comment by fyears** [comment]
ao have you enabled syncing config dir on your second device?

**Comment by notapelican** [comment]
I'm having the same issue.  Can confirm, the .obsidian and plugin folders are syncing to the onedrive cloud, but not down to the device that they're synced with.

**Comment by notapelican** [comment]
Yup, enabled on both

**Comment by fyears** [comment]
> but not down to the device that they're synced with.

how do u confirm this? on mobile the folder is hidden and u can't easily directly view that folder

**Comment by fyears** [comment]
i *believe* the plugin should work if the settings is enabled on both side. are u using android? have you done anything unusual like changing the config folder? or can you reproduce the error if uou have 2 computers?

**Comment by fyears** [comment]
and please export the sync plan on second device and see if the .obsidian folder occur inside the sync plan

**Comment by JEONGHA-SHIN** [comment]
In fact, I checked that the config values of communitu plugin's configuration values are synchronized in the second device.

But the most first thing I have to do was manually installing the community plug-in, for the each other devices.After installing plug-in at all devices, the each configurations of plugins were well synchronized.

**Comment by fyears** [comment]
yeah sure. if you do not install remotely-save on second device, surely the second device will not know anything about syncing.

**Comment by JEONGHA-SHIN** [comment]
Ofcourse i installed remotely save in all devices, and what I meant was I should install other plug-ins manually.

After manual install of all plugins that i'm using, then the configs are synchronized correctly.

**Comment by notapelican** [comment]
> i _believe_ the plugin should work if the settings is enabled on both side. are u using android? have you done anything unusual like changing the config folder? or can you reproduce the error if uou have 2 computers?

I am on android, yes.

I don't believe I changed the config folder.

I'll try it out on my laptop and see, but last time I tried it, it didn't work.

**Comment by fyears** [comment]
> After manual install of all plugins that i'm using, then the configs are synchronized correctly.

that’s abnormal. in the code, the plugin treats config files or folders almost the same way…

**Comment by notapelican** [comment]
I just tried it on my laptop - the plugins appeared in the folder, but I had to manually activate each of them in settings. It was also hit and miss how much customisation came along with them

**Comment by fyears** [comment]
> the plugins appeared in the folder, but I had to manually activate each of them in settings.

that's because, the file that recording which plugin is activated, is always changed or modified by obsidian itself. no way to work around

**Comment by notapelican** [comment]
> > the plugins appeared in the folder, but I had to manually activate each of them in settings.
> 
> that's because, the file that recording which plugin is activated, is always changed or modified by obsidian itself. no way to work around

Right, makes sense, thanks.

At the moment, every time I use Obsidian on mobile, it (obviously) disables the non-mobile plugins. But because I have plugins synced, when I open it again on my PC, it has the non-mobile plugins disabled.

Any idea how to avoid this?

**Comment by fyears** [comment]
i think disabling syncing plugin folder is sufficient. usually it’s not changed very often

**Comment by notapelican** [comment]
> i think disabling syncing plugin folder is sufficient. usually it’s not changed very often

I want plugins I install on PC to also install on my phone, though

**Comment by notapelican** [comment]
> i think disabling syncing plugin folder is sufficient. usually it’s not changed very often

Is there a way to make it keep syncing the Config Dir, but not community-plugins.json, which to my understanding (based on help from someone on the Obsidian Discord) should make it continue syncing the community plugins, just not whether they're enabled?

**Comment by fyears** [comment]
the plugin has a setting to ignore some files.

you can input

```
.obsidian/community.json
```

there

**Comment by notapelican** [comment]
> the plugin has a setting to ignore some files.
> 
> you can input
> 
> ```
> .obsidian/community-plugins.json
> ```
> 
> there

Thank you!!

**Comment by notapelican** [comment]
> the plugin has a setting to ignore some files.
> 
> you can input
> 
> ```
> .obsidian/community-plugins.json
> ```
> 
> there

Sorry, I just tried it and it seems to not sync community plugins at all now...

I could always activate them on each device independently, it'd just be cool if they synced across

**Comment by fyears** [comment]
I am sure the plugins will be synced if you:

1. turn on sync config dir
2. add `.obsidian/community-plugins.json` into ignore

**Comment by CnsMaple** [comment]
@notapelican 
During the first sync, select Incremental Pull and Delete. Otherwise, the new device's configuration files will overwrite the old ones, causing plugin synchronization failures. This is because the new device's configuration files meet the conflict criteria and use the newer revision.

After selecting the above option, syncing, and restarting Obsidian, your workspace will be identical to the cloud, including the options you just set.

**Comment by notapelican** [comment]
> [@notapelican](https://github.com/notapelican) During the first sync, select Incremental Pull and Delete. Otherwise, the new device's configuration files will overwrite the old ones, causing plugin synchronization failures. This is because the new device's configuration files meet the conflict criteria and use the newer revision.
> 
> After selecting the above option, syncing, and restarting Obsidian, your workspace will be identical to the cloud, including the options you just set.

Thank you, that makes a lot of sense, I'll try it now!
