### ISSUE TITLE
[Feature Request]: Sync status misleading

### ISSUE THREAD

**Issue by TaoranFu** [remotely-save/remotely-save#648]
### What feature are you suggesting?

Sync and sync status bar is really useful. However, when the sync is uncompleted due to empty files (which is an updated algorithm outcome I guess?) the sync status still reported itself as "synced now/synced 2 minutes ago", while the actual sync is not completed. 

When all error info is shown on the right and disappears in a second, it is very hard to scroll down all the info and track the correct sync status. Please could the sync status show "error and sync incomplete" instead of a misleading "synced now"?

Remotely Save v0.4.20

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> when the sync is uncompleted due to empty files

if you are using onedrive, the old version will silently skip the empty files, but the new version will complain so that users know what happen.

> could the sync status show "error and sync incomplete"

i will try to implement that in a few days

**Comment by fyears** [comment]
in 0.4.21, if the sync fails, in a minute the status bar shows the sync failed. but after a minute the status bar will show last **real** successful sync time.
