### ISSUE TITLE
[Bug]: copying local=>encrypt(s3,rclone-base64): size not matched 

### ISSUE THREAD

**Issue by kele1997** [remotely-save/remotely-save#649]
### What happened?

# 1. first sync 
There are no errors in console during first sync 

 
# 2. second sync 
android will show error like `size not matched`  

chrome console also show `size not matched`  
```
error copying local=>encrypt(s3,rclone-base64): size not matched
        at eval (plugin:remotely-save:338:172475)
```

the real size of file in android filesystem is `0`. But I can open the note/picture in obsidian normally. 
Everytime I delete the whole vault, and sync, there are serveral files show `size not matched`,and the files is randomly choosed. 

![image](https://github.com/remotely-save/remotely-save/assets/24707678/79f1327f-8a65-4f75-aad6-b73479af89ba)

## 3. second sync plan: 

```json
  "something/somenote": {
    "key": "something/somenote",
    "remote": {
      "key": "something/somenote",
      "keyRaw": "something/somenote",
      "mtimeSvr": 1714976456000,
      "mtimeCli": 1714976456000,
      "sizeRaw": 5047,
      "size": 5047,
      "etag": "\"191A7D8636F53B155D45820C0BBCE2E2\"",
      "synthesizedFolder": false,
      "keyEnc": "something/somenote",
      "sizeEnc": 5047,
      "mtimeCliFmt": "2024-05-06T14:20:56+08:00",
      "mtimeSvrFmt": "2024-05-06T14:20:56+08:00"
    },
    "prevSync": {
      "key": "something/somenote",
      "keyRaw": "something/somenote",
      "mtimeSvr": 1714976456000,
      "mtimeCli": 1714976456000,
      "sizeRaw": 5047,
      "size": 5047,
      "etag": "\"191A7D8636F53B155D45820C0BBCE2E2\"",
      "synthesizedFolder": false,
      "keyEnc": "something/somenote",
      "sizeEnc": 5047,
      "mtimeCliFmt": "2024-05-06T14:20:56+08:00",
      "mtimeSvrFmt": "2024-05-06T14:20:56+08:00"
    },
    "local": {
      "key": "something/somenote",
      "keyRaw": "something/somenote",
      "mtimeCli": 1714976456000,
      "mtimeSvr": 1714976456000,
      "size": 0,
      "sizeRaw": 0,
      "mtimeCliFmt": "2024-05-06T14:20:56+08:00",
      "mtimeSvrFmt": "2024-05-06T14:20:56+08:00",
      "keyEnc": "something/somenote",
      "sizeEnc": 0
    },
    "decisionBranch": 10,
    "decision": "local_is_modified_then_push"
  }
```

## 4.1 note files information 
all files: 1280 (contain .obsidian plugins, jpg,webp, pdf) 
the size of total files is about 60mb. 

|ext|count|
|---|---|
|jpg|56|
|png|94|
|webp| 87|
|pdf | 3|
|md| 884|
|js|90|
css|23|

## 4.2 remotely save settings
parts concurrency: 20(default) 
skip large files: no set
advanced settings -- concurrency: 5(default)
action for empty folders: leave them as is(default)

## 5. current solution
modify remotely save `sync direction` from `Bidirectional` to `Incremental Pull Only` ，and sync manualy, then any file in vault is ok. after that , modify `sync directoin` back.

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.4.20

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by kele1997** [comment]
I think it's file system bug or miui bug.

After a while , I found the file's size changed.


![image](https://github.com/remotely-save/remotely-save/assets/24707678/3d1b4c56-9c4a-4593-9db6-42da5ef3ece1)


![image](https://github.com/remotely-save/remotely-save/assets/24707678/1f85452b-d06e-43aa-b83f-28e282170175)

**Comment by fyears** [comment]
yeah... i am afraid i can do nothing here. please try to upgrade your os
