### ISSUE TITLE
[Bug]: 在我的dropbox中看到了别人的Ob库

### ISSUE THREAD

**Issue by BCS1037** [remotely-save/remotely-save#65]
### What happened?

在我的dropbox库中，竟然有别人的ob库

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using?

OneDrive for personal, Dropbox

### Version of the plugin

0.3.14

### Version of Obsidian

0.14.2

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
??? 有点离谱。请问您是中文论坛的 BCS 吗？请问有 discord 账号吗？我们交流一下详情？

**Comment by fyears** [comment]
此外，建议立刻吧本地的文档移走备份，并且把删除操作上传到 dbx。

此外，请问你有把 data.json 分享过给他人吗？

**Comment by fyears** [comment]
此外，麻烦确认一下这里的用户名是不是你本人的用户名？

![95389517-76D0-4042-94A6-08024DFA1CFF](https://user-images.githubusercontent.com/1142836/161110816-6c4cf468-0f8e-4017-b3e3-b4ea1c85d6b8.jpeg)

**Comment by fyears** [comment]
可能是信息泄露了

1. s3：重设 accesskeyid 和 accesssecretkey 
2. webdav：重设账号密码
3. onedrive: https://microsoft.com/consent 完全取消授权。一定要完全在网页里取消授权，仅仅 remotely-save 里取消授权是不够的。
4. dropbox： https://www.dropbox.com/account/connected_apps 完全取消授权。一定要完全在网页里取消授权，仅仅 remotely-save 里取消授权是不够的。

**Comment by lishid** [comment]
@fyears 建议把用户授权码存在 `localStorage` 里而不是 `this.settings` 这样就不会不小心被分享出去了。

比如说 `localStorage.setItem('REMOTELYSAVE-DROPBOX-TOKEN', token)`

**Comment by fyears** [comment]
@lishid 居然引来了作者大佬来评论……

这里的一个矛盾点在于，如果放在 localstorage ，那么**同一个人**就无法方便地把配置从自己的设备A复制到自己的设备B了，当初正是出于此考虑而放在 data.json 了。

不过，唉，我看看要不要改吧……

**Comment by lishid** [comment]
有道理。。。
