### ISSUE TITLE
Synology Drive support?

### ISSUE THREAD

**Issue by joy521125apple** [remotely-save/remotely-save#650]
### What feature are you suggesting?

can support Synology Drive

### What remote cloud services are you using, or suggesting adding the feature to?

others

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by joy521125apple** [comment]
I am using Synology NAS WebDav Server, and the prompt requires https. Currently I only have http 。iOS: 16.0.3 ob:1.5.12；
![微信图片_20240507154300](https://github.com/remotely-save/remotely-save/assets/14277489/1b27342d-ad45-48dd-a3c8-a82409d9012d)
Synology Drive Server is a comprehensive file management, sharing and synchronization solution.....
https://www.synology.cn/zh-cn/dsm/solution/cross-office_file_sharing

So,is it possible to support Synology Drive?

**Comment by fyears** [comment]
https 在 ios 无法绕过，这是系统限制，你一定要配置一个正常的 https 证书，比如说用 tailscale 或者 mkcert 或群晖自己的服务。

目前支持的是群晖 webdav server


不清楚 synology drive 和 webdav server 有什么区别。他们是不同的吗？
