### ISSUE TITLE
[Bug]: Empty file is not allowed in OneDrive, and please write something in it.

### ISSUE THREAD

**Issue by Andy001000** [remotely-save/remotely-save#651]
### What happened?

I have updated to the lasted version 0.4.20 and when I run the sync, it report the message: "Empty file is not allowed in OneDrive, and please write something in it."  

Then all the sync ended, the sync doesn't work.

I am sure all my file are not empty file . luckily, I stored the old version 0.3.25 , and I reused it and worked well, did not message the above.

<img width="296" alt="image" src="https://github.com/remotely-save/remotely-save/assets/145722734/b971e760-732f-403b-9d7a-184e57c82417">

### What OS are you using?

macOS

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.4.20

### Version of Obsidian

1.5.12

### Using password or not

- [x] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
it's likely to be an empty file.

you can export the sync plan and find out what original file name the encrypted file `U2F...iPIs` refer to.

the old version seems to work but that's a "lie", because the old version silently ignore the empty file instead of telling you with an error

**Comment by Andy001000** [comment]
> silently

 Thanks for your reply,i am sure i don't have the empty files,and i have check the original file, but those notes maybe very small,less than 1kb,therefore，perhaps ignore it maybe is a good strategy or if possible,give an option to ignore it.

**Comment by fyears** [comment]
Finally I found out the bug and fixed it. Please try 0.4.21. Thanks for your report!
