### ISSUE TITLE
[Bug]: Error: No active file found

### ISSUE THREAD

**Issue by smilesxsy** [remotely-save/remotely-save#652]
### What happened?

I get this error when pulling from scratch on mobile, but it doesn't seem to have any other effect, the documents are pulled down
![Snipaste_2024-05-09_11-59-02](https://github.com/remotely-save/remotely-save/assets/40155072/98da4d02-e45a-4fd4-980d-7b6345e48867)

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (NextCloud)

### Version of the plugin

0.4.20

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
no active file 是同步中出现的，还是同步完毕后做了什么动作出现的？

**Comment by smilesxsy** [comment]
@fyears 同步中出现的，有看到文件数一直在增长

**Comment by fyears** [comment]
那么所以文件内容正常同步下来了吗？随便点开一个md文件后，再次触发同步，正常吗？

**Comment by smilesxsy** [comment]
点开几个笔记看着都正常，附件也正常，尝试了编辑md文件和新建md文件触发同步也正常

**Comment by fyears** [comment]
那么可能就是偶尔抽风了。不能复现的话就先关闭了。
