### ISSUE TITLE
Is there a version history?

### ISSUE THREAD

**Issue by ArneTillmann** [remotely-save/remotely-save#653]
### What feature are you suggesting?

Thanks for this great plugin. Love it since I've set it up recently.
Is there a version history of a file, like the one from the [official sync service](https://help.obsidian.md/Obsidian+Sync/Version+history)?
I couldn't find it, if it exists. 

### What remote cloud services are you using, or suggesting adding the feature to?

webdav, webdav (NextCloud)

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
No (currently). Admittedly it's technically hard to implement and may consume user's local storage.
