### ISSUE TITLE
Webdav Nextcloud not work

### ISSUE THREAD

**Issue by Anatoliyr210** [remotely-save/remotely-save#654]
### What happened?

![Screenshot_20240511_122829_Obsidian](https://github.com/remotely-save/remotely-save/assets/25100399/9ab503b4-6b64-4f68-b09b-e0b9b235c271)
![Screenshot_20240511_122811_Obsidian](https://github.com/remotely-save/remotely-save/assets/25100399/1608e4f0-d22d-456b-986e-7f12de2ed900)

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (NextCloud)

### Version of the plugin

0.4.21

### Version of Obsidian

Last

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
please configure a valid ssl certificate.

**Comment by Anatoliyr210** [comment]
I have a nextcloud setup at home. There is no domain name, only an ip address. The signed certificate itself has been made.
Other applications connect without problems.
![Screenshot_20240511_133728_MiXplorer](https://github.com/remotely-save/remotely-save/assets/25100399/57f901a2-b610-4ca6-85b0-07b0c9ef1b85)
![Screenshot_20240511_133740_MiXplorer](https://github.com/remotely-save/remotely-save/assets/25100399/2fbae1e1-daff-41f7-8c12-d0c8560bc014)

**Comment by fyears** [comment]
the obsidian api doesn't support self-signed https certificate so the plugin cannot skip it too

you have to either:

1. use a real valid certificate
2. if you are using lan, you can use tailscale and configure a ts.net valid certificate 
3. use mkcert to generate a self-signed certificate, **and install its root ca into your mobile and computer** https://github.com/FiloSottile/mkcert

**Comment by fyears** [comment]
and please don't expose your ip because it may not be safe. i hide it for you.

**Comment by Anatoliyr210** [comment]
Thank you very much for your help.
 Connected to webdav without a certificate on http, without https.
