### ISSUE TITLE
[Bug]: Obsidian Mobile keeps refreshing

### ISSUE THREAD

**Issue by Screen5058** [remotely-save/remotely-save#656]
### What happened?

手机上的黑曜石不停的刷新, 关掉插件以后可以正常使用, 应该是一个 bug

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

newest

### Version of Obsidian

newest

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Screen5058** [comment]
这个问题已经存在有一两个月了，好像从更新插件以后就一直会这样，目前我都是把手机上的remotely save文件夹移动到另一个地方再打开obsidian使用, 用完了要同步再移回去

**Comment by fyears** [comment]
没看懂，不停刷新是什么样子的？文件不断新建？

**Comment by fyears** [comment]
你开启了 auto sync 吗？

**Comment by Barmaid1076** [comment]
![IMG_1255](https://github.com/remotely-save/remotely-save/assets/110725436/c01f6590-b5d0-4402-939b-e74ef41b51d1)
刷新就是不停的重复loading plugins，间隔的时间不够我点进community plugins setting 去把remotely save 给关掉

**Comment by Barmaid1076** [comment]
我应该是没有开auto sync的

**Comment by fyears** [comment]
完全不知道为什么，方便的话，看一下 console？

https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/check_console_output.md

**Comment by Screen5058** [comment]
> 完全不知道为什么，方便的话，看一下 console？
> 
> https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/check_console_output.md

刷新的间隔时间不够进到设置里面去debug

**Comment by Screen5058** [comment]
> ios 什么版本，obsidian 什么版本，plugin 什么版本？有用 icloud 吗？
> 
> 新建测试 vault，随便写几个文件，只安装本插件，可以复现问题吗？

都是最新的版本，没有用 iCloud
我觉得有一个非常有可能的原因, 就是我的插件不是直接安装的，而是从windows上直接复制到ios里面去的

**Comment by Screen5058** [comment]
> 我应该是没有开auto sync的

我弄错了，我一直都是开着auto sync的，请问手机上是不能开这个设置吗？

**Comment by Screen5058** [comment]
> ios 什么版本，obsidian 什么版本，plugin 什么版本？有用 icloud 吗？
> 
> 新建测试 vault，随便写几个文件，只安装本插件，可以复现问题吗？

没有办法复现问题, TEST库很正常没有频繁的刷新

**Comment by Screen5058** [comment]
> > ios 什么版本，obsidian 什么版本，plugin 什么版本？有用 icloud 吗？
> > 新建测试 vault，随便写几个文件，只安装本插件，可以复现问题吗？
> 
> 都是最新的版本，没有用 iCloud 我觉得有一个非常有可能的原因, 就是我的插件不是直接安装的，而是从windows上直接复制到ios里面去的

然后我刚刚尝试了重新安装插件, 问题在原来的库上面还是存在

**Comment by Screen5058** [comment]
还有值得注意的一点是iphone有频繁刷新的问题。但是ipad没有

**Comment by fyears** [comment]
先不要auto run 然后正常运行试试。此外你的 ios 系统是什么版本？

**Comment by Barmaid1076** [comment]
> 先不要auto run 然后正常运行试试。此外你的 ios 系统是什么版本？

不auto run 手动sync也会重新刷新，ios系统是16.5

**Comment by fyears** [comment]
有多少个文件呢？此外这里其实不是 load 的问题，而是 sync 的问题吧。

方便回忆一下是哪个版本开始的吗？

**Comment by Screen5058** [comment]
> 有多少个文件呢？此外这里其实不是 load 的问题，而是 sync 的问题吧。
> 
> 方便回忆一下是哪个版本开始的吗？

大概一两个月之前或者更久吧

是指我的库里面总共有多少文件吗？很多, 几10个G, 2500多个文件, 

对好像是sync的问题, 之前没有注意到, 但是文件好像都能同步到手机上, 同步好像还能正常用, 就是要刷新个十几次

**Comment by Screen5058** [comment]
> > 有多少个文件呢？此外这里其实不是 load 的问题，而是 sync 的问题吧。
> > 方便回忆一下是哪个版本开始的吗？
> 
> 大概一两个月之前或者更久吧
> 
> 是指我的库里面总共有多少文件吗？很多, 几10个G, 2500多个文件,
> 
> 对好像是sync的问题, 之前没有注意到, 但是文件好像都能同步到手机上, 同步好像还能正常用, 就是要刷新个十几次

应该是两个版本或者3个版本之前

**Comment by fyears** [comment]
有大文件吗？应该是大文件的问题（超过 20 mb 的），可以去设置里设置跳过大文件看是否正常

**Comment by fyears** [comment]
webdav 是有性能问题；假如用 nextcloud 做服务器的话，可能有点办法。

**Comment by Screen5058** [comment]
> 有大文件吗？应该是大文件的问题（超过 20 mb 的），可以去设置里设置跳过大文件看是否正常

设置跳过10MB 的文件就不会在sync的时候刷新了，但是50mb都会有这个问题



> webdav 是有性能问题；假如用 nextcloud 做服务器的话，可能有点办法。

但是ipad和windows都没有这个问题，会不会是ios手机的问题?
webdav 是什么样子的性能问题呢？

**Comment by fyears** [comment]
10 mb 以上，读取都会有内存问题。此外也可能和 ios 版本有关。

**Comment by Barmaid1076** [comment]
> 10 mb 以上，读取都会有内存问题。此外也可能和 ios 版本有关。
请问是服务器的内存问题吗，有什么办法可以调高吗，我还装了两个内存条，内存都20g了好像

**Comment by fyears** [comment]
这是手机性能问题，不是服务器。手机内存有限制。

假如你的 webdav 服务器是 nextcloud / apache mod_dav / sabre 的话，那么支持分块上传，今晚会发布新版本支持分块上传功能，减轻手机内存压力减少 crash 几率。

假如你的 webdav 服务器是其他的话，那么没办法了。

**Comment by Screen5058** [comment]
> 这是手机性能问题，不是服务器。手机内存有限制。
> 
> 假如你的 webdav 服务器是 nextcloud / apache mod_dav / sabre 的话，那么支持分块上传，今晚会发布新版本支持分块上传功能，减轻手机内存压力减少 crash 几率。
> 
> 假如你的 webdav 服务器是其他的话，那么没办法了。

okok，谢谢！
