### ISSUE TITLE
[Bug]: `error copying local=>encrypt(...)` with OneDrive on Android

### ISSUE THREAD

**Issue by shcott** [remotely-save/remotely-save#657]
### What happened?

I am using Remotely Save with OneDrive successfully with my Windows PC. However, I just tried setting it up on my Samsung S23+. The initial sync was fine, but when I tried to sync again, I saw the error messages in the screenshot below. My phone is on Android 14. Any ideas what's going on here, and if it's working successfully or not?

![image](https://github.com/remotely-save/remotely-save/assets/14829183/4ba88e9e-109a-4835-9f0f-ba6d121eec67)

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.4.21

### Version of Obsidian

1.5.12 (134)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
do you edit the file at the same time of syncing? 

please consider not make edits and trigger the sync again, the error should be gone and the sync should succeed

**Comment by shcott** [comment]
Nope, I didn't make any edits to any files.

**Comment by shcott** [comment]
Is it possible for the android system to make some kind of formatting edit to files? Not sure, just spitballing.

**Comment by fyears** [comment]
have you triggered the sync again and see if the error goes?

**Comment by shcott** [comment]
I just tried again and it started working! Not sure what happened but all good now.
