### ISSUE TITLE
[Bug]: Sync make my file removed

### ISSUE THREAD

**Issue by Litt7e** [remotely-save/remotely-save#658]
### What happened?

After a major version upgrade (I don't remember which version it was, maybe V0.4.10), my files disappeared a lot. I used the webdav tool to retrieve the missing files. Since then, the synchronization function has encountered problems, and every time I synchronize, my files are deleted. I tried reinstalling the plugin and deleting the last synchronization details, but none of them worked. What should I do to make synchronization function work properly.

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (坚果云 JianGuoYun/NutStore)

### Version of the plugin

0.4.21

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
1. firstly please make a backup of your valult

2. please consider export the sunc plan and see what happened to delete files https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/export_sync_plans.md

**Comment by fyears** [comment]
你用坚果云？那可能是正常的，本插件不兼容坚果云

坚果云有限制 api 数量等设定。本插件会产生若干查询，如果文件较多很容易触发 api 上限，从而工作不正常。这不是插件 bug，也没有办法解决。

**Comment by Litt7e** [comment]
> 你用坚果云？那可能是正常的，本插件不兼容坚果云
> 
> 坚果云有限制 api 数量等设定。本插件会产生若干查询，如果文件较多很容易触发 api 上限，从而工作不正常。这不是插件 bug，也没有办法解决。

我在services_connectable_or_not.md看到是支持坚果云的呢，现在是插件的一些功能不支持坚果云还是整个都不支持呢？

**Comment by fyears** [comment]
是坚果云对于文件和api有限制，文件一多，就会出错，这个不是插件不支持，而是坚果云限制。

**Comment by Litt7e** [comment]
好的 谢谢你的解答
