### ISSUE TITLE
[Bug]: Failed to load plugin remotely-save

### ISSUE THREAD

**Issue by dotedu** [remotely-save/remotely-save#659]
### What happened?

I use iphone 15 pro, iOS 17.5. After I install the plugin, I can't enable it.
When turning on the switch, it always pop up a message saying "Failed to load plugin remotely-save"

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.4.21

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
how to install 17.5 ios? is it a beta version?

**Comment by fyears** [comment]
and what's the detailed ios version (17.5.???) ?

have you try to load it on 17.4 ios?

**Comment by fyears** [comment]
i have upgraded the ios to 17.5 now and have no problem.

please consider uninstall and reinstall the plugin. and update obsidian to the latest version. previously some other user reported that they downloaded the corrupted plugin files and failed to load, then reinstalled (re downloaded) the plugin and succeeded.
