### ISSUE TITLE
[Bug]: Problems when renaming, moving or deleting folders and files with Plugin Folder Notes

### ISSUE THREAD

**Issue by kabokabeso** [remotely-save/remotely-save#660]
### What happened?

I have many problems with Remotely Save Syncs when I delete, move or rename files and folders on windows 11 or on Iphone and then sync again via onedrive personal and remotely save. Files are suddenly empty on one device although everything is correct on onedrive. Or the alrady deleted files are recreated or the file with the previous name is recreated but now has no content anymore while next to it is the original file with everything correct. 
I also often get this error message then:
![20240514_145630000_iOS](https://github.com/remotely-save/remotely-save/assets/142225284/3d323851-3c14-48cb-8c3f-df84f5e5814a)

and at them moment sync on Iphone even fails completely (status sync failed) after the picture with the error message is shown.

I use the Plugin Folder Notes by Lost Paul. I have the suspicion that this causes the troubles?

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

up to date

### Version of Obsidian

current

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by kabokabeso** [comment]
The list of files that is concerned on Iphone and Windows also gets longer and longer. I do not know how to bring them back in sync and start not trusting the sync anymore...

**Comment by fyears** [comment]
> Files are suddenly empty on one device although everything is correct on onedrive.

and thirdly, if you think it's not relevant to folder notes. please consider exporting sync plans to see what happens to the deleted file. **by design, plugin doesn't delete any file or even make any file empty unless it detectes deletion on another device** https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/export_sync_plans.md

**Comment by kabokabeso** [comment]
Thanks for the fast answer and planning the update. I have the impression, that when I rename a file or delete a folder or file sowehow after the next sync additionally to the renamed file/folder the original file/folder without any contend is recreated in the same location. 

And also some files are not updated anymore. For instance the whole content of many files in one folder was not shown on smartphone (only on onedrive it was still shown but not on Obsidian). Once I changed the content a bit on windows, after the next sync the whole content was also available on smartphone. I have not really a clue how these doubles are created and can cause obsidian not anymore showing the content. The only error message I get seems to be the one I listed above.

**Comment by fyears** [comment]
> For instance the whole content of many files in one folder was not shown on smartphone (only on onedrive it was still shown but not on Obsidian).

for the next time please consider exporting the sync plan

**Comment by kabokabeso** [comment]
ok, and for which error messages should I look out exactly in the sync plan to find out which files are failing the sync?

**Comment by fyears** [comment]
`"size": 0` might be useful

**Comment by kabokabeso** [comment]
The more I think about the issue, the less I think the error message of Obsidain is correct. Why should OneDrive not allow files with no content? As I wrote before I have hundreds of files with no text in it and just a title. But I never heard before that this is a problem for any system. I think the problem is in Obsidian, that somehow remotely save does not recognize changes immediately when they are written on one drive (maybe because of the automatic creation of files by folder notes) and then tries to synchronize files that are not existent anymore and also shows them in the Obsidian File explorer (as I said there are often files that can’t be open anymore on Obsidian but still shown in the obsidian file explorer  and on one drive they are not existent because I changed them to a newer file title, moved them or deleted them). So the challenge remains: how can I make sure that obsidian and remotely save notices my changes in files immediately as OneDrive does? And how can I bring it back on track to the actual files that are now on OneDrive correclty up to date, but partly not up to date shown in obsidian file explorer and causing obsidian not to synch at all anymore?

**Comment by fyears** [comment]
> Why should OneDrive not allow files with no content? 

it's a limitation from onedrive , and you cannot even try to upload an empty file on official onedrive website.

> Until the upper error message no sync at all is possible and changes are neither uploaded to onedrive locally nor synched between the devices.

yeah it's a design decision of remotely save. and i give up and will add an option to ignore empty files so that users can still at least sync useful notes. please be patient for the new version

**Comment by kabokabeso** [comment]
ok, really looking forward to the update and thanks a lot for putting it in the new release!!!
Really hope that it then solves alle the issues.

**Comment by kabokabeso** [comment]
Empty notes are also really useful for me. Because I directly always like to create a folder note when a folder is created, because often later on I want to add some more general points in the folder note (e.g. content-links to the folders/notes inside the folder).

**Comment by fyears** [comment]
i will release a new version allowing skipping empty files upload on onedrive
