### ISSUE TITLE
[Bug]: webdav sync breaks at tab indentation.

### ISSUE THREAD

**Issue by c0wjay** [remotely-save/remotely-save#663]
### What happened?

Currently, I'm using obsidian in multi OS (macOS, windowOS, iPadOS, and even with android too.)
and run NAS server using nextcloud on ubuntu 22.04 LTS.
I connect nextcloud with obsidian clients via webdav.
but it breaks with all of tab indentation when files saved in NAS, so it makes too many diffs even if there are no changes.
(I can't figure out the problem because of encryption, and I finally figure out whats happening after turn off encryption.)

My remotely-save configure is default, only server address, username, and password are set.

For example,
```original
## Title
- Text
	![[Image]]
```
turns into
```nas
## Title
- Text ![[Image]]
```
when saved in NAS.

### What OS are you using?

macOS

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (NextCloud)

### Version of the plugin

0.4.21

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by c0wjay** [comment]
It seems reproduced on indented textblock under bullet point.
for example,
```
- TextWithBullet1
	- TextWithBullet2
	Text3
```
turns into
```
- TextWithBullet1
	- TextWithBullet2 Text3
```

**Comment by fyears** [comment]
remotely save doesn’t understand or modify content to remove whitesapces/tab etc at all. so i *think* it’s not a bug from remotely save

please check:

1. does your nas/nextcloud/nginx/apache have any special features omitting tabs? if you manually upload a md file in nextcloud web address, does the error occur
2. have you installed any special plugins? can uou reproduce the error using a test vault? please consider create a test vault and only enable remotely save and try to reproduce the error.
3. and according to your example, it seems that the line breaks are removed too. will it be a capability issue accross different os? see: https://stackoverflow.com/a/3720674 please download the file and compare their sizes or hashes

**Comment by c0wjay** [comment]
Thanks! as I tried your instruction, tt seems my nextcloud issue. (same issue occured when I purely upload same md files to NAS)
I will close this issue.
