### ISSUE TITLE
[Feature Request]: add support for import and export webdav part

### ISSUE THREAD

**Issue by Screen5058** [remotely-save/remotely-save#665]
### What feature are you suggesting?

![image](https://github.com/remotely-save/remotely-save/assets/168877538/48fa6bef-175c-4c99-a9ae-45656ab8655b)
Import and Export Partial Settings - add support for import and export webdav part

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
the first one: export non oauth2 part, contains basic,advanced,s3,webdav settings together.

**Comment by Screen5058** [comment]
Got it, Thank you!
