### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xwshan** [remotely-save/remotely-save#666]
### What happened?

Fail to synchronize. 

![image](https://github.com/remotely-save/remotely-save/assets/43837345/dd2f2020-60c3-43b9-a6e3-3777c1f56cca)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (InfiniCloud (formally TeraCLOUD))

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
please check your network connection, and also remove the special chars % in file folder name

**Comment by xwshan** [comment]
It can work properly now. Thank you. :smile:
