### ISSUE TITLE
[Bug]: Failed to load plugin remotely-save

### ISSUE THREAD

**Issue by jackw111** [remotely-save/remotely-save#667]
### What happened?

你好fyears
我的手机是8p ios13系统，obsidian是最新版1.5.12，
但是使用【remotely save】，只有 0.3.16 及以前的的版本能用，使用0.3.17以后版本就一直无法开启插件，显示  Failed to load plugin remotely-save。
请问这个是什么原因？

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (坚果云 JianGuoYun/NutStore)

### Version of the plugin

0.3.16

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
应该是因为更新了一些依赖，需要一些最新的 web 技术；但是 ios 13 的 safari 内核太老了所以不支持。

无法解决，因为我手上没有那么老的机型。更新一下 ios 系统吧。

**Comment by jackw111** [comment]
ok  谢谢回答
