### ISSUE TITLE
[Bug]: update to 0.4.21 broke webdav sync for me

### ISSUE THREAD

**Issue by pirad** [remotely-save/remotely-save#668]
### What happened?

Today I updated remotely save on my Android phone to the current version 0.4.21. Since then I can't sync with the webdav server from mailbox.org any more. I tried to copy the configuration to the DAVx5 App and there it works. The logs show 
`["remote vault folder not exists, creating"]`
`[{"status":409,"response":{}}]`.
Sorry I can't tell any more, what version i had before that worked last. I also tried another Android system, there it didn't work either with same problem. 

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.4.21

### Version of Obsidian

1.512 (134)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
are you using digest auth?

**Comment by pirad** [comment]
No. But if I activate this the log shows: `["startting sync."]` then `[{}]` (as error) and `["endding sync."]`. While the pop ups show something like `Invalid response: no root multistatus found`.

**Comment by fyears** [comment]
are you sure your webdav address is set correctly? i think that's because you configure the webdav address incorrectly.

**Comment by pirad** [comment]
Well if I copy the exact same address to DAVx5 App it works. 

Oh I found the problem: the address according to my provider is https://dav.mailbox.org/servlet/webdav.infostore/Userstore/User%20Name/ if I now replace the '%20' by a space it works. But I'm the previous version it worked with the escaped space. 
Thanks for the quick help.

**Comment by fyears** [comment]
thanks for pointing. yeah it's annoying that the web address contains special characters like spaces. i will try to find a way to auto detect the correct encoding.
