### ISSUE TITLE
[Feature Request]: 請問是否有同步圖片檔案的功能

### ISSUE THREAD

**Issue by jimmy123j** [remotely-save/remotely-save#670]
### What feature are you suggesting?

最近開始使用 OB，且透過內網建立 Webdav 進行同步，整體很方便
因為筆記內會引用 Vault 中的圖片，但發現 Vault 內的圖片並不會同步
希望可以連同 Vault 中的圖片也一併同步 (因安全問題無外網)

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
会同步的，不区分图片还是文件。再检查一下你的设置吧。

如果设置了跳过大文件，那么就要手动一次性处理大文件了
