### ISSUE TITLE
[Bug]: window webdav sync error

### ISSUE THREAD

**Issue by djhdj1** [remotely-save/remotely-save#671]
### What happened?

When using windows for sync, folder sync works fine, file sync reports 401 unauthorized, webdav can check it through, but sync on android phone doesn't have any problem, both folder and file sync fine.
Regardless of whether the files are created on windows or on android, attached below are the images.
![2024-05-20_110930](https://github.com/remotely-save/remotely-save/assets/57862829/34bc6c72-2ac5-4b2d-b4d6-1952d40b1a87)
![2024-05-20_110818](https://github.com/remotely-save/remotely-save/assets/57862829/6d95d27a-81d3-454a-a5b7-1de971f6532c)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (AList)

### Version of the plugin

0.4.21

### Version of Obsidian

1.5.12

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
你的鉴权模式是 digest 吗？

alist 部署在哪里？中间有 nginx 之类的吗？有防火墙之类的吗？

**Comment by djhdj1** [comment]
> 你的鉴权模式是 digest 吗？
> 
> alist 部署在哪里？中间有 nginx 之类的吗？有防火墙之类的吗？

用的basic鉴权，alist部署在远程主机vps上，使用了nginx proxy mananger 做反代，本机的iptable已经关闭，还有个vps自带的网络管理，因为我反代了，所以只开放了443和80端口，跟这个有关系吗...我在安卓上同步就正常，在windows上文件夹也能同步，就是文件同步不了

**Comment by fyears** [comment]
端口是没问题的。

安卓没问题，windows 有问题，确认配置是完全一致的吗？试试把 android 的 data.json 复制到 windows 呢？

**Comment by djhdj1** [comment]
> 端口是没问题的。
> 
> 安卓没问题，windows 有问题，确认配置是完全一致的吗？试试把 android 的 data.json 复制到 windows 呢？

安卓的datajson在什么位置啊

**Comment by fyears** [comment]
一个方法是手动复制粘贴 data.jaon，在 android / win 的 vault 里面的 .obsidian/plugins/remotely-save/ 文件夹里


另一个方法是 android 导出url，然后粘贴进电脑的设置：https://github.com/remotely-save/remotely-save/blob/master/docs/import_export_some_settings.md

**Comment by djhdj1** [comment]
> 一个方法是手动复制粘贴 data.jaon，在 android / win 的 vault 里面的 .obsidian/plugins/remotely-save/ 文件夹里
> 
> 另一个方法是 Android 导出URL，然后粘贴进电脑的设置：https://github.com/remotely-save/remotely-save/blob/master/docs/import_export_some_settings.md

我将插件卸载，并重新安装，用url的方式添加了安卓的配置，还是不行

**Comment by fyears** [comment]
不合理。

但是整个事情很诡异，android 可以 windows 不行，这里显然是哪里做了什么拦截。你用 windows 去 alist 网站可以上传成功吗？

这里没啥排查方法，去掉反向代理试一下？

**Comment by fyears** [comment]
安装一下开源的 webdav 软件，例如 https://cyberduck.io 试试能否连上和上传吧？

**Comment by fyears** [comment]
这里有类似的问题，换了反代就解决了。试试用 caddy 或者去掉反代吧。

https://help.nextcloud.com/t/webdav-broken-recently-401-for-keepass-clients/158593/19

**Comment by djhdj1** [comment]
> 这里有类似的问题，换了反代就解决了。试试用 caddy 或者去掉反代吧。
> 
> https://help.nextcloud.com/t/webdav-broken-recently-401-for-keepass-clients/158593/19

好的我试一下

**Comment by fyears** [comment]
目前无法复现。且用自己搭建、在线注册的 nextcloud 和 infinicloud 都是正常的。如无进一步信息，就先关闭了。

**Comment by NoNameCanUse9** [comment]
我我复现了这个问题，mac 原本正常的，同步手机和平板后，mac 就不行了
