### ISSUE TITLE
[Bug]: stubborn files can't delete - UPDATE: Sync doesn't work [SOLVED]

### ISSUE THREAD

**Issue by itoldusoandso** [remotely-save/remotely-save#673]
### What happened?

Stubborn notes - deleted notes coming back on iOS after having been deleted. Sync is via Dropbox. The notes were deleted on another device and deletions synched with Dropbox, so dropbox folder was empty (except for the .obsidian folder). After that iOS Obsidian was started and manual remotely save was triggered. The sync will again copy the files from iOS into Dropbox. 
Again attempt to delete the files directly in Dropbox. Again sync on iOS. Again files recreated in Dropbox. Tried this a half a dozen times. 

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

latest as of today

### Version of Obsidian

latest as of today

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> Again attempt to delete the files directly in Dropbox. Again sync on iOS.


please export the sync plan after "again sync on ios" and see what happened to that note file

**Comment by itoldusoandso** [comment]
So I started from scratch.. deleted the plugin, deleted database, cleaned up Dropbox.  loaded the md files again. All looks good in Obsidian. Added Remotely Save plugin, configured, set to manual, verified connection etc.

Now it doesn't sync at all. 

I think there is something that happened since I updated the plugin yesterday.  Is it possible?

I can't get a single file to sync. Remotely Sync just creates the folders and it starts to create subfolders but doesn't finish, it only creates half of them and gives up. My dropbox has lots of space.

No .md files are synched, no attachements.  All I want right now is to see the database gets replicated in Dropbox. But it doesn't. Tried several times to reset it, rerun, again deleted and started from cratch.

Not sure if it matters, here is my database structure, this is what I have in the Vault folder:

![image](https://github.com/remotely-save/remotely-save/assets/71971273/10ec396e-f1e8-47bd-848b-9cddce1454f0)


I looked at the sync plan and here is example of what I see there. Comparing this with the help link, I can't see how this compares to the examples listed on the link. Didn't the format change?

For example:

   "mtimeCli": 1715752895000,
      "mtimeSvr": 1715752895000,

I don't see reference to this in the example documentation ,instead it talks instead about these:

      "mtimeRemote":,
      "mtimeLocal":,

Also I don't see reference to "mixedStates" in my file sync_plans_hist_exported_on_1716308610562.md


Wondering if I try to load the previous extension, is there a way to install the older plugin?

  

```
"l J Training/Seles process on psychological level - The P-R-O-S Approach to Selling.md": {
    "key": "l J Training/Seles process on psychological level - The P-R-O-S Approach to Selling.md",
    "local": {
      "key": "l J Training/Seles process on psychological level - The P-R-O-S Approach to Selling.md",
      "keyRaw": "l J Training/Seles process on psychological level - The P-R-O-S Approach to Selling.md",
      "mtimeCli": 1715752895000,
      "mtimeSvr": 1715752895000,
      "size": 11755,
      "sizeRaw": 11755,
      "mtimeCliFmt": "2024-05-15T06:01:35.000Z",
      "mtimeSvrFmt": "2024-05-15T06:01:35.000Z",
      "keyEnc": "l J Training/Seles process on psychological level - The P-R-O-S Approach to Selling.md",
      "sizeEnc": 11755
    },
    "decisionBranch": 6,
    "decision": "local_is_created_then_push",
    "change": true
  }
```

**Comment by fyears** [comment]
files/folders startting with underscore is ignored by default. can you create a "normal, not empty file" directly under the root of vault and see what happen?

**Comment by fyears** [comment]
is yor "today's plan" under the folder of _resource?

**Comment by itoldusoandso** [comment]
Okay, so it is not the version problem. I found version 0.4.16 and loaded but same issue, does not sync. Out of 300 folders it is supposed to create, it creates about 30-40 folders and uploads no files and no attachments. 

Subsequent sync shows:

![image](https://github.com/remotely-save/remotely-save/assets/71971273/d61be0c8-a7bc-4b81-93ca-9efedd9e59db)

**Comment by fyears** [comment]
The sync plan format is changed (like you said), and the doc is a little outdated. but the "spirit" is the same, and hopefully the new format is easier to be interpreted by human. As you may guess,  the plugin found that your file should be uploaded to remote

```
...
"decision": "local_is_created_then_push",
...
```

But the key point is, **why the plugin successfully create the folder, but do not upload the files?"**

As your latest screenshot indicates: "429 too many requests". In a fresh install, the plugin will create lots of folders and upload lots of files, and the dropbox site thinks it's abnormal so has some rate limit strategy: blocking you (and the remotely-save plugin) to do more for a few seconds..

Please go to remotely-save settings page, and go to "advanced settings", set "concurrency" to 1 (from the default value 5). And try again. It *should* slowly create the folders, and slowly upload the files.

**Comment by fyears** [comment]
It's not a bug but a short-term limit from dropbox.

I could do some optimizations in the future though.

**Comment by itoldusoandso** [comment]
Okay I think I found the solution. 

The reason why it fails is because the plugin first creates the missing folders in the remote drive (dropbox). My current vault has about 300 subfolders under the main notebook folders. All of these 300 subfolders are nested 3 levels deep.

When I observe how the folders get created on Dropbox, it is quite slow. 

So I adjusted the concurrency to 1 and later increased to 2.  Now it seems the sync works better.  

I also have added the folders to sync into Vault gradually. So I no longer let the plugin to do the full upload in one shot, but I broke it down. This helped to actually to find out the issue with the concurrency because some folders had lots of subfolders, others didn't.
It took me quite a couple of hours, days this to figure out. It's nuts. For the time I spent on this, I could have paid for Evernote storage for next 100 years, I guess. 

Anyhow, this is my recommendation for the plugin: The important notifications get lost. There are toast messages (notifications) that pop up ... when sync starts, when there is another sync attempt and existing sync not finished, when sync is FINISHED (yes!, this one is important!), and when there are errors.... etc..
There are lots of messages that show quickly and go away. If I don't sit and look at the right top edge of the screen, I wouldn't know if things went well or not with the last sync...) 
I know there are bunch of detail detailed reports. But these are detailed, and nerdy... 
All I want to know if last sync went fine and what were the errors showing in the messages. That gives me piece of mind that notes are synced. I guess this is also in console, okay.
But my suggestion is to put somewhere a flexible text field in the configuration window of the plugin that would give me the concatenated version of all the toast messages showing during the LAST sync. 
I know if I however over the status bar "Synced x minutes ago", it shows me information saying it was successfully synced. But does it also show if there was an issue, like the ones described earlier?

Been staring in Little Snitch network monitor for long time just to figure out what is happing in the background. So maybe a little information about the amount of data in MB would also help in the notification for the paranoid type...haha

![image](https://github.com/remotely-save/remotely-save/assets/71971273/00dab356-5e0f-472c-96f8-906534188e23)

**Comment by itoldusoandso** [comment]
> 
> Please go to remotely-save settings page, and go to "advanced settings", set "concurrency" to 1 (from the default value 5). And try again. It _should_ slowly create the folders, and slowly upload the files.


I didn't see your response, was just typing in my own, probably around the same time.

Maybe the message should say:

You are uploading too fast. Dropbox doesn't like it. For the initial sync, go tp lower your gear captain...  or something, because the messages only say there are too many requests ;)
But anyways, I only discovered the error messages later after several times trying, because I don't stare into Obsidian window all the time if I have other stuff to do, so I completely missed those messages. I think there should be a place where these messages are accessible, like I suggested perhaps somewhere in the configuration window of the plugin.

Something like this:

![image](https://github.com/remotely-save/remotely-save/assets/71971273/3c604b4a-8b6c-45d6-afef-28958f6da307)

**Comment by fyears** [comment]
thanks for your detailed report and your suggestions are vaulable.

yeah the notices, or generally, "ux" (User experience), are not as great as it should be. initially remotely save is a plugin designed for myself to sync over s3, and everything is designed from a "nerdy" way.

and for the "pay for evernote" part, i think the plugin provides value to those who wants "control" (or *the feeling* of control) over their data, along with Obsidian. haha

anyways thanks for your suggestions and i will think about them. and i am glad you've solved the issue.

**Comment by fyears** [comment]
oh, please don't forget to make a backup of your vault elsewhere. seriously you should do that while you are using *any* sync software.
