### ISSUE TITLE
[Feature Request]: Would be nice to be able adjust Abort for Sync if Modif above Percentage to set own percentage

### ISSUE THREAD

**Issue by itoldusoandso** [remotely-save/remotely-save#676]
### What feature are you suggesting?

If I have 5000 notes, allowing 500 notes to get modified is too much. If I sync notes on hurly basis, or every few minutes, then I won't need the limit as high, I would like to set it at no more than 1% of notes, that would be still 50 notes. Maybe 0.2%, that is 10 notes, that is plenty for me.

So would be nice if there was a field to enter a custom number percentage. 

![image](https://github.com/remotely-save/remotely-save/assets/71971273/d9d7585a-02bf-4459-a50b-04e29ab26457)

Thank you!

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
yeah sure why not. please install the latest version 0.4.25
