### ISSUE TITLE
[Bug]: Mobile cannot sync to webdav server after initial download

### ISSUE THREAD

**Issue by marcus-k** [remotely-save/remotely-save#677]
### What happened?

On a brand new, fresh install of Obsidian Mobile on Android, I successfully synced (really just downloaded) my Obsidian vault from a webdav server that was originally populated by a Windows version of Obsidian. Windows can sync (upload and download) to the webdav server with no issue.

However, upon syncing (first downloading), changing no files (or changing a file it doesn't matter), then syncing again (assuming uploading now), the second sync failed immediately stating:
```
folder/filename.md: error copying local=>encrypt(webdav,rclone-base64): size not matched
```
I do not use any encryption, nor did I ever even touch that option when setting up the plugin.

Not sure what's going on here since indeed, Windows can sync to the webdav server fine, it's just the Android version that cannot seem to sync again after downloading all the files.

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (NextCloud)

### Version of the plugin

0.4.22

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by kayg04** [comment]
I just tested this with MacOS ⇄ iPadOS, and this works on my nextcloud without encryption enabled.

**Comment by fyears** [comment]
please export the sync plan and see whether the size of that file is read successfully 

https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/export_sync_plans.md

**Comment by marcus-k** [comment]
Sure, this is the sync plan:

```json
"folder/filename.md": {
    "key": "folder/filename.md",
    "remote": {
      "key": "folder/filename.md",
      "keyRaw": "folder/filename.md",
      "mtimeSvr": 1715963507000,
      "mtimeCli": 1715963507000,
      "size": 2165,
      "sizeRaw": 2165,
      "keyEnc": "folder/filename.md",
      "sizeEnc": 2165,
      "mtimeCliFmt": "2024-05-17T16:31:47.000Z",
      "mtimeSvrFmt": "2024-05-17T16:31:47.000Z"
    },
    "prevSync": {
      "key": "folder/filename.md",
      "keyRaw": "folder/filename.md",
      "mtimeSvr": 1715963507000,
      "mtimeCli": 1715963507000,
      "size": 2165,
      "sizeRaw": 2165,
      "keyEnc": "folder/filename.md",
      "sizeEnc": 2165,
      "mtimeCliFmt": "2024-05-17T16:31:47.000Z",
      "mtimeSvrFmt": "2024-05-17T16:31:47.000Z"
    },
    "local": {
      "key": "folder/filename.md",
      "keyRaw": "folder/filename.md",
      "mtimeCli": 1715963507000,
      "mtimeSvr": 1715963507000,
      "size": 0,
      "sizeRaw": 0,
      "mtimeCliFmt": "2024-05-17T16:31:47.000Z",
      "mtimeSvrFmt": "2024-05-17T16:31:47.000Z",
      "keyEnc": "folder/filename.md",
      "sizeEnc": 0
    },
    "decisionBranch": 10,
    "decision": "local_is_modified_then_push",
    "change": true
  },
```

**Comment by fyears** [comment]
Do you actually have any content inside your file? I guess the content is not empty, is it?

```json
    "local": {
      "key": "folder/filename.md",
      "keyRaw": "folder/filename.md",
      "mtimeCli": 1715963507000,
      "mtimeSvr": 1715963507000,
      "size": 0,    <------------------------------see this
      "sizeRaw": 0,
      "mtimeCliFmt": "2024-05-17T16:31:47.000Z",
      "mtimeSvrFmt": "2024-05-17T16:31:47.000Z",
      "keyEnc": "folder/filename.md",
      "sizeEnc": 0
    },
```

As you may see, the api of obsidian returns **0** size, while it has actual content (I guess).

I don't know how to fix it since it's not an issue from the plugin part. But maybe you can write something into it, or install the latest Obsidian and try again. Of course you might try to update your Android operating system,

**Comment by fyears** [comment]
Or I can provide a debug setting to skip the "size check" in remotely save. It should do no harm...

**Comment by marcus-k** [comment]
Yeah the file is not empty, it is odd that the size is reported as 0. It is not just this file unfortunately, this occurs for every file in my obsidian vault and then the sync is aborted for having too many errors.

**Comment by fyears** [comment]
I decide to ignore the error and let the sync go on. Please install the latest version 0.4.24.

**Comment by CNYoki** [comment]
Hey, I have the same problem... I was try to sync between Windows and iOS, and have to delete or rename the original file then create new one to sync to solve. Any way to fix?

**Comment by fyears** [comment]
please export the sync plan to debug firstly

**Comment by MasterChief220** [comment]
> please export the sync plan to debug firstly

I've got the same issue.  The thing i I even deleted the file from my obsidian vault and moved it outside in onedrive but for some reason it still throws this issue. 

This is the sync plan:
"Areas/Hacking/tryhackme/Junior Penetration Tester/PrivilegeEscalation.md": {
    "key": "Areas/Hacking/tryhackme/Junior Penetration Tester/PrivilegeEscalation.md",
    "remote": {
      "key": "Areas/Hacking/tryhackme/Junior Penetration Tester/PrivilegeEscalation.md",
      "keyRaw": "Areas/Hacking/tryhackme/Junior Penetration Tester/PrivilegeEscalation.md",
      "mtimeSvr": 1720026299787,
      "mtimeCli": 1720026299787,
      "size": 131099,
      "sizeRaw": 131099,
      "synthesizedFile": false,
      "keyEnc": "Areas/Hacking/tryhackme/Junior Penetration Tester/PrivilegeEscalation.md",
      "sizeEnc": 131099,
      "mtimeCliFmt": "2024-07-03T22:04:59+05:00",
      "mtimeSvrFmt": "2024-07-03T22:04:59+05:00"
    },
    "prevSync": {
      "key": "Areas/Hacking/tryhackme/Junior Penetration Tester/PrivilegeEscalation.md",
      "keyRaw": "Areas/Hacking/tryhackme/Junior Penetration Tester/PrivilegeEscalation.md",
      "mtimeSvr": 1710588656000,
      "mtimeCli": 1710588656000,
      "size": 131099,
      "sizeRaw": 131099,
      "synthesizedFile": false,
      "keyEnc": "Areas/Hacking/tryhackme/Junior Penetration Tester/PrivilegeEscalation.md",
      "sizeEnc": 131099,
      "mtimeCliFmt": "2024-03-16T16:30:56+05:00",
      "mtimeSvrFmt": "2024-03-16T16:30:56+05:00"
    },
    "decisionBranch": 5,
    "decision": "remote_is_modified_then_pull",
    "change": true
  },
  "/$@meta": {
    "key": "/$@meta",
    "sideNotes": {
      "version": "20240714 fs version",
      "generateTime": 1724174391072,
      "generateTimeFmt": "2024-08-20T22:19:51+05:00",
      "service": "onedrive",
      "concurrency": 5,
      "hasPassword": false,
      "syncConfigDir": false,
      "syncBookmarks": false,
      "syncUnderscoreItems": false,
      "skipSizeLargerThan": -1,
      "protectModifyPercentage": 100,
      "conflictAction": "keep_newer",
      "syncDirection": "bidirectional",
      "triggerSource": "auto_once_init",
      "sizeof": 1717566
    }
  }
}

**Comment by RobTranquillo** [comment]
I am experiencing the same problem, the first time the synchronisation works fine, the second and subsequent times it fails.
_(The question for me is where can I find the error log?)_

But I found the problem in my case, which may not be your problem, but may be interesting for others coming along this thread. I enabled the option: ‘Abord sync If Modification Above Percentage’ and set it to 20%, but only had two files (and two directories) in my vault and was editing one of them. Unfortunately this is over 20%. :-) 
_(I would argue that this case could be specified in the error message) _.

I hope it helps someone.

**Comment by fyears** [comment]
@MasterChief220 

>  The thing i I even deleted the file from my obsidian vault and moved it outside in onedrive but for some reason it still throws this issue.

As your sync plan indicated: 

1. your file was synced on the current device on "2024-03-16T16:30:56+05:00"
2. you deleted your file locally
3. but your file on onedrive was modified on "2024-07-03T22:04:59+05:00"
4. so the plugins thinks you created a new file remotely and decided to "remote_is_modified_then_pull"

The correct way is remove the file locally **after** syncing then the plugin will send the delete operation to remote as well

**Comment by fyears** [comment]
@RobTranquillo 

> (The question for me is where can I find the error log?)

Your error is trivial, and the error notice (too many files modified) should be shown in the notice.
