### ISSUE TITLE
[Bug]: partial upload failure triggers `tooManyErrors`

### ISSUE THREAD

**Issue by slinderud** [remotely-save/remotely-save#678]
### What happened?

I'm self hosting a webdav server using nginx which seemingly doesn't support partial upload.
This leads to many "no partial upload / update" failures since i got many files above 10MB.
It seems like these triggers the following check:
https://github.com/remotely-save/remotely-save/blob/b769becb97f177bd396e62e63e3c1c80991211bd/src/sync.ts#L1335-L1338

I suggest that the error should be exempt from this check, somehow

Update: Manually installed `0.4.21` to test if this version works. It does. No errors related to partial up/download

### What OS are you using?

Linux, macOS

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (nginx)

### Version of the plugin

latest

### Version of Obsidian

latest beta

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
may i ask are you using nextcloud or sabre? the plugin automatically detects the server and should not fail in this case...

**Comment by fyears** [comment]
and the partial upload is introduced in 0.4.22

**Comment by slinderud** [comment]
Thanks for your quick reply!

I'm using nginx as webdav server using ngx_http_dav_module and nginx-dav-ext-module.

I experience this bug using `0.4.22`. I manually installed `0.4.21` after to see if this solved the issue. It did.
So this bug is introduced in 0.4.22

**Comment by fyears** [comment]
> I'm using nginx as webdav server using ngx_http_dav_module and nginx-dav-ext-module.

May I ask how to install them? any tutorial or any docker instructions?


Yeah you can use 0.4.21 for now.

**Comment by fyears** [comment]
Ok I found the bug. Please install the latest version 0.4.23 and try again.
