### ISSUE TITLE
[Bug]: failed to load plugin remotely-save

### ISSUE THREAD

**Issue by hy771** [remotely-save/remotely-save#682]
### What happened?

安卓软件启动提示失败
安卓软件启动提示失败
Android software startup prompt failed

failed to load plugin remotely-save
无法远程加载插件-保存

### What OS are you using?

Windows, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.4.25

### Version of Obsidian

1.5.12

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
如果你正在使用 android webview，请升级 android webview。

如果你不是正在使用 android webview 的话，比如说华为的话，可以升级 huawei webview。
