### ISSUE TITLE
[Bug]: webdav, http request to IOS Intranet IP

### ISSUE THREAD

**Issue by luoluoqixi** [remotely-save/remotely-save#683]
### What happened?

webdav ip: http://192.168.2.199:9001/dav
ios version: 17.4.1
obsidian version: 1.5.12 (134)
API v1.5.12

Error http request to IOS Intranet IP: Your webdav address could only be https, not http, because of the iOS restriction.

In my tests, ios Intranet http access to webdav works fine
![888D12135C75EC9E049E0EAA17168D09](https://github.com/remotely-save/remotely-save/assets/59384810/1d70f85e-50bd-4ddc-bc4d-cbc5d1c99104)
![F6295644FBB8DD8568191E97D95FBDCF](https://github.com/remotely-save/remotely-save/assets/59384810/0b1083eb-f6ca-460f-8e3e-ee59f5cd89bc)

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (AList)

### Version of the plugin

0.4.25

### Version of Obsidian

1.5.12 (134)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by luoluoqixi** [comment]
https://github.com/luoluoqixi/remotely-save/commit/cbd29c1bcf3c78a0a88597dbb48d2841d584f544

**Comment by fyears** [comment]
新版本已去除插件方的检测。
