### ISSUE TITLE
[Bug]: An ssl error has occurred and a secure connection to the server cannot be made

### ISSUE THREAD

**Issue by Skywind5487** [remotely-save/remotely-save#684]
### What happened?

![IMG_8086](https://github.com/remotely-save/remotely-save/assets/101578572/509393e8-9e3a-40e7-a322-b4e28930267d)

As a title, my wabdav can't be used suddenly. But I have no idea.
I use my asus router to ddns but its SSL seems not working.

https://stackoverflow.com/questions/32755674/ios9-getting-error-an-ssl-error-has-occurred-and-a-secure-connection-to-the-ser 

btw I tried download my certification to my ipad but it didn't work also.

maybe help

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.4.25

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
请使用 https://www.ssllabs.com/ssltest/ 或者 https://myssl.com/ssl.html 或者 https://www.godaddy.com/zh-sg/ssl-checker 等网站检测证书状态。或者重新配置一下证书。这个插件解决不了。。。
