### ISSUE TITLE
[Bug]: 安卓使用s3同步.obsidian配置文件夹报错：Request Failed. IOException stream closed

### ISSUE THREAD

**Issue by bigoovip** [remotely-save/remotely-save#686]
### What happened?

使用搭建的的minIO的s3服务，remotely-save的配置是一样的，pc端和ios端均连接正常，且能正常同步配置文件夹，但是在安卓端连接就会报错。
错误信息很多，只显示一条，如下，其它错误除了文件路径和文件名，全都一样，即错误全都是`Request Failed. IOException stream closed`。
```
.obsidian/pluginx/attachment-management/manifest.json: Request Failed. IOException stream closed
```
但是在安卓中关闭同步配置文件夹，笔记的内容可以正常同步。

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (MinIO)

### Version of the plugin

0.5.2

### Version of Obsidian

1.5.12(134)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
这里不知道啊，有没有可能，是 android 系统的问题。

插件设置里把并行度调整为 1 试试？

**Comment by bigoovip** [comment]
@fyears 谢谢建议，我删除了obsibian和库，然后重新同步，现在正常了。
