### ISSUE TITLE
[Bug]: Automatically delete empty folders

### ISSUE THREAD

**Issue by taocwang** [remotely-save/remotely-save#687]
### What happened?

Automatically delete empty folders, the same will happen on the mobile version.
空文件夹同步自动删除,手机版同样会删除。

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (腾讯云 COS Tencent Cloud COS)

### Version of the plugin

0.5.2

### Version of Obsidian

V1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by ongiei-ab** [comment]
不光空文件夹，我这里没有字段的空文件也会被删掉，已经停用了，等更新吧

**Comment by fyears** [comment]
@ongiei-ab 是 onedrive 还是 s3 呢？请发一个新issue和导出一下同步计划哈。此外这个不符合预期，因为文件大小本身不会导致删除。

**Comment by fyears** [comment]
新版（周六发布）会修复空文件夹问题。

至于文件问题，建议另开一个新 issue 排查。

**Comment by alongflow** [comment]
同步还是会自动删除空文件夹

**Comment by ongiei-ab** [comment]
我这边不用onedrive改用webdav后没有这个问题了，应该是onedrive的问题
