### ISSUE TITLE
[Bug]: 同步异常缓慢，接连好几个版本都是如此

### ISSUE THREAD

**Issue by wavetg** [remotely-save/remotely-save#688]
### What happened?

我大概从四月份开始跟随更新察觉同步变得异常缓慢，主要的耗时在`listing remote`这个步骤，通过查阅issue发现有报告过类似问题#644，但我是桌面端耗时，移动端没有测试。尝试过删除远端所有文件重新同步，卸载然后重装插件所有配置保持默认，都是没有效果，仍然非常非常的缓慢

另使用最新版本导出性能报告时，提示`No profiler results found`（已经运行过多次同步），以下的性能数据是降至0.4.16导出的（因为发现issue中报告过此版本解决同步缓慢问题，但我没有效果，只是能导出性能报告了）

![image](https://github.com/remotely-save/remotely-save/assets/19207540/fd6032f6-bde9-4f8e-9b7d-7e45c7ce11f5)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.5.2

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
s3里有多少个文件？

**Comment by fyears** [comment]
之前修复过的是 prev sync 慢的问题。现在你的是 list remote 慢的问题。

这一步几乎不可能解决，因为这一步纯粹就是列举远程文件列表，耗时都在 io 里，用任何版本都是这个步骤的。

**Comment by fyears** [comment]
你有没有用加密呢？之前的 issue 是说加密导致的解密加密缓慢。

**Comment by fyears** [comment]
你没有加密，所以的确和之前的问题不一样的。你的阿里云有限速吗……

**Comment by fyears** [comment]
用 backblaze 试试？有免费额度

**Comment by fyears** [comment]
我想想为什么……你的 s3 怎么配置的？

**Comment by fyears** [comment]
有没有开启“使用精确时间”？

**Comment by fyears** [comment]
0.3.35 和之后，提供了这个选项。最新版本默认是关闭的，但是之前有些版本默认开启。你用0.3.34当时没有这个功能。

这里原理是假如开启了的话，会逐个文件读一次修改信息，因此你有几百个文件它就要读几百次……

最新版本已经支持了关闭这个选项并正确同步。请改回用最新版本，关闭这个选项，同步一次。之后就正常了！

谢谢你的反馈！我想想怎么给用户提示吧……
