### ISSUE TITLE
[Bug]: ios14.4.2加载插件错误

### ISSUE THREAD

**Issue by YrRedCrew** [remotely-save/remotely-save#689]
### What happened?

ios14.4.2中Obsidian无法正常加载remotely-save插件

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.5.3

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
抱歉，手上没有对应设备开发测试，此外版本太老了。没有计划支持了。

**Comment by YrRedCrew** [comment]
好的，感谢回复。
