### ISSUE TITLE
[Feature Request]: 配置文件夹的同步可以再弄个细分控制选项吗？

### ISSUE THREAD

**Issue by youarenever** [remotely-save/remotely-save#690]
### What feature are you suggesting?

目前配置文件同步的功能是全部同步，但是在实际使用过程中，pc端和移动端配置可能会有一些差异化的配置。
不开配置同步很不方便，开了的话，每次会把差异化的配置覆盖掉

是否可以针对配置文件夹再弄个细分控制选项？控制只同步填写的文件或目录。

比如这样：

![ui](https://github.com/remotely-save/remotely-save/assets/18183177/ff19612f-e992-411b-829a-5946cf9ea3e7)

感谢

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
太复杂了，暂不打算支持。（又或者说做成付费功能，是否愿意付费呢？）现在有全局黑名单，可以自行用正则表达式配置一下。
