### ISSUE TITLE
[Feature Request]: Sync empty folders option

### ISSUE THREAD

**Issue by registran4ik** [remotely-save/remotely-save#691]
### What feature are you suggesting?

I'm using a setting in the plugin "Action for empty folders" - "leave them as is". And it not working for created new empty folders.
I have created a lot of empty folders and want them to sync. Can this be implemented please?

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
It will be fixed in next version (will be released on Saturday).

I over complicated the algorithm, and the folder should be created or removed as expected.
