### ISSUE TITLE
[Bug]: sync deletes content since yesterday 

### ISSUE THREAD

**Issue by garugc** [remotely-save/remotely-save#692]
### What happened?

Since yesterday, the contents of Notes and Canvas have been deleted during synchronization. Everything I made or changed yesterday is empty today. Edit: when I open a note or canvas, that is empty now, I can't open any other note from my vault. It's like freezing the notes. When I close the app and open again, I can open older notes, but when I open one of the empty, it freezes again 

### What OS are you using?

Windows, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

1.5.12 (134)

### Version of Obsidian

Latest

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
"freeze while opening" is likely not something the plugin will cause: the plugin doesn't involve GUI or anything around your edit page.

Would you like to disable the plugin and restart Obsidian and see if the Obsidian is "frozen" still?

**Comment by garugc** [comment]
Hi, thanks for your mail. I reinstalled the plugin and I found out that Dropbox makes trouble. Maybe the problems came from that in general and the broken files have blocked Obsidian. I have no idea.. I linked to OneDrive today and so far everything is working again. If there are still problems, I'll get back to you.Thank youVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: fyears ***@***.***> Datum: 06.06.24  17:48  (GMT+01:00) An: remotely-save/remotely-save ***@***.***> Cc: garugc ***@***.***>, Author ***@***.***> Betreff: Re: [remotely-save/remotely-save] [Bug]: sync deletes content since
  yesterday  (Issue #692) 
and have you enabled auto sync, etc?
