### ISSUE TITLE
[Bug]: 自动删除无字段的.md和空文件夹

### ISSUE THREAD

**Issue by ongiei-ab** [remotely-save/remotely-save#693]
### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
描述一下原始问题？以及是哪个文件出问题？

**Comment by ongiei-ab** [comment]
在obsidian外系统资源管理器中创建了多个没有内容的md文件，打开obsdiain发现文件不存在，全部跑到回收站了，试了几次都不可以。关掉插件后可以成功创建了。刚刚我又打开插件想复现bug，但是又能成功创建。我现在也不知道是不是插件的问题

**Comment by fyears** [comment]
你有没有开启自动同步呢

**Comment by ongiei-ab** [comment]
有开自动同步，启动时同步，每十分钟同步一次。今天测试也没有复现。或许是我自己得问题吧
