### ISSUE TITLE
[Bug]: error while sync: .DS_Store in remote

### ISSUE THREAD

**Issue by devtobi** [remotely-save/remotely-save#695]
### What happened?

For about a week now I get a sync failed error on all my devices (Mac, Windows, iOS) when syncing from my own WebDAV server.
The log in Obsidian is shown below:

![image](https://github.com/remotely-save/remotely-save/assets/28538704/0cb2bac2-f266-453f-a078-47348d733751)

It seems like it has to do with files `.DS_Store`.

I don't know how that file got there and I don't know how to get rid of this error.
I cannot delete the file because the directory is encrypted.

Is this a bug of the plugin? If the file was placed there by macoS (which I guess), the plugin should be able to handle that.

### What OS are you using?

Windows, macOS, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.5.3

### Version of Obsidian

1.6.2

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
i suspect you change the file name in the webdav server...

can you go to the webdav server vault root, and see if any file name contains dot?

**Comment by fyears** [comment]
Oh i see, do you visit or mount the webdav server using mac? the system will create the hidden file into webdav server beside the encrypted files created by Remotely Save...

I will try to ignore this file in next version.

**Comment by devtobi** [comment]
Actually I don‘t manually visit the webdav server with my mac. I only use it through remotely-save. So I don’t know where that file is actually coming from.

**Comment by devtobi** [comment]
I manually deleted the file and now it‘s working again. Anyways I‘ll leave this issue open until the ignore for .DS_Store is implemented. 😉

**Comment by fyears** [comment]
Fixed in https://github.com/remotely-save/remotely-save/commit/d067937138f20b73507e5220f3ff780e7ec3c602

Will be released in this weekend

**Comment by delaaxe** [comment]
I'd like to sync `.DS_Store` files since they contains macOS tags. Is this preventing it?
