### ISSUE TITLE
[Bug]: Data loss using Remotely Save Pro Smart Conflict

### ISSUE THREAD

**Issue by tenebrisnox** [remotely-save/remotely-save#697]
### What happened?

When using the Smart Conflict settings, I’m losing data from notes. The “deleted” data is not then retrievable (from the .obsidian trash folder).

I’m syncing between up to four devices (2 macbooks, phone and ipad) - but I’ve carefully checked that all the setting were the same across devices.

This data loss has only happened since I’ve been trying out the Smart Conflict option. Before that it worked ok.

### What OS are you using?

macOS, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.2

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Can you share the details a little bit? Are you referring to markdown files or binary files? You said "loss", but does the file still exist but the content is not expected?

Please enable smart conflict, then disable auto sync and sync on save and sync while start up.  Then try to generate a reproducible example with detailed steps.

**Comment by fyears** [comment]
Close due to bo further response.

If you can **reproduce** the bug consistently , feel free to to re open the issue
