### ISSUE TITLE
[Feature Request]: Allow us to change the sync folder location in Onedrive

### ISSUE THREAD

**Issue by pranesh-sekar** [remotely-save/remotely-save#698]
### What feature are you suggesting?

Currently remotely-save  allows us to save the vault in Onedrive -> Apps -> <vault name>.
It would be helpful if I can change this location.

I currently organize my folder with a particular naming convention like 01 Apps, 02 Docs, 03 Pictures, etc. The 'Apps' folder became an odd when it is generated. 

Thanks in advance

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Only Dropbox and Onedrive has this limitation. 

For Onedrive, a new PRO feature is developed in 0.5.11. Please see the [doc](https://github.com/remotely-save/remotely-save/blob/master/docs/remote_services/onedrivefull/README.md)
