### ISSUE TITLE
[Bug]: Issue of sync

### ISSUE THREAD

**Issue by AnnW-123** [remotely-save/remotely-save#699]
![Uploading sync issue ios.jpg…]()
### What happened?

When I was trying to sync the content newly created, I found that it failed to upload the change and showed as below.

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.3.25

### Version of Obsidian

1.6.2

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
"show as below", any screenshots missing?

**Comment by AnnW-123** [comment]
![sync issue ios](https://github.com/remotely-save/remotely-save/assets/134689197/c0f0c38c-dfe9-4e07-9c48-cbc8005bddaa)

![image](https://github.com/remotely-save/remotely-save/assets/134689197/f5e85b1b-4ee7-41c7-a7d3-821504656dbf)

See if you can see the pic. now? Seems was not uploaded successfully just now. Thank you!

**Comment by fyears** [comment]
你的本地数据库不够位置了

1. 手动备份你的vault
2. 去到设置页，到最下面，点击重设本地缓存和数据库
3. 再次备份
4. 之后应该正常了

**Comment by AnnW-123** [comment]
> 你的本地数据库不够位置了
> 
> 1. 手动备份你的vault
> 2. 去到设置页，到最下面，点击重设本地缓存和数据库
> 3. 再次备份
> 4. 之后应该正常了

问题解决了，感谢！
