### ISSUE TITLE
[Bug]: 使用正则忽略部分插件文法，同步后，本地相关插件被删除

### ISSUE THREAD

**Issue by youarenever** [remotely-save/remotely-save#700]
### What happened?

我打开了配置同步，同时使用如下的正则忽略文件

```
.obsidian\/app.json
.obsidian\/appearance.json
.obsidian\/plugins\/oz-clear-unused-images\/.+
.obsidian\/plugins\/pdf-plus\/.+
.obsidian\/plugins\/obsidian-outliner\/.+
...
```
同步完后，本地的以上列表中的插件相关的全被删除，服务端的正常。

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3

### Version of the plugin

0.5.3

### Version of Obsidian

1.6.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
忽略之后应该是不删除也不增加的……具体操作步骤是怎样的？

**Comment by youarenever** [comment]
我是先把所有插件全量同步到服务端，然后再添加忽略正则，再次同步时，被忽略的插件在本地就被删除了

**Comment by fyears** [comment]
无法复现。

新建一个测试 vault，随便安装一些插件，和 remotely save，先同步一次，再忽略，再同步，看删除行为能复现吗？

**Comment by fyears** [comment]
无法复现，无进一步信息，先关闭了
