### ISSUE TITLE
[Bug]: 阿里云OSS同步问题Help

### ISSUE THREAD

**Issue by git10135405** [remotely-save/remotely-save#701]
### What happened?

5月底开始出现同步失败，原以为是暂时，但是闲下来看了下之前都是正常，阿里云一直也没登录去操作什么？最近主要有跟着更新同步插件
目前提示访问不到存储桶，但实际有也授权AK/AS了也没错，点同步提示如下（疑问不应该是同步失败吗？？）：
![image](https://github.com/remotely-save/remotely-save/assets/35558611/a0a66870-1f12-4c04-84ad-9e3022d608c8)

### What OS are you using?

Windows, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.5.5

### Version of Obsidian

1.6.3

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
region 确认没配置错？不能用域名，region 里不应该有英文句号（点号 .）

此外网络确认是通的吗？有用 vpn 之类的吗？

**Comment by git10135405** [comment]
> region 确认没配置错？不能用域名，region 里不应该有英文句号（点号 .）
> 
> 此外网络确认是通的吗？有用 vpn 之类的吗？

确定了，而且是电脑和手机都用不了了
![image](https://github.com/remotely-save/remotely-save/assets/35558611/949a6bc9-6e52-4905-97c1-b7cc71807c54)

**Comment by fyears** [comment]
有配置 vpn 吗？而且，用不带 proxy 的 s3 cmd 能连接吗？

阿里云那里确认没有设置权限阻断吗？读权限和写权限都有吗？

存储桶名字确定没错吗？前后没有空格吗？

**Comment by fyears** [comment]
域名也可以试一下加上 https:// 前缀

**Comment by git10135405** [comment]
> 域名也可以试一下加上 https:// 前缀

![image](https://github.com/remotely-save/remotely-save/assets/35558611/123a662f-e1a9-4c7d-ad2c-544bc191ea61)


开没开vpn都一样不行，没空格，云oss一直没去动 5月前都没问题
![image](https://github.com/remotely-save/remotely-save/assets/35558611/c926844b-0671-4bdb-b46b-f76ba03c3a4c)
![image](https://github.com/remotely-save/remotely-save/assets/35558611/6440e2c0-283b-4fbf-a087-8f08b97b0b74)

**Comment by git10135405** [comment]
有点怀疑是鉴权方面出了点问题 看着有访问
![image](https://github.com/remotely-save/remotely-save/assets/35558611/55928915-88d7-408d-a7f3-017c285f735e)
![image](https://github.com/remotely-save/remotely-save/assets/35558611/864ed85b-46dc-4c41-b8ea-d3b4d898ac82)

**Comment by git10135405** [comment]
> access key 有没有可能失效了？用 s3cmd 之类的可以正常访问吗？

看着是没失效，而且我新创建了一个也不行。s3cmd 之类的没用过😅
![image](https://github.com/remotely-save/remotely-save/assets/35558611/221e25ef-b4e6-4748-8fa6-7b9f61107d17)

**Comment by fyears** [comment]
请使用此步骤验证：

1. 去阿里云网页端，随便上传一些东西到 bucket 里

2. 下载 amazon 官方的 aws cli，并安装： 
    * 说明网页 https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
    * windows 直接下载链接： https://awscli.amazonaws.com/AWSCLIV2.msi

3. 你在 windows，可以直接用 cmd.exe 进入命令行，仿照以下命令修改：
    * 说明网页 https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
    * 实际命令：
        ```
        set AWS_ACCESS_KEY_ID=你的keyid注意不要有空格
        set AWS_SECRET_ACCESS_KEY=你的secret注意不要有空格
        set AWS_DEFAULT_REGION=oss-cn-hongkong
        set AWS_ENDPOINT_URL=https://oss-cn-hongkong.aliyuncs.com

        aws s3 ls s3://你的bucket名字
        ```
    * 如果一切顺利，上述 `aws s3 ls s3://你的bucket名字` 会返回一堆文件列表，就是你上传在 bucket 根目录下的。
    * 如果出错，看看出错内容是什么

**Comment by git10135405** [comment]
> aws s3 ls s3://你的bucket名字

![image](https://github.com/remotely-save/remotely-save/assets/35558611/1df4a777-9c59-4d6f-b3d6-99fb43f460af)

**Comment by git10135405** [comment]
> 请使用此步骤验证：
> 
> 1. 去阿里云网页端，随便上传一些东西到 bucket 里
> 2. 下载 amazon 官方的 aws cli，并安装：
>    
>    * 说明网页 https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
>    * windows 直接下载链接： https://awscli.amazonaws.com/AWSCLIV2.msi
> 3. 你在 windows，可以直接用 cmd.exe 进入命令行，仿照以下命令修改：
>    
>    * 说明网页 https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
>    * 实际命令：
>      ```
>      set AWS_ACCESS_KEY_ID=你的keyid注意不要有空格
>      set AWS_SECRET_ACCESS_KEY=你的secret注意不要有空格
>      set AWS_DEFAULT_REGION=oss-cn-hongkong
>      set AWS_ENDPOINT_URL=https://oss-cn-hongkong.aliyuncs.com
>      
>      aws s3 ls s3://你的bucket名字
>      ```
>    * 如果一切顺利，上述 `aws s3 ls s3://你的bucket名字` 会返回一堆文件列表，就是你上传在 bucket 根目录下的。
>    * 如果出错，看看出错内容是什么

![image](https://github.com/remotely-save/remotely-save/assets/35558611/2b5648bf-e616-4c57-a823-e32d9c8786e6)

**Comment by fyears** [comment]
```
set AWS_ACCESS_KEY_ID=你的keyid注意不要有空格
set AWS_SECRET_ACCESS_KEY=你的secret注意不要有空格
set AWS_DEFAULT_REGION=oss-cn-hongkong
set AWS_ENDPOINT_URL=https://bucket名字.oss-cn-hongkong.aliyuncs.com

aws s3 ls s3://你的bucket名字

```

这样子呢？

**Comment by git10135405** [comment]
> ```
> set AWS_ACCESS_KEY_ID=你的keyid注意不要有空格
> set AWS_SECRET_ACCESS_KEY=你的secret注意不要有空格
> set AWS_DEFAULT_REGION=oss-cn-hongkong
> set AWS_ENDPOINT_URL=https://bucket名字.oss-cn-hongkong.aliyuncs.com
> 
> aws s3 ls s3://你的bucket名字
> ```
> 
> 这样子呢？

![image](https://github.com/remotely-save/remotely-save/assets/35558611/b2ab8809-8c3b-4641-b421-efa50329d285)

**Comment by fyears** [comment]
所以确实是你的桶或者哪里配置有问题哇。建议自行排查直到上述命令行正确输出文件列表

**Comment by git10135405** [comment]
> 所以确实是你的桶或者哪里配置有问题哇。建议自行排查直到上述命令行正确输出文件列表

郁闷啊，不过还是谢谢你！
很久没上云动过了，搞不清楚为啥突然不行了，得好好看下哪里出问题了，这两天也在看但是权限啥的配置看着都没问题😅

**Comment by fyears** [comment]
这里思路很简单，我们用官方工具尝试连接，连得上的话就是正常（然后是插件bug），现在是无法用官方工具连上，所以无法证实确实是插件问题还是你的配置问题

最后的尝试，end point 没有 bucket ，然后参数里增加 addressing style

```

set AWS_ACCESS_KEY_ID=你的keyid注意不要有空格
set AWS_SECRET_ACCESS_KEY=你的secret注意不要有空格
set AWS_DEFAULT_REGION=oss-cn-hongkong
set AWS_ENDPOINT_URL=https://oss-cn-hongkong.aliyuncs.com

aws s3 ls s3://你的bucket名字 --addressing_style virtual
```

还不行的话，折腾一下 s3cmd （似乎要安装 python ） 或者 minio client https://min.io/docs/minio/linux/reference/minio-mc.html 看能否连上

**Comment by fyears** [comment]
有无我没有阿里云，所以只能猜测了。我自己用 cloudflare 和本地 minio server 是没问题的。

**Comment by git10135405** [comment]
> 这里思路很简单，我们用官方工具尝试连接，连得上的话就是正常（然后是插件bug），现在是无法用官方工具连上，所以无法证实确实是插件问题还是你的配置问题
> 
> 最后的尝试，end point 没有 bucket ，然后参数里增加 addressing style
> 
> ```
> 
> set AWS_ACCESS_KEY_ID=你的keyid注意不要有空格
> set AWS_SECRET_ACCESS_KEY=你的secret注意不要有空格
> set AWS_DEFAULT_REGION=oss-cn-hongkong
> set AWS_ENDPOINT_URL=https://oss-cn-hongkong.aliyuncs.com
> 
> aws s3 ls s3://你的bucket名字 --addressing_style virtual
> ```
> 
> 还不行的话，折腾一下 s3cmd （似乎要安装 python ） 或者 minio client https://min.io/docs/minio/linux/reference/minio-mc.html 看能否连上

![image](https://github.com/remotely-save/remotely-save/assets/35558611/777cbebd-d3c1-4d86-aa7b-e322ea42b8af)

**Comment by git10135405** [comment]
> 有无我没有阿里云，所以只能猜测了。我自己用 cloudflare 和本地 minio server 是没问题的。

注册个账号 香港免费资源够用就没折腾其他了

**Comment by git10135405** [comment]
阿里售后问了给答复是：国内用户访问海外区域的bucket，会受到跨境链路的影响 会出现无法访问、访问超时的情况  郁闷了 之前都没问题

你们都在用什么同步方案 有免费的吗？

**Comment by fyears** [comment]
cloudflare r2 和 backblaze b2 都有免费额度，可以考察一下。

**Comment by fyears** [comment]
不过我认为不是网络问题，而是授权问题，或者是配置问题。因为你的命令行可以看到是有返回数据的。也可以再查一下。

**Comment by git10135405** [comment]
@fyears 服了这鬼东西，发现我有两个bucket 其中一个没问题  把有问题的删了重新创建同名还是不行 再次删除新增一个不一样的名字bucket竟然可以了 Shit ...

**Comment by git10135405** [comment]
> 那肯定是哪一个策略配置了 bucket 屏蔽了

刚才又不行了 另外可以的还是可以  怀疑是不是免费的只能搞一个bucket  算了 把不行的换webdav了
