### ISSUE TITLE
[feature] Sync Direction: Push Only (mirror mode)

### ISSUE THREAD

**Issue by obsidianmduser** [remotely-save/remotely-save#703]
Hi, first of all, I want to thank you for your work 🙏.

### Setup

I have created on my android device a _test-vault_ and configured **remotely-save** as following:
- **Remote Service**: Dropbox
- **Encryption Password**: \*\*\*\*\*
- **Schedule For Auto Run**: every 10 minutes
- **Run Once On Start Up Automatically**: sync once after 10 seconds of start up
- **Deletion Destination**: Obsidian .trash folder
- **Action For Empty Folders**: leave them as is (default)
- **Abort Sync If Modification Above Percentage**: 100 (disable the protection)
- **Sync Direction**: Incremental Push Only (aka backup mode)

Everything else is set to default.

### Test case

1. I have created 2 test files and 1 test folder with another test file in the local vault via Obsidian app.
2. Trigered sync. 
3. Checked Dropbox – everything was pushed there as expected. 
4. Deleted one of the top level test files from the local vault via app. 
5. Trigerred sync.
6. Checked Dropbox – **file was not removed from Dropbox**. 

#### Expected behavior

Given *'Sync Direction: Incremental Push Only (aka backup mode)'*, when file is deleted in local vault via Obsidian app, then file SHOULD BE removed from remote vault.

#### Actual behavior

Given *'Sync Direction: Incremental Push Only (aka backup mode)'*, when file is deleted in local vault via Obsidian app, then file IS NOT removed from remote vault.

### Workaround

If I set *'Sync Direction: Bi-directional (default)'* deleted file via app is immediatelly removed from Dropbox. 

### Why I want to use 'push only' mode

I want to **upstream any changes made by myself** from the app (push local changes to remote), but **prevent plugin to touch my local files**, which is the case in bi-directional mode, when local files are affected by the state of the remote on downstream operation (pulling remote changes to local). 

With 'push only' mode I don't have to worry if in future there will be some **sync bug which might delete any of my files by accident** or when **files were deleted by accident on remote** (either by user or malfunction of the service provider) which will be **propagated to local vault causing data loss**, since plugin will operate **only in upstream manner** (push only). 

### Why I want to mirror file deletion in remote

If changes, including file deletion, would be mirrored upstream, **state of the remote vault will be consistent with the state of the local vault**, so if I decide in future to restore my vault from remote on new device, vault would not be **cluttered by files that were deleted ages ago** (if the restored vault would contain also files that were already deleted long time ago, and vault contain hundreds or thousands of files, how would I know, if any of the files in my vault is still relevant?).

### Why mirroring file deletion is safe

If I **delete some file by accident locally**, it will end up in obsidian *'.trash'* folder so even if "push changes" will delete remote file, I can always **restore this file from local '.trash'**.

### Proposed solution

Implementation of an another sync option *'Sync Direction: Push Only (mirror mode)' which will be mirroring also deleted files in remote. 

**Extra step**: '.trash' folder could also be synced, so we would be able to restore deleted files also from the remote vault.

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

0.5.5

### Version of Obsidian

1.6.3

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
the main point is the optionate "Incremental Push Only (aka backup mode)" and the deletion is not synced as expected.

since it's "incremental", may be it's better not delete anything in the remote?

you might actually want a "mirror local into remote" direction?

**Comment by fyears** [comment]
What happens if I add more files into remote?

What happens if I modify some synced files in the remote?

**Comment by fyears** [comment]
added in 0.5.6
