### ISSUE TITLE
[Bug]: seems not working properly when setting the [Skip Large Files]

### ISSUE THREAD

**Issue by Qiguang** [remotely-save/remotely-save#704]
### What happened?

I have upgraded the plugin to the latest version(0.5.5)
I just set the [Skip Large Files] to 5MB
At first, sync worked well
After I modified some files, their size exceeded 5MB
Then I get this error prompt, and seems all other files sync failed not just these few files
![snipping](https://github.com/remotely-save/remotely-save/assets/10783991/8b332253-ebed-4dee-83f6-4baca440c6f8)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.5

### Version of Obsidian

1.6.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
这里是符合预期的运作方式。

本质上，你同步了 4 mb 的文件，然后又把它改成 6 mb，那么插件到底应该同步还是不同步呢？同步的话又超出了约定，不同步的话又存在两边**同时有文件**且不一致，用户也会认为是 bug。

目前对于边界条件不知道如何处理，因此抛出错误给用户手动处理。此外目前所有错误都会阻断后继同步逻辑，也是符合预期的。

处理方式：既然你都有 6mb 文件了，那么跳过大文件可以放宽一点（例如 10mb），从而正确同步。又或者确定不需要同步的话，去 onedrive 网页端手动删除对应的 4mb 文件。
