### ISSUE TITLE
[Bug]: 手机端同步文件导致崩溃

### ISSUE THREAD

**Issue by lixingyu41** [remotely-save/remotely-save#705]
### What happened?

使用windows端同步了一个36MB大小的pdf文档，在安卓手机端拉取时obsidian崩溃，并且同步失败，手动删除windows端文件后双端都可以正常同步

### What OS are you using?

Windows, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.3

### Version of Obsidian

1.6.2

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
能确认更改部分只是这一个文件吗？可以这样复现：

1. 重新手动上传到onedrive，
2. 然后触发同步
3. 然后导出 sync plan （最近一次，仅变更部分）


看看 sync plan 是不是只有那个新的文件。

**Comment by fyears** [comment]
我找到一个方法来试图避免下载崩溃，不过最好还是确认一下是不是这个原因。

此外无论如何，手机内存一定要是下载文件的 2~3 倍或以上。

**Comment by lixingyu41** [comment]
{
  "A我的项目/技术项目/嵌入式/飞控/基于BF的飞控设计V1/STM32H743参考手册中文版.pdf": {
    "key": "A我的项目/技术项目/嵌入式/飞控/基于BF的飞控设计V1/STM32H743参考手册中文版.pdf",
    "remote": {
      "key": "A我的项目/技术项目/嵌入式/飞控/基于BF的飞控设计V1/STM32H743参考手册中文版.pdf",
      "keyRaw": "gg8dwIM6ESP9SmPysdjREA/WwKdb9N9GYAC8g_ALS99ag/NZJP6oxL_0wTb2ocCWisSw/vVPErYvIVCFJpjfb3r_8bQ/bmauX3W5zVdD9aI4IQtXf380vMPJlFaLJAYhwUdqcpo/ntTaL7WtjycLCrIqSDIlAPL_BKSYtD4h8r7Ew3VgUj-sQi83lINodb4u63iGPrhJ",
      "keyEnc": "gg8dwIM6ESP9SmPysdjREA/WwKdb9N9GYAC8g_ALS99ag/NZJP6oxL_0wTb2ocCWisSw/vVPErYvIVCFJpjfb3r_8bQ/bmauX3W5zVdD9aI4IQtXf380vMPJlFaLJAYhwUdqcpo/ntTaL7WtjycLCrIqSDIlAPL_BKSYtD4h8r7Ew3VgUj-sQi83lINodb4u63iGPrhJ",
      "mtimeCli": 1718461519041,
      "mtimeSvr": 1718461519041,
      "sizeEnc": 37775329,
      "sizeRaw": 37775329,
      "mtimeCliFmt": "2024-06-15T22:25:19+08:00",
      "mtimeSvrFmt": "2024-06-15T22:25:19+08:00"
    },
    "decisionBranch": 3,
    "decision": "remote_is_created_then_pull",
    "change": true
  },
  "/$@meta": {
    "key": "/$@meta",
    "sideNotes": {
      "version": "20240525 fs version",
      "generateTime": 1718461566320,
      "generateTimeFmt": "2024-06-15T22:26:06+08:00",
      "service": "onedrive",
      "concurrency": 5,
      "hasPassword": true,
      "syncConfigDir": false,
      "syncUnderscoreItems": true,
      "skipSizeLargerThan": -1,
      "protectModifyPercentage": 50,
      "conflictAction": "keep_newer",
      "syncDirection": "bidirectional",
      "triggerSource": "manual",
      "sizeof": 943736
    }
  }
}



这是导出的仅修改过的部分，而且也测试了几次只有那一个文件，而且是windows端可以同步，手机端一拉取obsidian就会崩溃，
下面是软件崩溃前的日志
java.lang.OutOfMemoryError: Failed to allocate a 50367128 byte allocation with 7768536 free bytes and 7586KB until OOM, target footprint 268435456, growth limit 268435456
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:124)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:109)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:79)
	at android.util.Base64.encodeToString(Base64.java:458)
	at com.capacitorjs.plugins.app.AppPlugin.requestUrlAndroid(AppPlugin.java:256)
	at com.capacitorjs.plugins.app.AppPlugin.lambda$requestUrl$2(AppPlugin.java:162)
	at com.capacitorjs.plugins.app.AppPlugin.$r8$lambda$kPUN2Qle0kJjDsRC1OYLJoNfNxo(Unknown Source:0)
	at com.capacitorjs.plugins.app.AppPlugin$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by fyears** [comment]
你的手机上只剩下7mb内存，但是要下载30多mb的文件。建议清理一下内存……

解决方案：

1.清理内存
2.rs设置“跳过大文件”，这样就可以忽略且不会下载

**Comment by lixingyu41** [comment]
> 你的手机上只剩下7mb内存，但是要下载30多mb的文件。建议清理一下内存……
> 
> 解决方案：
> 
> 1.清理内存 2.rs设置“跳过大文件”，这样就可以忽略且不会下载

我手机24G内存（16G加8G的swap）啊，是不是系统限制了软件内存的占用，我用软件一是基本不留后台，日常都会有10G左右空闲，这给bug是只有我遇到吗，那可能是系统调度的原因，我尝试了只留obsidian一个后台还是会崩溃

**Comment by fyears** [comment]
@lixingyu41 onedrive 我换了一种下载方式。试试最新版 0.5.6 。这里很有可能是 Obsidian app 本身也有一些奇怪的 bug。

**Comment by lixingyu41** [comment]
> @lixingyu41 onedrive 我换了一种下载方式。试试最新版 0.5.6 。这里很有可能是 Obsidian app 本身也有一些奇怪的 bug。

大佬太牛了，问题解决了，现在可以正常拉取了，感谢！！！
