### ISSUE TITLE
[Feature Request]: IOS 无法连接http的webdav

### ISSUE THREAD

**Issue by kids0cn** [remotely-save/remotely-save#709]
### What feature are you suggesting?

之前的版本是可以通过http+ip的方式连接非https的webdav服务的，这样对于自建webdav的就很方便。
现在是因为苹果的要求，不能这样使用了吗？ 大佬可以通过技术手段把这个feature加回来吗

### What remote cloud services are you using, or suggesting adding the feature to?

webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
不行。这个是操作系统 && obsidian app 本身的限制。

要绕过限制，一定要服务器加点东西或者设置什么。

因此，我建议搞个便宜域名和 https，一劳永逸，安全也有保证。
