### ISSUE TITLE
[Bug]: Fail to sync on Android because `The XML you provided was not well-formed or did not validate against our published schema`

### ISSUE THREAD

**Issue by pullopen** [remotely-save/remotely-save#71]
### What happened?

I try to start scyncing on my Android Obsidian and failed. The Error Message shows:
```
The XML you provided was not well-formed or did not validate against our published schema.
```

It happens after the recent plugin update. Previously it worked fine.

### What OS are you using?

Android

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.17

### Version of Obsidian

Android 1.1.1

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by pullopen** [comment]
Solved by modify CORS.

My CORS setting if anyone needed:

```
{
    "CORSRules": [
        {
            "AllowedHeaders": [
                "*"
            ],
            "AllowedMethods": [
                "GET",
                "PUT",
                "POST",
                "DELETE",
                "HEAD"
            ],
            "AllowedOrigins": [
                "app://obsidian.md",
                "capacitor://localhost",
                "http://localhost"
            ],
            "ExposeHeaders": [
                "Etag"
            ]
        }
    ]
}
```

**Comment by fyears** [comment]
It basically means something goes wrong while uploading large files. As you mentioned, you need to add `ETag` into exposed headers in CORS config (besides all other allowed origins config), and then the problem should be solved.
