### ISSUE TITLE
[Bug]:  Cannot read properties of undefined (reading 'valueOf')

### ISSUE THREAD

**Issue by jingling2000** [remotely-save/remotely-save#710]
### What happened?

无法同步文件，只能同步文件夹，同步的时候提示 Cannot read properties of undefined (reading 'valueOf')。在PC端使用windows 10，也出现过这样的提示，但是，后来莫名其妙的好了。我是向自建的MinIO中同步数据的。

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (MinIO)

### Version of the plugin

0.5.7

### Version of Obsidian

1.6.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by jingling2000** [comment]
plugin:Enhanced-editing:1571 Uncaught TypeError: Cannot read properties of null (reading 'editor')
    at MyPlugin.获取编辑模式 (plugin:Enhanced-editing:1571:29)
    at MyPlugin.获取编辑器信息 (plugin:Enhanced-editing:1577:21)
    at HTMLDocument.eval (plugin:Enhanced-editing:942:18)
获取编辑模式 @ plugin:Enhanced-editing:1571
获取编辑器信息 @ plugin:Enhanced-editing:1577
eval @ plugin:Enhanced-editing:942
plugin:remotely-save:90 startting sync.
plugin:remotely-save:234 AggregateError: 
    Error: 我的资料/应用/win10 TIM修改聊天记录保存路径无效的解决方案.md: Cannot read properties of undefined (reading 'valueOf')
        at eval (plugin:remotely-save:90:95745)
    Error: 我的资料/Halo 个人博客/在 Halo 个人博客系统中使用 Obsidian 发布文章.md: Cannot read properties of undefined (reading 'valueOf')
        at eval (plugin:remotely-save:90:95745)
    Error: 我的资料/应用/DBeaver Ultimate Edition 破解方式.md: Cannot read properties of undefined (reading 'valueOf')
        at eval (plugin:remotely-save:90:95745)
    Error: 我的资料/应用/Debian 11 Bullseye 中重置 Root 密码.md: Cannot read properties of undefined (reading 'valueOf')
        at eval (plugin:remotely-save:90:95745)
    Error: 我的资料/Halo 个人博客/使用自建对象存储（Object Storage）方式存储obsidian中的图片及同步obsidian笔记.md: Cannot read properties of undefined (reading 'valueOf')
        at eval (plugin:remotely-save:90:95745)
    Error: 我的资料/应用/docker-compose yml 文件编写.md: Cannot read properties of undefined (reading 'valueOf')
        at eval (plugin:remotely-save:90:95745)
    Error: 我的资料/应用/Nginx mime.type 最全配置文件.md: Cannot read properties of undefined (reading 'valueOf')
        at eval (plugin:remotely-save:90:95745)
    Error: 基础/01. ⚪ 知识地图/📍 Obsidian使用.md: Cannot read properties of undefined (reading 'valueOf')
        at eval (plugin:remotely-save:90:95745)
    Error: too many errors, stop the remaining tasks
        at eval (plugin:remotely-save:90:95849)
        at Generator.next (<anonymous>)
        at s (plugin:remotely-save:76:363672)
    at eval (plugin:remotely-save:90:95905)
    at Generator.next (<anonymous>)
    at s (plugin:remotely-save:76:363672)
eval @ plugin:remotely-save:234
eval @ plugin:remotely-save:76
e @ plugin:remotely-save:76
eval @ plugin:remotely-save:234
eval @ plugin:remotely-save:90
a @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
plugin:remotely-save:90 endding sync.

**Comment by jingling2000** [comment]
上面是从我另一台PC机上导出的结果。也出现了这样的问题。obs版本1.6.3，remotely-save 版本 0.5.7，操作系统WINDOWS 10

**Comment by fyears** [comment]
没什么头绪，注册一个 backblaze 试试有没有同样的问题？

也可以等下一个版本我加点提示

**Comment by fyears** [comment]
请更新到 0.5.9 看看出错提示

**Comment by fyears** [comment]
请更新到 0.5.10 试试。加了点错误提示

**Comment by fyears** [comment]
无进一步反馈先关闭了

**Comment by payprays** [comment]
![Image](https://github.com/user-attachments/assets/feb20126-e57f-421e-ac7a-27b025ab2756)
webdav同样的错误，安卓最新版，只能同步文件夹，无法同步文件
但是在PC上同样的版本是能够同步的

但是在PC和安卓上使用s3同步失败，具体报错如下

![Image](https://github.com/user-attachments/assets/85b257af-3e9c-4bef-a975-2dc97d7823c5)

两个服务器都是alist最新版本下的webdav和s3，目录都是相同的

**Comment by payprays** [comment]
实测似乎网络包都没发出去，没抓到流量
