### ISSUE TITLE
[Bug]: 同步状态栏异常

### ISSUE THREAD

**Issue by lyiton** [remotely-save/remotely-save#713]
### What happened?

更新0.5.8版本后，启动时同步、手动同步、保存时同步完成后，均卡在“(同步类型)：正在同步”，正确状态应为“同步成功：刚刚”。

我确定已经同步完成，而非真的正在同步。

错误效果如下：
启动时同步：
![启动时同步](https://github.com/remotely-save/remotely-save/assets/76651858/0705a68d-0ccb-42b0-9c18-7a51600a6ba6)
手动同步：
![手动同步](https://github.com/remotely-save/remotely-save/assets/76651858/5a495049-05ff-4b66-99d9-f50e6d348494)
保存时同步：
![保存时同步](https://github.com/remotely-save/remotely-save/assets/76651858/009ac9e2-d014-4d0d-bdfd-a5cc259eac62)

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.5.8

### Version of Obsidian

1.6.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by lyiton** [comment]
由于gif的循环性，手动同步的演示效果存在错误，最后跳出“同步成功：刚刚”，是由于初始状态为“同步成功：刚刚”，实际仍然卡在“正在同步”这一步。

**Comment by lyiton** [comment]
另外，提几个小错误，由于不一定会采纳，所以没有提交PR。

![PixPin_2024-06-20_21-41-20](https://github.com/remotely-save/remotely-save/assets/76651858/6c2e7bc4-e268-4b83-a4ba-517fdee50e48)

①②③④应该是想体现同步类型，所以建议更改为“手动同步、自动同步、启动时同步、保存时同步”。

⑤是一个细节问题，由于{{time}}显示为阿拉伯数字，且“之内”和“前”不统一，所以建议更改为“1分钟内”。

**Comment by fyears** [comment]
这里做得是有点粗糙了，有空时候改改。

**Comment by fyears** [comment]
另外1234故意用了短描述，因为手机上显示很占用位置

**Comment by lyiton** [comment]
> 另外1234故意用了短描述，因为手机上显示很占用位置

了解了，“启动时自动”意思不明确，仍然建议改为“启动时同步”。😂😂

**Comment by banshaobao** [comment]
PC端也是状态栏异常

**Comment by banshaobao** [comment]
我建议【手动】【自动】【启动】【保存】【1分钟内】

**Comment by fyears** [comment]
0.5.9 已修复

**Comment by fyears** [comment]
（0.5.9 有点问题，我得查一下）

**Comment by fyears** [comment]
0.5.10 已修复

**Comment by lyiton** [comment]
似乎还是有点问题：在编辑时切换后台，再次进入Obsidian，同步状态栏会消失。
PS：我经常切换后台，我确定之前的版本没有该问题。
![PixPin_2024-06-23_09-51-02](https://github.com/remotely-save/remotely-save/assets/76651858/c94f8c70-1a90-408f-8a59-aeda23e15f20)

**Comment by lyiton** [comment]
抱歉，今天尝试回退插件旧版本，问题仍然存在；回退obsidian旧版本，问题消失。

由此猜测，该问题大概率是obsidian自身的问题（近期obsidian更新了两次）。

**Comment by fyears** [comment]
好的，不过 status bar 本身就是一个 hack ，默认手机上是隐藏的。不知道官方是否愿意支持。
