### ISSUE TITLE
[Bug]: Plugin loading failure

### ISSUE THREAD

**Issue by chen-jingliang** [remotely-save/remotely-save#717]
### What happened?

For versions 0.5.8-0.5.11, the plugin fails to load!
macos Sequoia 15.0 beta： the plugin fails to load!
macos Sonoma14.5：Plugin loaded successfully
win11 23H2： the plugin fails to load!
![remotely save](https://github.com/remotely-save/remotely-save/assets/28627641/cba6cba1-883c-46e9-87b7-454ce0106b50)

### What OS are you using?

Windows, macOS

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.11

### Version of Obsidian

1.6.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
打开console看看有什么错误提示？

https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/check_console_output.md

**Comment by fyears** [comment]
以及0.5.7可以正常load？

**Comment by fyears** [comment]
你的 obsidian 确认是最新版吗？

**Comment by chen-jingliang** [comment]
经过逐个版本的测试，在MAC sequoia beta系统中，从0.5.6开始，加载失败，0.5.5可以正常使用。
我刚刚在Win11 23h2的电脑上测试了，0.5.11正常加载，另一台MAC系统是14.5时可用，不知是否与MAC sequoia BETA版本有关。
<img width="571" alt="0 5 5" src="https://github.com/remotely-save/remotely-save/assets/28627641/40f2e9af-45f9-4eae-80e7-39c6d4199cf2">
<img width="563" alt="0 5 6" src="https://github.com/remotely-save/remotely-save/assets/28627641/94332b69-8200-438e-8808-37129df32aa5">

**Comment by chen-jingliang** [comment]
已经设置为debug模式，但是按下快捷键无显示，不知如何操作，如果是0.5.6以上插件，安装后没有设置选项，见文中插图显示。

**Comment by fyears** [comment]
截图错误里，前5个链接都点击进入一下，应该会跳转到一个代码 tab ，把代码截全一下发一下？

**Comment by fyears** [comment]
有没有 mac 正式版可以看到是否加载成果？如果正式版可以测试版不能那么应该就是系统问题。

我这里没有 mac 电脑调试，用 win 10 最新版没问题，你也用 win 11 最新版没问题。实在想不到哪里会出错了。

此外 obsidian 也可以试试官网下载最新安装包然后覆盖安装一下看看会不会自动好了。

**Comment by chen-jingliang** [comment]
我刚刚在另一台MAC上测试了一下，系统是MAC 14.5正式版，可以正常使用，应该是系统问题。

**Comment by fyears** [comment]
谢谢反馈
