### ISSUE TITLE
[Bug]: Failed to load plugin on iPhone 6s (14.5)

### ISSUE THREAD

**Issue by MusArtVlad** [remotely-save/remotely-save#718]
### What happened?

When I try to run Remotely Save, I get “Failed to load plugin” displayed.
The plugin used to work before, but after the update it stopped working.
iPhone 6s, iOS 14.5 (18E199)
[IMG_6776](https://github.com/remotely-save/remotely-save/assets/61934491/be1bfdde-e598-4e3f-bb74-0254cde60e06), [IMG_6777](https://github.com/remotely-save/remotely-save/assets/61934491/9bc645b2-10a2-483e-b59f-3b7b9e7a5df3), [IMG_6778](https://github.com/remotely-save/remotely-save/assets/61934491/9019a9fd-2c6b-46b1-bee9-41f114f79bfe)

Everything works on iPad, plugin version 0.5.3. I'm afraid to update.
iPadOS 16.7.8

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

0.5.11

### Version of Obsidian

1.6.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> The plugin used to work before, but after the update it stopped working.

Do you remember what’s the version? And I am afraid ios 14 is toooooo old and only remotely save ~0.3.12 supports it.

> Everything works on iPad, plugin version 0.5.3. I'm afraid to update.
> iPadOS 16.7.8

I think it has a newer ios version than your phone and it should be ok. try to update the plugin please.

And don’t worry, you can always install bart and use bart to install the older version of remotely save:  https://tfthacker.com/BRAT

**Comment by fyears** [comment]
close due to no further response
