### ISSUE TITLE
[Bug]: 每次退出重新打开都导入插件失败

### ISSUE THREAD

**Issue by kids0cn** [remotely-save/remotely-save#719]
### What happened?

每次退出obsidian，再次打开，remotely save 插件都会导入失败，只能删除之后重新安装才能回复
然后退出之后，再次导入失败，配置文件丢失

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

最新版

### Version of Obsidian

1.6.3最新版

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
导入失败，什么叫导入失败？还是开启失败？

**Comment by kids0cn** [comment]
> 导入失败，什么叫导入失败？还是开启失败？

开启失败。

![image](https://github.com/remotely-save/remotely-save/assets/9114283/82734424-b56b-4ff9-b315-029af3edd102)

**Comment by kids0cn** [comment]
![image](https://github.com/remotely-save/remotely-save/assets/9114283/47e4dad7-765a-4f7c-b812-6245c6a7a667)

**Comment by fyears** [comment]
这个错误，非常奇怪，在这里下载一下 main.js 直接替换一下然后重启 obsidian 试试？

https://github.com/remotely-save/remotely-save/releases/tag/0.5.11

**Comment by kids0cn** [comment]
关闭 同步 .obsidian文件  这个功能后 ，正常了

**Comment by fyears** [comment]
那么插件载入应该没问题了，之前可能是下载失败没有下载完整。

然后同步 .obsidian 这个，建议查一下 webdav 服务器设置，有些不允许同步隐藏文件夹

**Comment by kids0cn** [comment]
不是哦 ，只有同步 remotely save 自己的main.js 才出问题哦   其他的都好好的。   应该是remotely save自己的配置文件在同步的时候出现的冲突

**Comment by kids0cn** [comment]
开了这个同步 .obisidan的选项后 ，选择重建本地缓存和数据库。故障消失
