### ISSUE TITLE
[Bug]: main.js Failed to fetch

### ISSUE THREAD

**Issue by stuartchuan** [remotely-save/remotely-save#721]
### What happened?

![bbed6b15-61fe-463c-9603-5cd4d7341fe1](https://github.com/remotely-save/remotely-save/assets/11676849/329b0446-074d-4789-8518-9cc77e178134)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.11

### Version of Obsidian

v1.6.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
onedrive 里面有这个文件吗？

有开启同步冲突：智能处理（PRO功能）吗？

**Comment by stuartchuan** [comment]
onedrive里有这个文件。
没有开启同步冲突，用的是：保留最后修改的版本（默认）

**Comment by fyears** [comment]
请尝试用0.5.12

**Comment by stuartchuan** [comment]
还是同样报错

**Comment by fyears** [comment]
复现不了……手机会有同样错误吗？

电脑手动下载放置main.js后会有这个错误吗？总觉得是您的电脑有什么权限问题

**Comment by stuartchuan** [comment]
一都是没问题的，就这次出问题了。
我试试手动下载
