### ISSUE TITLE
[Bug]: .dub.dub.dub - Obsidian system files multiplying

### ISSUE THREAD

**Issue by Cossackx** [remotely-save/remotely-save#722]
### What happened?

![image](https://github.com/remotely-save/remotely-save/assets/121278003/6193d11c-19c8-415e-aff3-abc882ab404c)
![image](https://github.com/remotely-save/remotely-save/assets/121278003/21cf1c05-db16-4ad9-addc-00371e71f3e1)

I'm not sure, but could it caused by the Smart Conflict feature? That's the only thing that's really different from original settings. 
![image](https://github.com/remotely-save/remotely-save/assets/121278003/f755ad5c-80fe-4494-ab2e-c55657bc8448)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

current

### Version of Obsidian

current

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
yes. i will try to debug it. it seems that these files are consistently changing so bad things happen in smart conflict and syncing .obsidian

**Comment by fyears** [comment]
please use latest 0.5.12
