### ISSUE TITLE
[Bug]: sync failed for note with question mark

### ISSUE THREAD

**Issue by simply-me** [remotely-save/remotely-save#723]
### What happened?

Contents/xxx?.md: Request failed, status 400

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.11

### Version of Obsidian

1.6.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
onedrive doesn't allow uploading files with question mark in name. please change your file name
