### ISSUE TITLE
WIN11 23H2出现插件载入失败

### ISSUE THREAD

**Issue by chen-jingliang** [remotely-save/remotely-save#725]
### What happened?

使用最新的版本，显示载入错误，无法使用.
之前我已经提交了MAC版类似问题，现在家里WIN11系统可以导入，但公司相同系统且系统版本一致，但报错，与MAC报错一样，均显示载入失败。

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.11

### Version of Obsidian

1.6.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
真是神奇了……这是 win11最新版本吗？

obsidian 直接去官网下载最新版覆盖安装后试试？

**Comment by chen-jingliang** [comment]
我试试后再反馈

**Comment by fyears** [comment]
听上去应该是没问题的。先关闭了。
