### ISSUE TITLE
[Bug]: Empty file is not allowed in OneDrive,andplease write something in it.

### ISSUE THREAD

**Issue by leiman147** [remotely-save/remotely-save#726]
### What happened?

when i is running remotely , then This error is prompted

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by leiman147** [comment]
all the files are picture

**Comment by fyears** [comment]
So it's not a bug. As the notice said, onedrive doesn't allow empty files. You can go to the settings and set skipping empty files.

**Comment by leiman147** [comment]
> So it's not a bug. As the notice said, onedrive doesn't allow empty files. You can go to the settings and set skipping empty files.所以这不是一个错误。正如通知所述，onedrive 不允许空文件。您可以转到设置并设置跳过空文件。

But the folder is not empty, it contains pictures

**Comment by fyears** [comment]
这是说你有某一个文件是没有内容的。不是说文件夹是空的
