### ISSUE TITLE
[Bug]: Plugin fails to load on ios

### ISSUE THREAD

**Issue by giuseppetomassetti** [remotely-save/remotely-save#727]
### What happened?

![32BDCB26-B52D-4E28-A9F1-E8CA236139D0](https://github.com/remotely-save/remotely-save/assets/17876695/9532aeed-5d2a-42c9-9559-4a61950f34ad)

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

0.5.11

### Version of Obsidian

1.6.5

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
what's the version of your ios?

**Comment by xiedantibu** [comment]
iphone 12 has the same problem, version:ios 14.5.1

**Comment by fyears** [comment]
sorry ios 14 is too old and i don't have such device to debug.
