### ISSUE TITLE
[Bug]: Conflict with Git

### ISSUE THREAD

**Issue by epleone** [remotely-save/remotely-save#729]
### What happened?

I use Remotely Save to sync documents to the WebDAV and also use Git for synchronization.

I set Git for Windows to use linux file endings with git config: `git config --global core.autocrlf input` .

Then, the plugin Remotely Save indicates that Invalid response: 503 service Unavailable.

however, It works when I use a VPN.  the Remotely Save prompts that more than 50% of the files have been modified.

I think this might be a bug caused by conflicts in Git for Windows regarding the use of Linux file endings.

You can refer to this link: https://forum-zh.obsidian.md/t/topic/34339

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (坚果云 JianGuoYun/NutStore)

### Version of the plugin

all recent versions

### Version of Obsidian

1.6.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> I think this might be a bug caused by conflicts in Git for Windows regarding the use of Linux file endings.

正如你所说，很可能就是所有文件的 line ending 都被修改了。这不是 bug 啊。

1. 另外备份一下整个 vault 以免出问题
2. 放开修改百分比保护，同步一次
3. 增加百分比保护

**Comment by epleone** [comment]
哈哈，原来大佬是国人。

现在主要问题是同步总提示503 service Unavailable，除非挂VPN。这是ip被坚果云封了吗？

但在不挂VPN的情况下，可以同步Zotero到坚果云， 这貌似说明不是IP的问题。

**Comment by epleone** [comment]
@fyears 我联系过坚果云的客服，她说我的账号没有问题，能正常使用。

同时在没有任何文件更新的情况，不挂VPN就是同步不了，一直会报503 service Unavailable。
 
和 [这个链接](https://forum-zh.obsidian.md/t/topic/34339) 里的表现是一致的。

**Comment by fyears** [comment]
用官方客户端试试呢
