### ISSUE TITLE
[Feature Request]: UI password/credential input box input string is recommended to hide, do not show directly

### ISSUE THREAD

**Issue by ZetaoYang** [remotely-save/remotely-save#73]
### What feature are you suggesting?

UI password/credential input box input string is recommended to hide, do not show directly. Like the following screenshot,
![image](https://user-images.githubusercontent.com/10769951/162651436-afbefac7-c736-41d4-9170-5807cbdd3b7c.png)
![image](https://user-images.githubusercontent.com/10769951/162651463-03808ef5-6560-4a27-bda2-6a8474e1ffd0.png)

### What remote cloud services are you using, or suggesting adding the feature to?

S3, OneDrive for personal, Dropbox, webdav

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
The point is, the password itself is still saved locally unencryptedly. 

I am afraid that the ui hiding password may incorrectly give the hint to users that passwords are encrypted locally.

**Comment by i-iooi-i** [comment]
同需要这样的功能，一直在密码框显示，感觉好不习惯。。。

**Comment by fyears** [comment]
> 同需要这样的功能，一直在密码框显示，感觉好不习惯。。。

密码总要保存在本地的，没有理解，变成星号密码框带来什么好处？ @i-iooi-i

**Comment by i-iooi-i** [comment]
> > 同需要这样的功能，一直在密码框显示，感觉好不习惯。。。
> 
> 密码总要保存在本地的，没有理解，变成星号密码框带来什么好处？ @i-iooi-i

1 当我想要在B站直播，推荐分享给其他人remotely save的时候，我是不敢往这个设置页面点的，因为账户名字跟密码就明文显示在那里。

2 当我在公司使用安装了remotely save，不在工位或者没有锁屏，或者恰好疫情突然紧急封楼，结果我没法再回工位，电脑却一直开的状态，我是多少会有些不放心的。

3 刚使用或者刚接触Obsidian的人，好奇甚至查看你都装了哪些插件的时候，为别有用心的人降低了获取账号密码的难度，因为密码就显示在那里。

4 大部分使用remotely save的都是普通用户，甚至来不了github的普通用户，他们不懂开发，也不太懂产品逻辑，甚至有些人都不清楚密码居然是保存在本地（比如没有使用过remotely save的人）。即便不怀好意，想要获取账号密码，在密码框内显示成。。。。。也比直接显示12345678从心理上来说也让人更安心一些吧。

5 IOS与MAC用户的.obsidian目录是隐藏的，data.json也就相对安全一点点，被意外获取查看的概率就小一点点。但是在设置里明文显示密码，这门槛可就一点点都没有了。

总结：做这些的目的虽然看上去是掩耳盗铃，但是仅仅是为了防君子不防小人，外加心理上与视觉上求个安心。

目前能想到的就这些啦。😂

**Comment by exoticknight** [comment]
> > 同需要这样的功能，一直在密码框显示，感觉好不习惯。。。
> 
> 
> 
> 密码总要保存在本地的，没有理解，变成星号密码框带来什么好处？ @i-iooi-i 

背后有人的时候能输放心密码

**Comment by fyears** [comment]
https://github.com/remotely-save/remotely-save/commit/dd39e229d87559b84eed9a78142e266c2f0a7ff9

added in code, and will be available in next release.

代码已增加支持。会随着下一个版本发布。

**Comment by fyears** [comment]
https://github.com/remotely-save/remotely-save/releases/tag/0.3.19
