### ISSUE TITLE
[Bug]: Plugin fails to load on Android

### ISSUE THREAD

**Issue by melt923** [remotely-save/remotely-save#730]
### What happened?

![Screenshot_2024-07-01-11-11-29-986_md obsidian](https://github.com/remotely-save/remotely-save/assets/131335490/a86d1811-ded3-4fd3-855e-d75bb8d5dc7b)
小米Mix2s

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.12

### Version of Obsidian

1.6.5

### Using password or not

- [x] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
换一下或者升级一下 android web view

**Comment by HeleJia84deSp** [comment]
> 换一下或者升级一下 android web view

实测有效

**Comment by HeleJia84deSp** [comment]
> 换一下或者升级一下 android web view

it works
