### ISSUE TITLE
[Bug]: config sync problem with Mac and iPhone

### ISSUE THREAD

**Issue by mambalong** [remotely-save/remotely-save#731]
### What happened?

# My setup
I use iPhone to create a new vault and sync with oneDrive, the "Sync Config Dir" option is enabled. On Mac, I open the vault from the oneDrive location.

# Problem
I change the "Themes" on Mac, and I found that, when the iPhone app is running on the front and I click sync and restart the app, the "Themes" is changed as expected. But if the iPhone is closed, and I open it, the "Themes" is not changed.

So in the iPhone app fresh start case, I export the sync_plans, which is pasted in the below, I found that decision is "conflict_modified_then_keep_local", but since I just open the app, there should not be any modification, so I am guessing that maybe obsidian will regenerate config file every time is opened.

```json
".obsidian/appearance.json": {
    "key": ".obsidian/appearance.json",
    "remote": {
      "key": ".obsidian/appearance.json",
      "keyRaw": ".obsidian/appearance.json",
      "mtimeSvr": 1719828088742,
      "mtimeCli": 1719828088742,
      "size": 24,
      "sizeRaw": 24,
      "synthesizedFile": false,
      "keyEnc": ".obsidian/appearance.json",
      "sizeEnc": 24,
      "mtimeCliFmt": "2024-07-01T18:01:28+08:00",
      "mtimeSvrFmt": "2024-07-01T18:01:28+08:00"
    },
    "prevSync": {
      "key": ".obsidian/appearance.json",
      "keyRaw": ".obsidian/appearance.json",
      "mtimeSvr": 1719827790049,
      "mtimeCli": 1719827790049,
      "size": 24,
      "sizeRaw": 24,
      "synthesizedFile": false,
      "keyEnc": ".obsidian/appearance.json",
      "sizeEnc": 24,
      "mtimeCliFmt": "2024-07-01T17:56:30+08:00",
      "mtimeSvrFmt": "2024-07-01T17:56:30+08:00"
    },
    "local": {
      "key": ".obsidian/appearance.json",
      "keyRaw": ".obsidian/appearance.json",
      "mtimeCli": 1719828138119,
      "mtimeSvr": 1719828138119,
      "size": 24,
      "sizeRaw": 24,
      "mtimeCliFmt": "2024-07-01T18:02:18+08:00",
      "mtimeSvrFmt": "2024-07-01T18:02:18+08:00",
      "keyEnc": ".obsidian/appearance.json",
      "sizeEnc": 24
    },
    "decisionBranch": 16,
    "decision": "conflict_modified_then_keep_local",
    "change": true
  }
```

On mac, I tried to start the obsidian, and I see the config the uploaded every time I reopen the app. But the "appearance.json" file content is always the same, which is `{
  "cssTheme": "Atom"
}`, the oneDrive sync details is as follows.
<img width="367" alt="image" src="https://github.com/remotely-save/remotely-save/assets/43390812/83f3de1f-0b03-493e-90d1-65fcd6d6b059">

So it seems that remotely-save is doing the right thing, but the problem is ob will regenerate config files every time, is there any solution with this problem? Thanks a lot for your attention!

### What OS are you using?

macOS, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.12

### Version of Obsidian

1.6.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
like you said, the plugin actually doesn't know which one is right except by checking modified time. 

I suggest manually sync once, or keep different config dir for different devices

**Comment by mambalong** [comment]
> like you said, the plugin actually doesn't know which one is right except by checking modified time.
> 
> I suggest manually sync once, or keep different config dir for different devices

My point is that in this case, the configuration actually doesn't sync, which doesn't meet the expected functionality.

**Comment by fyears** [comment]
i don’t understand. could you note down a timeline which machine is triggered and which machine’s files are uploaded or not uploaded?

**Comment by mambalong** [comment]
> i don’t understand. could you note down a timeline which machine is triggered and which machine’s files are uploaded or not uploaded?

Sorry for the late reply. I changed my setup a little bit.
# Setup
- Use iPhone to create a vault and save it to the local. Use oneDrive to sync.
- On mac, create a vault with the same name and use remotely-save to connect to onDrive.
# Problem
I set the sync config file option to "enable". And here I will use changing the themes as example. The ob apps on mac and iPhone are closed.
- On mac, I launch the app, then I change the themes to be "Obsidian Nord", then use remotely-save to sync. As shown in the sync plans, the "appearance.json" file is pushed to remote. 
[mac_sync_plans_hist_exported_on_1720069210870.md](https://github.com/user-attachments/files/16093545/mac_sync_plans_hist_exported_on_1720069210870.md)
And in oneDrive, "appearance.json" is changed to "Obsidian Nord"
![image](https://github.com/remotely-save/remotely-save/assets/43390812/cee980aa-7606-4178-9424-dc7c45a155a7)
- On iPhone, I launch the app, remotely-save starts auto-sync, in the sync plan, the decision for "appearance.json" is "conflict_modified_then_keep_local", and the "appearance.json" in oneDrive change back to "Atom". **So my settings on the Mac haven't taken effect.**
[iphone_sync_plans_hist_exported_on_1720069513429.md](https://github.com/user-attachments/files/16093605/iphone_sync_plans_hist_exported_on_1720069513429.md)
![image](https://github.com/remotely-save/remotely-save/assets/43390812/b1abbd52-65f2-4ee0-8245-e0c8d7c3e323)
- Then back to mac, use remotely-save to sync, and reload the app, **the themes change back to "Atom"**. And the sync plan says that the decision is "local_is_modified_then_push", but in fact, apart from the initial modification, I haven't made any other changes.
[mac_sync_plans_hist_exported_on_1720069993378.md](https://github.com/user-attachments/files/16093648/mac_sync_plans_hist_exported_on_1720069993378.md)

**Comment by fyears** [comment]
I tested on my machine (Windows) and find out that each time opening Obsidian the file `.obsidian/appearance.json`'s modified time is changed!

So yeah that's annoying and actually destroys the assumption of modified time being reliable. I am sorry but the plugin doesn't deal with this situation by design.

If you have a robust algorithm I would be happy to evaluate it.

**Comment by mambalong** [comment]
> I tested on my machine (Windows) and found out that each time opening Obsidian the file `.obsidian/appearance.json`'s modified time is changed!
> 
> So yeah that's annoying and actually destroys the assumption of modified time being reliable. I am sorry but the plugin doesn't deal with this situation by design.
> 
> If you have a robust algorithm I would be happy to evaluate it.

Yes, I noticed that some configuration content didn't change, but the modification time did, which caused the configurations to not sync between devices. Maybe comparing the content of the files is a solution, but I'm not an expert in this area; it's just a suggestion.

Actually, I'm happy that this issue has been confirmed by you. I previously asked in a WeChat group, and everyone said the configurations could sync normally, so I was quite confused. Because according to the sync principle of the plugin, this is impossible.

Anyway thank you for your time.
