### ISSUE TITLE
[Bug]: 坚果云同步出错

### ISSUE THREAD

**Issue by epleone** [remotely-save/remotely-save#733]
### What happened?

最近几个月，使用`remotely-save` 同步到坚果云总提示503 service Unavailable。尝试了网上很多设置，都没有成功过。只有挂VPN，才能正确同步。

怀疑可能是IP被封，但在不挂VPN的情况下，同一台电脑可以正常同步Zotero到坚果云， 这貌似说明不是IP的问题。

后面我联系了坚果云的客服，她说我的账号状态正常。按照她的提示，在坚果云的`账户信息`- `安全选项` - `第三方应用管理` 中删除了obsidian的应用授权，重新开了一个新的授权用于同步。

这次重新使用`remotely-save` 可以正常同步到坚果云，第一次同步成功了。 但是当我隔了一个小时，第二次点击同步时，又开始提示503 service Unavailable， 这期间我的修改非常少。这个是否说明bug应该和坚果云的上传限制无关？

之前的issue被关闭了，我觉得这个bug值得再开一个issue.
同样的，这个问题也有其它网友出现过，比如[这里](https://forum-zh.obsidian.md/t/topic/34339) 。

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (坚果云 JianGuoYun/NutStore)

### Version of the plugin

最近几个月的插件都存在问题

### Version of Obsidian

1.6.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
这个插件每次会读取坚果云的列表，即使没有变更，也需要读一次列表，才能知道没有变更。期间会消耗坚果云的 api 额度。

你想想，一次可以连上，一次坚果云返回 503，这里插件做的代码都是相同的，所以显然就是服务器限制了。同理，换 vpn 就好了也是同样的道理。你可以试试一个手机在 4g 遇到限制后，换成 wifi 试试，应该就好了。

同理，可以换成 infinicloud 试试有没有同样的症状。

**Comment by epleone** [comment]
@fyears 感谢及时解答。

换成 infinicloud ，不会报503，会触发保护，提示超过99%的文件会被修改。

**Comment by fyears** [comment]
把infini上面的已有文件删除就不会触发变更保护了

**Comment by epleone** [comment]
> 把infini上面的已有文件删除就不会触发变更保护了

@fyears 抱歉，没有搞清楚这步应该怎么操作。是指重设本地缓存和数据库吗？

**Comment by fyears** [comment]
> 换成 infinicloud ，不会报503，会触发保护，提示超过99%的文件会被修改。


这样吧：

1.手动备份到别的地方
2.去掉保护触发一次同步
3.打开保护

这样之后的同步应该正常了
