### ISSUE TITLE
[Feature Request]: Custom HTTP Headers

### ISSUE THREAD

**Issue by lutzky** [remotely-save/remotely-save#735]
### What feature are you suggesting?

I'd like to be able to set custom extra HTTP headers.

My use-case: I self-host my vaults on WebDAV, and it works well within my network. My preferred way of giving myself access from outside the network is using Cloudflare Zero Trust. This will require setting the `CF-Access-Client-Id` and `CF-Access-Client-Secret` HTTP headers; see https://developers.cloudflare.com/cloudflare-one/identity/service-tokens/.

### What remote cloud services are you using, or suggesting adding the feature to?

webdav, webdav (rclone webdav)

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
are these headers static?

**Comment by lutzky** [comment]
About as "static" as the username and password. I wouldn't need to change them often, and they'd be identical between my machines, but different users (i.e. people who are not me) would need different values. Not sure if that counts as "static".

**Comment by fyears** [comment]
yeah, i mean what you mean. if the values are dynamically changed then it's impossible to add them in plugin settings.

i will check how to support this feature in near future.

and you are strongly welcome to contribute a tutorial about how to configure custom webdav and cloudflare zero trust. :-) i have heard of it but never tried it. it's especially useful to those who want to add https support to homelab webdav

**Comment by lutzky** [comment]
Specifically my interest in this project is so I can remove battery hogs such as syncthing from my phone. I wouldn't want to replace it with always-on tailscale 😁

**Comment by lutzky** [comment]
Unfortunately the CLA prohibits me from contributing a pull request directly. I will however let you know that I've written the patch, adding a text field to the UI, parsing it in the webdav code, and attaching the resulting headers to the webdav client (in addition to the cache-control one already present). Attaching the CF-Access-Client-Id and CF-Access-Client-Secret headers to the requests works perfectly.

If you implement this, I can create a tutorial for how to use this - on my blog, which you're welcome to link to. (I'm assuming I can't contribute it directly here, as that would also be bound by the CLA).

**Comment by fyears** [comment]
> Unfortunately the CLA prohibits me from contributing a pull request directly.

May I ask why? You still maintain the full copyright for your contributions under the CLA.

But anyways I respect your decision. And you can wait for my implementation.

**Comment by lutzky** [comment]
My employment contract governs my open-source contributions as well, and although it's comparatively permissive, I am specifically not allowed to sign CLAs that have not been pre-approved with the employer. If this were a substantial patch, the paperwork might be worth it, but I don't think it is, in this case; I suspect that implementing this particular feature would be less work for you than responding to potential queries from company lawyers about the CLA.

**Comment by fyears** [comment]
Please checkout 0.5.13.

**Comment by lutzky** [comment]
Thank you very much, it works beautifully!

**Comment by lutzky** [comment]
In terms of documenting how to use it, cloudflare already did a very good job:

* Follow this thorough guide for "how to grant tunnel access": https://developers.cloudflare.com/learning-paths/zero-trust-web-access/. Notably, you'll be testing out the default flow with a browser, and it won't work with remotely-save.
* Once you're comfortable with the default flow, use https://developers.cloudflare.com/cloudflare-one/identity/service-tokens/ to give remotely-save access. Specifically, it shows you how to create the token, and explains the `CF-Access-Client-{Id,Secret}` keys - and how to test them. Treating every request as the [initial request](https://developers.cloudflare.com/cloudflare-one/identity/service-tokens/#initial-request) works fine, so no extra logic is needed.

This should work with any DAV server, I'm personally using it with `rclone` :shrug: .

**Comment by fyears** [comment]
thanks!
