### ISSUE TITLE
[Bug]: Syncing on Android crashes Obsidian

### ISSUE THREAD

**Issue by jdcaraujo** [remotely-save/remotely-save#736]
### What happened?

When I setup Remotely Save on my laptop it runs smoothly (via WebDAV on a Synology NAS), but when I try to replicate on my Android tablet and my Android phone, after a couple of seconds after the sync Obsidian crashes. 

I've uninstalled the plugin and confirmed it was causing the issue. I've also reset the whole sync setup to see if it would go away, to no avail. 

Happy to provide additional logs / video if needed. 

[sync_plans_hist_exported_on_1720028525178.md](https://github.com/user-attachments/files/16088741/sync_plans_hist_exported_on_1720028525178.md)

### What OS are you using?

Linux, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.5.12

### Version of Obsidian

1.6.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
it looks like you are downloading large files (> 10mb)

unfortunately android / ios obsidian's api has performance issue for downloading large files. no easy way to workaround. believe me i tried... :-(

suggestion: 

1. set ignore large files in mobile remotely save settings
2. manually copy these large files across devices. they should not be modified frequently anyway
3. small files like normal markdown notes or pics should be synced normally
