### ISSUE TITLE
[Bug]: Files could download from webdav server.

### ISSUE THREAD

**Issue by Miclita** [remotely-save/remotely-save#74]
### What happened?

By using remotely save, my pc and WebDav server can sync very well.
While after I built an empty vault and installed remotely-save plugin on my iPad, only the folders were synchronized. 
**[Problem 1]**There is no file in any folder. 

Then I  created a new md file and synchronized it to the WebDav server. This worked well.
**[Problem 2]**When I tried to synchronize this file on my PC, 503 error occurred. Invalid response:503 Service Unavailable.

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.18

### Version of Obsidian

1.1.1(48)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
are you using teracloud? and could you please config the “depth” to “only supports depth=1” and try again?

**Comment by fyears** [comment]
It’s likely to be a problem in depth setting

**Comment by Miclita** [comment]
> are you using teracloud.jp? and could you please config the “depth” to “only supports depth=1” and try again?

Thanks for your reply. I am using jianghuoyun.com. 

I deleted all the files in the WebDav server and the vault on my iPad, and reinstalled the plugin. At this moment, no matter whether I config the “depth” to “only supports depth=1” or not, the 409 conflict error occurred.

**Comment by fyears** [comment]
Can you reproduce the error in another test vault including some test files? do your file names contain emoji? I also tried jianguoyun 坚果云 but could not reproduce the error…

**Comment by fyears** [comment]
Closed because of no reply for a while.
