### ISSUE TITLE
[Bug]: Request failed, status 403 changing Note title

### ISSUE THREAD

**Issue by D1StrX** [remotely-save/remotely-save#740]
### What happened?

Noticing some repetitive behavior on new Notes with a S3 backend. Whenever you change the title of a Note, it returns Request failed, status 403.

I noticed it first with with the experimental `Sync On Save` option. But this issue is also reproducible with `Sync On Save` disabled.
The error is manually triggered/visible when clicking on the `Remote save` button, but under the hood it silently errors 403. I know this for sure, because the changes aren't synced into the S3 bucket. The S3 bucket initially only displays `Untitled.md`, when saved automatically (Or with whatever title you use, save -> change -> save)

### What OS are you using?

Windows, Linux, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (MinIO)

### Version of the plugin

0.5.12

### Version of Obsidian

v1.6.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
are you sure you are configuring s3/minio correctly? status 403 means access denied. it’s usually caused by a misconfiguration on server.

**Comment by D1StrX** [comment]
Absolutely sure. It works perfect with other notes on the S3 backend. Just changing the title triggers this error.

**Comment by fyears** [comment]
can you create another note and write some thing and sync, _then delete and sync_?

renaming files is actually deleting and creating (uploading) new file. i suspect you are denying deletion requests

**Comment by D1StrX** [comment]
Now you mention it... policy didn't have "s3:PutObject" in it. Thanks 👍
