### ISSUE TITLE
[Feature Request]: The data.json file of the plug-in cannot be updated

### ISSUE THREAD

**Issue by bomin8418** [remotely-save/remotely-save#743]
### What feature are you suggesting?

The data.json file of the plug-in cannot be updated. When I modify the plug-in settings on one device, I want it to be synchronized on other devices.

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
please enable syncing config folder option in the plugin setting

**Comment by bomin8418** [comment]
I have turned on the option to synchronize the configuration folder, but it does not take effect. Only if I manually delete data.json will a new file be pulled during synchronization.

**Comment by fyears** [comment]
1. on device A, enable the setting, 
2. on device B, enable the setting manually. have you done this step?
3. on device A, change something, and sync
4. go to onedrive website, does the data.json changed to the latest one?
5. on device B, sync. has the data.json downloaded from onedrive website?
