### ISSUE TITLE
[Bug]: Failed to load plugin "remotely-save"

### ISSUE THREAD

**Issue by Xiaoxuehaimeibiyene** [remotely-save/remotely-save#744]
### What happened?

我从上一个版本更新到这个版本后，无法加载 remotely-save 插件。我尝试过重新下载插件、重启 Obsidian、重启 Windows，还尝试了新建一个 vault 来下载 remotely-save 插件，但都是相同的结果。

我在 Obsidian Developer Console 里我看到了

```
Plugin failure: remotely-save ReferenceError: Request is not defined
    at eval (VM161 plugin:remotely-save:90:393406)
    at eval (VM161 plugin:remotely-save:234:150745)
    at anonymous (VM161 plugin:remotely-save:234:150977)
    at e.<anonymous> (app.js:1:2292461)
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)
(anonymous) @ app.js:1
```

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (InfiniCloud (formally TeraCLOUD))

### Version of the plugin

0.5.13

### Version of Obsidian

1.6.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
obsidian 在官网重新下载然后覆盖安装一下后试试？

**Comment by Xiaoxuehaimeibiyene** [comment]
> obsidian 在官网重新下载然后覆盖安装一下后试试？

覆盖安装 Obsidian 后问题解决了，感谢 fyears
