### ISSUE TITLE
[Bug]: I am getting a looped duplicate of my current vault being created with each sync until sync fails.

### ISSUE THREAD

**Issue by realizetm** [remotely-save/remotely-save#745]
### What happened?

I changed my vault via file manager, opened and renamed it via Obsidian (and confirmed in file manager) and now I am getting duplicate, looped vaults being created inside my top level vault.

This is new behaviour and I didn't knowingly change any of my settings. I moved the .obsidian/plugins folder to the new vault and all my settings looked to match what was there previously when I checked and turned the plugin back on.

I can, with Obsidian closed, delete the newly created duplicate vault folder inside my vault via file manager (it isn't visible inside Obsidian). It seems each "loop" it saves to the top level folder. upon subsequent saves it will create the folder and save a duplicate of the vault, keep dropping down another level each save, increasing the total files syncing. This takes an increasing amount of time as it's not just syncing what is changed, but the entire vault, multiple times.

### What OS are you using?

macOS

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.5.14

### Version of Obsidian

1.6.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by realizetm** [comment]
i removed the data at the top level, and just left the secondary folder. now it's failing to sync but it's not creating any more duplicate folders.

**Comment by fyears** [comment]
could you please export the sync plan and check what happened?

**Comment by realizetm** [comment]
hi, I found a way to export it the plan but then... I realized that I was syncing to Yandex AND saving to Yandex, so it was doing both. I moved my vault to another folder then opened it from there and it seems to be syncing fine now. I expect the folder was getting a little too much action with the double syncing... so user error (not a bug).
