### ISSUE TITLE
[Bug]: Graph View Groups Don't Sync

### ISSUE THREAD

**Issue by Tartarus6** [remotely-save/remotely-save#746]
### What happened?

I am syncing through an S3 compatible service.

After enabling config and hidden directory syncing, the groups for the graph view still don't sync. The created groups do not show up on newly synced devices, and do not update on devices with groups already.

### What OS are you using?

Linux

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (MinIO)

### Version of the plugin

0.5.14

### Version of Obsidian

1.6.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> the groups for the graph view still don't sync. 

do you know where does this info stored?

**Comment by Tartarus6** [comment]
i do not. ill look into it right now

**Comment by Tartarus6** [comment]
I believe its stored in `.obsidian/graph.json`. so it should be enabled when config is synced.

**Comment by fyears** [comment]
please try to go to minio management and see if this file is there after a sync

also please make sure that you haven't ignored this file in settings

also please consider upgrading the minio to latest version. some user reported the weird bug of minio before

**Comment by fyears** [comment]
I am sure the `.obsidian/graph.json` can be synced normally if you enable syncing config dir. may be obsidian needs restart to load the synced graph data.
