### ISSUE TITLE
[Bug]: Smart Conflict 

### ISSUE THREAD

**Issue by nallebrean** [remotely-save/remotely-save#749]
### What happened?

When two files are changed I got files where every word are on a new line. 

![image](https://github.com/user-attachments/assets/3a5925b9-a354-471c-9d2a-0226ac187bda)

version 0.5.14

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.14

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
can you reproduce this consistently?

can you upload two files before merge into here?

**Comment by nallebrean** [comment]
[Testfile 3 finale file.md](https://github.com/user-attachments/files/16248184/Testfile.3.finale.file.md)
[Testfile 1 Start file.md](https://github.com/user-attachments/files/16248185/Testfile.1.Start.file.md)
[Testfile 2 Android.md](https://github.com/user-attachments/files/16248186/Testfile.2.Android.md)
[Testfile 2 win.md](https://github.com/user-attachments/files/16248187/Testfile.2.win.md)

Test steps:

1. Created the file on the computer.
2. Let the file sync to both the computer and phone via OneDrive.
3. Enabled airplane mode for 0 sync.
4. Added a line in both devices.
5. Copied the files to new names in the repository tree.
6. Synced the computer.
7. Synced the phone and the file got corrupted.
8. Synced to the computer and the corrupted file got copied. I assume it simply goes by time then.

**Comment by TechJack78** [comment]
Happens with number lists too
![Screenshot 2024-07-24 014638](https://github.com/user-attachments/assets/3d656cc6-9a0a-43cc-9e20-899fe5dffce1)
![Screenshot 2024-07-24 014709](https://github.com/user-attachments/assets/5ad9c75a-97f6-4eae-b9d1-0685cfd790dc)

**Comment by fyears** [comment]
please checkout 0.5.15

**Comment by nallebrean** [comment]
This is better but should it look like this with the arrow and equal
letters?

Den lör 27 juli 2024 13:39fyears ***@***.***> skrev:

**Comment by fyears** [comment]
yes because we have to note down what changed
