### ISSUE TITLE
[Bug]:  Failed to load plugin remotely-save on IOS Device.

### ISSUE THREAD

**Issue by leeh11** [remotely-save/remotely-save#75]
### What happened?

我是一个obsidian新用户，MacOS上面启动插件，配置S3，同步等功能都正常。IOS设备启动失败，报如下错误：
![WechatIMG192](https://user-images.githubusercontent.com/24563847/162915974-2e4b0bc8-1703-48f0-8910-d60d18dcd3e8.jpeg)

请帮忙分析一下，不吝感激。

IOS版本：14.4

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.18

### Version of Obsidian

1.2.0

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
无法复现……你能安装其他插件吗？

**Comment by leeh11** [comment]
可以安装其他插件，刚刚装了一个markmind.

obsidian的插件有log日志吗？刚开始使用， 不太熟悉。

![WechatIMG194](https://user-images.githubusercontent.com/24563847/162948645-72715bb3-f735-4ac4-bc4e-45ec14962598.jpeg)

**Comment by leeh11** [comment]
我昨天晚上更新ios15.4后插件就能启动了，我怀疑是obsidian软件的兼容问题。非常感谢。

**Comment by fyears** [comment]
谢谢反馈！这一个原因，我还真的没想到！捂脸

**Comment by Zayia** [comment]
ios14.3无法启动插件

**Comment by fyears** [comment]
@Zayia 不好意思，没有测试条件，可以更新系统后试试？

**Comment by slimx** [comment]
希望能解决这个问题 在不升级系统的前提下

**Comment by Amcio** [comment]
It would be great if this could be solved without updating the system

**Comment by ffxung** [comment]
ipad的IOS14.4系统,也是一样的问题, 请解决~   谢谢  因为是老设备了,不方便升级系统

**Comment by mxziino** [comment]
i have the same problem on ios

**Comment by yufanme** [comment]
iphone xs 14.4系统 也没办法开启 估计不支持15以下系统

**Comment by ngousan** [comment]
是缺少main.js。

**Comment by aidoit** [comment]
> 是缺少main.js。

在插件社区里下载的压缩包解压后确实没有这个文件，感谢。

**Comment by hycinthyyl** [comment]
> > 是缺少main.js。
> 
> 在插件社区里下载的压缩包解压后确实没有这个文件，感谢。

所以应该怎么解决？我也面临着这个困难

**Comment by aidoit** [comment]
> > > 是缺少main.js。
> > 
> > 
> > 在插件社区里下载的压缩包解压后确实没有这个文件，感谢。
> 
> 所以应该怎么解决？我也面临着这个困难

下载 https://github.com/remotely-save/remotely-save/releases/download/0.3.25/main.js 手动添加到插件目录里。

**Comment by D-Q-B** [comment]
安卓最新版的也有这个问题，而且我检查了安装目录，有main.js这个文件
![S30312-10395505](https://user-images.githubusercontent.com/105706321/224521215-6c305651-6477-4f0d-80d8-98a011e8f626.png)

![Uploading S30312-10402819.png…]()

**Comment by hoey94** [comment]
所以是怎么解决了？

**Comment by hoey94** [comment]
我的iphone7在ios13.6.1 版本，也发现了这个问题，采用升级ios的方式解决问题不友好，因为升级系统以后，iphone可能变成板砖...希望作者能兼容历史ios版本。兼容到ios 13版本就可以了，因为iphone6现在都没人用了。。。

**Comment by suibianzai** [comment]
> @Zayia 不好意思，没有测试条件，可以更新系统后试试？

大佬能否考虑支持一下ios14？旧设备现在升级的话会很卡 我是ipad mini5 ios14 安装完插件后点选enable也是提示“failed to load plugin remotely-save”

**Comment by fyears** [comment]
> > @Zayia 不好意思，没有测试条件，可以更新系统后试试？
> 
> 大佬能否考虑支持一下ios14？旧设备现在升级的话会很卡 我是ipad mini5 ios14 安装完插件后点选enable也是提示“failed to load plugin remotely-save”

不好意思，没有旧设备，无法开发和测试
