### ISSUE TITLE
[Bug]: Can't sync my one drive.

### ISSUE THREAD

**Issue by Michael679089** [remotely-save/remotely-save#752]
### What happened?

Well I set my vault name to the same name of the Sync in the OneDrive because that's what the modal told me to when I try to change the string in the vault text input box.

This is the image, I got an error:

![image](https://github.com/user-attachments/assets/e075ba30-f13e-47a5-ae83-c93c56fc85e7)

The Structure is simple. Projects, Areas, Resources, Journals. Archives isn't included because it's from my Google Drive.

### What OS are you using?

Windows, macOS, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.14

### Version of Obsidian

1.6.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
do you have node_modules inside onedrive website?

**Comment by fyears** [comment]
close due to no response
