### ISSUE TITLE
设置组合同步逻辑

### ISSUE THREAD

**Issue by fooltal** [remotely-save/remotely-save#756]
### What feature are you suggesting?

大佬你好，后续您是否考虑设置保存组合逻辑，比如我启用了保存时同步逻辑，当我处于连续编辑状态下可能连续编辑了一小时，假设1秒同步一次1小时就是3600次。能否设置系统检测最近1分钟或更多如果连续同步10次或更多就启用几分钟（比如1分钟）保存1次逻辑，这样1小时同步次数就能变成10+60（或59次）。在隔一段时间检测用户有没有连续编辑，比如1分钟检测发现用户没有连续编辑了，可能用户做几个小时其他事情这样就可以省心了，这样就能减少次数，减少不少流量请求费用啥的。

### What remote cloud services are you using, or suggesting adding the feature to?

S3 (腾讯云 COS Tencent Cloud COS)

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
建议用定时同步哈
