### ISSUE TITLE
[Bug]: Webdav Mandarin username not support

### ISSUE THREAD

**Issue by leokt** [remotely-save/remotely-save#757]
### What happened?

wanted to connect my webdav drive with mandarin username in obsidian，but not supported like this 

![image](https://github.com/user-attachments/assets/f200f211-bc55-42fe-b472-aa347b5a1273)

Any ideas? 

Much appreciated.

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (ownCloud)

### Version of the plugin

0.5.14

### Version of Obsidian

1.6.5

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by leokt** [comment]
By the way, my username and pwd are correct, I have connected in raidrive.

**Comment by fyears** [comment]
账号和密码都是中文？确实没测试过

**Comment by leokt** [comment]
Only usrname is mandarin，not pwd

**Comment by fyears** [comment]
will be fixed in version >= 0.5.15 released on Sunday
