### ISSUE TITLE
[Bug]: failed to sync after updating

### ISSUE THREAD

**Issue by PYH1107** [remotely-save/remotely-save#758]
### What happened?

I've tried to turn off all my community plugins but the error remains.
It keeps telling me "cannot read properties of undefined."
![image](https://github.com/user-attachments/assets/b0322770-9ace-4491-83e9-8353da2c3722)

Things went well before i updated it to the latest version.
However, it showed that i can no longer sync my files within 10 minutes and the only thing i've done is updating remotely-save.

---
(though i'm struggling with it right now, thank you for developing such great plugins. 
Hope everything goes well, tks)

### What OS are you using?

both Windows and iOS

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.14

### Version of Obsidian

1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
can you try directly downgrade the plugin (by downloading the older version, and put it into .obsidian/remotely-save) and try again?

**Comment by fyears** [comment]
and are you using OneDrive for Business?

**Comment by fyears** [comment]
still no idea why the mtime is not presented...

but please upgrade to 0.5.15 and see the more detailed error hint

**Comment by fyears** [comment]
close due to no response
