### ISSUE TITLE
[Bug]: redirection back to app after dropbox auth not working

### ISSUE THREAD

**Issue by Pra3t0r5** [remotely-save/remotely-save#759]
### What happened?

Expected that, after granting permissions on Dropbox, the direction to the app would complete auth process of the extension.

Look at the video:
[Screen recording 2024-07-21 15.51.25.webm](https://github.com/user-attachments/assets/e7ea3639-b844-470c-be9f-493f5c9bf62d)

Recorded on HP x2 11 Chromebook: Versión 127.0.6533.50 (Build oficial) beta (64 bits)

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

0.5.14

### Version of Obsidian

1.6.5 (147)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
some users report the same bug before. it looks like it's an issue of the obsidian app and chromeos

but sorry i do not have chromebook to debug.


don't worry, you can auth dropbox on windows/mac or another device and import the setting to your chromeos obsidian remotely save

**Comment by Pra3t0r5** [comment]
I could give you TeamViewer/AnyDesk/VNC access to check the issue if you desire to understand the issue 👍
