### ISSUE TITLE
regex issue

### ISSUE THREAD

**Issue by Barmaid1076** [remotely-save/remotely-save#761]
### What happened?

我试图忽略除文件夹 AAA 和文件夹 BBB 之外的所有内容，因此我使用了以下正则表达式：
```
^(?AAA/).* 
^(?!BBB/).*
```
但插件没有同步任何内容。

然而，`^(?*(AAA|BBB)/).*` 可以完美地工作，它只同步这两个文件夹中的文件。

很想知道为什么会有这种情况发生，十分感谢！！！

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

latest

### Version of Obsidian

latest

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
请在 https://regex101.com 检查一下呢。

第一个 regex 显示语法错误

**Comment by fyears** [comment]
第二个的斜杠其实也需要转义

**Comment by Barmaid1076** [comment]
> 第二个的斜杠其实也需要转义

谢谢!

**Comment by Barmaid1076** [comment]
啊，我好像知道了
regex中是不允许换行符吗
我以为换行就等于新的一个regex 也需要match

**Comment by Barmaid1076** [comment]
我现在在regex to ignore之中填入
```
^(?!AAA\/).*
^(?!BBB\/).*
```

还是没有办法同步这两个文件夹

但是如果我只在其中填入`^(?!AAA\/).*` 或者 `^(?!BBB\/).*`, 那么同步其中一个文件夹是可以的

请问应该如何同时同步两个文件夹并且不使用 `^(?!（AAA|BBB)\/).*` 呢？

**Comment by fyears** [comment]
这时候，是不是其实搞一个白名单比较好？

**Comment by fyears** [comment]
可以考虑

**Comment by fyears** [comment]
> 但是如果我只在其中填入^(?!AAA\/).* 或者 ^(?!BBB\/).*, 那么同步其中一个文件夹是可以的
> 请问应该如何同时同步两个文件夹并且不使用 ^(?!（AAA|BBB)\/).* 呢？

目前是做不到的。你拆开两行，它判断是满足任意一行则进入黑名单。因此，会造成所有文件夹都命中黑名单了（满足一个则不满足另一个）

只能混在一起写

**Comment by Barmaid1076** [comment]
> > 但是如果我只在其中填入^(?!AAA/).* 或者 ^(?!BBB/)._, 那么同步其中一个文件夹是可以的
> > 请问应该如何同时同步两个文件夹并且不使用 ^(?!（AAA|BBB)/)._ 呢？
> 
> 目前是做不到的。你拆开两行，它判断是满足任意一行则进入黑名单。因此，会造成所有文件夹都命中黑名单了（满足一个则不满足另一个）
> 
> 只能混在一起写

原来是这样，好的！

**Comment by Barmaid1076** [comment]
> > 但是如果我只在其中填入^(?!AAA/).* 或者 ^(?!BBB/)._, 那么同步其中一个文件夹是可以的
> > 请问应该如何同时同步两个文件夹并且不使用 ^(?!（AAA|BBB)/)._ 呢？
> 
> 目前是做不到的。你拆开两行，它判断是满足任意一行则进入黑名单。因此，会造成所有文件夹都命中黑名单了（满足一个则不满足另一个）
> 
> 只能混在一起写

freeefilesync 好像就是弄完一个黑名单和一个白名单，然后放在白名单里面的东西就算被放到了黑名单里面是一直都会被同步的，也许可以参考一下

**Comment by fyears** [comment]
理解成本比较高，还是只保留黑名单吧。也即保持现状
