### ISSUE TITLE
[Bug]: png:request failed,status 403

### ISSUE THREAD

**Issue by frja1234** [remotely-save/remotely-save#764]
### What happened?

the png not save

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.5.14

### Version of Obsidian

1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by frja1234** [comment]
图片同步失败，大小尺寸都不行

**Comment by fyears** [comment]
上传失败，还是下载失败，还是覆盖写入失败，还是删除失败？

**Comment by fyears** [comment]
请更新到最新版，用设置里的检测连接，试一下。

**Comment by fyears** [comment]
因为没有响应，先关闭了
