### ISSUE TITLE
[Bug]: webdis "you should not call getOrigEntity on..."

### ISSUE THREAD

**Issue by maxiride** [remotely-save/remotely-save#767]
### What happened?

I've firstly installed the plugin on Windows and synced successfully the vault.

I then installed it on Android and performed a sync with no issue, later I decided to rename the vault on PC and to keep everything on sync correctly I thought to rename it the same way on mobile too.

However, whenever I sync (both from mobile and PC) I get the error below, like if there is some "memory" of the original vault name that keeps being prefixed to the error message (deleted in the screenshot)

![IMG_20240727_184313](https://github.com/user-attachments/assets/af61ba6f-697d-4596-8578-e6554dab6ccf)

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

others
Webdis

### Version of the plugin

0.5.16

### Version of Obsidian

1.6.7 (mobile)

### Using password or not

- No

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
do you mean changing the vault name directly on obsidian?

and is the redis key (in your screenshot) the one before rename or after?

and please be aware that the plugin actually doesn't support rename, so all data will be uploaded again normally.

**Comment by fyears** [comment]
i think i know what happen. i forget to deal with multi vault. the bug will be fixed in 24 hours.

however, the old vault name keys are not removed automatically. so you can directly remove them manually and get around the bug now.

**Comment by fyears** [comment]
fixed in 0.5.17

**Comment by maxiride** [comment]
> do you mean changing the vault name directly on obsidian?

Yes I renamed the vault in obsidian.

> and is the redis key (in your screenshot) the one before rename or after?

The key in the screenshot, which is the key the plugin was working with was the **before** key

> and please be aware that the plugin actually doesn't support rename, so all data will be uploaded again normally.

That was my understanding, indeed I expected a fresh new push to happen, but the behaviour observed was that the plugin was still using the old vault name as a key.

> however, the old vault name keys are not removed automatically. so you can directly remove them manually and get around the bug now.

Yep, manually nuked the key in redis and everything got back working as expected.

---

Thanks for the prompt reply and everything!
