### ISSUE TITLE
[Bug]: request failed,status 400

### ISSUE THREAD

**Issue by qinwangs** [remotely-save/remotely-save#768]
### What happened?

onedrive（个人版）
插件更新到最新版了
鉴权时提示：onedirve的回调请求有些异常
但是我确认我点的是继续
并且插件页面也有您已作为用户xx连接上了
之后点击检查可否连接提示：
我们未能连接上onedrive
request failed,status 400

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
手机有配置链接吗？手机连接成功的话，可以手机导出电脑导入试试

**Comment by qinwangs** [comment]
手机之前是可以的，但是现在也提示400

**Comment by fyears** [comment]
本地删除鉴权，onedrive 官网也删除鉴权，然后用 vpn  的话换一个节点，从头重新鉴权试试呢

**Comment by RehemChan** [comment]
> 本地删除鉴权，onedrive 官网也删除鉴权，然后用 vpn 的话换一个节点，从头重新鉴权试试呢

你好, 我遇到了相同的问题, 然而尝试重新鉴权或更换节点均不起作用
下面是一些截图, 希望能能够提供帮助
![image](https://github.com/user-attachments/assets/1df12fd0-a80b-47c4-bec4-facc89864bff)
![image](https://github.com/user-attachments/assets/ba313ba5-e98e-454f-bb63-160ce08c1c16)
![image](https://github.com/user-attachments/assets/1d487e51-42f5-4117-be26-8066a4b95f40)

实际上测试文件夹已经创建成功(但文件夹内容为空)
![image](https://github.com/user-attachments/assets/78a14e16-19c8-4df3-b02e-c8cd4fd17f77)

**Comment by pablogila** [comment]
I confirm to have the exact same error 400 with OneDrive Personal since the last update. It first started on my PC, now it is also my phone and tablet.

I also tried synthing with DropBox and a different error happened, though seems related:
DropboxResponseError: Response failed with a 409 code.

Test folders were also created on the vault with OneDrive, yet not with DropBox.

**Comment by RehemChan** [comment]
> Update: **downgrading** to v0.5.14 fixes all connections.

It works on my device as well.

**Comment by fyears** [comment]
@pablogila @RehemChan 

let me have a quick fix in 24 hours

**Comment by fyears** [comment]
@pablogila @RehemChan @qinwangs 

Hi 

1. please upgrade to 0.5.18 for the fix.
2. the bug should only affect "check connectivity".
    * the plugin tries to upload a randomly-named folder `rs-testfolder-xxx` and file `rs-testfile-yyy` to see if it can actually upload and download. 
     * no other way, nor the sync, should be affected.
     * you can delete the created-but-not-removed folder `rs-testfolder-xxx` and file `rs-testfile-yyy` manually on onedrive website.
     * then "check connectivity" again.

**Comment by pablogila** [comment]
Works fine now! Thanks :D

**Comment by RehemChan** [comment]
> 1. please upgrade to 0.5.18 for the fix.

更新后工作正常, 感谢!

**Comment by lr0513** [comment]
我的Remotely-Save 插件（0.5.25 版本）出现电脑端显示同步成功、手机端报 400 错误的问题：先重启电脑端 Obsidian，通过 ctrl+shift+I 打开控制台检查无报错，随后对手机端重新鉴权，鉴权操作成功完成。
