### ISSUE TITLE
[Bug]:  Syncing error: abort sync, triggerSource=manual, error while syncing

### ISSUE THREAD

**Issue by leeh11** [remotely-save/remotely-save#77]
### What happened?

同步出错了。 我在MacOS上面新建了2个文件夹，每个文件夹里有5~6个文件，根目录下也有几个文件，同步上传一切正常；但是手机同步下载的时候出错了，手机端是一个空仓库，同步过程中断，只有部分文件同步过来了。

看log我感觉好像是时间戳的问题？

![WechatIMG197](https://user-images.githubusercontent.com/24563847/163076440-ad528672-4561-492e-852f-f86fa5777dc5.jpeg)

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.18

### Version of Obsidian

1.2.0

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by leeh11** [comment]
神奇了，我刚刚又尝试同步一次，竟然成功了，今天我多测试几次，如果没复现这个bug我就关掉了。

**Comment by fyears** [comment]
你是不是有些大文件，上传卡住了，上传时间太久。

重新同步没问题的话那应该是没问题了，这个插件本次没有同步的文件，下次会继续同步，只要中间没有更改文件的话就不怕中断的。

**Comment by leeh11** [comment]
确实有几个大文件，非常感谢！

**Comment by leeh11** [comment]
这个问题又复现了，我在用手机编辑一个文档后同步，也报同样的错误了，这次的文件很小，应该不是大文件导致的。间隔几个小时候再尝试同步依然报错。
![WechatIMG200](https://user-images.githubusercontent.com/24563847/163321676-a7024358-f915-439f-addb-6bfad4dc551f.jpeg)

**Comment by fyears** [comment]
你的 s3 是什么服务？

**Comment by fyears** [comment]
目前看来，就是本地时间是5:42但是服务器时间3:50所以出错了

**Comment by leeh11** [comment]
是的， 我用的甲骨文的对象存储，支持S3协议， 并不是自己的服务器，不知道哪里能看到或者设置服务时间。

我用的是韩国的服务器， 要是有1个小时的时差倒是合理，但是看时间差都两个多小时了，感觉又不是时区导致的。

我刚刚又同步成功了，感觉很迷惑。

**Comment by leeh11** [comment]
我刚刚又测试了一次， 在同步成功后过半个小时再次同步，就会报错，本地时间和服务器时间间隔了半个小时。

感觉像是软件记录了我的第一次请求信息，并用第一次请求的信息再次同步数据， 导致请求时间和当前时间不一致。

**Comment by leeh11** [comment]
经过长时间测试发现，请求时间(Request Date)和当前时间(current time)相差3个小时候，就可以同步了。而且同步后十几分钟内编辑文档都可以正常同步。

**Comment by fyears** [comment]
> 感觉像是软件记录了我的第一次请求信息，并用第一次请求的信息再次同步数据， 导致请求时间(Request Date)和当前时间(current time)不一致。而且每次操作同步，这个时间差都在增加。增加的时间和我操作同步按钮的时间间隔一致。

如果这样说的话，应该是杀掉 obsidian 进程然后重启就好了，可以试试？

此外你的测试都是手动同步吗？

我这边也查查怎么回事，不过老实说我也很迷惑，代码层面上，每次同步请求应该都是独立的，没有复用上次同步的信息的。

**Comment by fyears** [comment]
此外你这里能看得出是上传还是下载出问题的吗？

**Comment by leeh11** [comment]
> > 感觉像是软件记录了我的第一次请求信息，并用第一次请求的信息再次同步数据， 导致请求时间(Request Date)和当前时间(current time)不一致。而且每次操作同步，这个时间差都在增加。增加的时间和我操作同步按钮的时间间隔一致。
> 
> 如果这样说的话，应该是杀掉 obsidian 进程然后重启就好了，可以试试？
- 试过杀掉进程，问题依旧。
> 
> 此外你的测试都是手动同步吗？
- 手动同步
> 
> 我这边也查查怎么回事，不过老实说我也很迷惑，代码层面上，每次同步请求应该都是独立的，没有复用上次同步的信息的。
> 
> 此外你这里能看得出是上传还是下载出问题的吗？
- 出问题都是上传的过程中。

我好像发现问题出在哪了，我之前的操作是编辑文档后没有点击保存，而是直接划出左侧操作栏，点击同步按钮。这时就会出现上述问题。

我再尝试先保存文档，然后再同步，目前为止没有发现问题，我测试了几分钟后编辑，十几分钟后编辑，再保存后同步，都没有报错。

我会继续测试，确认一下是不是这个问题。

**Comment by fyears** [comment]
> 试过杀掉进程，问题依旧。

从概念上，如果，你所说的“…时间累积…”的猜想是真的话，杀掉进程，那么插件的一切同步必然是从头来过（包括所有本地时间的判断）。然后你说的问题依旧，那么就很有可能是服务器端的问题了？

> 我再尝试先保存当前文件，然后再同步，目前为止没有发现问题

这……不合理啊。解释一下插件的原理，就是它每次都读取本地的所有文件列表，和s3的所有文件列表，然后对逐个文件，对比最后修改时间。如果你修改了一个文件，但是没有保存的话，那么很大概率就是，插件读取到的文件修改时间没有更新，那么顶多就是不会判断出“此文件需要上传”的决定，而已……

当然，也有可能是每次手动保存了文件之后，obs 内获取时间戳的功能才变正常，这个是有可能的，但是较难证实了……

此外 obs 应该是每隔几秒（一秒？）自动保存。

**Comment by leeh11** [comment]
经过你的分析，我又想起一个细节，我一直编辑的文档是脑图插件 markmind rich模式下的脑图，会不会是markmind脑图文件在自动保存这里有一些未知的bug。

我做了几次普通文本文件直接同步操作，没复现bug。

**Comment by leeh11** [comment]
普通文本也复现这个bug了，而且在复现这个bug后我操作保存再同步，问题依旧；杀掉进程再保存后同步，问题依旧。

**Comment by fyears** [comment]
此外方便的话，换个 s3 服务商试一下（用个测试vault）？比如说 backblaze 提供了免费额度

**Comment by leeh11** [comment]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/24563847/163515228-622ecb76-9def-470d-951d-6e1cae23670a.png">
时间戳看起来没问题。

而且我刚刚测试普通文本在保存后同步，也出错了， 我现在彻底懵了，我换个S3服务商试一下吧。

**Comment by fyears** [comment]
你好，另一位用户遇到类似问题，我修改了代码，每次请求都重设一下背后的参数，似乎避免了请求过期的问题。

可以尝试一下手动下载这里的 `my-dist.zip` ，解压，用里面的 `main.js` 覆盖掉现网的 `main.js`，再尝试一下？

**Comment by fyears** [comment]
一切正常的话，那就继续用最新版+b2即可了（据论坛网友反馈，腾讯云和阿里云也是支持的）……至于甲骨文这里，我没有测试资源，暂无法排查

**Comment by leeh11** [comment]
> 你好，另一位用户遇到类似问题，我修改了代码，每次请求都重设一下背后的参数，似乎避免了请求过期的问题。
> 
> 可以尝试一下手动下载这里的 `my-dist.zip` ，解压，用里面的 `main.js` 覆盖掉现网的 `main.js`，再尝试一下？

我在哪里获得`my-dist.zip`，抱歉没找到。

**Comment by fyears** [comment]
抱歉，忘记了回复，当初说的是这个特殊版本，需要手动替换。

https://github.com/remotely-save/remotely-save/actions/runs/2180555194

**Comment by leeh11** [comment]
> 抱歉，忘记了回复，当初说的是这个特殊版本，需要手动替换。
> 
> https://github.com/remotely-save/remotely-save/actions/runs/2180555194

我替换了这个版本后，目前工作正常。

但是这个版本我发现了一个bug， 就是删除文件的时候删除操作在两台设备间不会同步。
具体步骤是，我在手机端删除一个文件，同步后手机端文件删除了，但是我在电脑端点击同步按钮，文件还在；这时候我再点击手机端的同步按钮，删除的文件又回来了。

**Comment by fyears** [comment]
原 bug 问题，请问你用回了甲骨文也正常吗？还是说仅仅是b2 正常？

同步问题，有可能是电脑端编辑了文件？按照最后编辑时间判断的。可以导出 sync plan 看看 mtimelocal 和 deltimeremote 两个字段是否 mtimelocal 正常了。

**Comment by leeh11** [comment]
> 原 bug 问题，请问你用回了甲骨文也正常吗？还是说仅仅是b2 正常？
> 
> 同步问题，有可能是电脑端编辑了文件？按照最后编辑时间判断的。可以导出 sync plan 看看 mtimelocal 和 deltimeremote 两个字段是否 mtimelocal 正常了。

我替换你说的特殊版本（只替换了main.js），用回甲骨文，请求过期问题没有再出现，但是这个特殊版本出现了如下的bug。

文件a是我在手机端创建的，同步到服务器上后，PC端将文件a下载下来，并没有编辑；然后手机端删除文件a，点击同步，再到PC端点击同步（目的是同步这个删除文件a的操作），但是得到的结果是PC端文件a还在；这时候手机再点击同步按钮，删除的文件a又回来了（应该是PC端同步的时候将本地的文件a上传到服务器上了）。

我应该在哪一步导出sync plan?

**Comment by fyears** [comment]
> s3 的问题，

我还是不知道怎么回事，不过先把特殊版本的逻辑合并到主线里，这样下个版本可以直接更新。


> 删除文件的问题，

我理解你的意思，就是手机删除这个操作没有同步上去。然后电脑版又传了一次。

假如还能复现，或者能够回忆起出问题的那次同步的时间，那么，可以在根据这个步骤来（从手机和电脑，分别）导出 sync plan，看看是什么回事： https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/export_sync_plans.md （里面会有很多次的记录，可以翻回去看看当初“删除操作没有同步”那个时候，对应文件 a 的 deltimelocal 和 mtimelocal 和 deltimeremote）

假如不能复现的话，那么可以先用着，下次有 bug 时候，再导出最新的 sync plan。

非常感谢你的耐心反馈！！！

**Comment by leeh11** [comment]
客气了，伸手就用的工具包含的是你们的无私奉献，反馈遇到的问题这是我们最基本的责任。

这个bug只在这个特殊版本出现的，0.3.19这个release版本不存在这个bug。

这个bug是必现的，我完整的跑了一遍流程，导出了sync plan，和文件a相关的信息如下：

<img width="521" alt="image" src="https://user-images.githubusercontent.com/24563847/164358442-792e89d8-8ce5-4f55-8459-0e970769951a.png">
<img width="519" alt="image" src="https://user-images.githubusercontent.com/24563847/164358563-214db823-a0db-412e-afc7-3335fabe7d68.png">
<img width="518" alt="image" src="https://user-images.githubusercontent.com/24563847/164358608-08b05237-ba43-4282-990c-41042875a8d4.png">

并没有deltimeremote信息。

**Comment by fyears** [comment]
新版已经发布 https://github.com/remotely-save/remotely-save/releases/tag/0.3.20

且上述的删除没有同步的问题也在这里版本解决了
