### ISSUE TITLE
[Bug]: Departure obsidian

### ISSUE THREAD

**Issue by jestxfot** [remotely-save/remotely-save#770]
### What happened?

The plugin causes obsidian to fly out 10 seconds after launch. I checked other plugins and realized that crashes only happen when I enable it

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
please go to obsidian settings -> community plugins and enable debug startup time. then kill and restart obsidian, you should see the start up time of all plugins in a notice. can you see and take a screenshot of the notice?

and do you have enabled start up sync in remotely save?

**Comment by jestxfot** [comment]
After reinstalling the program everything worked 🤷‍♂️

**Comment by fyears** [comment]
thanks for your report!
