### ISSUE TITLE
[Bug]: SSLHandshakeException java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by tossmilestone** [remotely-save/remotely-save#771]
### What happened?

I use synology webdav server as the webdav. The server address is like https://example.org:10506/obsidian, the domain certs is signed by let's encrypt.
When check the webdav, the error says:
```
Error: Request Failed. SSLHandshakeException java.security.cert.CertPathValidatorException:
Trust anchor for certification path not found.
```

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.5.17

### Version of Obsidian

1.4.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
please configure your server correctly, **and update your android**

https://community.letsencrypt.org/t/trust-anchor-for-certification-path-not-found-android-5-1/172032/6

https://stackoverflow.com/questions/45488917/lets-encrypt-on-android-gives-java-security-cert-certpathvalidatorexception-tr

https://forum.seafile.com/t/solved-android-trust-anchor-for-certification-path-not-found/6665/2

https://www.digicert.com/help/
