### ISSUE TITLE
总感觉移动端同步比桌面端慢很多，这是正常的吗？

### ISSUE THREAD

**Issue by QyhOfficial** [remotely-save/remotely-save#774]
### What happened?

如题

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (InfiniCloud (formally TeraCLOUD))

### Version of the plugin

latest

### Version of Obsidian

latest

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
可以看看并行度设置和网络设置是否一样。代码都是同一份。
