### ISSUE TITLE
[Bug]: RegEx Issue

### ISSUE THREAD

**Issue by Barmaid1076** [remotely-save/remotely-save#776]
### What happened?

使用 `^(?!(AAA|BBB\/bbb|BBB\/ccc)\/).*` 的时候, 会出现 `unexpectedly keptFolder no decisions: BBB/` 的错误并且无法同步, 但是在python中测试时似乎没有发现有问题

测试:
```
import re

patterns = [
    r'^(?!(AAA|BBB\/bbb|BBB\/ccc)\/).*',
    ] 

# False if want to sync, True if want to ignore
test_strings = [
    'AAA/aaa.txt',
    'BBB/ccc/file.md',
    'BBB/bbb'
]

# Testing the patterns
for pattern in patterns:
    print(f'Testing pattern: {pattern}')
    for test_str in test_strings:
        match = re.match(pattern, test_str)
        print(f'Test string: "{test_str}" | Match: {bool(match)}')
    print()


```

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

latest

### Version of Obsidian

latest

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Barmaid1076** [comment]
![image](https://github.com/user-attachments/assets/3c5ab1ac-8476-45cf-81f1-f62a3e761914)

**Comment by fyears** [comment]
我们的 sync plan 是一层一层处理的。

也就是说，我们要处理的，实际上是以下字符串：

```
AAA/aaa.txt       //
AAA/              //

BBB/ccc/file.md   //
BBB/ccc/          //
BBB/bbb/          // 
BBB/              // 被 regex 干掉了
```

这个 regex， 保留了 `BBB/ccc/` 和 `BBB/bbb/` 却干掉了 `BBB/` ，因此程序会出错。

修复方式：修改 regex 使其保留 `BBB/`

**Comment by Barmaid1076** [comment]
感谢大佬

> 我们的 sync plan 是一层一层处理的。
> 
> 也就是说，我们要处理的，实际上是以下字符串：
> 
> ```
> AAA/aaa.txt       //
> AAA/              //
> 
> BBB/ccc/file.md   //
> BBB/ccc/          //
> BBB/bbb/          // 
> BBB/              // 被 regex 干掉了
> ```
> 
> 这个 regex， 保留了 `BBB/ccc/` 和 `BBB/bbb/` 却干掉了 `BBB/` ，因此程序会出错。
> 
> 修复方式：修改 regex 使其保留 `BBB/`
