### ISSUE TITLE
[Bug]: Rclone 加密在 iOS 上变现不佳

### ISSUE THREAD

**Issue by Coding-Yuan** [remotely-save/remotely-save#778]
### What happened?

问题描述：
当笔记文件数量达到 2 千多个，在 Mac 上使用 Rclone 加密还是 OpenSSL 加密方式都没问题，但在 iOS 设备小内存机型（如 3GB 运存）或 CPU 算力不够的情况下，Rclone 加密方式会表现的同步非常慢，且容易在同步过程中导致 Obsidian 崩溃重启，结果就是文件同步不了。

另外一个相关问题：
改成 OpenSSL 加密方式，Mac 能上传至 OneDrive，可在 iOS 设备上同步下载时报“descrypt error”。

另外：
是否是因为文件数量多了以后，导致内存溢出崩溃？能否优化一下这个迭代器，分批次处理加解密释放旧内存占用，让 Remotely Save 运行的更稳定可靠一点。

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.18

### Version of Obsidian

1.6.7

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
改成 OpenSSL 加密方式，Mac 能上传至 OneDrive，可在 iOS 设备上同步下载时报“descrypt error”。

ios 设备也改了加密方式设置了吗？

**Comment by fyears** [comment]
关于性能问题，你是哪个型号的 iphone 呢？

**Comment by Coding-Yuan** [comment]
> 改成 OpenSSL 加密方式，Mac 能上传至 OneDrive，可在 iOS 设备上同步下载时报“descrypt error”。
> 
> ios 设备也改了加密方式设置了吗？

改成了相同的加密方式，然后点击同步提示“解密错误”。最后我直接将 OneDrive 远程目录改名，重新从 Mac 上备份上传，iPhone  上清空文件，改回 Rclone  的加密方式，这才同步正常。

每次随着使用时间增长，都会出现同步缓慢、卡死 ，都需要重置远端文件夹。

**Comment by Coding-Yuan** [comment]
> 关于性能问题，你是哪个型号的 iphone 呢？

设备是  iPhone 8。我那是 Mac 上经常点击同步至 OneDrive 个人版，然后手机上没能随时去点击同步，隔了一段时间在 iPhone Obsidian 点击 Remotely Save 同步，发现同步不成功了，即使将修改文件数量超过 100% (去除保护) 也是同步很长时间没有反应，最后是 Obsidian 崩溃重启，再点击同步，又是等待很久然后软件崩溃 。Debug 模式下的同步提示信息也很简单，完全看不出问题和同步步骤的进度。

无奈，我只能将远程保存目录更改名称，从重新开始同步。

**Comment by fyears** [comment]
可以减少并行同步试一下，这样一次性处理的文件就会变少一点。
