### ISSUE TITLE
[Bug]: Unable to load plugins on mobile devices

### ISSUE THREAD

**Issue by erduotong** [remotely-save/remotely-save#779]
### What happened?

# 问题描述
我尝试在手机端使用remotely save插件，当我尝试开启后，出现了`Failed to load plugin "remotely-save"`，并且无法开启插件。  
我尝试下载`vConsole`插件来查看错误信息，结果如下:  
![N{~HYT@$Q~ OMAGN}~8I~JM](https://github.com/user-attachments/assets/72f938af-6291-42ef-8fec-2c01d183adb7)
出现了该错误，并且经过多次尝试后仍出现上述错误，我做了如下尝试，全部出现相同错误并失败
- 从电脑端下载好remotelySave后，整个valut发送到手机，并加载
- 新建仓库，单独下载`vConsole`和`remotely-save`(挂了梯)
- 删除remotely save，手动下载最新版本，手动迁移到plugins内
- 重新安装Obsidian并重启我的设备
- 安装更低版本的Obsidian，尝试单独下载及手动下载
# 一些信息
- 使用的系统:Harmony OS 3.0.0
- 仓库位于`Document/obsidianStore/Test`

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.18

### Version of Obsidian

1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by DZL1943** [comment]
补充：在其他安卓设备上是正常的, 排除所有因素后, 极有可能是鸿蒙系统的问题。

**Comment by fyears** [comment]
鸿蒙可以切换或者升级 webview 试试吗？

**Comment by fyears** [comment]
这个其实就是系统 webview 不支持新语法。

**Comment by erduotong** [comment]
已解决: 在开发者选项中将webview实现从Google WebView切换到Huawei Webview

**Comment by CraftOldWang** [comment]
> 已解决: 在开发者选项中将webview实现从Google WebView切换到Huawei Webview

我nova 11, HarmonyOS 4.2.0,webview实现中只有Huawei Webview, 加载插件失败，想问下你是如何获取Google WebView的？

**Comment by erduotong** [comment]
我仍然在Harmony OS 3.0(

**Comment by CraftOldWang** [comment]
谢谢你，已经ok了。
我打开开发者选项之前，尝试过重装插件，重启手机，仍无法启用插件；打开开发者选项后，"设置WebView实现"中只有Huawei Web View。之后先重启手机，无法启用插件，然后重装插件，就可以启用插件了。
可能打开开发者选项之后就有什么东西改变了，因此可以启用插件。


> 我仍然在Harmony OS 3.0(

**Comment by sober-wang** [comment]
卓易通内启动 obsidian remotely-save 插件启动失败，但是remotely-sync可以启动，无法同步S3。应该如何解决？
