### ISSUE TITLE
[Bug]: Path style URL has a length limit.

### ISSUE THREAD

**Issue by leeh11** [remotely-save/remotely-save#78]
### What happened?

我用的是OCI的对象存储，S3的协议，Endpoint格式大致是这样：https://namespace.compat.objectstorage.ap-seoul-1.oraclecloud.com

当我的Bucket的名字大于2个字母的时候，就会报错：The S3 bucket cannot be reached.

2个字母的Bucket就工作正常。

所以我怀疑是路径长度导致的。

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.18

### Version of Obsidian

1.2.0

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
没有那么长路径的 s3 资源测试。。。

不过，这里插件并没有人为增加任何长度限制，如果是 s3 api 自带的 api 限制，那么这里也没有什么办法绕过。。。

另外，能否用 virtual host style 呢？

**Comment by leeh11** [comment]
remotely-save默认设置就是virtual host style，我将其切换成Path-Style后，问题解决了。
