### ISSUE TITLE
[Bug]: 使用坚果云Webdav同步出错

### ISSUE THREAD

**Issue by xwshan** [remotely-save/remotely-save#780]
### What happened?

报错提示：
![image](https://github.com/user-attachments/assets/195d1aad-907e-494d-a156-431b07043b7e)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (坚果云 JianGuoYun/NutStore)

### Version of the plugin

v0.5.18

### Version of Obsidian

1.6.7

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
有 api 限制，无法绕过

**Comment by amitbha** [comment]
@fyears 没有看太懂，意思是坚果云有限制，所以无法支持坚果云了吗？

**Comment by xwshan** [comment]
> 坚果云对于调用 api 有次数频率限制，你这个错误应该是插件的请求被坚果云拦截了。
> 
> 可以考虑等一小时后再次同步，或者换个云厂商，

ok，了解了，谢谢你的帮助 😄

**Comment by amitbha** [comment]
打算换 box 了，多谢解答！

**Comment by amitbha** [comment]
那就换盘吧，多谢解答！
