### ISSUE TITLE
[Bug]: Smart resolve adds line breaks after each single word

### ISSUE THREAD

**Issue by phxyz12** [remotely-save/remotely-save#781]
### What happened?

I use the smart merge feature. I observe the following problem:

When smart merge "merges", it adds a line break after each single word. Here is an illustration:

Text in note before smart merge:

Hi, I am an example sentence and I will get badly treated by smart merge :-).

Here is how it looks in the note after smart merge:

Hi, 
I
am
an
example
sentence
and
I
will
get
badly
treated
by
smartmerge
:-).

This is catastrophic in particular for longer notes and there is no way of "undoing" this.

### What OS are you using?

macOS, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (NextCloud)

### Version of the plugin

0.5.18

### Version of Obsidian

1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
have you updated to latest version?

you indicate a bug in old version

**Comment by phxyz12** [comment]
I installed it via Obsidian and indicated the version in the issue.

If I go to 'community plugins' - - > 'check for updates', it doesn't indicate any new version.

So on my end, the bug is still there.

**Comment by fyears** [comment]
what version is your remotely save?

and can you reproduce the bug consistently with new files in new **test** vault?

could you please provide these files (directly uploaded to github comment here)

original file
file changed on device1
file changed on device2
smart merged file

also please note that those incorrectly merged files (in other version) will not be “automatically fixed” in latest version. you could try to find out the history in obsidian’s official settings

**Comment by fyears** [comment]
no further response so far.

**Comment by phxyz12** [comment]
Sorry for my late respone. I couldn't reproduce it anymore although I didn't make any changes to my setup or installed versions. I suggest to close this.

Thank you for taking care.
