### ISSUE TITLE
[Bug]: when you syncthing  big files it crashed

### ISSUE THREAD

**Issue by violentrant** [remotely-save/remotely-save#782]
### What happened?

[Bug]: when you syncthing  big files it crashed
ios 17
newst version 

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
sorry it's due to obsidian's api's performance limit. no easy way to fix.

you can set skip large files in remotely save settings
