### ISSUE TITLE
[Bug]: Minio S3同步报错，提示Request failed, status 400

### ISSUE THREAD

**Issue by leomanxin** [remotely-save/remotely-save#783]
### What happened?

J检查连接的时候，提示Request failed, status 400，无法访问到对应的存储桶
MINIO是自己部署的DOCKER
以下是控制台提示的错误信息，截图是我的设置，区域和我的minio是保持一致的，也试过改成us-east-1，同样报错
![屏幕截图 2024-08-18 134833](https://github.com/user-attachments/assets/32ddb31e-49e5-4d6b-9faf-745b30380fd2)

startting sync.
plugin:remotely-save:236 Error: Request failed, status 400
    at new t (app.js:1:2030716)
    at vK (app.js:1:2030908)
    at app.js:1:2031587
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)
eval @ plugin:remotely-save:236
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
eval @ plugin:remotely-save:236
eval @ plugin:remotely-save:229
a @ plugin:remotely-save:76
Promise.then（异步）
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then（异步）
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then（异步）
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then（异步）
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then（异步）
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then（异步）
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then（异步）
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then（异步）
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then（异步）
l @ plugin:remotely-save:76
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
wx @ plugin:remotely-save:229
eval @ plugin:remotely-save:236
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
syncRun @ plugin:remotely-save:236
eval @ plugin:remotely-save:236
plugin:remotely-save:229 
endding sync.

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (MinIO)

### Version of the plugin

0.5.18

### Version of Obsidian

V1.6.7

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
在 minio 网页里，新建了名字叫 obsidian 的桶了吗？

有设置访问限制或者 acl 吗

**Comment by fyears** [comment]
没进一步信息，先关闭了
