### ISSUE TITLE
[Bug]: 当创建一个名称包含**的文件夹后，文档丢失，无法同步，删除后也无法同步

### ISSUE THREAD

**Issue by leafiy** [remotely-save/remotely-save#784]
### What happened?

![image](https://github.com/user-attachments/assets/761a90d6-ab4f-4c57-b430-5cfa6683af4c)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Windows 不允许创建带有 `**` 的文件。实际上你可以在 obsidian 里创建文件试试，会有以下出错：

![1c29b81e9bb1dc99e657201c43144a0](https://github.com/user-attachments/assets/15f7e736-c304-4087-b2b1-c6cd84c553b4)

修复方式：无法修复，只能手动在 s3 上删除对应文件。然后修改任意地方的带有上述字符的文件名。
