### ISSUE TITLE
[Bug]: remotely save不支持自签证书的webdav？

### ISSUE THREAD

**Issue by fitnig** [remotely-save/remotely-save#785]
### What happened?

remotely save通过webdav连接服务器时提示ssl错误，由于证书有效期太短所以自签到9999-12-31的证书，无论系统是否信任自己的根证书，都提示ssl错误无法同步。
webdav是通过windows iis提供的，换成威联通webdav也不可以同步，其它webdav软件忽略ssl提示后可正常连接。
目前在macos和windows上均可复现

### What OS are you using?

Windows, macOS

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.4.16

### Version of Obsidian

1.6.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> 无论系统是否信任自己的根证书，都提示ssl错误无法同步。

可以搜索一下 electron 如何信任自签证书，电脑版 obsidian 用的是 electron 框架。

插件用的是 obsidian 提供的 api ，无法从插件端自行绕过。

**Comment by xd5520026** [comment]
在 Electron 应用中，如果你使用的是自签名的 SSL/TLS 证书（self-signed certificate），默认情况下 Electron 不会信任这个证书，因此访问该网站时会出现 NET::ERR_CERT_AUTHORITY_INVALID 错误。要解决这个问题，你可以使用以下几种方法来信任自签名证书。
方法一：忽略 SSL 证书验证

⚠️ 警告：此方法会禁用 Electron 中的所有 SSL 证书验证，因此在生产环境中不推荐使用，仅适用于开发环境。

在主进程中（通常是 main.js 或 index.js 文件），添加以下代码：

const { app } = require('electron');

app.on('certificate-error', (event, webContents, url, error, certificate, callback) => {
  // 忽略证书验证错误
  event.preventDefault();
  callback(true);
});

解释

    certificate-error 事件会在出现证书错误时触发。
    使用 event.preventDefault() 阻止默认行为。
    调用 callback(true) 告诉 Electron 信任该证书。

方法二：手动添加自签证书到系统信任存储

    导入证书到系统：
        将 .crt 文件导入系统的证书管理器，并添加到「受信任的根证书颁发机构」中。
        Windows: 使用「证书管理器」(certmgr.msc)。
        macOS: 使用「钥匙串访问」(Keychain Access)。
        Linux: 将证书添加到系统证书目录（例如 /usr/local/share/ca-certificates），然后更新证书 sudo update-ca-certificates。

    重启 Electron 应用。

解释

    通过将证书添加到系统信任存储，所有应用（包括 Electron 应用）都会信任该证书。

方法三：使用 NODE_EXTRA_CA_CERTS 环境变量

你可以通过设置 NODE_EXTRA_CA_CERTS 环境变量来为 Node.js 和 Electron 指定额外的 CA 证书。

export NODE_EXTRA_CA_CERTS=/path/to/your/cert.pem

或者在启动 Electron 应用时设置：

NODE_EXTRA_CA_CERTS=/path/to/your/cert.pem electron .

解释

    NODE_EXTRA_CA_CERTS 让 Node.js 在验证证书时，额外加载自定义 CA 证书。
    这种方法更加安全，不会禁用证书验证。

方法四：使用 session.setCertificateVerifyProc

你可以为特定的 Electron 会话配置自定义的证书验证逻辑。

const { app, session } = require('electron');

app.whenReady().then(() => {
  session.defaultSession.setCertificateVerifyProc((request, callback) => {
    const { hostname } = request;
    // 允许特定的域名
    if (hostname === 'yourdomain.com') {
      return callback(0); // 0 表示成功
    }
    callback(-2); // -2 表示失败，使用默认行为
  });
});

解释

    setCertificateVerifyProc 方法允许你自定义证书验证逻辑，可以为特定域名或 IP 地址信任自签证书。

方法五：通过 electron-fetch 等库设置 rejectUnauthorized

如果你在 Electron 应用中使用 fetch、axios 等库请求自签名证书的资源，可以配置 rejectUnauthorized 为 false。

例如，在 axios 中：

const axios = require('axios');

const instance = axios.create({
  baseURL: 'https://yourdomain.com',
  httpsAgent: new (require('https').Agent)({ rejectUnauthorized: false }),
});

解释

    rejectUnauthorized: false 配置项会忽略自签名证书验证错误。

总结

    开发环境：推荐使用方法一（忽略证书验证）或方法四（自定义验证逻辑）。
    生产环境：推荐使用方法二（导入系统证书）或方法三（设置 NODE_EXTRA_CA_CERTS），确保安全性。
    网络请求库：对于 axios、fetch 等库，使用配置 rejectUnauthorized: false 选项。

**Comment by xd5520026** [comment]
能否参考方法一或方法四，增加一个绕过ssl证书验证的选项开关； nas或者自己私有部署webdav或者存储桶又希望公网能访问，使用免费证书3个月要换一次，付费证书又太贵，使用自签证书是个相对经济的方案。Electron绕过ssl验证的方法依赖平台的ca证书机制，ios和android系统基本没办法操作

**Comment by fyears** [comment]
不能的，插件是 obsidian 的插件，你这个方式要修改 obsidian 本身，且不支持手机，手机端不是 obsidian
