### ISSUE TITLE
[Bug]: Error: net::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by hornhaut** [remotely-save/remotely-save#788]
### What happened?

Hi,
Running remotely safe (webdav) in a tailscale network results in the following error:
```

plugin:remotely-save:236 Error: net::ERR_CERT_COMMON_NAME_INVALID

    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:114352)

    at SimpleURLLoaderWrapper.emit (node:events:519:28)

eval @ plugin:remotely-save:236

```
Is there any way to manually accept certificates?

Best
Sebastian

### What OS are you using?

macOS

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.5.18

### Version of Obsidian

1.6.7

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
sorry but no it's not possible to workaround the invalid certificates
