### ISSUE TITLE
Sync button

### ISSUE THREAD

**Issue by chrisurf** [remotely-save/remotely-save#789]
### What feature are you suggesting?

Thanks for this great project. 👏

Can you please consider adding a sync button either to the status bar or side panel. 

Always having to wait 1 minutes until all files are in sync between all devices isn't very efficient and increases the chance of unwanted drifts.

Allowing the user to trigger the sync manually when needed can improve performance and efficiency.

If you like this idea please add a thumbs up. Thanks 

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by lichfiet** [comment]
I believe there is already a side-bar icon that when pressed allows you to sync. I don't believe there is one for mobile, but mine looks like this

<img width="793" alt="image" src="https://github.com/user-attachments/assets/b1883397-5d0d-4e26-948c-a43702cd39c8">

**Comment by fyears** [comment]
status bar is not suitable for placing a button, and usually on mobile the status bar is not shown.

i believe currently the ribbon icon should be enough for desktop?
