### ISSUE TITLE
[Bug]: net::ERR_CERT_COMMON_NAME_INVALID，使用https自签名证书

### ISSUE THREAD

**Issue by xjcoka** [remotely-save/remotely-save#79]
### What happened?

# 概述
> 使用采用自建webdav, 使用了自签名证书，已将自签名证书加入根信任证书。
webdav域名： https://dav.demo.com/dav，证书为泛域名： *.demo.com

# 问题：
```
net::ERR_CERT_COMMON_NAME_INVALID
```

# 推测原因：
因为使用泛域名，请问有解决办法吗？

# 截图
![image](https://user-images.githubusercontent.com/10301776/163503374-be002426-06bc-4579-82bd-fa4b6cb81746.png)

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.18

### Version of Obsidian

0.14.2

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
你好，本插件处理 https 是完全交由 electron 处理的。请试一下用电脑原生的 chrome 浏览器看看是否有相同错误？此外可以查一下是不是 ssl 证书设置有问题？

例如： https://stackoverflow.com/questions/43665243/invalid-self-signed-ssl-cert-subject-alternative-name-missing

**Comment by xjcoka** [comment]
> 

好的，我尝试使用chrome试试

**Comment by MortalKim** [comment]
在手机上遇到了这个问题，电脑端正常、使用Chrome/Edge测试了webdav，证书正常访问正常。
在PC、Mac上使用插件同步访问也是正常的，在Android 13 的MIUI14上出现了SSL证书错误

**Comment by cn-specter** [comment]
@xjcoka 请问你解决了么？我也是https同样错误。但是其他软件挂载webdav没问题

**Comment by wsyu52** [comment]
> @xjcoka 请问你解决了么？我也是https同样错误。但是其他软件挂载webdav没问题

按照这篇的第一个回答的步骤, 不会报错了. https://stackoverflow.com/questions/21297139/how-do-you-sign-a-certificate-signing-request-with-your-certification-authority/21340898#21340898
