### ISSUE TITLE
[Bug]: SSLHandshakeExceptioniava.security.cert.CertPathValidatorException: Trustanchor for certification path not found.

### ISSUE THREAD

**Issue by Sawyerxu** [remotely-save/remotely-save#793]
### What happened?

I use obsidian on a Xiaomi phone (Android 14) and use this plugin to synchronize the webdav server (no problem on a windows11 computer) and then export the webdav part settings as a url and use this url on the phone. I check that the configuration is fine, but the error message shown like this.
<img width="309" alt="202408291317" src="https://github.com/user-attachments/assets/e174e98f-748e-4588-8713-71fbb273e4c3">

The webdav is a **https server using self-signed SSL certificate(this certificate had been installed on the phone, and other webdav file management softwares in this phone can run normally)**.

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (nginx)

### Version of the plugin

latest

### Version of Obsidian

latest

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
can you visit the webdav website directly in android browser like android chrome?

**Comment by fyears** [comment]
Actually I believe it's not fixable on the plugin side. you need to fix your server, or upgrade your mobile phone's system, or try to switch webview of your mobile phone.

Please checkout the first answer here: https://stackoverflow.com/questions/6825226/trust-anchor-not-found-for-android-ssl-connection
