### ISSUE TITLE
[Bug]: Not importing settings on AppImage

### ISSUE THREAD

**Issue by olgasoboleva23** [remotely-save/remotely-save#796]
### What happened?

I exported plugin setting from iOS as URI. Put it in the input for it on pc. As result only password for encryption was imported.

Using Obsidian  AppImage
My system is manjaro and desktop environment is gnome

### What OS are you using?

Linux

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.5.18

### Version of Obsidian

1.6.7

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [x] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
each part of config is exported and imported independently. do you export only one part of it?

and please install the latest version

and please restart the setting page after each import

**Comment by fyears** [comment]
no further info. close for now.

**Comment by olgasoboleva23** [comment]
what do you mean only part of it? "Export webdav part" yes, because i've chosen webdav as remote service. but only password was imported although all other parameters clearly were in URI string.

With latest version of plugin this bug is not happening

**Comment by fyears** [comment]
ok then let’s use the latest version and close the issue
