### ISSUE TITLE
[Bug]: 一台设备同步报错，其他设备可同步，帮忙看下哪里的问题，非法转义。

### ISSUE THREAD

**Issue by zhangxiaochang** [remotely-save/remotely-save#797]
### What happened?

![图片](https://github.com/user-attachments/assets/2f8b2848-9e1b-4d83-8e5f-635b1db3ef6f)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.5.18

### Version of Obsidian

1.6.3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
什么设备报错了呢？确认密码等没有问题吗？

**Comment by fyears** [comment]
没有进一步信息，先关闭了
