### ISSUE TITLE
[Bug]: your remote folder/file name is invalid: reserved character: >

### ISSUE THREAD

**Issue by invasionofsmallcubes** [remotely-save/remotely-save#799]
### What happened?

After the last update (I updated it today) I see the following error:

<img width="360" alt="Screenshot 2024-09-02 at 10 37 22" src="https://github.com/user-attachments/assets/38783275-a826-4007-af8b-60962ad2b804">

I tried even to reconnect to dropbox but it doesn't see it's working. I can't see any other errors and I'm using default value for the directory.

### What OS are you using?

macOS

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

0.5.20

### Version of Obsidian

1.6.7

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by supmir** [comment]
I'm facing this issue too. On both Windows and ios (I'm not gonna test it on Linux as well) so I'm guessing it's not platform specific.

**Comment by supmir** [comment]
@invasionofsmallcubes 

I rolled back to 0.5.18. Steps I took:

1. Close Obsidian
2. Download main.js, manifest.json, styles.css from [here](https://github.com/remotely-save/remotely-save/releases/tag/0.5.18). 
3. Copy it into .obsidian/plugins/remotely-save (replacing the three existing files.
4. Reopen Obsidian

**Comment by haasal** [comment]
Same but for me it's `?`

**Comment by fyears** [comment]
but file name containing this char is invalid. are you sure you don’t have files with names containing the character?

**Comment by invasionofsmallcubes** [comment]
well first of all it's encrypted so I don't see their names, but no, in my Obsidian there is no file with that char.

**Comment by invasionofsmallcubes** [comment]
Ok, here's what happening.
First of all yes @fyears  there was a title with a `->` and therefore there was a `>` char there. Having said that, the file is one year old, so I'm pretty sure there is a bug here. Because now that I removed that, I have another failure with `"` and this is even older than the file with `>`

**Comment by fyears** [comment]
are you using mac?

**Comment by fdiotalevi** [comment]
Confirmed. After the last plugin upgrade, I can't sync anymore due to this bug. I'm using Mac

**Comment by abdrhnf** [comment]
How to downgrading this plugin on iPad?

**Comment by fyears** [comment]
are you mainly using mac not windows?

**Comment by invasionofsmallcubes** [comment]
Yes I sync Mac and iPhone

**Comment by 7loro** [comment]
I have same issue. And I also have files those names include -> as https://github.com/remotely-save/remotely-save/issues/799#issuecomment-2330755639
I roll back the plugin to 0.5.18 and rename local files which have -> in file name. But still issue is occurred. It seems there are files which name includes -> in dropbox.

**Comment by Ensell84** [comment]
I encountered the same issue today after updating plugins, but with the '?' character. 
I checked the Obsidian directory using the command `find . -type f | grep '\?'` but no files containing the '?' character were found. 
As suggested, I downgraded the plugin to version 0.5.18, which resolved the issue. Therefore, this is likely a plugin bug.

**Comment by balusch** [comment]
> I encountered the same issue today after updating plugins, but with the '?' character. I checked the Obsidian directory using the command `find . -type f | grep '\?'` but no files containing the '?' character were found. As suggested, I downgraded the plugin to version 0.5.18, which resolved the issue. Therefore, this is likely a plugin bug.

same here: https://github.com/remotely-save/remotely-save/issues/802#issuecomment-2336718442

**Comment by 7loro** [comment]
I remove or rename files those name includes > or ? on both local and remote (Dropbox) directory.
Then, issue is not occurred in the latest version plugin.

**Comment by fyears** [comment]
Hi, please update remotely save to 0.5.21 and I remove the file name checking now.
