### ISSUE TITLE
[Bug]: no decision for {"key":"A FILE THAT I HAVE ALREADY DELETED ","

### ISSUE THREAD

**Issue by llewis0** [remotely-save/remotely-save#80]
### What happened?

After I deleted some folders and the notes they contained, the error ocurred：

> remotely-save: abort sync,triggerSource=manual,error while generating_plan

> no decision for {"key":"**A FILE THAT I HAVE ALREADY DELETED** ","mtimeLocal":1633106921321
> "mtimeLocalFmt":"2022-04-14T11:29:16+08:00","changeLocalMtime
> UsingMapping":true,"existLocal":false,"existRemote":false}

I have tried to delete the previous backups and reinstall the plugin, the error still exists.

### What OS are you using?

macOS

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.18

### Version of Obsidian

0.14.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
Hi,

did you delete the files outside Obsidian (using system finder)? and would you like to fully close Obsidian and reopen Obsidian and try again?

**Comment by llewis0** [comment]
Yes, I just deleted them in Finder, after reinstalling and resetting the plugin everything goes well now.
Thank you so much for your reply.
