### ISSUE TITLE
[Bug]: 双向同步导致文件夹恢复和重复文件问题Folder Restoration and Duplicate Files Issue in Bidirectional Sync

### ISSUE THREAD

**Issue by PapainTea** [remotely-save/remotely-save#800]
### What happened?

我在remotely save时，设置的双向同步，我同步的时候出现设备A删除文件夹，然后同步，设备B同步（文件夹未删除），设备A再同步，出现删除的文件又恢复的现象，这个怎么解决？还有我移动了文件到文件夹之后，同步会出现重复文件。版本：v0.5.20

When I set up bidirectional sync in Remotely Save, I encountered an issue during synchronization where Device A deletes a folder, syncs, Device B syncs (the folder is not deleted), and then when Device A syncs again, the deleted folder reappears. How can I solve this problem? Additionally, after I move files to a folder, the sync results in duplicate files.
version 0.5.20

### What OS are you using?

Windows, iOS (iPhone, iPad), Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (InfiniCloud (formally TeraCLOUD)), webdav (坚果云 JianGuoYun/NutStore)

### Version of the plugin

0.5.20

### Version of Obsidian

1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
请导出 sync plan 检查一下。大概率是有一端文件更新了

**Comment by PapainTea** [comment]
最近更新了安卓端的插件，需要保证所有设备的插件版本一致是吗？

**Comment by fyears** [comment]
不是插件更新，而是你的文件有更新。

举例：

1. 设备 a 同步了
2. 设备 b 同步了
3. 设备 a 删除了文件
4. 设备 b 更新了 md 笔记
5. 设备 b 同步了。这时候更新的文件会重新上传。
6. 设备 a 下一次同步的时候，会认为被删除的文件被别的设备更新了，从而下载回来。

**Comment by PapainTea** [comment]
我没有更新，设备b直接点的同步

**Comment by fyears** [comment]
应该是有更新的。或者你有插件导致文件更新了。可以在 b 导出 sync plan 确认。
