### ISSUE TITLE
[Bug]: Google Drive syncing has "/" in their name. Despite it's a reserved character.

### ISSUE THREAD

**Issue by ZhMster** [remotely-save/remotely-save#802]
### What happened?

While using PRO Google Drive, sometimes when syncing may cause to file have "/" in their name, if they were nested in folders before.
Maybe u should create folder first and then copy the file retaining ONLY his filename.

It happened when I started syncing with google drive, idk what caused that but it filled the folder with a bunch of weird named files. Sometimes that bug doesn't happen tho.

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

others

### Version of the plugin

0.5.20

### Version of Obsidian

1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
in mu design the / char is the splitter of folders. for example `aaa/bbb/` means a folder `aaa/` and a nested folder `bbb/` inside `aaa/`.

so if you can see a folder or file whose name contains slash in it, that’s a bug.

and can you consistently reproduce the bug using a test vault with random folders and files?

**Comment by fyears** [comment]
that being said, remotely save is dumb: it just upload or download the files and folders accordingly.

are you sure the slash is exactly the same as english slash `/`, other than a symbol that looks like the slash?

**Comment by balusch** [comment]
Met a similar issue:

>your remote folder/file name is invalid: reserved character：？

I used s3 as my remote storage and it indeed contained some files whose name contains `?`. However, it must be the plugin itself that uploaded the file into s3 since I've never manually put files, which means that the plugin worked well with such names previously but some recent changes broke it.

**Comment by fyears** [comment]
@balusch Hi your issue is different and is tracked in #799 . please update to 0.5.21

**Comment by balusch** [comment]
@fyears it works! Thanks for your quick fix!

**Comment by fyears** [comment]
no further response and cannot reproduce. close for now
