### ISSUE TITLE
[Bug]: v0.5.21 supports only a single config folder 

### ISSUE THREAD

**Issue by ttii6** [remotely-save/remotely-save#804]
### What happened?

For my PC and cellphone, I set Obsidian's config folder differently as ".obsidian" and ".obsidian_ios", so I can have different settings. 

And I enable remotely-save to sync config folder, to my webdav server. Everything works well when version <= 0.5.20.

Today I just updated Remotely-save to v0.5.21, after syncing on PC, the other folder ".obsidian_ios" was deleted from the server. (It seems to be due to commit 74125f8?).

I have backups so I can recover the data, but I have to downgrade to v0.5.20 on all devices.
Could you please help take a look?

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.5.21

### Version of Obsidian

1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
https://github.com/remotely-save/remotely-save/commit/74125f8dff5634bcb8ffe3fdae38339696fdc1b4 should only be effective when you delete everything in the vault.

but anyways let me try to debug when i have free time these days

**Comment by ttii6** [comment]
Thank you.
And I was able to repro the issue consistently by below steps:
1. On the webdav server, make sure there are config dirs: `.obsidian` and `.obsidian_ios`.
2. On my PC, make sure remotely-save's version is 0.5.21, and `.obsidian` is the config dir.
3. Click remotely-save's ribbon button ->  sync succeeds, the two config dir folders are still on the server.
4. Click remotely-save's ribbon button again -> sync succeeds., the `.obsidian_ios` folder is deleted on the server.

If v0.5.20 is used in step 2, everything works well.

**Comment by ttii6** [comment]
btw, sometimes even the first click on PC will erase `.obsidian_ios`.

**Comment by fyears** [comment]
should be fixed in 0.5.22 
please make a backup of your vault then update then try again
