### ISSUE TITLE
[Bug]: cannot authenticate with dropbox

### ISSUE THREAD

**Issue by sagartmg** [remotely-save/remotely-save#805]
### What happened?

![image](https://github.com/user-attachments/assets/7143c525-e6e9-4651-8503-976bde86a81f)

it stucks on this all the time

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

0.5.21

### Version of Obsidian

1.6.1

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
are you sure you don’t have network connection issues?

or if you are planning to also use the plugin on mobile, you can auth the plugin on mobile firstly and import the setting to windows

**Comment by fyears** [comment]
no further response. close for it now. probably the network issue or dropbox rate limiting issue.
