### ISSUE TITLE
[Bug]: Vim key bindings set back to false after using on mobile

### ISSUE THREAD

**Issue by lewisblackburn** [remotely-save/remotely-save#807]
### What happened?

I am syncing configuration files as well as my notes between my desktop and mobile. However, for obvious reasons the vim key bindings setting automatically gets disabled on mobile devices and therefore when settings are synced it turns it off on my desktop. I suppose this is a feature request to make it so the vim key bindings setting is ignored in the sync.

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
are you using “sync config dir” features?

obsidian or its plugins change config dir or its modified time unexpectedly and may confuse remotely save. so it’s not advised to sync config dir. you can disable this feature and tweak the setting on each device.
