### ISSUE TITLE
[Bug]: Fails to sync images

### ISSUE THREAD

**Issue by guizaodev** [remotely-save/remotely-save#808]
### What happened?

Every time I try to sync I get the following error:

![Screenshot_7](https://github.com/user-attachments/assets/a8113134-45bb-4ce0-94fb-20570e10fb23)

From what I understand, the images are sent to the bucket normally, but for some reason this error is returned to me.

### What OS are you using?

Linux

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (MinIO)

### Version of the plugin

0.5.21

### Version of Obsidian

1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by guizaodev** [comment]
After a few hours, I finally located the problem. Since I'm using cloudflare to manage my domain, I had to apply a filter to bypass the cache on the s3 URL, as this was causing authentication issues.

**Comment by Zyztem** [comment]
Thanks, also had the same issue
