### ISSUE TITLE
[Bug]: Folders and files with underscore as first character in name are synced even when function is disabled

### ISSUE THREAD

**Issue by mikaelth** [remotely-save/remotely-save#809]
### What happened?

When syncing over WebDAV, folder and files named with a leading _ are synced in release 0.5.21 regardless of setting (Disable, Enable).

This worked fine up to and including 0.5.18

### What OS are you using?

Windows, Linux, macOS, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.5.21

### Version of Obsidian

1.6.7

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by patricklatorre** [comment]
Same issue and details as mikaelth, except using S3.

**Comment by fyears** [comment]
hmmm that’s unexpected let me check the bug when i am not busy

**Comment by fyears** [comment]
should be fixed in 0.5.22
