### ISSUE TITLE
[Feature Request]: multiple synchronization strategies 按照目录指定同步策略（双向/单向）

### ISSUE THREAD

**Issue by trincer** [remotely-save/remotely-save#810]
### What feature are you suggesting?

Dear ,

First of all, thank you for the excellent extension!
I hope this message finds you well. I would like to suggest a feature enhancement for the "Remotely Save" plugin that would greatly improve its flexibility and usability.

### Feature Request

It would be beneficial to support multiple synchronization strategies within the plugin, allowing users to specify different synchronization modes for different directories. Specifically:

- **Bidirectional Sync**: Users should be able to select certain directories to use bidirectional sync.
- **Unidirectional Sync**: Other directories could be set to use unidirectional sync (either from local to remote or remote to local).

Additionally, I suggest allowing the definition of directories using regular expressions. This would enable users to easily manage complex directory structures and customize their synchronization preferences without the need to manually specify each path.

This feature would provide users with greater control over their synchronization process and better cater to varying workflow needs.

Thank you for considering this request. I appreciate your efforts in maintaining and improving this plugin.

Best regards,
Trincer

remotely save 开发者，

希望您一切都好。我想提出一个针对“remotely save”插件的功能增强建议，这将大大提高其灵活性和可用性。

功能请求
支持插件中多种同步策略的功能，将使用户能够为不同目录指定不同的同步模式，具体如下：

双向同步：用户能够选择某些目录使用双向同步。
单向同步：其他目录可以设置为使用单向同步（可以是从本地到远程或从远程到本地）。
此外，我建议允许使用正则表达式来定义目录。这将使用户轻松管理复杂的目录结构，并自定义他们的同步偏好，而不需要手动指定每个路径。

此功能将为用户提供更大的同步控制权，更好地满足不同的工作流需求。

感谢您考虑这个请求。我非常感激您对维护和改进此插件所付出的努力。

此致，
Trincer

### What remote cloud services are you using, or suggesting adding the feature to?

S3 (阿里云 OSS Alibaba Cloud OSS)

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
（可以直接用中文）

这个建议的问题是会使得配置极端复杂，即使 rclone 也没有那么复杂的。暂不考虑哈。
