### ISSUE TITLE
[Bug]: Recommended to offer an option to disable telemetry, or disable pop-up window.

### ISSUE THREAD

**Issue by hxac** [remotely-save/remotely-save#813]
### What happened?

Recommended to offer an option to disable telemetry, or disable pop-up window.

Frequently encountered issues include `net::ERR_BLOCKED_BY_RESPONSE.NotSameOrigin`, `net::ERR_CONNECTION_RESET`, or `net::ERR_TIMED_OUT`, with a very annoying pop-up prompt box.

For example, when attempting to fetch `https://cdn.ko-fi.com/cdn/kofi3.png?v=3`.
The website blocks IP addresses from mainland China, resulting in a 403 Access Denied error. It is reasonable to infer that this is the action of the CDN provider. Even when accessed via detour from countries such as Japan and South Korea, a 500 error is returned. It could be due to the service provider experiencing excessive traffic.

This issue severely impacts the user experience, with constant pop-ups disrupting note-taking.

The problem persists across various services, including Amazon S3, Microsoft's cloud services, Tencent Cloud, Upyun, Alibaba Cloud, and self-hosted cloud servers. Even when switching to a local area network server, these errors continue to occur.

The current mitigation method is to delete the error handling function in main.js:236.

`
((e,t)=>r(this, void 0, void 0, (function*() {var r; if (console.error(t), t instanceof h) for (const r of t.errors) _(e, r.message, 1e4); else _(e, null !== (r = null == t ? void 0 : t.message) && void 0 !== r ? r : "error while sync", 1e4) }))
`

change to:

`
((e,t)=>r(this,void 0,void 0,(function*(){var r;if(console.error(t),t instanceof h)for(const r of t.errors) console.info(t);else console.info(t)})))
`

![image](https://github.com/user-attachments/assets/5bedc251-6dad-494c-b916-f03fdb93c4a3)

This method can effectively alleviate the severe inconvenience caused during normal usage.

This method will still display the status in the status bar, and show errors along with their causes in the console (Ctrl+shift+I).
![image](https://github.com/user-attachments/assets/f62b5cfe-accc-4e75-a6e8-3a8b1ab61a35)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3, S3 (Cloudflare R2), S3 (腾讯云 COS Tencent Cloud COS), S3 (阿里云 OSS Alibaba Cloud OSS), webdav (坚果云 JianGuoYun/NutStore), webdav (nginx), others

### Version of the plugin

0.5.21

### Version of Obsidian

1.6.7

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by hxac** [comment]
This method doesn't work. I used Burp Suite to monitor all day long, but didn't receive any alerts. After restarting my computer, if I open Obsidian first, a pop-up error window will appear, but it can also sync after manually retrying. However, after opening Burp Suite, the pop-up window will never appear again. I can't find a suitable method for analysis at the moment. However, keeping Burp Suite running in the background does effectively solve the problem of frequent pop-up windows.

![image](https://github.com/user-attachments/assets/8e3c2222-abc1-4dc2-b346-1e1a3a75f2c7)

The host name in the image is my local server, which uses an HTTPS encrypted connection to eliminate issues related to HTTPS.

**Comment by fyears** [comment]
i don’t know what do you mean. the plugin should  not have telemetry or links to ko-fi website by intention. especially i don’t collect any donations from ko-fi! you can check the source code in this repo by yourself.

and when you are saying “pop up window”, maybe you can provide a screenshot next time.
