### ISSUE TITLE
[Bug]: Whenever I change a setting on iOS all settings are reset to default on my desktop

### ISSUE THREAD

**Issue by wael-t** [remotely-save/remotely-save#814]
### What happened?

I configured some settings on the desktop app (Appearance, Hotkeys, Editor), then when I configure the mobile toolbar or even make any setting change on the ios app, all my settings that I configured on my desktop app will be set back to default (edit: and vice-versa). I tried to uninstall the ios app and reinstall it and re-configuring the plugin from the beginning many times but the issue keeps happening. I didn't have this issue prior to updating both the desktop and the plugin to their new releases. 

### What OS are you using?

Linux

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (NextCloud)

### Version of the plugin

0.5.21

### Version of Obsidian

On Fedora the Flatpack version 1.6.7, on iOS 1.6.7 (149)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by laenan8466** [comment]
Same here. Also when enable the setting Sync on desktop all information is deleted. :/

**Comment by fyears** [comment]
the same as https://github.com/remotely-save/remotely-save/issues/818 the issue will be fixed soon
