### ISSUE TITLE
[Bug]: Plugin cannot be synchronized

### ISSUE THREAD

**Issue by eutopiazen** [remotely-save/remotely-save#815]
### What happened?

在Windows和ios的同步过程中，插件的配置信息无法更新

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.5.21

### Version of Obsidian

1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
是否开启了“同步插件文件夹”呢

**Comment by fyears** [comment]
没有进一步信息，先关闭了
