### ISSUE TITLE
[Bug]: When using plugin sync in HyperOS, the Obsidian software directly exits.

### ISSUE THREAD

**Issue by bbls-ai** [remotely-save/remotely-save#817]
### What happened?

Phone system: Xiaomi HyperOS 1.0.6.0.TKHCNXM
Bug: When sync is turned on in obsidian, it directly exits the software after a while, during which there is no error reporting prompt.

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (阿里云 OSS Alibaba Cloud OSS)

### Version of the plugin

0.5.21

### Version of Obsidian

1.6.7(149)

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
尝试配置跳过大文件

**Comment by bbls-ai** [comment]
> 尝试配置跳过大文件

好的，已解决，谢谢。
