### ISSUE TITLE
[Bug]: Config dir is synced even with the option turned off

### ISSUE THREAD

**Issue by terrytw** [remotely-save/remotely-save#818]
### What happened?

1. I have disabled the "sync config dir" option, but .obsidian is still synced.
2. .trash is also synced.
3. Weirdly, when I put .obsidian in exclude regex, .trash is not synced.
4. Both .trash and .obsidian is deleted from source (webdav server) after the sync.

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.5.21

### Version of Obsidian

1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by xvqinghong** [comment]
Hi bro, I found a workaround solution that add `.obsidian/` in the ignore list in the plugin setting.

**Comment by terrytw** [comment]
Thanks, but I think I already mentioned it.

It just feels super risky and unreliable to me that this can happen.

**Comment by Josiahdh** [comment]
I also experienced this issue. Did the temporary fix of adding the config folder to the ignore list for the time being.

**Comment by fyears** [comment]
should be fixed in 0.5.22
