### ISSUE TITLE
[Bug]: Syncing fails when plugin version is greater than 0.5.18 on Android

### ISSUE THREAD

**Issue by mcurly** [remotely-save/remotely-save#819]
### What happened?

Syncing fails whenever I try to sync files using this plugin to my WEBDAV  Linux server running Nextcloud

I noticed this after updating from 0.5.18 to 0.5.20.

Syncing began to fail immediately but when I returned or downgraded the plugin version to 0.5.18 the usual behavior was restored.

### What OS are you using?

Linux, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (NextCloud)

### Version of the plugin

0.5.21; 0.5.20; 0.5.18

### Version of Obsidian

Android 1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by mcurly** [comment]
hi again!

 well I'm moving this to closed because apparently I can no longer reproduce this issue and it's working as expected again

so sorry for having flagged this issue up because I can't even reproduce it no longer...

sorry. 

thank you for this plugin by the way!

**Comment by fyears** [comment]
thanks for reporting. glad you can use the plugin again
