### ISSUE TITLE
[Bug]: 在同步时obsidian崩溃

### ISSUE THREAD

**Issue by JerryFake** [remotely-save/remotely-save#82]
### What happened?

在同步某些大文件时，如100m的pdf，obsidian崩溃了，崩溃信息如图
![Screenshot_2022-04-16-15-57-34-943_com miui bugreport](https://user-images.githubusercontent.com/48702745/163667377-216b9a92-dc36-41c8-b8fe-0aea9f4a7148.jpg)

### What OS are you using?

Android

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.18

### Version of Obsidian

1.2.0

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
抱歉，现在上传大文件时候必须首先把大文件载入到内存里，因此如果内存不足装载的话，确实会导致程序崩溃，没有好办法避免。

如果你想跳过此文件的同步的话，可以把文件名 `<原文件名>` 改为 `_<原文件名>`，并关闭同步 `_` 开头文件的选项。

**Comment by JerryFake** [comment]
> 抱歉，现在上传大文件时候必须首先把大文件载入到内存里，因此如果内存不足装载的话，确实会导致程序崩溃，没有好办法避免。
> 
> 如果你想跳过此文件的同步的话，可以把文件名 `<原文件名>` 改为 `_<原文件名>`，并关闭同步 `_` 开头文件的选项。

这个问题在0.2的插件版本没有出现过，是因为软件更新加了限制吗

**Comment by fyears** [comment]
想了想，有可能是因为之前的一个 bug 导致的。我在代码里更新了一下，会随着下个版本发布。可以到时候试一下，谢谢！

**Comment by JerryFake** [comment]
> 想了想，有可能是因为之前的一个 bug 导致的。我在代码里更新了一下，会随着下个版本发布。可以到时候试一下，谢谢！

是否考虑添加一下单向同步的功能，我在pc端添加PDF然后在Android端同步后会直接删除onedrive内对应的PDF(因为使用过foldersync同步过所以插件会将Android当做最新的库)

**Comment by JerryFake** [comment]
> 想了想，有可能是因为之前的一个 bug 导致的。我在代码里更新了一下，会随着下个版本发布。可以到时候试一下，谢谢！

同步大文件导致obsidian崩溃的bug已经解决

**Comment by fyears** [comment]
有foldersync的话，为啥还要用本插件……

**Comment by JerryFake** [comment]
> 有foldersync的话，为啥还要用本插件……

因为iPad没法用...

**Comment by fyears** [comment]
那么什么叫做单向同步呢？此外本插件也支持跨平台的

**Comment by JerryFake** [comment]
> 



> 那么什么叫做单向同步呢？此外本插件也支持跨平台的

> 那么什么叫做单向同步呢？此外本插件也支持跨平台的

我理解的单向同步就是本次同步只进行下载或只进行上传，因为iOS无法使用foldersync所以我用这个插件作为iPad的同步方案

**Comment by fyears** [comment]
> 我理解的单向同步就是本次同步只进行下载或只进行上传，

假设本次只进行下载，那么本地修改了的文件就不上传？

**Comment by JerryFake** [comment]
> > 我理解的单向同步就是本次同步只进行下载或只进行上传，
> 
> 假设本次只进行下载，那么本地修改了的文件就不上传？

对，我的想法是，进行单向同步首先知晓本地库和云端库哪一个是自己需要的版本，这样只需要进行单方面的覆盖就可以了

**Comment by fyears** [comment]
> 进行单向同步首先知晓本地库和云端库哪一个是自己需要的版本，这样只需要进行单方面的覆盖就可以了

那么这里是怎么个操作呢？直接弹出一个列表勾选，还是怎么样呢？

**Comment by fyears** [comment]
你好，欢迎在这里继续讨论：https://github.com/remotely-save/remotely-save/issues/85

**Comment by JerryFake** [comment]
> > 进行单向同步首先知晓本地库和云端库哪一个是自己需要的版本，这样只需要进行单方面的覆盖就可以了
> 
> 那么这里是怎么个操作呢？直接弹出一个列表勾选，还是怎么样呢？

这个功能用到的频率应该不会很频繁，可以考虑在插件设置里面添加一个选项，此次同步：双向同步，仅下载，仅上传

**Comment by SoHugePenguin** [comment]
我改进了这个插件，但仍然不支持手机的大文件读取，readBinary / readLocalFile 貌似最大只能150M

**Comment by fyears** [comment]
@SoHugePenguin 欢迎提交 pr，但是我看你的一个改进是检查前 n 个字节的 sha256，这会不会有误判呢

**Comment by fyears** [comment]
> 比如：上传文件有多少本地上传，不管远端有没有都会一起上传，流量给我干废了 等问题。

这里是 modify time 的判断逻辑，之前的逻辑还有问题，得修复，修复了就好了。

> 我自己改了，用到现在都没有误判，我记得我应该是分块看sha256的自己测了没出问题。并且优化了很多问题。

远端的大部分不会自动提供这个值，一般来说都是要下载来计算的（除非针对某些场景特化）。所以如果是看头部一段数据计算sha256，那么一定是会有问题的，比如说你改了一个 txt 的文件的尾部。当然，一般来说 txt md 文件很小你可以直接计算整个文件的 sha256。如果是大文件全部块都计算了 sha256，那么很好奇如何不下载来计算……

此外新版会陆续引入 hash 计算。部分代码合并进去了。

总之，可以考虑一下提 pr 哈，谢谢。
