### ISSUE TITLE
[Bug]: Sync causes crash on iOS 18

### ISSUE THREAD

**Issue by rbajevs** [remotely-save/remotely-save#820]
### What happened?

Part way through syncing the splash screen for Obsidian shows up and after it's gone, the sync status reads as failed. Disabling the sync plugin prevents the issue from happening, so I'm confident its the plugin

### What OS are you using?

iOS 18 (iPhone 12 Mini) 

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (NextCloud)

### Version of the plugin

0.5.21

### Version of Obsidian

1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
please try to set “skip large files “

usually on mobile large files have performance issues

**Comment by rbajevs** [comment]
Looks like that was it. I tracked it down to a 45MB jpeg file I added to a note. It might have been around the same time I updated to iOS 18, so I thought that was the issue. 

Do the newer phones have a better time handling 45MB files by any chance? A challenge worthy of the mighty A18 Pro chip?

**Comment by zonshi** [comment]
I just installed Obsidian on my iPhone 12 and downloaded this plugin, but it won't enable and always prompts that the plugin failed to load.

**Comment by rbajevs** [comment]
Yeah, I think I was right the first time. There's something about iOS 18 that's making the plug-in less stable. I've had to set the file size limit to 5 MB and just hope that a better solution comes along.

**Comment by rbajevs** [comment]
Better solution has come along! So, on iOS 18 you can now force an iCloud folder to always be downloaded. This makes using Obsidian with iCloud not terrible! I recommend this solution to anyone else having this issue until it gets sorted out

**Comment by fyears** [comment]
Some it's about the icloud part which is not under my control.

Thanks for your report and solution

**Comment by rbajevs** [comment]
I was using Local before, not iCloud. iCloud was just the solution I came up with when the plug-in stopped working properly after iOS 18.
