### ISSUE TITLE
[Bug]: Google Drive - Haven't Manually Auth'd

### ISSUE THREAD

**Issue by PhotexMedia** [remotely-save/remotely-save#821]
### What happened?

Whenever I auth Google Drive and close out of Obsidian it removes the authentication on both Windows and Android clients requiring me to reauthorize every time the application is opened. 

### What OS are you using?

Windows, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

others

### Version of the plugin

0.5.21

### Version of Obsidian

1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
> close out of Obsidian it removes the authentication on both Windows and Android clients

are you sure that the first time the auth is successful?

**Comment by PhotexMedia** [comment]
> > close out of Obsidian it removes the authentication on both Windows and Android clients
> 
> are you sure that the first time the auth is successful?

Yes, auth is successful because changes will get pushed to google drive normally when I save.

**Comment by fyears** [comment]
fixed in next version released in 48 hours.
