### ISSUE TITLE
[Bug]: error - failing patch requests in Yandex resulting in Internal Server Errors

### ISSUE THREAD

**Issue by realizetm** [remotely-save/remotely-save#822]
### What happened?

are the console error logs:

plugin:remotely-save:229 
        
        
       PATCH https://cloud-api.yandex.net/v1/disk/resources?path=disk%3A%2FObsidian%2FX%2FLookups%2FBooks%2FLookup+-+Status+-+Books.md 500 (INTERNAL SERVER ERROR)
eval @ plugin:remotely-save:229
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
_api @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
diskResourcesPatch @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
writeFile @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
writeFile @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
q_ @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
eval @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
wx @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
h @ plugin:remotely-save:229
eval @ plugin:remotely-save:90
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
plugin:remotely-save:229 
        
        
       PATCH https://cloud-api.yandex.net/v1/disk/resources?path=disk%3A%2FObsidian%2F%2BIN%2FLean+ALL+240831%2F02+Areas%2F%40+Seller.md 500 (INTERNAL SERVER ERROR)
eval @ plugin:remotely-save:229
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
_api @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
diskResourcesPatch @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
writeFile @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
writeFile @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
q_ @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
eval @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
wx @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
h @ plugin:remotely-save:229
eval @ plugin:remotely-save:90
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
plugin:remotely-save:229 
        
        
       PATCH https://cloud-api.yandex.net/v1/disk/resources?path=disk%3A%2FObsidian%2FJournal%2F01+Daily%2F2024%2F09%2F2024-09-16.md 500 (INTERNAL SERVER ERROR)
eval @ plugin:remotely-save:229
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
_api @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
diskResourcesPatch @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
writeFile @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
writeFile @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
q_ @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
eval @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
wx @ plugin:remotely-save:229
eval @ plugin:remotely-save:229
s @ plugin:remotely-save:76
Promise.then (async)
l @ plugin:remotely-save:76
eval @ plugin:remotely-save:76
r @ plugin:remotely-save:76
h @ plugin:remotely-save:229
eval @ plugin:remotely-save:90
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
await in eval (async)
#v @ plugin:remotely-save:90
#y @ plugin:remotely-save:90
eval @ plugin:remotely-save:90
plugin:remotely-save:236 AggregateError: 
    Error: X/Lookups/Books/Lookup - Status - Books.md: {"message":"Ошибка сервера.","description":"Internal Server Error","error":"InternalServerError"}
        at eval (plugin:remotely-save:229:49358)
    Error: +IN/Lean ALL 240831/02 Areas/@ Seller.md: {"message":"Ошибка сервера.","description":"Internal Server Error","error":"InternalServerError"}
        at eval (plugin:remotely-save:229:49358)
    Error: Journal/01 Daily/2024/09/2024-09-16.md: {"message":"Ошибка сервера.","description":"Internal Server Error","error":"InternalServerError"}
        at eval (plugin:remotely-save:229:49358)
    Error: too many errors, stop the remaining tasks
        at eval (plugin:remotely-save:229:49462)
        at Generator.next (<anonymous>)
        at s (plugin:remotely-save:76:371760)
    at eval (plugin:remotely-save:229:49518)
    at Generator.next (<anonymous>)
    at s (plugin:remotely-save:76:371760)
    
    

This is a second sync. same error on first sync (where Remotely Save created the folder and performed first sync (with protection disabled (100%). Sync direction - bidirectional. Concurrency was set at 5, will try at 3.

thanks!

### What OS are you using?

macOS

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

others

### Version of the plugin

current: 0.5.21

### Version of Obsidian

current: v1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by realizetm** [comment]
it resolved itself with a setting of 3 concurrencies. might be a normal Yandex configuration requirement.

**Comment by fyears** [comment]
thanks for reporting
