### ISSUE TITLE
[Bug]: Cloudflare R2 Needs Admin Access, not just Object Read + Write

### ISSUE THREAD

**Issue by kothavade** [remotely-save/remotely-save#826]
### What happened?

When setting up R2 with the instructions from the README, it kept failing with 403: Forbidden errors. Switching to an Admin token allowed it to work, so the R2 instructions should be updated accordingly.

### What OS are you using?

macOS

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (Cloudflare R2)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
If you encounter an issue and are sure the info are correct, please upgrade remotely-save to version >= 0.3.29 and try again.

> Cloudflare doesn't allow HeadBucket for access keys with "Object Read & Write". So it may be possible that checking connectivity is not ok but actual syncing is ok. New version >= 0.3.29 of the plugin fix this problem by using ListObjects instead of HeadBucket.

And I am personally using R2 for my vault. It's no problem.

**Comment by kothavade** [comment]
Strange--I set this up using the latest version on the Obsidian Community Plugin page as of 3 days ago, which is definitely past 0.3.29, which seems to be from back in January. I must have been doing something wrong--online you can see people having the same issue (https://www.reddit.com/r/ObsidianMD/comments/16t90wk/remotely_save_syncing_across_all_devices/ka2cpxw/) but that was 10 months ago, I think prior to the fix you mention. 

In any case, admin is working for now, and I don't have any other buckets on R2 anyways, but I might try debugging this later to see if I can reproduce the 403 errors again.

Thank you for the plugin!

**Comment by fyears** [comment]
yeah sure.

but anyway the difference is on the "check the connection " checking.

if actual sync, the plugin doesn't use any admin api.
