### ISSUE TITLE
[Bug]: S3 Sync Config Dir throws unexpectedly keptFolder no decisions: .obsidian/

### ISSUE THREAD

**Issue by Panthon13** [remotely-save/remotely-save#828]
### What happened?

When I enable "Sync Config Dir" option to sync the .obsidian folder with an S3 sync target, I get the error `unexpectedly keptFolder no decisions: .obsidian/` and no files are synced.

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3

### Version of the plugin

0.5.22

### Version of Obsidian

1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
do you have any deny list or allow list settings?

do you enable sync bookmarks?

do you see any .obsidian files or folders in s3?

have you updated the plugin to latest version (released a few hours before)?

**Comment by kwt052** [comment]
I created an Obsidian folder on Synology NAS and am using remotely save's webDAV connection. 

After updating to version 0.5.22 in Windows, an unexpectedly keptFolder error occurs and the program does not work properly, even though nothing has changed from the existing settings.

Attached is a picture file.
![image](https://github.com/user-attachments/assets/796ebbda-be3e-45a6-b663-5752120ac441)

The 0.5.21 version of Obsidian being used on the phone does not display any errors and the program operates normally.

**Comment by fyears** [comment]
please consider export the sync plan and post the items under .obsidian and meta keys here, after removing all other sensitive personal info

**Comment by byxrolland** [comment]
Yes. I have this problem as well.
This bug appears after the recent update.

**Comment by fyears** [comment]
> Yes. I have this problem as well.
> 
> This bug appears after the recent update.

please consider export the sync plan and post the items under .obsidian and meta keys here, after removing all other sensitive personal info
