### ISSUE TITLE
[Bug]: Sync broken when switching from pCloud to WebDav connection

### ISSUE THREAD

**Issue by j-xella** [remotely-save/remotely-save#829]
### What happened?

I use pCloud disk as a storage for Remotely Save. There are 2 ways to connect to pcloud:

* native pCloud API
* WebDav ( via https://webdav.pcloud.com )

Here is what I did: 

1. Connected via pCloud API
2. Synced my vault
3. Changed the connection to WebDav (all other settings, such as vault password, location, etc... are the same, only the _remote service_ part of the config is changed)
4. Tried to sync again

Suddenly, I am getting errors that sync is impossible because there are more than 50% differences or something like that.

I did not make any changes to the repo during the whole exercise.

Also, if I set another device to use the same pcloud sync space _via webdav_, it syncs. So, it's not like different connection method produces differently encrypted files....

Since nothing really changed except from the connection method, I expected that switching from pCloud API to webdav connection, with all other parameters being the same, should just result in syncing working as usual. In this case, just quickly returning success as there are no changes to save or load.

I wonder if using different connection method produces different time stamps on the remote files, and this somehow puts the plugin off ???

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.5.21

### Version of Obsidian

1.6.7

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
pcloud and webdav use different api to get the last modified time on server, so it's likely that the info returned are different.

I suggest you make a backup of your vault manually and directly allow the sync (over 50% changes), then after that everything should be normal.
