### ISSUE TITLE
[Bug]: 0.5.24 webdav sync fail

### ISSUE THREAD

**Issue by study630** [remotely-save/remotely-save#831]
### What happened?

0.5.24 webdav sync fail

### What OS are you using?

Windows, Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (InfiniCloud (formally TeraCLOUD))

### Version of the plugin

0.5.24

### Version of Obsidian

1.6.7

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
may i ask what's the error msg?

**Comment by study630** [comment]
![Uploading QQ截图20241007192531.jpg…]()

**Comment by study630** [comment]
![QQ截图20241007192951](https://github.com/user-attachments/assets/7be44828-9d48-43fe-b5dd-9c74fed935b7)

**Comment by study630** [comment]
![QQ截图20241007193227](https://github.com/user-attachments/assets/531add7d-3403-4674-a3da-3c528ff3a15a)

**Comment by smthvitas** [comment]
I've encountered this issue as well. Using QNAP's built-in WebDAV service, I've successfully synchronized on two PCs (though it's still often unstable). However, on one laptop, I can't access it at all and keep getting a timeout error. Curiously, curl works fine. The configuration is exactly the same across all devices.
### Version of the plugin
0.5.24
### Version of Obsidian
1.6.7
### Using password or not
 Yes
![clipboard_2024-10-13_10-00](https://github.com/user-attachments/assets/e0fe08dc-9899-46dd-9dec-cfcf5012f140)
![clipboard_2024-10-13_10-03](https://github.com/user-attachments/assets/d810bf93-ac15-4d76-b9c7-841c56576ae2)

**Comment by smthvitas** [comment]
似乎找到原因了。remotely-save在https连接时需要验证服务器证书，因此在Qnap上安装了一个Let's Encrypt的域名证书，然后在本地改hosts文件，把Qnap内网IP和域名对应起来。开了clash系统代理以后，这个域名似乎被远程解析了，所以经常连不上。关掉clash系统代理就解决了。

> I've encountered this issue as well. Using QNAP's built-in WebDAV service, I've successfully synchronized on two PCs (though it's still often unstable). However, on one laptop, I can't access it at all and keep getting a timeout error. Curiously, curl works fine. The configuration is exactly the same across all devices.
> 
> ### Version of the plugin
> 0.5.24
> 
> ### Version of Obsidian
> 1.6.7
> 
> ### Using password or not
> Yes ![clipboard_2024-10-13_10-00](https://private-user-images.githubusercontent.com/18712253/376002148-e0fe08dc-9899-46dd-9dec-cfcf5012f140.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MDQxNzcsIm5iZiI6MTcyODgwMzg3NywicGF0aCI6Ii8xODcxMjI1My8zNzYwMDIxNDgtZTBmZTA4ZGMtOTg5OS00NmRkLTlkZWMtY2ZjZjUwMTJmMTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDA3MTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NWJkNjJlNWVhOTFiNmQ2MzM2MGRkMTA3MDZiMmEyZmY5MmY2YWVmMDk2MjIwNWVlMDRmN2Y0ZTgyODk5NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dCXVUEzI1RxF16UhYK2YU7rN8uNREk_3heLye2J-YCM) ![clipboard_2024-10-13_10-03](https://private-user-images.githubusercontent.com/18712253/376002185-d810bf93-ac15-4d76-b9c7-841c56576ae2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MDQxNzcsIm5iZiI6MTcyODgwMzg3NywicGF0aCI6Ii8xODcxMjI1My8zNzYwMDIxODUtZDgxMGJmOTMtYWMxNS00ZDc2LWI5YzctODQxYzU2NTc2YWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDA3MTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYWExODk1YjAzYTBiYTIyZDMxMmQ4MTNhODQ4YzFiODUxNjc4YjU4YTYxZDQ2NGJkOWEwNjQ2Y2ZmYjA2ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W3lWJBcfkHosKfqx1jITvVZqClV6vOyQ5Ap5KxNJgVU)

**Comment by smthvitas** [comment]
似乎找到原因了。remotely-save在https连接时需要验证服务器证书，因此在Qnap上安装了一个Let's Encrypt的域名证书，然后在本地改hosts文件，把Qnap内网IP和域名对应起来。开了clash系统代理以后，这个域名似乎被远程解析了，所以经常连不上。关掉clash系统代理就解决了。

> I've encountered this issue as well. Using QNAP's built-in WebDAV service, I've successfully synchronized on two PCs (though it's still often unstable). However, on one laptop, I can't access it at all and keep getting a timeout error. Curiously, curl works fine. The configuration is exactly the same across all devices.
> 
> ### Version of the plugin
> 0.5.24
> 
> ### Version of Obsidian
> 1.6.7
> 
> ### Using password or not
> Yes ![clipboard_2024-10-13_10-00](https://private-user-images.githubusercontent.com/18712253/376002148-e0fe08dc-9899-46dd-9dec-cfcf5012f140.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MDQxNzcsIm5iZiI6MTcyODgwMzg3NywicGF0aCI6Ii8xODcxMjI1My8zNzYwMDIxNDgtZTBmZTA4ZGMtOTg5OS00NmRkLTlkZWMtY2ZjZjUwMTJmMTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDA3MTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NWJkNjJlNWVhOTFiNmQ2MzM2MGRkMTA3MDZiMmEyZmY5MmY2YWVmMDk2MjIwNWVlMDRmN2Y0ZTgyODk5NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dCXVUEzI1RxF16UhYK2YU7rN8uNREk_3heLye2J-YCM) ![clipboard_2024-10-13_10-03](https://private-user-images.githubusercontent.com/18712253/376002185-d810bf93-ac15-4d76-b9c7-841c56576ae2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MDQxNzcsIm5iZiI6MTcyODgwMzg3NywicGF0aCI6Ii8xODcxMjI1My8zNzYwMDIxODUtZDgxMGJmOTMtYWMxNS00ZDc2LWI5YzctODQxYzU2NTc2YWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDA3MTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYWExODk1YjAzYTBiYTIyZDMxMmQ4MTNhODQ4YzFiODUxNjc4YjU4YTYxZDQ2NGJkOWEwNjQ2Y2ZmYjA2ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W3lWJBcfkHosKfqx1jITvVZqClV6vOyQ5Ap5KxNJgVU)
