### ISSUE TITLE
[Bug]: File sync fails if file name contains % when using WebDAV

### ISSUE THREAD

**Issue by hotate29** [remotely-save/remotely-save#832]
### What happened?

I recently switched from syncing using OneDrive to syncing using WebDAV and have since noticed that files containing %(U+0025) in the file name are failing to sync.

I mainly see code 409, but occasionally code 401 as well. ~~After reading the code a bit, the plugin appears to stop URL encoding when the filename contains %.~~ Sorry, my guess above was wrong. In any case, it seems that the filenames are not URL encoded.

https://github.com/remotely-save/remotely-save/blob/7bc2fad88bc6d48d16fa4617da8739e0dd6479a2/src/fsWebdav.ts#L216-L222

Requesting “%.md” to the WebDAV server returned an error, but requesting “%25.md” instead successfully retrieved the file.

For the sake of the template, I'm assuming this happened on Windows, but it has happened on Windows, iOS (iPhone, iPad) (all devices I use Obsidian on).

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (InfiniCloud (formally TeraCLOUD))

### Version of the plugin

0.5.21

### Version of Obsidian

v1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
i uses a famous webdav js library and it just does it way like this.

do you encounter the same error using teracloud?

**Comment by fyears** [comment]
![37f530cd6730b7ce3257dc42abb38d0](https://github.com/user-attachments/assets/df7ec598-c5f1-4c67-8b86-19e6f4151387)


it looks like the library actually encode the url for us. but maybe infinicloud doesn't support this way.

**Comment by fyears** [comment]
and i use dufs https://github.com/remotely-save/remotely-save/blob/master/docs/remote_services/webdav_dufs/README.md to test, the file with `%` is uploaded successfully.

so i am afraid it's a special bug on infinicloud service. we have to manually avoid the character by ourselves.
