### ISSUE TITLE
[Bug]: reading 'enableAllowMode' error

### ISSUE THREAD

**Issue by carolbarata** [remotely-save/remotely-save#833]
### What happened?

When syncing for the first time on my Linux machine, I get the following error:
`Cannot read properties of undefined (reading 'enableAllowMode')`

I've installed Obsidian with flatpak and run it with the command below
`> flatpak run md.obsidian.Obsidian`

Are there any permissions that I should update? Any idea what might be causing this issue?

### What OS are you using?

Linux

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

v0.5.24

### Version of Obsidian

v1.6.7

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by AVKurbatov** [comment]
I am experiencing the same issue 'Cannot read properties of undefined (reading 'enableAllowMode')' with plugun with v0.5.24 on my Android device. I installed the plugin from standard menu "Community plugins". Although, I have Obsidian with the same vesions of the plugin installed on Windows and it works. I am using Webdav cloud service.

**Comment by bjeram** [comment]
same problem: Android, Dropbox

**Comment by nipunaherath** [comment]
Same issue on S3

**Comment by joshdesharnais1** [comment]
same issue iphone 12

**Comment by fyears** [comment]
fixed in 0.5.25

**Comment by AVKurbatov** [comment]
Confirm, it worked for me.
