### ISSUE TITLE
[Feature Request]: mTLS support for s3 storage

### ISSUE THREAD

**Issue by stanislau-arkhipenka** [remotely-save/remotely-save#837]
### What feature are you suggesting?

Hey,
Is there a chance we could get mTLS authentication supported on the plugin? 
It's a standard for enterprise deployments, and it would be nice to have it in the Obsidian as well.
Thank you

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
it's an interesting idea, but the plugin runs in the browser environment of obsidian, so i think it's hard or technically impossible to implement mtls.

if you are sure it's technically possible under the above restrictions, or even have any prototype, feel free to post any code here.
