### ISSUE TITLE
Mega support

### ISSUE THREAD

**Issue by alexcavadora** [remotely-save/remotely-save#838]
### What feature are you suggesting?

Being able to use Mega as a way to sync notes. I am a student. I use obsidian on my mac and windows computer and sync my vault on there, but i can’t seem to be able to sync my vault with my phone. 
Why Mega? it’s super lightweight and has a free plan. It seems to only use 0.1% of my cpu on PC vs 5-10% for Onedrive while idle. I could help out with the code, there already seems to be a Mega API out there.

### What remote cloud services are you using, or suggesting adding the feature to?

others

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
i sincerely would like to support mega too. but unfortunately mega has a complex setting and doesn't have official js library. so technically it's hard or impossible to support
