### ISSUE TITLE
[Bug]: Encription does not work

### ISSUE THREAD

**Issue by kabokabeso** [remotely-save/remotely-save#843]
### What happened?

I want to set up my vault with encryption. Up to now  I did not use encryption and everything worked fine.

I have a bigger vault with many files and sync it via onedrive personal through remotly safe on my Iphone 14 and my Windows 11 laptop. 

![image](https://github.com/user-attachments/assets/2b4697bb-e466-4c39-bd9a-0b0a716523ea)

![image](https://github.com/user-attachments/assets/14e26f5d-3476-44fc-9507-1127ca4d827f)

I also tried without Enable Config Dir, but it also was buggy even with a fiew files.

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

up to date

### Version of Obsidian

up to date

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
hello if you have synced the unencrypted files, you have to 

1. make a backup of your vault
2. remove everything in the cloud synced folder
3. setup password
4. sync again (so the plugin will upload the encrypted version to the cloud)

**Comment by fyears** [comment]
and from your steps, you meet request failed.

please output the errors from this tutorial: 

pc mac https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/check_console_output.md
mobile https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/check_vconsole_output.md

**Comment by kabokabeso** [comment]
I think I followed the steps you describe with described  in my Post. The console logs would have bin interesting. But sorry, at the moment I am not willing to try it again whit the quite probable result that it does not work and I have to rollback everything again…

**Comment by fyears** [comment]
ok but debugging needs some further info. i will close this issue now, and feel free to reopen it if you have time and resources to try to check the console
