### ISSUE TITLE
[Bug]: Automatically delete empty folders

### ISSUE THREAD

**Issue by alongflow** [remotely-save/remotely-save#845]
### What happened?

空文件夹同步仍然会自动删除。

创建空文件夹后第一次点击同步不会删除，但是再次点击同步仍然会删除空文件夹.

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (腾讯云 COS Tencent Cloud COS)

### Version of the plugin

0.5.24

### Version of Obsidian

1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
你好，由于s3云端没有存储空文件夹信息，所以会出现这种情况。

唯一解决方法是塞一个文件进入文件夹里。

**Comment by netsecninja** [comment]
A fix I found is to create the folder in the S3 Console. You can then use the sync command/button in Obsidian to pull the folder in for use. This seems to work for folders that need to exist but the contents are later moved to other folders, such as an Inbox.
