### ISSUE TITLE
[Bug]: 同步时报错 401 Unauthorized

### ISSUE THREAD

**Issue by djhdj1** [remotely-save/remotely-save#847]
### What happened?

我使用AList作为webdav进行同步，但无论是test还是直接同步 都无法进行，报错401 Unauthorized。
但文件夹内已经生成rs-test-folder-3obkld-uCCkegbeKvVN8A文件夹内有文件rs-test-file-821mbe4Z_qys8_GBqC6dC和.obsidian文件夹

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (AList)

### Version of the plugin

0.5.24

### Version of Obsidian

1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by Chester-gz** [comment]
我用windows webdav报错503 onedrive报错401 重新鉴权无法成功

**Comment by fyears** [comment]
你好，你肯定是权限设置有问题。这里的意思是连接上了但是能创建不能删除或上传。

**Comment by BabyMelvin** [comment]
解决了吗? NAS 同样问题，没找到啥原因。

**Comment by Chen-tu** [comment]
我用的 InfiniCLOUD 做 Webdav 遇到了同样的问题，能够连接上但是报错 401 Unauthorized，最后发现是 InfiniCLOUD 平台更新了需要重新验证邮箱，验证了之后就好了，就是权限问题。

**Comment by chenjunqiang** [comment]
> 我用的 InfiniCLOUD 做 Webdav 遇到了同样的问题，能够连接上但是报错 401 Unauthorized，最后发现是 InfiniCLOUD 平台更新了需要重新验证邮箱，验证了之后就好了，就是权限问题。

怎么让他重新验证邮箱？

**Comment by Chen-tu** [comment]
> > 我用的 InfiniCLOUD 做 Webdav 遇到了同样的问题，能够连接上但是报错 401 Unauthorized，最后发现是 InfiniCLOUD 平台更新了需要重新验证邮箱，验证了之后就好了，就是权限问题。
> 
> 怎么让他重新验证邮箱？

打开 InfiniCLOUD 平台的网站，如果需要重新验证邮箱的话，我记得他好像会提示你的
