### ISSUE TITLE
[Bug]: OneDrive cannot authenticate

### ISSUE THREAD

**Issue by V0idC0de** [remotely-save/remotely-save#848]
### What happened?

> **Workaround found by @alex-pat:** https://github.com/remotely-save/remotely-save/issues/848#issuecomment-2419504239

Since end of September 2024, I'm facing an issue with failing OneDrive authentication.
I tested the auth process with my private Microsoft account (OneDrive for personal) on two Windows devices and my Android device. The result was the same with all of them.
However, I was able to authenticate successfully before that. Once, my authentication was apparently revoked or timed out, but no issues getting the authentication up and running again.
Now the authentication seems to be dysfunctional on all my devices.

Clicking "check" shows the following
![grafik](https://github.com/user-attachments/assets/069a6921-91e3-49e7-8efa-3847bc3d20c3)

Clicking "Auth" performs the following:
1. Click link and log into the Microsoft account successfully
2. Confirm I want to login with "remotely-save"
3. Link is attempted to be opened in Obisidan -> allowing it
4. Screen switches to Obsidian, showing the "Connecting to OneDrive, DO NOT close this modal"
5. This screen does not disappear, auth is never finished
6. Syncing or clicking "check" after that is not successful

The console reveals the following logs, starting with the click on "Auth":
![grafik](https://github.com/user-attachments/assets/984676d3-523b-41b2-aea8-f57ebe409eb5)

I successfully logged into my OneDrive account and can see the outdated files created by remotely-save, so the account is not terminated or blocked.

Unfortunately, remotely-save doesn't seem to log the actual error returned by the request, since it seems that the request for a proper token fails. According to logs, the access token is written, but maybe the next request, exchanging it for a Bearer Token, fails and brings the process to a halt.

**Edit:** I discovered, that my OneDrive has the `Apps/Graph/<vault name>/` path, instead of `Apps/remotely-save/<vault name>/`. I renamed the folder as outlined [here](https://github.com/remotely-save/remotely-save/blob/master/docs/remote_services/onedrive/README.md#i-cannot-find-appsremotely-save-folder), but nothing changed about the behavior.

### What OS are you using?

Windows, Android
([confirmation ](https://github.com/remotely-save/remotely-save/issues/848#issuecomment-2416796713)about the same behavior on Linux)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.24

### Version of Obsidian

1.6.7

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by rmonakhov** [comment]
The same thing on Linux Obsidian client v.1.6.7 and Remotely Save v.0.5.24. Check connectivity also fails.

**Comment by TJsr0015** [comment]
I also encountered almost the same problem
我遇到了一模一样的问题

**Comment by alex-pat** [comment]
Hi, I faced the same issue. Although I managed to fix it.

Before, obsidian used `Apps/Graph/<vault name>/` instead of `Apps/remotely-save/<vault name>/` but still worked.

When after the issue I renamed `Graph` to `remotely-save` and tried to sync, by some reason `Graph 1` directory appeared instead, but I still had sync error. Then I removed `Graph 1` and tried again, and sync worked now, although `Graph` appeared again and it didn't touch existing `remotely-save` directory. THEN I renamed `Graph` to `remotely-save` and after successful syncs `Graph` didn't appear anymore, only `remotely-save` was used

**Comment by V0idC0de** [comment]
> Hi, I faced the same issue. Although I managed to fix it.
> 
> Before, obsidian used `Apps/Graph/<vault name>/` instead of `Apps/remotely-save/<vault name>/` but still worked.
> 
> When after the issue I renamed `Graph` to `remotely-save` and tried to sync, by some reason `Graph 1` directory appeared instead, but I still had sync error. Then I removed `Graph 1` and tried again, and sync worked now, although `Graph` appeared again and it didn't touch existing `remotely-save` directory. THEN I renamed `Graph` to `remotely-save` and after successful syncs `Graph` didn't appear anymore, only `remotely-save` was used

This actually resolved the issue, so the issue is probably more about setting up the folder access?

I performed the following steps, since I reverted the change of renaming `Graph` to `remotely-save`.

1. Do note, that `Apps/Graph 1` is actually there
2. Rename `Graph` to `remotely-save` (skip, if the folder is already called `remotely-save`)
3. Remove `Graph 1`
4. Start the authentication flow (starting with the click on `Auth` in Obsidian's configuration for "Remotely-Save"
5. It will succeed as expected
6. Files are now synced
7. Remove unused folder(s), like `Graph 1`

Thanks a lot @alex-pat for this.
@fyears this probably helps a lot to locate the actual problem, since the auth flow itself doesn't seem to be terribly broken. It's more about the folder selection.

**Comment by fyears** [comment]
@alex-pat @V0idC0de  

hi thanks for your testing but the most annoying thing is that i have no idea why Graph 1 folder is created... (what the heck is that?)

i iwll try to detect the weird folde name in next version

**Comment by lsenala** [comment]
The following is just speculation and may not be helpful. The problem may occur when creating the "Graph" folder. Graph 1 was created because of the same name to avoid folder name conflicts.

**Comment by fyears** [comment]
fixed in next version released in a few hours

**Comment by Bill-Chill** [comment]
> > Hi, I faced the same issue. Although I managed to fix it.
> > Before, obsidian used `Apps/Graph/<vault name>/` instead of `Apps/remotely-save/<vault name>/` but still worked.
> > When after the issue I renamed `Graph` to `remotely-save` and tried to sync, by some reason `Graph 1` directory appeared instead, but I still had sync error. Then I removed `Graph 1` and tried again, and sync worked now, although `Graph` appeared again and it didn't touch existing `remotely-save` directory. THEN I renamed `Graph` to `remotely-save` and after successful syncs `Graph` didn't appear anymore, only `remotely-save` was used
> 
> This actually resolved the issue, so the issue is probably more about setting up the folder access?
> 
> I performed the following steps, since I reverted the change of renaming `Graph` to `remotely-save`.
> 
> 1. Do note, that `Apps/Graph 1` is actually there
> 2. Rename `Graph` to `remotely-save` (skip, if the folder is already called `remotely-save`)
> 3. Remove `Graph 1`
> 4. Start the authentication flow (starting with the click on `Auth` in Obsidian's configuration for "Remotely-Save"
> 5. It will succeed as expected
> 6. Files are now synced
> 7. Remove unused folder(s), like `Graph 1`
> 
> Thanks a lot @alex-pat for this. @fyears this probably helps a lot to locate the actual problem, since the auth flow itself doesn't seem to be terribly broken. It's more about the folder selection.

I also encountered this kind of bug on 2025/1/3.
OS: Windows 11 23H2
Version of the plugin: 0.5.25
Version of Obsidian: 1.7.7

I guess this bug is related to the writing of folder names? 
My solution is to add a folder with the same name as the vault in `Onedrive/Apps/remotely-save`. For example, if my vault name is "ABC", then I will add a folder named "ABC" under remotely-save.

**Comment by iabaro** [comment]
I am having this issue in MacOS, iPad, and Android. None of the suggested solutions is working for me.
