### ISSUE TITLE
[Bug]: Error messages

### ISSUE THREAD

**Issue by astroajay** [remotely-save/remotely-save#849]
### What happened?

I continually tried and failed to sync two files(notes) getting the error 400 but nothing else. 

![image](https://github.com/user-attachments/assets/d1f59cbd-8743-4e3c-aa48-cdc4d5e45f56)

I tried removing auth and reauthenticating etc with no luck. Finally when trying to debug the issue in the network tab, I opened the failing PUT request. Only when I opened the Preview and then the Response did I find the error

"error": {

        "code": "invalidRequest",
        "message": "One or more invalid characters are present in the path (/Jump/App_1#######/######/###/Write a short poem with including the line - \"If tomorrow started without me\".md).",
        "localizedMessage": "Please enter a name that doesn't include any special characters. Also make sure it doesn't end with a period or start with two periods.",
        "innerError": {
            "code": "nameContainsInvalidCharacters",
            "date": "2024-10-17T06:20:56",
            "request-id": "02c4f018-fe5e-430d-bb44-c30e4e0f251a",
            "client-request-id": "02c4f018-fe5e-430d-bb44-c30e4e0f251a"
        }

I finally changed the name of the note to exclude special characters( " and ? but not -) and the sync went 
through fine. 

The error messages should ideally be passed onto the user so that they can change what needs to be changed. 
So maybe a more descriptive error that passes on the text of the error message itself would be prudent.

### What OS are you using?

Linux

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.24

### Version of Obsidian

1.6.7

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
hi i would like to optimize the error message but the remote services are different and even behave differently on different os...

i would think about a way.

thanks for your reporting!
