### ISSUE TITLE
[Feature Request]: single direction sync 单向同步

### ISSUE THREAD

**Issue by fyears** [remotely-save/remotely-save#85]
### What feature are you suggesting?

是否考虑添加一下单向同步的功能，我在pc端添加PDF然后在Android端同步后会直接删除onedrive内对应的PDF(因为使用过foldersync同步过所以插件会将Android当做最新的库)

@JerryFake
从这里迁移 https://github.com/remotely-save/remotely-save/issues/82

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by JerryFake** [comment]
这个功能用到的频率应该不会很频繁，可以考虑在插件设置里面添加一个选项，此次同步：双向同步，仅下载，仅上传
这项功能主要在移动端会频发用到，桌面端有完整且方便的文件管理系统，删除的文件能在回收站找到。

**Comment by fyears** [comment]
仔细看了一下，有点难度，主要是要改写不少代码，后继计划可以做，先保持住这个 issue

**Comment by JerryFake** [comment]
> 这个功能用到的频率应该不会很频繁，可以考虑在插件设置里面添加一个选项，此次同步：双向同步，仅下载，仅上传。仅生效一次，在同步结束后会自动选择双向同步；上传和下载行为均为强制覆盖。 这项功能主要在移动端会用到，桌面端有完整且方便的文件管理系统，删除的文件能在回收站找到。

做成弹出列表勾选也许会方便代码编写(大概？)，我想了想两个同步方案的策略：文件存在差异->覆盖上传/覆盖下载；仅上传会出现本地没有文件，云端存在文件的情况，我的偏好策略是删除；仅下载会出现云端没有文件，本地存在文件的情况，我的偏好策略任然是删除。我认为在使用这个功能的情况下，是提前知道本地的库和云端的库哪一个才是自己需要的，对于这些多出来的文件可以进行删除操作，当然可以写一个warning提醒一下。

**Comment by fyears** [comment]
所以其实有四种

1. 覆盖上传
2. 尝试上传，但是如果远端有同名文件则不覆盖
3. 覆盖下载
4. 尝试下载，但是如果本地有同名文件则不覆盖

**Comment by fyears** [comment]
弹出列表勾选其实是更难的 hhh

**Comment by JerryFake** [comment]
对于覆盖上传/下载整个库可以考虑使用一下现有的文件映射，来跳过一些完全相同的文件，降低数据流通，当然如果代码实现困难那只直接覆盖整个库吧

**Comment by JerryFake** [comment]
> 所以其实有四种
> 
> 1. 覆盖上传全部本地文件
> 2. 尝试上传，但是如果远端有同名文件则不覆盖
> 3. 覆盖下载全部远端文件
> 4. 尝试下载，但是如果本地有同名文件则不覆盖
> 
> 这几种应该是足够用了，至于不同文件同时各种勾选处理则太复杂也不实用，不打算支持

不过我想，这个2和4是不是已经和现有的同步策略重复了

**Comment by fyears** [comment]
不一样的

**Comment by osnosn** [comment]
类似的需求。

* **使用场景 1**
多人共用一个webdav账号，
只有一人修改（正常使用，双向同步）。
其他人只读（单向拉取 pull）。

* **使用场景 2**
其中一个客户端，因误操作同步，导致服务器文件丢失。
正好，另外一个客户端的内容比较完整，需要 强制推送 push 到服务器，恢复文件。
（这里要考虑一下，是否需要把所有文件设置为最新）。

**Comment by fyears** [comment]
[A new beta version 0.4.1](https://github.com/remotely-save/remotely-save/releases/tag/0.4.1) has been released but you have to install it via [BART](https://github.com/TfTHacker/obsidian42-brat). It comes with force push and pull. This issue should be solved.

Also this issue is dup of #202
