### ISSUE TITLE
[Bug]: Failed to load plugin (iOS)

### ISSUE THREAD

**Issue by Tongkaio** [remotely-save/remotely-save#850]
### What happened?

您好，我在 ipad 上 (ios版本: 14.8) 启用此插件 (版本 0.5.24) 时，报错“插件加载失败”，我尝试使用BRAT安装0.3.25版本的remotely-save，但在通过"Add beta plugin with frozen version"安装时，点击 "Add Plugin"，没有任何反应。想求助一下应该如何解决呢？谢谢~

Hello, when I enable this plugin (version 0.5.24) on my iPad (iOS version: 14.8), I get an error saying "Plugin loading failed." I tried using BRAT to install version 0.3.25 of remotely-save, but when I used the "Add beta plugin with frozen version" option and clicked "Add Plugin", there was no response. Could you please help me with how to resolve this issue? Thank you~

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.24

### Version of Obsidian

1.7.4

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
你好 ios 14 不支持
