### ISSUE TITLE
[Bug]: Having thoubles connecting to OneDrive

### ISSUE THREAD

**Issue by 11111111123123** [remotely-save/remotely-save#852]
### What happened?

![pgn](https://github.com/user-attachments/assets/ed56b452-3d5b-41f1-bae5-553e0ede64ae)
can't sync on ios, windows and android.

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
what folder is created from your onedrive? are you using onedrive for personal?

**Comment by fyears** [comment]
maybe dup of https://github.com/remotely-save/remotely-save/issues/848
