### ISSUE TITLE
[Bug]: 发生了一些未知错误

### ISSUE THREAD

**Issue by 1755508167** [remotely-save/remotely-save#853]
### What happened?

<img width="223" alt="屏幕截图 2024-10-17 214636" src="https://github.com/user-attachments/assets/0156b548-b582-424c-8f5d-402221fc90a5">
我无法弄明白错误的来源并且解决它。SOS!

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
dup of https://github.com/remotely-save/remotely-save/issues/848

fixed in 0.5.25
