### ISSUE TITLE
[Bug]: Did latest update broke Minio ? (0.5.25)

### ISSUE THREAD

**Issue by krakerz** [remotely-save/remotely-save#857]
### What happened?

i've debugged my minio deploy for couple hours today, and it seems the latest version bugged out when doing s3:PutObject
here is the trace from minio console webui
![image](https://github.com/user-attachments/assets/351af52b-7f0f-4a3e-87ae-deb3d19747d3)

the last one was okay, because i tried it with different clients (ShareX) with same bucket, same key, but with obsidian + remotely save, i got handler.auth error

my current setup was 
minio docker tag RELEASE.2024-10-13T13-34-11Z
behind nginx with similar config from minio documentation
and cloudflare DNS (not proxied, only for DNS resolving purpose)

and here is last 3 log from nginx
`[23/Oct/2024:14:38:07 +0700] "GET /obsidian/?list-type=2 HTTP/2.0" 200 776 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.7.4 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36"` 

`[23/Oct/2024:14:38:08 +0700] "PUT /obsidian/rs-test-folder-hdbhJkymprWXgso4Ts2JE/rs-test-file-E3mGosvls97Jbl4X5gpEH?x-id=PutObject HTTP/2.0" 403 431 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.7.4 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36"`

`[23/Oct/2024:14:39:49 +0700] "PUT /obsidian/f221ca71-8601-458b-bd9f-6d2f880bcfee/shx_aRpEV3nD4U.mp4 HTTP/1.1" 200 0 "-" "ShareX/16.1.0"`

### What OS are you using?

Windows, iOS (iPhone, iPad), Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

S3 (MinIO)

### Version of the plugin

0.5.25

### Version of Obsidian

1.7.4

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by krakerz** [comment]
and somehow it's fixed by itself, closing it for now ._.
maybe it was cloudflare issue all the way

**Comment by timatlee** [comment]
@krakerz Did you do anything to change this?  I am seeing something similar, but with Garage S3 behind a Cloudflare tunnel.

**Comment by krakerz** [comment]
> @krakerz Did you do anything to change this? I am seeing something similar, but with Garage S3 behind a Cloudflare tunnel.

no, i didnt do anything, you just need to wait i guess, ETA ~ 1day
seems it's cache issue in Cloudflare, it will resolve itself after 1 day
