### ISSUE TITLE
[Bug]:  rescue question

### ISSUE THREAD

**Issue by etyrnal** [remotely-save/remotely-save#858]
### What happened?

**Question:**  can i recover from this problem (will describe) by temporarily setting Sync Direction on the mobile android device to be "Incremental Pull and Delete" to save my butt?

**Problem:**  Android device Obsidian unexpectedly quits when i try to remotely save.

**Environment / situation / normal usage:**

I use Obsidian on **three 2.5 devices**.  One installation on **android** phone when i make 99% of new notes.  One installation on a **linux desktop** -- because it's easier to make mass-edits/fixes/changes there.  And the .5 is my nextcloud **DAV server** (which works great).  I never run the desktop or the android Obsidian at the same time.  

**What happened:**  So last night i closed obsidian on the phone.  Opened obsidian on the desktop and did massive editing.  Moved hundreds of note using obsidian interface to do it.  Renamed/merged/deleted duplicate notes ending in " 1".

The desktop was perfectly happy.  Remote Saved it.  Everything happy.  Now, on the phone, since i knew this was going to be a massive change, i changed the Remotely Save settings to "Incremental Pull and Delete", hoping it would look at the fixed up tuned up database on the DAV server as being the 'master' temporarily -- thinking it would sync all edited notes, pull down any new notes/media files, and delete anything locally on the phone that was no longer there on the tuned up DAV copy of the Obsidian vault.

But Obsidian on the mobile device keeps crashing, and i suspect it's maybe due to some sort of N-way comparison out of memory thing?

Can i just **delete** the local Obsidian vault folder (or maybe just the notes in it) on the android device's file system, and start the phone's obsidian back up, and it will just pull everything down?  Then if/when it succeeds, set the Syn Direction back to the normal Bidirectional?

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

current

### Version of Obsidian

current

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
yeah i think it will work, since local empty vault should trigger all clean download, but **make a backup of your vault elsewhere firstly**, **do not bet on me or anyone**!
