### ISSUE TITLE
[Bug]: Sync Failure called "AWS authentication requires a valid Date or x-amz-date header"

### ISSUE THREAD

**Issue by Achieve777** [remotely-save/remotely-save#86]
## 使用的云服务商
阿里云 OSS

## 问题描述
同步的时候出现如下异常
在配置中验证能够访问bucket

<img width="297" alt="image" src="https://user-images.githubusercontent.com/15379292/163801208-ac9c5c67-6243-4cd2-92ee-30f05cd6a6c4.png">

### What OS are you using?

macOS

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.19

### Version of Obsidian

0.14.5

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
请问是首次发生吗？请问是可复现吗？

**Comment by fyears** [comment]
我这里没有阿里云的资源，也没有苹果电脑……无法复现……感觉出问题的都是苹果电脑

**Comment by fyears** [comment]
如果方便的话，可以我这边打一个 debug 包，然后您帮忙查看一下 console 的输出，可以吗？

**Comment by Achieve777** [comment]
> 请问是首次发生吗？请问是可复现吗？

今天更新到v0.3.19之后出现的这个问题, 开始同步就可以复现

> 如果方便的话，可以我这边打一个 debug 包，然后您帮忙查看一下 console 的输出，可以吗？

感谢您开发出这么好用的插件! 乐意之至, 您打包之后, 我这边随时可以调试

**Comment by Achieve777** [comment]
另外我刚才尝试重新复现, 第一次失败, 第二次莫名其妙又成功了. 
我怀疑是**OSS服务提供商**的网络问题

以下是两次使用同步服务的调用栈:
<img width="742" alt="image" src="https://user-images.githubusercontent.com/15379292/163819761-cfd546b2-b96c-479e-a118-d95829532069.png">

**Comment by Achieve777** [comment]
虽然问题暂时看起来解决了..  您可以打个 debug 的包, 下次再次出现问题我会带着 console 输出来向您反馈

**Comment by fyears** [comment]
这个debug分支对于请求的日期都print了出来，代码 https://github.com/remotely-save/remotely-save/commit/ba5593456f2cb9cfd5a622f56f3741ce31c01cdf

麻烦下载一下这里的 `my-dist.zip` 然后解压，然后用里面的 `main.js` 替换，然后 disable 然后 enable 一下插件（从而使得新的 `main.js` 生效

https://github.com/remotely-save/remotely-save/actions/runs/2184270248

控制台会把各个请求的 `x-amz-date` 都print出来，主要是想看看这个参数是不是正常的。。。：

![image](https://user-images.githubusercontent.com/1142836/163820827-72f21054-ce51-4637-8138-6dea9a22145c.png)

非常感谢！

**Comment by fyears** [comment]
> 以下是两次使用同步服务的调用栈:

这个截图信息不足，一开始是没有把 `x-amz-date` 打印出来的

**Comment by Achieve777** [comment]
<img width="483" alt="image" src="https://user-images.githubusercontent.com/15379292/163821641-ea2e8be3-f1fa-48bc-894d-b07aa839e8a5.png">


目前恢复正常, 无法复现了. 
我就正常使用这个版本然后关闭 issue 了, 下次再出现问题时我再打开这个 issue

最后, 感谢您如此无私的开发出这么好用的的插件, 还有这么及时的回复 👍

**Comment by fyears** [comment]
好，欢迎有bug继续反馈。从截图来看是正常的时间，
