### ISSUE TITLE
[Feature Request]: Obsidian更换客户端之后，怎么把远程数据拉取到本地？

### ISSUE THREAD

**Issue by anwangwang** [remotely-save/remotely-save#863]
### What feature are you suggesting?

不会用双向同步的功能。
目前只会把本地的数据同步到远程。

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
如果你是换手机的话，新手机是空的，可以先开启双向同步，它就会拉下来了。然后再设置成单向同步
