### ISSUE TITLE
[Bug]: 移动端同步报错

### ISSUE THREAD

**Issue by ZhXWei** [remotely-save/remotely-save#871]
### What happened?

使用群晖webdav http+IP，windows能正常使用同步。移动端必须使用https同步么？
Error: Request failed. The resource could not be Loaded because the App Transport Security policy requires the use of a secure connection.

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.5.25

### Version of Obsidian

1.7.4

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
是的一定要正常运作的 https 设置。这是 ios 系统的限制
