### ISSUE TITLE
[Bug]: Sign up on the website is dead

### ISSUE THREAD

**Issue by snoorkwashanging** [remotely-save/remotely-save#872]
### What happened?

When going to the Sign Up / Sign In page on the remotely save website, when you put your email in and then hit next, it just goes to an internal server error page. 

<img width="916" alt="image" src="https://github.com/user-attachments/assets/12373d2a-7d7f-47c0-a7d1-2a3581c43360">

<img width="454" alt="image" src="https://github.com/user-attachments/assets/671ac8e9-bb9c-48ca-9dcc-00f95ef0f778">

### What OS are you using?

macOS

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

others

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
hi maybe the website had too many requests at that moment. the link should be fixed now
