### ISSUE TITLE
[Bug]: 0.5.25使用onedrive个人版同步失败

### ISSUE THREAD

**Issue by chen-jingliang** [remotely-save/remotely-save#873]
### What happened?

升级到最新的0.5.25后，原先一直正常的onedrive同步失败。
PC端和MAC端都存在相同的问题。
在插件中测试是否可以连接，显示可以正常连接到onedrive
![2024-10-30 14 45 18](https://github.com/user-attachments/assets/23601b0d-1b41-4266-9628-14e8f04b51a2)

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.25

### Version of Obsidian

1.7.4

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by yunrr** [comment]
我也遇到这个问题了，回退至0.5.23版本我这边就正常了

**Comment by louiejordan** [comment]
暂时不用OneDrive，换成webdav了

**Comment by fyears** [comment]
有没有什么错误呢？onedrive网站看到文件夹有什么特殊名字吗？

**Comment by fyears** [comment]
用 #878 跟踪
