### ISSUE TITLE
[Bug]: webdav set https link（not http）If I create a new folder and then click sync, the synchronization will fail。http will success

### ISSUE THREAD

**Issue by kevinmu11er** [remotely-save/remotely-save#874]
### What happened?

webdav set https link（not http）If I create a new folder and then click sync, the synchronization will fail。http will success
![image](https://github.com/user-attachments/assets/52b1decd-770e-47dd-b71b-a455134a337a)

### What OS are you using?

Windows, macOS, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

0.5.25

### Version of Obsidian

1.7.4

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by kevinmu11er** [comment]
![image](https://github.com/user-attachments/assets/cd1ab6ee-4d5f-4cf2-b0d8-c8718071d36e)

**Comment by fyears** [comment]
大概率是你的 https 配置错误。对插件来说，http https 代码是完全一致的，它不理解它们的差异
