### ISSUE TITLE
[Feature Request]: Minio as S3 compatible sync target

### ISSUE THREAD

**Issue by mosenturm** [remotely-save/remotely-save#88]
### What feature are you suggesting?

At first thanks @fyears so much for this plugin!
What about minio (https://min.io) as synctarget? It should be possible to implement. An JS SDK is available (https://docs.min.io/docs/javascript-client-api-reference.html) and it looks extensive.

### What remote cloud services are you using, or suggesting adding the feature to?

S3, others

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
since minio is s3 compatible, you should be able to adjust the s3 config to directly connect to a minio instance.

**Comment by fyears** [comment]
and maybe you will need to adjust the url style option to path style for the self hosted minio
