### ISSUE TITLE
[Feature Request]: 增加忽略同步功能

### ISSUE THREAD

**Issue by YIRU69** [remotely-save/remotely-save#92]
### What feature are you suggesting?

你好，关注你的插件很久了，很感谢你的开发
我一直没有用的原因是因为我的库里面有很多不需要同步的文件，但我真的希望能用你的插件来方便同步
目前插件是支持不同步下划线开头的文件，那么能否增加以.开始的文件和文件夹不同步呢？
或者增加更好的忽略同步的功能
希望能收到你的消息，尽快的使用上插件

### What remote cloud services are you using, or suggesting adding the feature to?

others

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
你好，默认设定下，`.` 开头的文件和文件夹也是不同步的。
