### ISSUE TITLE
[Bug]: Can't start the sync with OneDrive for Personal

### ISSUE THREAD

**Issue by LBF38** [remotely-save/remotely-save#98]
### What happened?

I was expecting the plugin to sync my files into my OneDrive. 
However, I got an error on screen saying that it couldn't handle the parentPath. A screen is provided below.
![bug parentPath](https://user-images.githubusercontent.com/96347823/165402373-39164918-b2e6-4757-8ee9-11d7eb934a74.png)

I don't know how to change the default parentPath to solve this error. Moreover, I also don't know how to indicate the path to the folder I want the plugin to sync to.

If you need any information, please feel free to contact me.
Thanks a lot for your investment in this plugin based of an awesome idea!

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.19

### Version of Obsidian

0.14.6

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment]
are you using onedrive for **personal** or for **business**? remotely save doesn’t support the later yet

**Comment by LBF38** [comment]
I'm using Onedrive for personal. I know the difference and that's why I use Onedrive for personal.
I think I didn't set up well the plugin. Could you help me please?

**Comment by fyears** [comment]
Could you please go to onedrive web page and see if the folder /Apps/remotely-save/<vault name> has been created or not?

**Comment by ajmz** [comment]
> Could you please go to onedrive web page and see if the folder /Apps/remotely-save/ has been created or not?

我手动新建了/Apps/remotely-save/，也不能同步，报错提示如图：

![2022-04-27_185441](https://user-images.githubusercontent.com/30185045/165503599-2d1b816c-41da-4143-bf9d-d8f85ab77491.png)

![2022-04-27_185424](https://user-images.githubusercontent.com/30185045/165503628-66a12270-6e88-44e0-baaf-4c4d79771903.png)

**Comment by fyears** [comment]
授权成功之后，应该会自动新建上述文件夹，如果没有自动新建的话则有问题。

建议重新做各个步骤

1. 备份好本来的各个笔记文件
2. 在 onedrive 网页版，删除手动建立的 /Apps/remotely-save
3. 去 https://microsoft.com/consent 撤销本插件的授权
4. 新建一个 vault，专门用于测试
5. 在测试 vault 里，重新安装本插件，启动，授权，到最后，在设置页里点击“检查是否可连接”按钮，如果正常应该返回相应提示。
6. 在测试 vault 里新建和修改文件，测试一下上传下载是否异常。

**Comment by ajmz** [comment]
> 授权成功之后，应该会自动新建上述文件夹，如果没有自动新建的话则有问题。
> 
> 建议重新做各个步骤
> 
> 1. 备份好本来的各个笔记文件
> 2. 在 onedrive 网页版，删除手动建立的 /Apps/remotely-save
> 3. 去 https://microsoft.com/consent 撤销本插件的授权
> 4. 新建一个 vault，专门用于测试
> 5. 在测试 vault 里，重新安装本插件，启动，授权，到最后，在设置页里点击“检查是否可连接”按钮，如果正常应该返回相应提示。
> 6. 在测试 vault 里新建和修改文件，测试一下上传下载是否异常。

重新配置后正常了，谢谢。

**Comment by fyears** [comment]
好的，如果还有问题，欢迎继续提 bug。
